local M = {}

M.mapping = {
    ["予一以贯之"] = "consistent",
    ["予不得已也"] = "no alternative",
    ["予之不仁也"] = "unkindness",
    ["予也有三年之爱于其父母乎"] = "three years' love",
    ["予人"] = "give others",
    ["予人口实"] = "give cause for criticism",
    ["予以"] = "give",
    ["予以保密"] = "keep confidential",
    ["予以安排"] = "arrange",
    ["予以强调"] = "emphasize",
    ["予以执行"] = "execute",
    ["予以承认"] = "acknowledge",
    ["予以支持"] = "support",
    ["予以注册"] = "register",
    ["予以注意"] = "note",
    ["予以确认"] = "confirm",
    ["予以考虑"] = "take into account",
    ["予以重创"] = "devastate",
    ["予以重视"] = "prioritize",
    ["予又何规老聃哉"] = "why should i admonish laozi",
    ["予取予夺"] = "take freely",
    ["予取予求"] = "demand excessively",
    ["予口张而不能"] = "speechless",
    ["予夺"] = "give or take",
    ["予夺生杀"] = "power over life and death",
    ["予客居阖户"] = "guest house",
    ["予尝求古仁人之心"] = "seek ancient sages' hearts",
    ["予岂好辩哉"] = "do i love to argue",
    ["予怀渺渺"] = "my heart is vast",
    ["予恶乎知夫死者不悔其始之蕲生乎"] = "how do i know the dead don't regret their former craving for life",
    ["予恶乎知恶死之非弱丧而不知归者邪"] = "how do i know hating death isn't like an exile forgetting home",
    ["予恶乎知说生之非惑邪"] = "how do i know loving life isn't delusion",
    ["予无乐乎为君"] = "i find no joy in being lord",
    ["予智予雄"] = "arrogant",
    ["予智自雄"] = "self-important",
    ["予末小子"] = "humble i",
    ["予观夫巴陵胜状"] = "observing the splendid scenery of baling",
    ["予违汝弼"] = "i advise you against my own faults",
    ["予齿去角"] = "teeth without horns",
}

return M
