local M = {}

M.mapping = {
    ["乞丐"] = "beggar",
    ["乞丐之徒"] = "beggar's disciple",
    ["乞丐变王子"] = "beggar to prince",
    ["乞丐模拟器"] = "beggar simulator",
    ["乞丐版"] = "beggar edition",
    ["乞丐罪"] = "beggar crime",
    ["乞丐萝莉"] = "beggar loli",
    ["乞丐虫"] = "beggar worm",
    ["乞人"] = "beggar",
    ["乞人不屑也"] = "beggars disdain",
    ["乞儿"] = "beggar",
    ["乞儿乘车"] = "beggar rides a carriage",
    ["乞儿向火"] = "beggar warms by fire",
    ["乞儿暴富"] = "beggar suddenly rich",
    ["乞力马扎罗山"] = "kilimanjaro",
    ["乞宠求荣"] = "servile",
    ["乞巧"] = "begging for skill",
    ["乞巧节"] = "qixi festival",
    ["乞怜"] = "begging for pity",
    ["乞怜摇尾"] = "begging and wagging tail",
    ["乞援"] = "plead for help",
    ["乞求"] = "beg",
    ["乞灵"] = "invoke spirits",
    ["乞灵药石"] = "praying for panacea",
    ["乞穷俭相"] = "beggarly appearance",
    ["乞讨"] = "begging",
    ["乞讨狗"] = "begging dog",
    ["乞讨者"] = "beggar",
    ["乞贷"] = "begging loan",
    ["乞降"] = "beg for surrender",
    ["乞鞫"] = "appeal for retrial",
    ["乞食"] = "begging",
    ["乞骸骨"] = "retire",
}

return M
