local M = {}

M.mapping = {
    ["亭下"] = "under pavilion",
    ["亭下水连空"] = "water under pavilion meets sky",
    ["亭中"] = "pavilion",
    ["亭亭"] = "slender",
    ["亭亭五丈余"] = "towering over five zhang",
    ["亭亭如车盖"] = "tall like a canopy",
    ["亭亭山上松"] = "lofty mountain pine",
    ["亭亭月将圆"] = "full moon approaching",
    ["亭亭玉立"] = "slender and graceful",
    ["亭侯"] = "marquis",
    ["亭内"] = "in the pavilion",
    ["亭北"] = "north pavilion",
    ["亭午"] = "midday",
    ["亭南"] = "tingnan",
    ["亭可马里"] = "trincomalee",
    ["亭台"] = "pavilion",
    ["亭台六七座"] = "six or seven pavilions",
    ["亭台楼榭"] = "pavilions and terraces",
    ["亭台楼阁"] = "pavilions and towers",
    ["亭子"] = "pavilion",
    ["亭子庄"] = "tingzi village",
    ["亭子桥村"] = "tingziqiao village",
    ["亭子里"] = "in pavilion",
    ["亭子间"] = "pavilion room",
    ["亭山"] = "pavilion hill",
    ["亭店社区"] = "tingdian community",
    ["亭林"] = "tinglin",
    ["亭林先生"] = "mr. tinglin",
    ["亭榭"] = "pavilion",
    ["亭脚"] = "pavilion foot",
    ["亭自庄"] = "tingzi village",
    ["亭西"] = "west of the pavilion",
    ["亭里"] = "in pavilion",
    ["亭长"] = "town chief",
    ["亭顶"] = "pavilion roof",
    ["亭顶村"] = "tingding village",
}

return M
