local M = {}

M.mapping = {
    ["丘不与易也"] = "qiu bu yu yi ye",
    ["丘丘人"] = "hilichurl",
    ["丘东平"] = "qiu dongping",
    ["丘也请从而后也"] = "qiu ye follow",
    ["丘八"] = "qiu ba",
    ["丘力居"] = "qiu liju",
    ["丘北"] = "qiubei",
    ["丘北县"] = "qiubei county",
    ["丘吉尔"] = "churchill",
    ["丘垤"] = "anthill",
    ["丘墓"] = "grave mound",
    ["丘墟"] = "qiuxu",
    ["丘壑"] = "hills and valleys",
    ["丘壑泾渭"] = "clear distinctions",
    ["丘处机"] = "qiu chuji",
    ["丘头镇"] = "qiutou town",
    ["丘奇论题"] = "church's thesis",
    ["丘将军"] = "general qiu",
    ["丘小庆"] = "qiu xiaoqing",
    ["丘山"] = "hill",
    ["丘山之功"] = "great merit",
    ["丘岳"] = "qiu yue",
    ["丘志广"] = "qiu zhi guang",
    ["丘惠理奈"] = "riena hoka",
    ["丘成桐"] = "shing-tung yau",
    ["丘比兔"] = "cupid rabbit",
    ["丘比特"] = "cupid",
    ["丘海大道"] = "qiuhai avenue",
    ["丘疱疹"] = "herpetiform vesicles",
    ["丘疹"] = "papule",
    ["丘疹性荨麻疹"] = "papular urticaria",
    ["丘神纪"] = "qiu shenji",
    ["丘脑"] = "thalamus",
    ["丘脑下部"] = "hypothalamus",
    ["丘逢甲"] = "qiu fengjia",
    ["丘陵"] = "hills",
    ["丘陵区"] = "hilly region",
    ["丘陵地"] = "hilly land",
    ["丘陵地区"] = "hilly area",
    ["丘陵地形"] = "hilly terrain",
    ["丘集"] = "hill gathering",
    ["丘鹬"] = "woodcock",
}

return M
