local M = {}

M.mapping = {
    ["乃不知有汉"] = "ignorant of history",
    ["乃东县"] = "naidong county",
    ["乃中经首之会"] = "the meeting of zhongjingshou",
    ["乃仁克尔乡"] = "nairinkor township",
    ["乃令张良留谢"] = "then ordered zhang liang to stay and thank",
    ["乃兄"] = "elder brother",
    ["乃只盖乡"] = "naizhigai village",
    ["乃在大海南"] = "located south of the great sea",
    ["乃在大诲隅"] = "located at the corner of the great sea",
    ["乃夫"] = "husband",
    ["乃如"] = "nairu",
    ["乃尔"] = "nair",
    ["乃干屯"] = "naigantun",
    ["乃心在咸阳"] = "my heart is in xianyang",
    ["乃成"] = "thus accomplished",
    ["乃我困汝"] = "it is i who trouble you",
    ["乃托镇"] = "naito town",
    ["乃敢与君绝"] = "dare to part with you",
    ["乃是"] = "is",
    ["乃曰"] = "then said",
    ["乃木希典"] = "nogimura",
    ["乃止"] = "until",
    ["乃渠乡"] = "naiqu township",
    ["乃父"] = "father",
    ["乃玉乃金"] = "precious as jade and gold",
    ["乃知其密"] = "then knew the secret",
    ["乃知震之所在"] = "then knew where the earthquake was",
    ["乃祖乃宗"] = "ancestors and forefathers",
    ["乃祖乃父"] = "ancestors and fathers",
    ["乃积乃仓"] = "store grain",
    ["乃翁"] = "my father",
    ["乃翁依旧管些儿"] = "my father still manages some things",
    ["乃至"] = "even",
    ["乃至于"] = "up to",
    ["乃若所忧则有之"] = "nairuosuoyou zeyou zhi",
    ["乃西乡"] = "nishigo",
    ["乃见"] = "then see",
    ["乃重修岳阳楼"] = "restored yueyang tower",
    ["乃龙乡"] = "nailing township",
}

return M
