local M = {}

M.mapping = {
    ["乍一听"] = "at first listen",
    ["乍一看"] = "at first glance",
    ["乍一看来"] = "at first sight",
    ["乍冷"] = "sudden cold",
    ["乍冷乍热"] = "hot and cold",
    ["乍同乍异"] = "sometimes same sometimes different",
    ["乍听"] = "at first hearing",
    ["乍听之下"] = "on first hearing",
    ["乍富"] = "newly rich",
    ["乍富不知新受用"] = "new rich don't know how to enjoy",
    ["乍得"] = "chad",
    ["乍得共和国"] = "republic of chad",
    ["乍得副项鲿"] = "chad catfish",
    ["乍得沙赫人"] = "chad sahelanthropus",
    ["乍得花鹿宝螺"] = "chad cowrie",
    ["乍得野鲮"] = "chad labeo",
    ["乍得项鲿"] = "chad catfish",
    ["乍暖"] = "suddenly warm",
    ["乍暖还寒"] = "warm but still cold",
    ["乍暖还寒时候"] = "time of warmth and chill",
    ["乍暖还轻冷"] = "warm yet still chilly",
    ["乍泄"] = "leak",
    ["乍波蛸"] = "octopus",
    ["乍浦"] = "zhapu",
    ["乍浦港"] = "zhapu port",
    ["乍浦路"] = "zhapu road",
    ["乍热"] = "sudden heat",
    ["乍然"] = "abruptly",
    ["乍猛的"] = "suddenly",
    ["乍现"] = "flash",
    ["乍疏乍数"] = "intermittent",
    ["乍看"] = "at first glance",
    ["乍看之下"] = "at first sight",
    ["乍看起来"] = "at first glance",
    ["乍绛蕊海榴"] = "sudden crimson pomegranate",
    ["乍见"] = "at first sight",
    ["乍贫难改旧家风"] = "poverty can't change old habits",
    ["乍起"] = "sudden rise",
}

return M
