local M = {}

M.mapping = {
    ["例一"] = "example one",
    ["例三"] = "example three",
    ["例举"] = "enumerate",
    ["例二"] = "example two",
    ["例会"] = "regular meeting",
    ["例会上"] = "meeting",
    ["例会制"] = "regular meeting system",
    ["例会制度"] = "regular meeting system",
    ["例会取消"] = "meeting canceled",
    ["例假"] = "menstruation",
    ["例假日"] = "holiday",
    ["例句"] = "example sentence",
    ["例图"] = "example diagram",
    ["例外"] = "exception",
    ["例外情况"] = "exceptional case",
    ["例外放行"] = "exceptional release",
    ["例如"] = "e.g.",
    ["例如说"] = "for example",
    ["例子"] = "example",
    ["例文"] = "example text",
    ["例牌"] = "regular",
    ["例直禁简"] = "simple and strict",
    ["例禁"] = "prohibited",
    ["例程"] = "routine",
    ["例行"] = "routine",
    ["例行公事"] = "routine business",
    ["例行工作"] = "routine work",
    ["例行性"] = "routine",
    ["例行检查"] = "routine inspection",
    ["例行程序"] = "routine procedure",
    ["例行试验"] = "routine test",
    ["例规"] = "convention",
    ["例言"] = "introductory remarks",
    ["例证"] = "example",
    ["例题"] = "example problem",
}

return M
