local M = {}

M.mapping = {
    ["侨中"] = "overseas chinese school",
    ["侨乡"] = "hometown of overseas chinese",
    ["侨光小学"] = "qiaoguang primary school",
    ["侨光西"] = "west qiaoguang",
    ["侨光路"] = "qiaoguang road",
    ["侨兴环球"] = "qiaoxing global",
    ["侨兴花园"] = "qiaoxing garden",
    ["侨务"] = "overseas chinese affairs",
    ["侨务办公室"] = "office of overseas chinese affairs",
    ["侨务局"] = "bureau of overseas chinese affairs",
    ["侨务工作"] = "overseas chinese work",
    ["侨商"] = "overseas merchant",
    ["侨团"] = "overseas association",
    ["侨城东路"] = "east qiaocheng road",
    ["侨委会"] = "overseas chinese council",
    ["侨居"] = "reside abroad",
    ["侨居国"] = "country of residence abroad",
    ["侨居地"] = "place of residence abroad",
    ["侨居海外"] = "overseas residence",
    ["侨属"] = "relatives of overseas chinese",
    ["侨民"] = "expatriate",
    ["侨民们"] = "expatriates",
    ["侨汇"] = "overseas remittance",
    ["侨生"] = "overseas student",
    ["侨界"] = "overseas chinese community",
    ["侨眷"] = "overseas chinese family",
    ["侨社"] = "overseas community",
    ["侨群"] = "diaspora",
    ["侨联"] = "overseas chinese federation",
    ["侨胞"] = "overseas compatriots",
    ["侨苑"] = "overseas chinese garden",
    ["侨资"] = "overseas chinese capital",
    ["侨资企业"] = "overseas-funded enterprise",
    ["侨雄"] = "qiaoxiong",
    ["侨领"] = "overseas chinese leader",
    ["侨香村"] = "qiaoxiang village",
    ["侨鸿国际"] = "qiaohong international",
}

return M
