local M = {}

M.mapping = {
    ["乖不乖"] = "good not good",
    ["乖乖"] = "good",
    ["乖乖嘞"] = "good",
    ["乖乖地"] = "good",
    ["乖乖就范"] = "good comply",
    ["乖乖的"] = "good",
    ["乖了"] = "good",
    ["乖于情"] = "contrary to emotion",
    ["乖僻"] = "eccentric",
    ["乖儿"] = "good son",
    ["乖儿子"] = "good son",
    ["乖剌"] = "perverse",
    ["乖呀"] = "good",
    ["乖哦"] = "good",
    ["乖唇蜜舌"] = "sweet lips honey tongue",
    ["乖啦"] = "good",
    ["乖嘴蜜舌"] = "honey-lipped",
    ["乖女"] = "good girl",
    ["乖孩子"] = "good child",
    ["乖宝"] = "good baby",
    ["乖宝宝"] = "good baby",
    ["乖巧"] = "clever",
    ["乖巧懂事"] = "clever and sensible",
    ["乖异"] = "eccentric",
    ["乖张"] = "perverse",
    ["乖得"] = "good get",
    ["乖得像"] = "good like",
    ["乖戾"] = "perverse",
    ["乖点"] = "good point",
    ["乖着呢"] = "good",
    ["乖离"] = "alienation",
    ["乖舛"] = "perverse",
    ["乖觉"] = "alert",
    ["乖误"] = "error",
    ["乖谬"] = "absurd",
    ["乖蹇"] = "unlucky",
    ["乖违"] = "disobey",
}

return M
