local M = {}

M.mapping = {
    ["吵不吵"] = "noisy or not",
    ["吵不赢"] = "cannot win an argument",
    ["吵了"] = "quarreled",
    ["吵人"] = "noisy",
    ["吵到"] = "noise to",
    ["吵吗"] = "argue?",
    ["吵吵"] = "noisy",
    ["吵吵嚷嚷"] = "noisy and clamorous",
    ["吵吵打打"] = "noisy and fighting",
    ["吵吵闹闹"] = "noisy and bustling",
    ["吵嘴"] = "quarrel",
    ["吵嚷"] = "clamor",
    ["吵得"] = "noise so",
    ["吵得像"] = "noise like",
    ["吵得比"] = "noise louder than",
    ["吵我"] = "disturb me",
    ["吵扰"] = "disturb",
    ["吵杂"] = "noisy",
    ["吵来吵去"] = "argue back and forth",
    ["吵架"] = "quarrel",
    ["吵架了"] = "quarreled",
    ["吵架公约"] = "quarrel convention",
    ["吵死"] = "so noisy",
    ["吵着"] = "arguing",
    ["吵着呢"] = "very noisy",
    ["吵着要"] = "demanding",
    ["吵翻"] = "quarrel",
    ["吵起来"] = "quarrel",
    ["吵起来了"] = "quarreled",
    ["吵过"] = "argued",
    ["吵醒"] = "wake up",
    ["吵闹"] = "noisy",
    ["吵闹声"] = "noise",
    ["吵闹着"] = "making noise",
    ["吵骂"] = "quarrel and scold",
}

return M
