local M = {}

M.mapping = {
    ["喂一喂"] = "feed",
    ["喂乳"] = "breastfeed",
    ["喂了"] = "fed",
    ["喂了喂"] = "hello hello",
    ["喂他"] = "feed him",
    ["喂你"] = "feed you",
    ["喂养"] = "feeding",
    ["喂哺"] = "breastfeed",
    ["喂喂"] = "hello",
    ["喂喂喂"] = "hello hello",
    ["喂大"] = "feed up",
    ["喂奶"] = "breastfeeding",
    ["喂她"] = "feed her",
    ["喂它"] = "feed it",
    ["喂屎"] = "feeding feces",
    ["喂我"] = "feed me",
    ["喂料"] = "feeding",
    ["喂料机"] = "feeder",
    ["喂水"] = "water feeding",
    ["喂点"] = "feeding point",
    ["喂牛"] = "feed cattle",
    ["喂狗"] = "feed dogs",
    ["喂猪"] = "feed pigs",
    ["喂猫"] = "feed cats",
    ["喂猫粮"] = "feed cat food",
    ["喂着"] = "feeding",
    ["喂稀饭"] = "feeding porridge",
    ["喂给"] = "feed",
    ["喂肉"] = "feed meat",
    ["喂草"] = "grass feeding",
    ["喂药"] = "administer medicine",
    ["喂过"] = "fed",
    ["喂食"] = "feeding",
    ["喂饭"] = "feeding",
    ["喂饱"] = "feed",
    ["喂马"] = "feed horses",
    ["喂马乡"] = "weima township",
    ["喂鱼"] = "feed fish",
    ["喂鸡"] = "feed chickens",
}

return M
