local M = {}

M.mapping = {
    ["契丹"] = "khitan",
    ["契兄弟"] = "sworn brothers",
    ["契卡"] = "cheka",
    ["契卡洛夫"] = "chkalov",
    ["契友"] = "close friend",
    ["契合"] = "fit",
    ["契合点"] = "point of fit",
    ["契合金兰"] = "sworn brotherhood",
    ["契弟"] = "sworn brother",
    ["契据"] = "deed",
    ["契文"] = "oracle script",
    ["契机"] = "opportunity",
    ["契父"] = "sworn father",
    ["契爷"] = "godfather",
    ["契爷岭"] = "qiyeling",
    ["契税"] = "deed tax",
    ["契税法"] = "deed tax law",
    ["契约"] = "contract",
    ["契约书"] = "contract document",
    ["契约制"] = "contract system",
    ["契约化"] = "contractualization",
    ["契约合同"] = "contract agreement",
    ["契约型"] = "contract type",
    ["契约型基金"] = "contractual fund",
    ["契约师"] = "contractor",
    ["契约式"] = "contractual",
    ["契约性"] = "contractual",
    ["契约法"] = "contract law",
    ["契约生效"] = "contract effect",
    ["契约登记"] = "contract registration",
    ["契约精神"] = "contract spirit",
    ["契约自由"] = "freedom of contract",
    ["契约论"] = "contract theory",
    ["契纸"] = "contract paper",
    ["契诃夫"] = "chekhov",
    ["契阔"] = "parting",
}

return M
