local M = {}

M.mapping = {
    ["勿下"] = "don't go down",
    ["勿丢垃圾"] = "do not litter",
    ["勿临渴而掘井"] = "don't dig a well when thirsty",
    ["勿为新婚念"] = "not for newlyweds",
    ["勿为醒者传"] = "not for the sober",
    ["勿以善小而不为"] = "do not neglect small good deeds",
    ["勿以恶小而为之"] = "do no evil though small",
    ["勿伤我心"] = "don't break my heart",
    ["勿使"] = "do not let",
    ["勿入"] = "do not enter",
    ["勿动"] = "do not move",
    ["勿外传"] = "do not disclose",
    ["勿失良机"] = "black stone ridge",
    ["勿忘"] = "don't forget",
    ["勿忘九一八"] = "never forget 9.18",
    ["勿忘历史"] = "never forget history",
    ["勿忘国殇"] = "never forget national martyrs",
    ["勿忘国耻"] = "never forget national humiliation",
    ["勿忘在莒"] = "never forget ju",
    ["勿忘我"] = "forget-me-not",
    ["勿念"] = "don't worry",
    ["勿怠勿忘"] = "never neglect nor forget",
    ["勿扔垃圾"] = "do not litter",
    ["勿扰"] = "do not disturb",
    ["勿扰模式"] = "do not disturb mode",
    ["勿摸"] = "do not touch",
    ["勿施于"] = "not impose",
    ["勿施于人"] = "not impose others",
    ["勿用"] = "do not use",
    ["勿用手摸"] = "do not touch",
    ["勿看"] = "do not look",
    ["勿要"] = "do not",
    ["勿言"] = "don't speak",
    ["勿言推理"] = "don't say reasoning",
    ["勿谓言之不预"] = "don't say unwarned",
    ["勿谓言之不预也"] = "don't say unwarned",
    ["勿近"] = "keep away",
    ["勿进"] = "do not enter",
    ["勿违今日言"] = "do not break today's promise",
}

return M
