local M = {}

M.mapping = {
    ["哲人"] = "philosopher",
    ["哲人王"] = "philosopher king",
    ["哲别"] = "zhebie",
    ["哲司"] = "zhesi",
    ["哲夫"] = "zhefu",
    ["哲学"] = "philosophy",
    ["哲学上"] = "philosophically",
    ["哲学体系"] = "philosophical system",
    ["哲学化"] = "philosophize",
    ["哲学博士"] = "phd in philosophy",
    ["哲学原理"] = "philosophical principles",
    ["哲学史"] = "history of philosophy",
    ["哲学基本问题"] = "basic problems of philosophy",
    ["哲学基础"] = "foundation of philosophy",
    ["哲学学士"] = "bachelor of philosophy",
    ["哲学家"] = "philosopher",
    ["哲学思想"] = "philosophical thought",
    ["哲学思潮"] = "philosophical trends",
    ["哲学流派"] = "schools of philosophy",
    ["哲学王"] = "philosopher king",
    ["哲学理论"] = "philosophical theory",
    ["哲学界"] = "philosophy circle",
    ["哲学的党性"] = "party spirit in philosophy",
    ["哲学的贫困"] = "the poverty of philosophy",
    ["哲学笔记"] = "philosophy notes",
    ["哲学系"] = "philosophy department",
    ["哲学美学"] = "philosophical aesthetics",
    ["哲学范畴"] = "philosophical categories",
    ["哲学著作"] = "philosophical works",
    ["哲学观"] = "philosophical view",
    ["哲学领域"] = "field of philosophy",
    ["哲思"] = "philosophy",
    ["哲文"] = "zhewen",
    ["哲理"] = "philosophy",
    ["哲理性"] = "philosophical",
    ["哲理故事"] = "philosophical story",
    ["哲蚌寺"] = "drepung monastery",
    ["哲言"] = "philosophical saying",
    ["哲里木"] = "zhelim",
    ["哲里木盟"] = "zhelim league",
}

return M
