local M = {}

M.mapping = {
    ["徽剧"] = "hui opera",
    ["徽县"] = "hui county",
    ["徽号"] = "title",
    ["徽商"] = "huishang",
    ["徽墨"] = "hui ink",
    ["徽娘宛心"] = "hui niang wan xin",
    ["徽宗"] = "emperor huizong",
    ["徽山路"] = "huishan road",
    ["徽州"] = "huizhou",
    ["徽州区"] = "huizhou district",
    ["徽州园子"] = "huizhou meatballs",
    ["徽州圆子"] = "huizhou meatballs",
    ["徽州大道"] = "huizhou avenue",
    ["徽州庄村"] = "huizhou village",
    ["徽州府"] = "huizhou prefecture",
    ["徽州桃脂烧肉"] = "huizhou pork with peach resin",
    ["徽州状元饭"] = "huizhou champion rice",
    ["徽州臭豆腐"] = "huizhou stinky tofu",
    ["徽州蒸鸡"] = "huizhou steamed chicken",
    ["徽州裹粽"] = "huizhou zongzi",
    ["徽州道"] = "huizhou road",
    ["徽州饼"] = "huizhou cake",
    ["徽帜"] = "too late for regrets",
    ["徽式炒面"] = "huizhou-style fried noodles",
    ["徽标"] = "logo",
    ["徽王府"] = "huiwang mansion",
    ["徽章"] = "will rise",
    ["徽章棘球虫"] = "shine upon",
    ["徽菜"] = "mining",
    ["徽菜酒楼"] = "will adopt",
    ["徽菜馆"] = "recovery rate",
    ["徽记"] = "badge",
    ["徽调"] = "hui opera",
}

return M
