local M = {}

M.mapping = {
    ["序偶"] = "ordered pair",
    ["序列"] = "xu lie",
    ["序列之争"] = "xu lie zhi zheng",
    ["序列分析"] = "xu lie fen xi",
    ["序列化"] = "xu lie hua",
    ["序列号"] = "xu lie hao",
    ["序列号吗"] = "xu lie hao ma",
    ["序列图"] = "xu lie tu",
    ["序列型"] = "xu lie xing",
    ["序列密码"] = "xu lie mi ma",
    ["序列帧"] = "xu lie zhen",
    ["序列改变"] = "xu lie gai bian",
    ["序列测定"] = "xu lie ce ding",
    ["序列的极限"] = "xu lie de ji xian",
    ["序列码"] = "xu lie ma",
    ["序列表达式"] = "xu lie biao da shi",
    ["序厅"] = "lobby",
    ["序号"] = "serial number",
    ["序幕"] = "prologue",
    ["序数"] = "ordinal number",
    ["序数词"] = "ordinal",
    ["序文"] = "preface",
    ["序时账"] = "chronological account",
    ["序曲"] = "prelude",
    ["序次"] = "order",
    ["序盘"] = "opening",
    ["序目"] = "preface index",
    ["序章"] = "prologue",
    ["序言"] = "preface",
    ["序言部分"] = "preface section",
    ["序论"] = "preface",
    ["序词"] = "preface word",
    ["序跋"] = "preface and postscript",
    ["序齿"] = "order by age",
}

return M
