local M = {}

M.mapping = {
    ["勘丈法"] = "survey method",
    ["勘十郎"] = "kurozumi kanjuro",
    ["勘定"] = "accounting",
    ["勘察"] = "prospect",
    ["勘察局"] = "survey bureau",
    ["勘察设计"] = "prospecting design",
    ["勘察设计注册冶金工程师制度暂行规定"] = "provisional regulations on registered metallurgical engineers for prospecting and design",
    ["勘察设计注册机械工程师制度暂行规定"] = "provisional regulations on registered mechanical engineers for prospecting and design",
    ["勘察设计注册石油天然气工程师制度暂行规定"] = "provisional regulations on registered oil and gas engineers for prospecting and design",
    ["勘察院"] = "prospecting institute",
    ["勘探"] = "stand ticket",
    ["勘探局"] = "exploration bureau",
    ["勘探工程"] = "exploration project",
    ["勘探开发"] = "exploration and development",
    ["勘探期"] = "exploration period",
    ["勘探者"] = "explorer",
    ["勘探部"] = "exploration department",
    ["勘探队"] = "exploration team",
    ["勘查"] = "explore",
    ["勘查区"] = "exploration area",
    ["勘查局"] = "exploration bureau",
    ["勘查院"] = "exploration institute",
    ["勘校"] = "proofread",
    ["勘正"] = "proofread",
    ["勘测"] = "survey",
    ["勘测大队"] = "survey team",
    ["勘测设计"] = "survey and design",
    ["勘测队"] = "survey crew",
    ["勘界"] = "demarcate",
    ["勘破"] = "penetrate",
    ["勘误"] = "errata",
    ["勘误表"] = "errata list",
    ["勘验"] = "inspection",
    ["勘验笔录"] = "inspection record",
}

return M
