local M = {}

M.mapping = {
    ["刨丝"] = "shredding",
    ["刨丝器"] = "shredder",
    ["刨光"] = "planing",
    ["刨冰"] = "shaved ice",
    ["刨冰机"] = "ice shaver",
    ["刨出去"] = "dig out",
    ["刨刀"] = "planer blade",
    ["刨刃"] = "planer blade",
    ["刨刃儿"] = "planer blade",
    ["刨削"] = "planing",
    ["刨去"] = "deduct",
    ["刨土"] = "dig soil",
    ["刨地"] = "dig ground",
    ["刨坑"] = "dig pits",
    ["刨头"] = "planer head",
    ["刨子"] = "plane",
    ["刨工"] = "planing work",
    ["刨平"] = "plane",
    ["刨床"] = "planer",
    ["刨木头"] = "plane wood",
    ["刨树搜根"] = "dig deep",
    ["刨根"] = "dig roots",
    ["刨根儿"] = "dig roots",
    ["刨根挖底"] = "dig deep",
    ["刨根究底"] = "get to the root",
    ["刨根问底"] = "inquire thoroughly",
    ["刨槽"] = "grooving",
    ["刨汤肉"] = "boiled meat",
    ["刨活"] = "undermine",
    ["刨活儿"] = "undermine",
    ["刨祖坟"] = "digging ancestral graves",
    ["刨花"] = "wood shavings",
    ["刨花板"] = "particle board",
    ["刨花板厂"] = "particle board factory",
    ["刨身"] = "body planing",
    ["刨除"] = "exclude",
    ["刨食"] = "forage",
    ["刨食儿"] = "scavenge",
}

return M
