local M = {}

M.mapping = {
    ["廖二平"] = "liao erping",
    ["廖仲恺"] = "liao zhongkai",
    ["廖俊涛"] = "liao juntao",
    ["廖公庄"] = "liaogongzhuang",
    ["廖公庄东站"] = "liaogongzhuang east station",
    ["廖凡"] = "liao fan",
    ["廖力生"] = "liao lisheng",
    ["廖化"] = "liao hua",
    ["廖化作先锋"] = "liao hua leads the vanguard",
    ["廖厝村"] = "liaocuo village",
    ["廖启智"] = "lawrence ng",
    ["廖国勋"] = "liao guoxun",
    ["廖国荣"] = "liao guorong",
    ["廖姓"] = "liao surname",
    ["廖子介"] = "liao zijie",
    ["廖家冲"] = "liao jiachong",
    ["廖家坡"] = "liao jiapo",
    ["廖家坪"] = "liao jiaping",
    ["廖家坪村"] = "liao jiaping village",
    ["廖家巷"] = "liao jia lane",
    ["廖家村"] = "liao jia village",
    ["廖家湾"] = "liao jiawan",
    ["廖家祠"] = "liao jia ancestral hall",
    ["廖峻涛"] = "liao juntao",
    ["廖廓街道"] = "liaokuo street",
    ["廖慧敏"] = "liao huimin",
    ["廖承志"] = "liao chengzhi",
    ["廖政国"] = "liao zhengguo",
    ["廖文毅"] = "liao wenyi",
    ["廖新波"] = "liao xinbo",
    ["廖月生"] = "liao yuesheng",
    ["廖某"] = "liao mou",
    ["廖桂永"] = "liao guiyong",
    ["廖梦雪"] = "liao mengxue",
    ["廖海军"] = "liao haijun",
    ["廖添丁"] = "liao tianding",
    ["廖秋云"] = "qiu yun liao",
    ["廖美英"] = "liao meiying",
    ["廖耀湘"] = "liao yaoxiang",
    ["廖角山多鳃鱼"] = "liao jiao mountain polybranch fish",
    ["廖警官"] = "officer liao",
    ["廖静文"] = "liao jingwen",
}

return M
