local M = {}

M.mapping = {
    ["坠下"] = "fall down",
    ["坠下来"] = "fall down",
    ["坠亡"] = "fall to death",
    ["坠入"] = "fall into",
    ["坠入地狱"] = "fall into hell",
    ["坠入情网"] = "fall in love",
    ["坠入爱河"] = "fall in love",
    ["坠地"] = "fall to ground",
    ["坠失"] = "fall loss",
    ["坠子"] = "pendant",
    ["坠崖"] = "cliff fall",
    ["坠心"] = "heart-sinking",
    ["坠机"] = "plane crash",
    ["坠机事件"] = "air crash incident",
    ["坠机事故"] = "plane crash",
    ["坠机身亡"] = "plane crash death",
    ["坠楼"] = "falling",
    ["坠楼案"] = "falling case",
    ["坠毁"] = "crash",
    ["坠毁了"] = "crashed",
    ["坠海"] = "fall into sea",
    ["坠渊加膝"] = "favoritism",
    ["坠琴"] = "zhuiquin",
    ["坠着"] = "hanging",
    ["坠积性肺炎"] = "hypostatic pneumonia",
    ["坠胡"] = "zhui hu",
    ["坠落"] = "fall",
    ["坠落伤"] = "fall injury",
    ["坠落在"] = "falling into",
    ["坠落的"] = "fallen",
    ["坠车"] = "car fall",
    ["坠饰"] = "pendant",
    ["坠马"] = "falling off horse",
}

return M
