local M = {}

M.mapping = {
    ["宅内"] = "inside residence",
    ["宅北乡"] = "north village",
    ["宅友"] = "homebody friend",
    ["宅吧"] = "house bar",
    ["宅园"] = "house garden",
    ["宅在"] = "stay at home",
    ["宅在家"] = "stay home",
    ["宅在家里"] = "stay at home",
    ["宅地"] = "homestead",
    ["宅地法"] = "homestead act",
    ["宅基"] = "homestead",
    ["宅基地"] = "homestead land",
    ["宅基地使用权"] = "homestead use right",
    ["宅基地法律问题"] = "homestead legal issues",
    ["宅基地纠纷"] = "homestead dispute",
    ["宅基地证"] = "homestead certificate",
    ["宅墙"] = "house wall",
    ["宅女"] = "otaku girl",
    ["宅子"] = "house",
    ["宅宅"] = "otaku",
    ["宅家"] = "stay home",
    ["宅心仁厚"] = "benevolent",
    ["宅心宽厚"] = "kind-hearted",
    ["宅心忠厚"] = "loyal and kind",
    ["宅急便"] = "takkyubin",
    ["宅急送"] = "zjs express",
    ["宅泥鱼"] = "residence fish",
    ["宅电"] = "home phone",
    ["宅男"] = "otaku",
    ["宅科"] = "zhaike",
    ["宅第"] = "residence",
    ["宅舍"] = "residence",
    ["宅西"] = "west of residence",
    ["宅边"] = "beside house",
    ["宅边有五柳树"] = "five willows beside house",
    ["宅邸"] = "mansion",
    ["宅门"] = "residence gate",
    ["宅院"] = "house and courtyard",
}

return M
