local M = {}

M.mapping = {
    ["幕上燕巢"] = "female snake",
    ["幕下"] = "under the curtain",
    ["幕僚"] = "advisor",
    ["幕僚长"] = "chief of staff",
    ["幕前"] = "onstage",
    ["幕前幕后"] = "onstage and backstage",
    ["幕友"] = "private advisor",
    ["幕后"] = "behind the scenes",
    ["幕后交易"] = "backroom deal",
    ["幕后人"] = "behind-the-scenes figure",
    ["幕后人物"] = "power behind the throne",
    ["幕后指挥"] = "backstage command",
    ["幕后指点"] = "backstage guidance",
    ["幕后操作"] = "backstage operation",
    ["幕后操纵"] = "pull strings",
    ["幕后活动"] = "backstage activity",
    ["幕后策划"] = "mastermind",
    ["幕后英雄"] = "unsung hero",
    ["幕后黑手"] = "mastermind",
    ["幕吏"] = "curtain official",
    ["幕墙"] = "curtain wall",
    ["幕天席地"] = "sleep under the open sky",
    ["幕客"] = "guest advisor",
    ["幕宾"] = "advisor",
    ["幕布"] = "curtain",
    ["幕幕"] = "veiled",
    ["幕府"] = "shogunate",
    ["幕府佳园"] = "shogunate garden",
    ["幕府制度"] = "shogunate system",
    ["幕府将军"] = "shogun",
    ["幕府山庄"] = "shogunate villa",
    ["幕府旧烟青"] = "shogunate old smoke",
    ["幕府时代"] = "shogunate era",
    ["幕府西路"] = "shogunate west road",
    ["幕村"] = "screen village",
    ["幕燕釜鱼"] = "sword of damocles",
    ["幕落"] = "curtain fall",
    ["幕里红丝"] = "curtain red silk",
    ["幕间曲"] = "intermezzo",
    ["幕骨"] = "tentorium",
}

return M
