local M = {}

M.mapping = {
    ["冶仙塔"] = "yexian pagoda",
    ["冶城"] = "yecheng",
    ["冶天"] = "ati",
    ["冶容"] = "seductive",
    ["冶山道院"] = "yeshan daoist temple",
    ["冶源"] = "yeyuan",
    ["冶源镇"] = "yeyuan town",
    ["冶炼"] = "smelting",
    ["冶炼专家"] = "smelting expert",
    ["冶炼业"] = "smelting industry",
    ["冶炼厂"] = "smelter",
    ["冶炼工"] = "smelter",
    ["冶炼技术"] = "smelting tech",
    ["冶炼设备"] = "smelting equipment",
    ["冶父山"] = "yefu mountain",
    ["冶艳"] = "glamorous",
    ["冶金"] = "metallurgy",
    ["冶金业"] = "metallurgical industry",
    ["冶金厂"] = "metallurgical plant",
    ["冶金学"] = "metallurgy",
    ["冶金学家"] = "metallurgist",
    ["冶金家"] = "metallurgist",
    ["冶金局"] = "metallurgical bureau",
    ["冶金工业"] = "metallurgical industry",
    ["冶金工业局"] = "bureau of metallurgical industry",
    ["冶金工业部"] = "ministry of metallurgical industry",
    ["冶金工程"] = "metallurgical engineering",
    ["冶金技校"] = "metallurgical technical school",
    ["冶金术"] = "metallurgical art",
    ["冶金机械"] = "metallurgical machinery",
    ["冶金矿产"] = "metallurgical minerals",
    ["冶金行业"] = "metallurgical sector",
    ["冶金路"] = "metallurgy road",
    ["冶金部"] = "ministry of metallurgy",
    ["冶铁"] = "iron smelting",
    ["冶铸"] = "smelting",
    ["冶锻"] = "forge and smelt",
    ["冶陶"] = "pottery making",
    ["冶鸟"] = "ye bird",
}

return M
