local M = {}

M.mapping = {
    ["块人独处"] = "solitary person",
    ["块体"] = "bulk",
    ["块儿"] = "piece",
    ["块儿八角"] = "small change",
    ["块元素"] = "block element",
    ["块块"] = "blocks",
    ["块垒"] = "block",
    ["块头"] = "build",
    ["块密码"] = "block cipher",
    ["块料"] = "material",
    ["块村营"] = "kuai village camp",
    ["块根"] = "tuber",
    ["块然一身"] = "solitary",
    ["块煤"] = "lump coal",
    ["块状"] = "blocky",
    ["块状元素"] = "block element",
    ["块状树"] = "block tree",
    ["块状物"] = "chunk",
    ["块状链表"] = "block linked list",
    ["块砖"] = "block brick",
    ["块糖"] = "cube sugar",
    ["块级作用域"] = "block-level scope",
    ["块级元素"] = "block-level element",
    ["块结构"] = "block structure",
    ["块结构语言"] = "block-structured language",
    ["块肉"] = "chunk meat",
    ["块茎"] = "tuber",
    ["块茎作物"] = "tuber crop",
    ["块菌"] = "truffle",
    ["块规"] = "gauge block",
    ["块设备"] = "block device",
    ["块钱"] = "yuan",
    ["块钱的"] = "yuan",
}

return M
