local M = {}

M.mapping = {
    ["句中"] = "in the sentence",
    ["句句"] = "every sentence",
    ["句句真研"] = "study every word",
    ["句号"] = "period",
    ["句型"] = "sentence pattern",
    ["句型分析"] = "sentence analysis",
    ["句型练习"] = "sentence practice",
    ["句城村"] = "jucheng village",
    ["句子"] = "sentence",
    ["句子中"] = "in sentence",
    ["句子成分"] = "sentence component",
    ["句子片段"] = "sentence fragment",
    ["句容"] = "jurong",
    ["句容县"] = "jurong county",
    ["句容市"] = "jurong city",
    ["句容市方山茶场"] = "jurong fangshan tea farm",
    ["句尾"] = "end of sentence",
    ["句式"] = "sentence pattern",
    ["句有可削"] = "wordy",
    ["句末"] = "end of sentence",
    ["句柄"] = "handle",
    ["句柄数"] = "handle count",
    ["句柄类"] = "handle class",
    ["句法"] = "syntax",
    ["句法关系"] = "syntactic relation",
    ["句法分析"] = "syntax analysis",
    ["句法树"] = "syntax tree",
    ["句法模式识别"] = "syntactic pattern recognition",
    ["句法结构"] = "syntactic structure",
    ["句法规则"] = "syntactic rule",
    ["句点"] = "period",
    ["句类"] = "sentence type",
    ["句群"] = "sentence group",
    ["句芒"] = "jumang",
    ["句话"] = "sentence",
    ["句读"] = "punctuation",
    ["句读之不知"] = "unable to punctuate",
    ["句首"] = "sentence start",
}

return M
