local M = {}

M.mapping = {
    ["奴为出来难"] = "servant's lament",
    ["奴仆"] = "servant",
    ["奴佛卡因"] = "novocaine",
    ["奴假鳃虱"] = "nujia gills louse",
    ["奴化"] = "enslave",
    ["奴婢"] = "slaves",
    ["奴家"] = "i",
    ["奴尔巴格街道"] = "nurbag street",
    ["奴尔干都司"] = "nurgan commandery",
    ["奴工"] = "slave labor",
    ["奴布拉鼠兔"] = "nubra pika",
    ["奴役"] = "enslave",
    ["奴役性"] = "enslavement",
    ["奴役恶魔"] = "enslave demon",
    ["奴役蚁"] = "slave ant",
    ["奴性"] = "servility",
    ["奴性十足"] = "submissive",
    ["奴才"] = "lackey",
    ["奴才相"] = "servile demeanor",
    ["奴比亚奶山羊"] = "nubian dairy goat",
    ["奴辈"] = "servants",
    ["奴隶"] = "slave",
    ["奴隶主"] = "slave owner",
    ["奴隶主义"] = "slave ideology",
    ["奴隶主阶级"] = "slave-owning class",
    ["奴隶亡灵"] = "slave spirits",
    ["奴隶人"] = "slave",
    ["奴隶制"] = "slavery",
    ["奴隶制五刑"] = "five penalties of slavery",
    ["奴隶制度"] = "slave system",
    ["奴隶制法"] = "slave law",
    ["奴隶区"] = "slave zone",
    ["奴隶宪法"] = "slave constitution",
    ["奴隶社会"] = "slave society",
    ["奴隶贩子"] = "slave trader",
    ["奴隶贸易"] = "slave trade",
    ["奴隶阶级"] = "slave class",
    ["奴面不如花面好"] = "slave face worse than flower",
    ["奴颜"] = "servile",
    ["奴颜婢膝"] = "obsequious",
    ["奴颜媚骨"] = "fawning",
}

return M
