local M = {}

M.mapping = {
    ["庐光尺蛾"] = "eupithecia luzhouensis",
    ["庐冢"] = "lu tomb",
    ["庐剧"] = "lu opera",
    ["庐山"] = "mount lu",
    ["庐山东南五老峰"] = "five old peaks of lushan",
    ["庐山云雾"] = "lushan clouds",
    ["庐山云雾茶"] = "lushan cloud tea",
    ["庐山会议"] = "lushan conference",
    ["庐山区"] = "lushan district",
    ["庐山华穹螽"] = "lushan huqiong grasshopper",
    ["庐山图"] = "lushan painting",
    ["庐山大厦"] = "lushan plaza",
    ["庐山巨蟹蛛"] = "lushan crab spider",
    ["庐山瀑布"] = "lushan waterfall",
    ["庐山真面"] = "true face of lushan",
    ["庐山真面目"] = "true colors of lushan",
    ["庐山石耳"] = "lushan stone ear",
    ["庐山石鱼"] = "lushan stone fish",
    ["庐山石鸡"] = "lushan stone frog",
    ["庐山谣寄卢侍御虚舟"] = "lushan poem to lu xuzhou",
    ["庐山路"] = "lushan road",
    ["庐山野猪"] = "lushan wild boar",
    ["庐山面目"] = "true face of lushan",
    ["庐山风景名胜区"] = "lushan scenic area",
    ["庐州"] = "luzhou",
    ["庐州太太"] = "luzhou wife",
    ["庐江"] = "lu jiang",
    ["庐江主人妇"] = "lu jiang zhu ren fu",
    ["庐江县"] = "lu jiang county",
    ["庐江县大成水产冷冻厂"] = "lu jiang dacheng aquatic products",
    ["庐江小吏仲卿妻"] = "lu jiang xiao li zhong qing qi",
    ["庐江小红头"] = "lu jiang xiao hong tou",
    ["庐江路"] = "lu jiang road",
    ["庐江郡"] = "lu jiang jun",
    ["庐舍"] = "cottage",
    ["庐阳"] = "luyang",
    ["庐阳区"] = "luyang district",
    ["庐陵"] = "luling",
    ["庐陵欧阳修也"] = "ouyang xiu of luling",
}

return M
