local M = {}

M.mapping = {
    ["倪一膺"] = "ni yiying",
    ["倪东艳"] = "ni dongyan",
    ["倪俊龙"] = "ni junlong",
    ["倪元璐"] = "ni yuanlu",
    ["倪光南"] = "ni guangnan",
    ["倪克斯神谕"] = "nyx oracle",
    ["倪嗣冲"] = "ni sichong",
    ["倪夏莲"] = "ni xialian",
    ["倪大红"] = "ni dahong",
    ["倪妮"] = "ni ni",
    ["倪姓"] = "ni surname",
    ["倪家"] = "ni family",
    ["倪家堰"] = "nijia weir",
    ["倪家巷"] = "nijia lane",
    ["倪家桥"] = "nijiaqiao",
    ["倪家桥路"] = "nijiaqiao road",
    ["倪岳峰"] = "ni yuefeng",
    ["倪志华"] = "backstop",
    ["倪敏然"] = "ni minran",
    ["倪景阳"] = "ni jingyang",
    ["倪朝搢"] = "ni chaojin",
    ["倪梁康"] = "ni liangkang",
    ["倪洪章"] = "ni hongzhang",
    ["倪海杉"] = "ni haishan",
    ["倪焕之"] = "ni huanzhi",
    ["倪瓒"] = "ni zan",
    ["倪田"] = "ni tian",
    ["倪睿思"] = "ni ruisi",
    ["倪萍"] = "ni ping",
    ["倪葆春"] = "ni baochun",
    ["倪虹洁"] = "ni hongjie",
    ["倪超"] = "ni chao",
    ["倪震"] = "ni zhen",
    ["倪鸿"] = "ni hong",
}

return M
