local M = {}

M.mapping = {
    ["冤业"] = "karmic debt",
    ["冤亲"] = "enemy",
    ["冤仇"] = "enmity",
    ["冤仇可解不可结"] = "better to get rid of an enmity than keep it",
    ["冤假错案"] = "unjust cases",
    ["冤冤相报"] = "vendetta",
    ["冤冤相报何时了"] = "endless vendetta",
    ["冤大头"] = "easy mark",
    ["冤天屈地"] = "wronged heaven earth",
    ["冤头"] = "wronged head",
    ["冤孽"] = "karma",
    ["冤家"] = "enemy",
    ["冤家亲家"] = "enemies turned in-laws",
    ["冤家债主"] = "creditor enemy",
    ["冤家宜解不宜结"] = "better to make friends than enemies",
    ["冤家对头"] = "sworn enemies",
    ["冤家路窄"] = "enemies cross paths",
    ["冤屈"] = "injustice",
    ["冤恨"] = "wronged hatred",
    ["冤情"] = "grievance",
    ["冤有头"] = "debt has owner",
    ["冤杀"] = "wrongful execution",
    ["冤枉"] = "wronged",
    ["冤枉了"] = "wronged someone",
    ["冤枉了你"] = "wronged you",
    ["冤枉路"] = "detour",
    ["冤枉钱"] = "wasted money",
    ["冤案"] = "miscarriage of justice",
    ["冤死"] = "wrongful death",
    ["冤气"] = "injustice",
    ["冤狱"] = "unjust trial",
    ["冤种"] = "unlucky person",
    ["冤苦"] = "injustice and suffering",
    ["冤钱"] = "unjust money",
    ["冤鬼"] = "wronged ghost",
    ["冤鬼路"] = "wronged ghost road",
    ["冤魂"] = "wronged ghost",
    ["冤魂不散"] = "lingering spirit",
}

return M
