local M = {}

M.mapping = {
    ["坡上"] = "on slope",
    ["坡上村"] = "poshang village",
    ["坡下"] = "downhill",
    ["坡刘村"] = "poliu village",
    ["坡县"] = "slope county",
    ["坡地"] = "sloping land",
    ["坡坑"] = "slope pit",
    ["坡坡岭岭"] = "slopes and hills",
    ["坡垒"] = "hopea",
    ["坡塘"] = "slope pond",
    ["坡头"] = "slope head",
    ["坡头区"] = "potou district",
    ["坡子"] = "slope",
    ["坡子街"] = "pozi street",
    ["坡底街道"] = "podijie street",
    ["坡度"] = "slope",
    ["坡度变化"] = "slope change",
    ["坡改梯"] = "slope to terrace",
    ["坡普腹链蛇"] = "pop's belly-chain snake",
    ["坡李村"] = "poli village",
    ["坡楼"] = "slope building",
    ["坡狗"] = "slope dog",
    ["坡田"] = "slope field",
    ["坡积物"] = "colluvium",
    ["坡胡镇"] = "pohu town",
    ["坡脚镇"] = "pojiao town",
    ["坡荷乡"] = "pohe township",
    ["坡角"] = "slope angle",
    ["坡跟"] = "wedge heel",
    ["坡跟凉鞋"] = "wedge sandals",
    ["坡跟鞋"] = "wedge shoes",
    ["坡路"] = "slope road",
    ["坡道"] = "ramp",
    ["坡里"] = "poli",
    ["坡面"] = "slope",
    ["坡顶"] = "hilltop",
    ["坡鹿"] = "eld's deer",
}

return M
