local M = {}

M.mapping = {
    ["弦乐"] = "strings",
    ["弦乐器"] = "string instrument",
    ["弦乐器组"] = "string section",
    ["弦乐四重奏"] = "string quartet",
    ["弦乐团"] = "string ensemble",
    ["弦乐队"] = "string orchestra",
    ["弦凝指咽声停处"] = "strings pause fingers stop",
    ["弦切角"] = "chord angle",
    ["弦动我心"] = "music moves me",
    ["弦图"] = "chord diagram",
    ["弦声"] = "string sound",
    ["弦外之意"] = "implied meaning",
    ["弦外之音"] = "hidden meaning",
    ["弦外有音"] = "overtones",
    ["弦子"] = "xianzi instrument",
    ["弦子戏"] = "xianzi opera",
    ["弦山街道"] = "xianshan subdistrict",
    ["弦平音自足"] = "balanced strings sound full",
    ["弦弦掩抑声声思"] = "each string muffled, full of longing",
    ["弦急悲声发"] = "urgent strings sad sound",
    ["弦无虚发"] = "no missed shots",
    ["弦月"] = "crescent moon",
    ["弦月枯叶蛾"] = "crescent moon lappet moth",
    ["弦歌"] = "string music",
    ["弦的"] = "chordal",
    ["弦索"] = "stringed instrument",
    ["弦纹"] = "bowstring pattern",
    ["弦线"] = "string",
    ["弦诵"] = "string chanting",
    ["弦轴"] = "tuning peg",
    ["弦长公式"] = "chord length formula",
    ["弦音"] = "string sound",
    ["弦鸣乐器"] = "chordophone",
    ["弦鼓一声双袖举"] = "sleeves rise with drumbeat",
}

return M
