local M = {}

M.mapping = {
    ["座上"] = "on seat",
    ["座上客"] = "honored guest",
    ["座上客常满"] = "guests always full",
    ["座上宾"] = "guest of honor",
    ["座下"] = "under seat",
    ["座位"] = "seat",
    ["座位上"] = "on seat",
    ["座位号"] = "seat number",
    ["座位数"] = "seat count",
    ["座位表"] = "seating chart",
    ["座儿"] = "seat",
    ["座充"] = "desk charger",
    ["座右铭"] = "motto",
    ["座号"] = "seat number",
    ["座圈"] = "seat ring",
    ["座地式"] = "floor-standing",
    ["座头鲸"] = "humpback whale",
    ["座套"] = "seat cover",
    ["座子"] = "seat",
    ["座对贤人酒"] = "wine with sages",
    ["座导凿"] = "guide chisel",
    ["座山雕"] = "mountain eagle",
    ["座席"] = "seat",
    ["座无虚席"] = "full house",
    ["座机"] = "landline",
    ["座机费"] = "landline fee",
    ["座板"] = "seat board",
    ["座椅"] = "seat",
    ["座椅上"] = "on the seat",
    ["座椅加热"] = "seat heating",
    ["座椅及附件"] = "seats and accessories",
    ["座椅调整器"] = "seat adjuster",
    ["座椅靠背"] = "seat back",
    ["座次"] = "seating",
    ["座次图"] = "seating map",
    ["座次表"] = "seating chart",
    ["座舱"] = "cockpit",
    ["座谈"] = "seminar",
    ["座谈会"] = "forum",
    ["座钟"] = "desk clock",
    ["座驾"] = "car",
}

return M
