local M = {}

M.mapping = {
    ["峰下"] = "below peak",
    ["峰不二子"] = "fujiko mine",
    ["峰中"] = "in the peak",
    ["峰会"] = "summit",
    ["峰位"] = "peak position",
    ["峰值"] = "peak value",
    ["峰值功率"] = "peak power",
    ["峰前"] = "front of peak",
    ["峰前小学"] = "fengqian primary school",
    ["峰前村"] = "fengqian village",
    ["峰前街"] = "fengqian street",
    ["峰南村"] = "fengnan village",
    ["峰回路转"] = "winding path",
    ["峰堆乡"] = "fengdui township",
    ["峰多巧障日"] = "peaks block sun",
    ["峰尖"] = "peak",
    ["峰尾镇"] = "fengwei town",
    ["峰岩乡"] = "fengyan village",
    ["峰峦"] = "peaks",
    ["峰峦叠嶂"] = "range upon range of mountains",
    ["峰峰矿区"] = "fengfeng mining area",
    ["峰峰集团总医院"] = "fengfeng group general hospital",
    ["峰崎村"] = "minezaki village",
    ["峰嶂亦冥密"] = "peaks shrouded in darkness",
    ["峰巅"] = "peak",
    ["峰年"] = "peak year",
    ["峰期"] = "peak period",
    ["峰来到"] = "peak arrives",
    ["峰林"] = "peak forest",
    ["峰灵乡"] = "fengling township",
    ["峰谷"] = "peak and valley",
    ["峰顶"] = "mountain top",
    ["峰骈仙掌出"] = "peak like immortal's palm emerges",
    ["峰高"] = "peak high",
}

return M
