local M = {}

M.mapping = {
    ["孕三烯酮"] = "gestrinone",
    ["孕三烯酮胶囊"] = "gestrinone capsules",
    ["孕中期"] = "second trimester",
    ["孕二烯酮"] = "gestodene",
    ["孕产"] = "pregnancy",
    ["孕产妇"] = "pregnant women",
    ["孕产期"] = "pregnancy period",
    ["孕假"] = "maternity leave",
    ["孕初期"] = "early pregnancy",
    ["孕前"] = "pre-pregnancy",
    ["孕吐"] = "morning sickness",
    ["孕周"] = "gestational week",
    ["孕囊"] = "gestational sac",
    ["孕囊回声"] = "gestational sac echo",
    ["孕妇"] = "pregnant woman",
    ["孕妇盗窃团"] = "pregnant women theft ring",
    ["孕妇装"] = "maternity wear",
    ["孕妊"] = "pregnancy",
    ["孕婴"] = "maternity and infant",
    ["孕婴用品"] = "maternity and baby products",
    ["孕康口服液"] = "yunkang oral liquid",
    ["孕情"] = "pregnancy status",
    ["孕早期"] = "early pregnancy",
    ["孕晚期"] = "late pregnancy",
    ["孕期"] = "pregnancy",
    ["孕检"] = "prenatal checkup",
    ["孕激素"] = "progestin",
    ["孕畜"] = "pregnant livestock",
    ["孕穗"] = "boot stage",
    ["孕穗期"] = "boot phase",
    ["孕肚"] = "pregnant belly",
    ["孕育"] = "conception",
    ["孕育出"] = "give birth to",
    ["孕育处"] = "place of conception",
    ["孕育期"] = "gestation period",
    ["孕育着"] = "pregnant with",
    ["孕蕾"] = "budding",
    ["孕酮"] = "progesterone",
    ["孕酮测定"] = "progesterone test",
    ["孕震"] = "seismic gestation",
}

return M
