local M = {}

M.mapping = {
    ["店上村委会"] = "dianshang village committee",
    ["店下"] = "under store",
    ["店东"] = "shop owner",
    ["店中"] = "in the store",
    ["店主"] = "shopkeeper",
    ["店伙计"] = "shop assistant",
    ["店内"] = "inside the temple",
    ["店内样品试用"] = "electric energy",
    ["店口"] = "diankou",
    ["店号"] = "store number",
    ["店名"] = "store name",
    ["店名称"] = "store name",
    ["店员"] = "shop assistant",
    ["店址"] = "store address",
    ["店堂"] = "shop hall",
    ["店外"] = "outside store",
    ["店头"] = "shop front",
    ["店子"] = "shop",
    ["店子村"] = "dianzi village",
    ["店家"] = "shopkeeper",
    ["店容"] = "store appearance",
    ["店小二"] = "waiter",
    ["店庆"] = "store anniversary",
    ["店张街道"] = "dianzhang street",
    ["店排"] = "shop row",
    ["店王"] = "store king",
    ["店租"] = "shop rent",
    ["店貌"] = "store appearance",
    ["店里"] = "in the store",
    ["店钱"] = "inn money",
    ["店铺"] = "shop",
    ["店铺优惠"] = "shop discount",
    ["店铺在此"] = "shop here",
    ["店铺扒手"] = "shop thief",
    ["店长"] = "store manager",
    ["店门"] = "shop door",
    ["店集乡"] = "dianji township",
    ["店面"] = "storefront",
    ["店面装修"] = "store renovation",
    ["店风"] = "store atmosphere",
}

return M
