local M = {}

M.mapping = {
    ["剥下"] = "peel off",
    ["剥不了"] = "cannot peel",
    ["剥了"] = "peeled",
    ["剥光"] = "strip naked",
    ["剥削"] = "exploitation",
    ["剥削制度"] = "exploitative system",
    ["剥削压迫"] = "exploitation and oppression",
    ["剥削者"] = "exploiter",
    ["剥削阶级"] = "exploiting class",
    ["剥卦"] = "bo hexagram",
    ["剥去"] = "strip off",
    ["剥取"] = "strip",
    ["剥啄"] = "peck",
    ["剥壳"] = "shelling",
    ["剥夺"] = "deprivation",
    ["剥夺了"] = "deprived",
    ["剥夺公权"] = "deprivation of civil rights",
    ["剥夺政治权利"] = "deprivation of political rights",
    ["剥夺政治权利终身"] = "deprivation of political rights for life",
    ["剥夺者"] = "depriver",
    ["剥开"] = "peel open",
    ["剥得"] = "peeled",
    ["剥掉"] = "peel off",
    ["剥皮"] = "skin",
    ["剥离"] = "peel off",
    ["剥离剂"] = "stripping agent",
    ["剥离子器"] = "dissector",
    ["剥离开"] = "peel off",
    ["剥离强度"] = "peel strength",
    ["剥脱"] = "exfoliation",
    ["剥花生"] = "shell peanuts",
    ["剥茧"] = "unravel",
    ["剥落"] = "peeling",
    ["剥蒜"] = "peeling garlic",
    ["剥蚀"] = "erosion",
    ["剥蚀作用"] = "erosion",
    ["剥除"] = "strip",
}

return M
