local M = {}

M.mapping = {
    ["域中"] = "domain",
    ["域中有四大"] = "four greats in the domain",
    ["域代码"] = "domain code",
    ["域信息"] = "domain info",
    ["域内"] = "within domain",
    ["域分解"] = "domain decomposition",
    ["域名"] = "domain",
    ["域名后缀"] = "domain suffix",
    ["域名地址"] = "domain address",
    ["域名抢注"] = "domain squatting",
    ["域名指向"] = "domain pointing",
    ["域名控制器"] = "domain controller",
    ["域名服务"] = "domain service",
    ["域名服务器"] = "domain server",
    ["域名查询"] = "domain lookup",
    ["域名注册"] = "domain registration",
    ["域名申请"] = "domain application",
    ["域名称空间"] = "domain namespace",
    ["域名空间"] = "domain space",
    ["域名系统"] = "domain system",
    ["域名经济"] = "domain economy",
    ["域名解析"] = "domain resolution",
    ["域名费"] = "domain fee",
    ["域名转换"] = "domain conversion",
    ["域后缀"] = "domain suffix",
    ["域命名主机"] = "domain naming host",
    ["域城镇"] = "domain town",
    ["域外"] = "extraterritorial",
    ["域外鸡虫事可哀"] = "extraterritorial trivialities",
    ["域完整性"] = "domain integrity",
    ["域密码"] = "domain password",
    ["域扩张"] = "field extension",
    ["域控"] = "domain ctrl",
    ["域控制器"] = "domain ctrl",
    ["域本地组"] = "domain local group",
    ["域模型"] = "domain model",
    ["域民不以封疆之界"] = "governance not by borders",
    ["域网"] = "local area network",
    ["域认证"] = "domain authentication",
    ["域账号"] = "domain account",
}

return M
