local M = {}

M.mapping = {
    ["帅不"] = "handsome or not",
    ["帅不帅"] = "handsome or not",
    ["帅云霓而来御"] = "ride clouds in splendor",
    ["帅到"] = "handsome to",
    ["帅印"] = "commander seal",
    ["帅吗"] = "handsome",
    ["帅吧"] = "handsome right",
    ["帅呆"] = "super cool",
    ["帅呆了"] = "extremely cool",
    ["帅哥"] = "handsome guy",
    ["帅哥哥"] = "handsome brother",
    ["帅哥队"] = "handsome team",
    ["帅啊"] = "so handsome",
    ["帅嘛"] = "handsome",
    ["帅小伙"] = "handsome guy",
    ["帅小子"] = "cool kid",
    ["帅帅"] = "cool",
    ["帅帅帅"] = "super cool",
    ["帅帅的"] = "dashing",
    ["帅帐"] = "command tent",
    ["帅府"] = "marshal's residence",
    ["帅府园"] = "shuaifu garden",
    ["帅府园胡同"] = "shuaifu garden alley",
    ["帅得"] = "handsome as",
    ["帅得像"] = "handsome like",
    ["帅我"] = "handsome me",
    ["帅才"] = "strategic talent",
    ["帅旗"] = "banner",
    ["帅气"] = "handsome",
    ["帅男"] = "handsome man",
    ["帅的"] = "handsome",
    ["帅着呢"] = "looking handsome",
    ["帅肯迪尔"] = "shuai kendir",
    ["帅脸"] = "handsome face",
    ["帅逼"] = "handsome dude",
}

return M
