local M = {}

M.mapping = {
    ["夕不谋朝"] = "xi bu mou zhao",
    ["夕余至乎县圃"] = "sunset reaches xianpu",
    ["夕余至乎西极"] = "sunset reaches western edge",
    ["夕寐宵兴"] = "late sleep",
    ["夕弭节兮北渚"] = "sunset festival north shore",
    ["夕日红"] = "sunset red",
    ["夕晖"] = "sunset glow",
    ["夕暮"] = "dusk",
    ["夕波红处近长安"] = "sunset near chang'an",
    ["夕烟"] = "evening mist",
    ["夕照"] = "sunset",
    ["夕照寺"] = "sunset temple",
    ["夕照寺街"] = "sunset temple street",
    ["夕照寺街北口"] = "north sunset temple street",
    ["夕照寺西里社区"] = "sunset temple west community",
    ["夕狼夜蛾"] = "evening wolf moth",
    ["夕瑶"] = "xiyao",
    ["夕蚖科"] = "sunset moth family",
    ["夕贬潮阳路八千"] = "demoted to chaoyang, 8000 miles away",
    ["夕阳"] = "sunset",
    ["夕阳下"] = "under the sunset",
    ["夕阳余晖"] = "sunset glow",
    ["夕阳古道"] = "sunset ancient road",
    ["夕阳在山"] = "sunset on the mountain",
    ["夕阳彝族乡"] = "sunset yi township",
    ["夕阳忧子孙"] = "sunset worries descendants",
    ["夕阳无限好"] = "endless beautiful sunset",
    ["夕阳穷登攀"] = "sunset endless climb",
    ["夕阳笔螺"] = "sunset volute",
    ["夕阳箫鼓"] = "sunset flute and drum",
    ["夕阳箫鼓几船归"] = "how many boats return at sunset flute and drum",
    ["夕阳红"] = "sunset glow",
    ["夕阳蝴蝶鱼"] = "sunset butterflyfish",
    ["夕阳西下"] = "sunset",
    ["夕阳西下几时回"] = "when will the sunset return",
    ["夕阳黄文蛤"] = "sunset yellow clam",
    ["夕露沾我衣"] = "evening dew wets my clothes",
    ["夕露见日晞"] = "morning dew meets sun",
    ["夕餐秋菊之落英"] = "dine on chrysanthemum petals",
    ["夕鹤"] = "evening crane",
}

return M
