local M = {}

M.mapping = {
    ["奏一"] = "play one",
    ["奏之"] = "play it",
    ["奏之曲"] = "play the song",
    ["奏乐"] = "play music",
    ["奏乐队"] = "orchestra",
    ["奏书"] = "petition",
    ["奏凯"] = "triumph",
    ["奏凯歌"] = "sing victory",
    ["奏出"] = "play out",
    ["奏出来"] = "play out",
    ["奏功"] = "achieve success",
    ["奏响"] = "play",
    ["奏国歌"] = "play national anthem",
    ["奏定学堂章程"] = "school regulations",
    ["奏技"] = "perform skill",
    ["奏折"] = "palace memorial",
    ["奏报"] = "report to throne",
    ["奏捷"] = "victory",
    ["奏效"] = "work",
    ["奏明"] = "report to emperor",
    ["奏曲"] = "play music",
    ["奏曹掾"] = "music official",
    ["奏本"] = "memorial to throne",
    ["奏流水以何惭"] = "play water without shame",
    ["奏状"] = "petition",
    ["奏琴"] = "play qin",
    ["奏疏"] = "memorial",
    ["奏章"] = "memorial",
    ["奏表"] = "memorial tablet",
    ["奏议"] = "memorial to throne",
    ["奏请"] = "petition",
    ["奏起"] = "play",
    ["奏起来"] = "play up",
    ["奏过"] = "played",
    ["奏鸣"] = "sonata",
    ["奏鸣曲"] = "sonata",
    ["奏鸣曲式"] = "sonata form",
}

return M
