local M = {}

M.mapping = {
    ["咽一咽"] = "swallow",
    ["咽下"] = "swallow",
    ["咽下去"] = "swallow down",
    ["咽不下"] = "can't stomach",
    ["咽不了"] = "can't swallow",
    ["咽了"] = "swallowed",
    ["咽了咽"] = "swallowed",
    ["咽后壁脓肿"] = "retropharyngeal abscess",
    ["咽后痈"] = "retropharyngeal carbuncle",
    ["咽后间隙"] = "retropharyngeal space",
    ["咽咽"] = "gurgle",
    ["咽喉"] = "throat",
    ["咽喉异物"] = "throat foreign body",
    ["咽喉溃疡"] = "throat ulcer",
    ["咽喉炎"] = "pharyngitis",
    ["咽喉痛"] = "sore throat",
    ["咽喉肿痛"] = "sore throat",
    ["咽喉要地"] = "strategic location",
    ["咽喉部"] = "throat area",
    ["咽峡炎"] = "tonsillitis",
    ["咽干"] = "dry throat",
    ["咽干咽痛"] = "dry throat sore throat",
    ["咽扁桃体"] = "pharyngeal tonsil",
    ["咽拭子"] = "throat swab",
    ["咽旁间隙"] = "parapharyngeal space",
    ["咽气"] = "breathe last",
    ["咽炎"] = "pharyngitis",
    ["咽炎含片"] = "pharyngitis lozenge",
    ["咽炎清片"] = "pharyngitis relief tablet",
    ["咽炎片"] = "pharyngitis tablet",
    ["咽炎药"] = "pharyngitis medicine",
    ["咽疼"] = "sore throat",
    ["咽痛"] = "throat pain",
    ["咽结膜热"] = "pharyngoconjunctival fever",
    ["咽肌痉挛"] = "pharyngeal spasm",
    ["咽苦吞甘"] = "endure hardship",
    ["咽部"] = "throat",
    ["咽部异感症"] = "globus pharyngeus",
    ["咽音"] = "pharyngeal voice",
    ["咽鼓管"] = "eustachian tube",
    ["咽鼓管咽口"] = "pharyngeal opening",
    ["咽齿"] = "pharyngeal teeth",
}

return M
