local M = {}

M.mapping = {
    ["奎依巴格镇"] = "kuiyibage town",
    ["奎元馆"] = "kuiyuan restaurant",
    ["奎元馆片儿川"] = "kuiyuan restaurant pian'er chuan",
    ["奎勒河镇"] = "kuile river town",
    ["奎因"] = "quinn",
    ["奎园小区"] = "kuiyuan residential area",
    ["奎壁"] = "kuibi",
    ["奎壁村"] = "kuibi village",
    ["奎宁"] = "quinine",
    ["奎宁水"] = "tonic water",
    ["奎宿"] = "kui constellation",
    ["奎宿九"] = "kui xiujiu",
    ["奎尔"] = "quell",
    ["奎尔丹尼"] = "queldanis",
    ["奎尔丹尼小屋"] = "queldanis cottage",
    ["奎尔林斯小屋"] = "quellien cottage",
    ["奎尼丁"] = "quinidine",
    ["奎屯"] = "kuitun",
    ["奎屯市"] = "kuitun city",
    ["奎山公园"] = "kuishan park",
    ["奎德素镇"] = "kuidesu town",
    ["奎恩"] = "quinn",
    ["奎文区"] = "kuiwen district",
    ["奎斯坦修"] = "kuistan xiu",
    ["奎星楼街"] = "kuixinglou street",
    ["奎河"] = "kuiriver",
    ["奎湖"] = "kuilake",
    ["奎溪坪村"] = "kuixiping village",
    ["奎照路"] = "kuizhao road",
    ["奎福古寺"] = "kuifu ancient temple",
    ["奎素村"] = "kuisu village",
    ["奎罗斯"] = "queiroz",
    ["奎聚"] = "kuiju",
    ["奎聚街道"] = "kuiju street",
    ["奎门村"] = "kuimen village",
    ["奎霞村"] = "kuixia village",
}

return M
