local M = {}

M.mapping = {
    ["喘不过气"] = "out of breath",
    ["喘不过气来"] = "gasp for breath",
    ["喘了"] = "panted",
    ["喘口气"] = "catch breath",
    ["喘吁吁"] = "panting",
    ["喘咳"] = "cough and pant",
    ["喘咳宁片"] = "cough relief tablets",
    ["喘喘气"] = "catch breath",
    ["喘声"] = "panting sound",
    ["喘定"] = "aminophylline",
    ["喘得"] = "panting",
    ["喘得像"] = "pant like",
    ["喘息"] = "gasp",
    ["喘息不已"] = "gasping continuously",
    ["喘息之机"] = "breathing space",
    ["喘息之间"] = "in a breath",
    ["喘息声"] = "gasping sound",
    ["喘息未安"] = "not yet settled",
    ["喘息未定"] = "not yet settled",
    ["喘息灵胶囊"] = "asthma relief capsule",
    ["喘息着"] = "gasping",
    ["喘息着说"] = "gasp out",
    ["喘月吴牛"] = "panting moon wu cow",
    ["喘气"] = "pant",
    ["喘气儿"] = "pant",
    ["喘气声"] = "panting sound",
    ["喘病"] = "asthma",
    ["喘着"] = "panting",
    ["喘着气"] = "panting",
    ["喘着粗气"] = "panting heavily",
    ["喘络通胶囊"] = "chuanluotong capsule",
    ["喘证"] = "asthma syndrome",
    ["喘鸣"] = "wheezing",
}

return M
