local M = {}

M.mapping = {
    ["凿井"] = "well drilling",
    ["凿井而饮"] = "dig well to drink",
    ["凿出"] = "chisel out",
    ["凿出来"] = "chiseled out",
    ["凿凿"] = "certain",
    ["凿刻"] = "carving",
    ["凿坏以遁"] = "escape by digging",
    ["凿坏而遁"] = "flee secretly",
    ["凿坯而遁"] = "escape",
    ["凿壁偷光"] = "bore a hole",
    ["凿子"] = "chisel",
    ["凿孔"] = "drill hole",
    ["凿山"] = "chisel mountain",
    ["凿岩"] = "rock drilling",
    ["凿岩机"] = "rock drill",
    ["凿开"] = "chisel open",
    ["凿成"] = "chiseled",
    ["凿户牖以为室"] = "carve windows for rooms",
    ["凿枘"] = "mortise",
    ["凿枘圆方"] = "fit perfectly",
    ["凿柱取书"] = "carve pillar",
    ["凿楹纳书"] = "carving inscriptions",
    ["凿沉"] = "scuttled",
    ["凿洞"] = "drill hole",
    ["凿石"] = "chisel stone",
    ["凿空"] = "hollow out",
    ["凿空丝路"] = "silk road pioneer",
    ["凿空取办"] = "extort",
    ["凿空投隙"] = "seize opportunity",
    ["凿空架虚"] = "fabricate",
    ["凿空立论"] = "force an argument",
    ["凿空者"] = "pioneer",
    ["凿穿"] = "pierce",
    ["凿花鳉"] = "rivulus",
    ["凿贝才女虫"] = "shell-boring worm",
    ["凿通"] = "tunnel through",
    ["凿险"] = "exploring dangers",
    ["凿险缒幽"] = "venture into peril",
    ["凿隧入井"] = "dig tunnel into well",
    ["凿饮耕食"] = "dig wells and farm",
    ["凿齿磨牙"] = "grind teeth",
    ["凿龟数策"] = "divine by tortoise",
}

return M
