local M = {}

M.mapping = {
    ["尹世明"] = "yin shiming",
    ["尹中立"] = "yin zhongli",
    ["尹丽川"] = "yin lichuan",
    ["尹仲容"] = "yin zhongrong",
    ["尹会一"] = "yin huiyi",
    ["尹卫红"] = "yin weihong",
    ["尹各庄村"] = "yingezhuang village",
    ["尹姓"] = "surname yin",
    ["尹姝贻"] = "yin shuyi",
    ["尹宗禹"] = "yin zongyu",
    ["尹家巷"] = "yinjia lane",
    ["尹家府"] = "yinjiafu",
    ["尹家河"] = "yinjia river",
    ["尹家河村"] = "yinjiahe village",
    ["尹家湖"] = "yinjia lake",
    ["尹家湾"] = "yinjia bay",
    ["尹家畈村"] = "yinjiafan village",
    ["尹宽"] = "yin kuan",
    ["尹庄镇"] = "yin town",
    ["尹志平"] = "yin zhiping",
    ["尹志超"] = "yin zhichao",
    ["尹成昕"] = "yin chengxin",
    ["尹旭"] = "yin xu",
    ["尹昌衡"] = "yin changheng",
    ["尹智圣"] = "yoon jisung",
    ["尹桂芳"] = "yin guifang",
    ["尹正"] = "yin zheng",
    ["尹江岸新村"] = "yinjiang'an new village",
    ["尹浩宇"] = "yin haoyu",
    ["尹灵芝镇"] = "yinlingzhi town",
    ["尹玉军"] = "yin yujun",
    ["尹相杰"] = "yin xiangjie",
    ["尹礼"] = "yin li",
    ["尹笑言"] = "yin xiaoyan",
    ["尹红"] = "yin hong",
    ["尹继善"] = "yin jishan",
    ["尹西"] = "yin xi",
    ["尹锡悦"] = "yoon suk-yeol",
}

return M
