local M = {}

M.mapping = {
    ["尸位素餐"] = "hold post without working",
    ["尸体"] = "corpse",
    ["尸体现象"] = "postmortem phenomena",
    ["尸体腐败"] = "corpse decay",
    ["尸体解剖"] = "autopsy",
    ["尸僵"] = "rigor mortis",
    ["尸冢之间"] = "between corpses and tombs",
    ["尸冷"] = "corpse cold",
    ["尸利素餐"] = "feed at the public trough",
    ["尸厥"] = "syncope",
    ["尸变"] = "corpse change",
    ["尸块"] = "body parts",
    ["尸字头"] = "corpse radical",
    ["尸居余气"] = "barely alive",
    ["尸山"] = "corpse mountain",
    ["尸巫王"] = "lich king",
    ["尸布"] = "shroud",
    ["尸斑"] = "livor mortis",
    ["尸检"] = "autopsy",
    ["尸检报告"] = "autopsy report",
    ["尸检结果"] = "autopsy result",
    ["尸横遍野"] = "corpses scattered everywhere",
    ["尸毒"] = "cadaveric poison",
    ["尸王"] = "corpse king",
    ["尸胺"] = "cadaverine",
    ["尸臭"] = "cadaver smell",
    ["尸蜡"] = "adipocere",
    ["尸解"] = "corpse liberation",
    ["尸谏"] = "remonstrance by death",
    ["尸身"] = "corpse",
    ["尸道"] = "corpse path",
    ["尸首"] = "corpse",
    ["尸骨"] = "skeleton",
    ["尸骨未寒"] = "body not yet cold",
    ["尸骸"] = "remains",
    ["尸鬼"] = "corpse demon",
    ["尸鬼封尽"] = "corpse demon seal",
}

return M
