local M = {}

M.mapping = {
    ["兄友弟恭"] = "brotherly love",
    ["兄台"] = "brother",
    ["兄妹"] = "siblings",
    ["兄妹俩"] = "siblings",
    ["兄嫂"] = "elder brother's wife",
    ["兄嫂当知之"] = "elder brother's wife should know",
    ["兄弟"] = "brother",
    ["兄弟两人"] = "two brothers",
    ["兄弟之情"] = "brotherly affection",
    ["兄弟二人"] = "two brothers",
    ["兄弟们"] = "brothers",
    ["兄弟会"] = "fraternity",
    ["兄弟俩"] = "two brothers",
    ["兄弟党"] = "brother party",
    ["兄弟关系"] = "brotherhood",
    ["兄弟厂"] = "brother factory",
    ["兄弟啊"] = "brother ah",
    ["兄弟姐妹"] = "siblings",
    ["兄弟岛楔齿蜥"] = "brother island tuatara",
    ["兄弟情"] = "brotherly love",
    ["兄弟情义"] = "brotherly bond",
    ["兄弟情深"] = "deep brotherly love",
    ["兄弟杯"] = "brother cup",
    ["兄弟民族"] = "brotherly nations",
    ["兄弟盟"] = "brother alliance",
    ["兄弟般"] = "brotherly",
    ["兄弟连"] = "band of brothers",
    ["兄弟阋于墙"] = "brothers fight at home",
    ["兄弟阋墙"] = "internal strife",
    ["兄弟队"] = "brother team",
    ["兄弟院校"] = "sister schools",
    ["兄死弟及"] = "brother dies, younger brother succeeds",
    ["兄长"] = "elder brother",
}

return M
