local M = {}

M.mapping = {
    ["嫌不够"] = "not enough",
    ["嫌人家"] = "dislike others",
    ["嫌他"] = "dislike him",
    ["嫌你"] = "dislike you",
    ["嫌吵"] = "noise complaint",
    ["嫌多"] = "too much",
    ["嫌多了"] = "too much already",
    ["嫌大"] = "too big",
    ["嫌她"] = "dislike her",
    ["嫌好道歹"] = "nitpick",
    ["嫌它"] = "dislike it",
    ["嫌小"] = "too small",
    ["嫌少"] = "too little",
    ["嫌弃"] = "disdain",
    ["嫌忌"] = "suspicion",
    ["嫌怨"] = "resentment",
    ["嫌恶"] = "disgust",
    ["嫌慢"] = "too slow",
    ["嫌憎"] = "disgust",
    ["嫌我"] = "dislike me",
    ["嫌烦"] = "annoyed",
    ["嫌犯"] = "suspect",
    ["嫌猜"] = "suspicion",
    ["嫌疑"] = "suspicion",
    ["嫌疑人"] = "suspect",
    ["嫌疑分子"] = "suspect element",
    ["嫌疑对象"] = "suspect",
    ["嫌疑最大"] = "prime suspect",
    ["嫌疑犯"] = "suspect",
    ["嫌疑者"] = "person of interest",
    ["嫌累"] = "dislike tiredness",
    ["嫌脏"] = "dislike dirty",
    ["嫌色细胞癌"] = "chromophobe cell carcinoma",
    ["嫌苦"] = "dislike bitterness",
    ["嫌贫爱富"] = "despise poor, adore rich",
    ["嫌贵"] = "too expensive",
    ["嫌这嫌那"] = "nitpicking",
    ["嫌远"] = "嫌远",
    ["嫌隙"] = "estrangement",
    ["嫌高"] = "too high",
}

return M
