local M = {}

M.mapping = {
    ["冈上肌"] = "supraspinatus muscle",
    ["冈下肌"] = "infraspinatus",
    ["冈仁波齐峰"] = "mount kailash",
    ["冈山"] = "okayama",
    ["冈峦"] = "hills",
    ["冈崎律子"] = "okazaki ritsuko",
    ["冈底斯"] = "gangdise",
    ["冈底斯山"] = "gangdise mountain",
    ["冈底斯山猫"] = "gangdise mountain cat",
    ["冈底斯山脉"] = "gangdise mountains",
    ["冈底斯山蝇子草"] = "gangdise mountain fly grass",
    ["冈本"] = "okamoto",
    ["冈本信彦"] = "okamoto nobuhiko",
    ["冈本圭人"] = "okamoto keito",
    ["冈本夏生"] = "okamoto natsuo",
    ["冈本多绪"] = "okamoto tao",
    ["冈本真夜"] = "okamoto maya",
    ["冈村孝子"] = "okamura takako",
    ["冈村宁次"] = "okamura neiji",
    ["冈村氏光鳃雀鲷"] = "okamura's chromis",
    ["冈村氏光鳃鱼"] = "okamura's chromis",
    ["冈村虫鳗"] = "okamura's worm eel",
    ["冈村软首鳕"] = "okamura's softhead cod",
    ["冈比亚"] = "gambia",
    ["冈比亚共和国"] = "republic of the gambia",
    ["冈比亚巨蝎"] = "gambian giant scorpion",
    ["冈比亚有袋鼠"] = "gambian marsupial rat",
    ["冈比亚歧须𬶏"] = "gambian catfish",
    ["冈比亚红"] = "gambia red",
    ["冈比西斯"] = "cambyses",
    ["冈特家族"] = "gaunt family",
    ["冈瑟氏中间真条鳅"] = "günther's intermediate loach",
    ["冈田准一"] = "junichi okada",
    ["冈田将生"] = "masaki okada",
    ["冈纬路"] = "on the job",
    ["冈萨雷斯"] = "gonzalez",
    ["冈谷钢机"] = "okaya steel machinery",
    ["冈陵"] = "hill",
    ["冈陵起伏"] = "rolling hills",
}

return M
