local M = {}

M.mapping = {
    ["己丑"] = "ji chou",
    ["己二烯雌酚"] = "dienestrol",
    ["己二胺"] = "hexamethylenediamine",
    ["己二酸"] = "adipic acid",
    ["己亥"] = "jihai",
    ["己亥杂诗"] = "jihai miscellaneous poems",
    ["己任"] = "one's own responsibility",
    ["己内酰胺"] = "caprolactam",
    ["己卯"] = "ji mao",
    ["己基肉桂醛"] = "hexyl cinnamaldehyde",
    ["己基间苯二酚"] = "hexylresorcinol",
    ["己巳"] = "jisi",
    ["己所不欲"] = "do not do to others",
    ["己所不欲勿施于人"] = "do unto others",
    ["己方"] = "own side",
    ["己未"] = "discipline inspection commission",
    ["己核算"] = "self-checked",
    ["己欲达而达人"] = "desire to help others succeed",
    ["己烯"] = "hexene",
    ["己烯醇"] = "hexenol",
    ["己烯醛"] = "hexenal",
    ["己烯雌酚"] = "diethylstilbestrol",
    ["己烯雌酚片"] = "diethylstilbestrol tablet",
    ["己烷"] = "hexestrol",
    ["己烷雌酚"] = "chicken pea jelly",
    ["己生来"] = "since birth",
    ["己用"] = "self-used",
    ["己见"] = "personal opinion",
    ["己身"] = "oneself",
    ["己酉"] = "jiyou year",
    ["己酮"] = "pentone",
    ["己酮可可碱"] = "pentoxifylline",
    ["己酸"] = "hexanoic acid",
    ["己酸乙酯"] = "ethyl caproate",
    ["己酸烯丙酯"] = "allyl caproate",
    ["己酸羟孕酮"] = "hydroxyprogesterone caproate",
    ["己醛"] = "hexanal",
    ["己队"] = "own team",
}

return M
