local M = {}

M.mapping = {
    ["儒冠多误身"] = "scholar's hat often hinders",
    ["儒冠误身"] = "scholar's hat hinders",
    ["儒勒·凡尔纳"] = "jules verne",
    ["儒勒斯"] = "jules",
    ["儒医"] = "confucian physician",
    ["儒商"] = "confucian merchant",
    ["儒垌"] = "ru dong",
    ["儒墨"] = "confucianism and mohism",
    ["儒士"] = "confucian scholar",
    ["儒士成林"] = "many scholars",
    ["儒学"] = "confucianism",
    ["儒家"] = "confucianism",
    ["儒家学者"] = "confucian scholar",
    ["儒家学说"] = "confucian doctrine",
    ["儒家思想"] = "confucian thought",
    ["儒家文化"] = "confucian culture",
    ["儒家理论"] = "confucian theory",
    ["儒家的"] = "confucian",
    ["儒家经书"] = "confucian texts",
    ["儒家经典"] = "confucian classics",
    ["儒将"] = "scholar-general",
    ["儒尼尼奥"] = "juninho",
    ["儒山"] = "confucian mountain",
    ["儒教"] = "confucianism",
    ["儒术"] = "confucianism",
    ["儒林"] = "confucian scholars",
    ["儒林外史"] = "the scholars",
    ["儒林社区"] = "ruling community",
    ["儒林雅居"] = "ruling elegant residence",
    ["儒江村"] = "rujiang village",
    ["儒法国家"] = "confucian-legalist state",
    ["儒生"] = "confucian scholar",
    ["儒生有长策"] = "scholar has plan",
    ["儒者"] = "confucian scholar",
    ["儒艮"] = "dugong",
    ["儒道"] = "confucian taoism",
    ["儒释道"] = "confucianism buddhism taoism",
    ["儒门事亲"] = "confucian family duties",
    ["儒雅"] = "scholarly",
    ["儒雅风流"] = "elegant",
    ["儒鲁亚河隐带丽鱼"] = "julidochromis regani",
}

return M
