local M = {}

M.mapping = {
    ["叹一口气"] = "sigh",
    ["叹为"] = "marvel at",
    ["叹为观止"] = "breathtaking",
    ["叹了"] = "sighed",
    ["叹人生"] = "sigh at life",
    ["叹人间"] = "sigh at the world",
    ["叹什么气"] = "why sigh",
    ["叹口气"] = "sigh",
    ["叹号"] = "exclamation mark",
    ["叹号问号"] = "exclamation and question marks",
    ["叹喟"] = "sigh",
    ["叹声"] = "sigh",
    ["叹息"] = "sigh",
    ["叹息之墙"] = "wall of sighs",
    ["叹息声"] = "sound of sigh",
    ["叹息未应闲"] = "sigh not idle",
    ["叹息桥"] = "bridge of sighs",
    ["叹息此人去"] = "sigh for this person's departure",
    ["叹息着"] = "sighing",
    ["叹息着说"] = "said with a sigh",
    ["叹息肠内热"] = "sigh with inner heat",
    ["叹惋"] = "sigh regretfully",
    ["叹惜"] = "lament",
    ["叹春来只有"] = "lament spring's arrival",
    ["叹曰"] = "sigh say",
    ["叹服"] = "admire",
    ["叹气"] = "sigh",
    ["叹气咳声"] = "sighing cough",
    ["叹流年又成虚度"] = "sigh wasted years",
    ["叹着气"] = "sighing",
    ["叹绝"] = "marvel",
    ["叹羡"] = "admire",
    ["叹老嗟卑"] = "lament aging",
    ["叹观止矣"] = "marvel at perfection",
    ["叹词"] = "interjection",
    ["叹赏"] = "admire",
    ["叹道"] = "sigh",
    ["叹门外楼头"] = "sigh at the scene",
    ["叹问号"] = "sigh of question mark",
}

return M
