local M = {}

M.mapping = {
    ["哑了"] = "muted",
    ["哑光"] = "matte",
    ["哑剧"] = "mime",
    ["哑剧字谜"] = "mime charades",
    ["哑剧演员"] = "mime actor",
    ["哑剧表演"] = "mime performance",
    ["哑口"] = "dumb",
    ["哑口仙女虫"] = "naidid worm",
    ["哑口无言"] = "speechless",
    ["哑吧英语"] = "dumb english",
    ["哑哑"] = "yaya",
    ["哑嗓"] = "hoarse voice",
    ["哑场"] = "awkward silence",
    ["哑声"] = "hoarse",
    ["哑女"] = "mute girl",
    ["哑婆婆"] = "mute granny",
    ["哑子"] = "mute",
    ["哑子做梦"] = "mute dreams",
    ["哑子寻梦"] = "mute seeks dream",
    ["哑子得梦"] = "mute dreams",
    ["哑巴"] = "mute",
    ["哑巴亏"] = "silent loss",
    ["哑巴吃黄连"] = "suffer silently",
    ["哑巴弄"] = "mute lane",
    ["哑弹"] = "dud",
    ["哑火"] = "misfire",
    ["哑火了"] = "misfired",
    ["哑炮"] = "dud",
    ["哑然"] = "speechless",
    ["哑然失笑"] = "laugh involuntarily",
    ["哑的"] = "mute",
    ["哑穴"] = "mute point",
    ["哑笑"] = "silent laugh",
    ["哑言失笑"] = "laugh silently",
    ["哑语"] = "sign language",
    ["哑谜"] = "riddle",
    ["哑迷"] = "puzzle",
    ["哑铃"] = "dumbbell",
    ["哑门"] = "yamen point",
    ["哑门穴"] = "yamen acupoint",
    ["哑霸鹟"] = "tyrant flycatcher",
}

return M
