local M = {}

M.mapping = {
    ["僵人综合征"] = "stiff-person syndrome",
    ["僵仆烦愦"] = "stiff and confused",
    ["僵住"] = "freeze",
    ["僵冷"] = "stiff and cold",
    ["僵化"] = "rigid",
    ["僵卧"] = "lie stiff",
    ["僵卧孤村不自哀"] = "stiff in a lonely village, not self-pitying",
    ["僵呆"] = "catatonia",
    ["僵在"] = "stuck at",
    ["僵尸"] = "zombie",
    ["僵尸博客"] = "zombie blog",
    ["僵尸山庄"] = "zombie mountain villa",
    ["僵尸模式"] = "zombie mode",
    ["僵尸男孩"] = "zombie boy",
    ["僵尸网络"] = "botnet",
    ["僵尸进程"] = "zombie process",
    ["僵局"] = "deadlock",
    ["僵持"] = "deadlock",
    ["僵持不下"] = "deadlocked",
    ["僵持着"] = "in a deadlock",
    ["僵掉"] = "stiffen",
    ["僵木"] = "stiff wood",
    ["僵桃代李"] = "substitute",
    ["僵死"] = "dead",
    ["僵死进程"] = "dead process",
    ["僵滞"] = "stagnant",
    ["僵狮子"] = "stiff lion",
    ["僵王博士"] = "dr. zomboss",
    ["僵的"] = "stiff",
    ["僵直"] = "rigid",
    ["僵着"] = "stiffening",
    ["僵硬"] = "stiff",
    ["僵硬不变"] = "rigid and unchanging",
    ["僵硬海参"] = "stiff sea cucumber",
    ["僵硬的"] = "stiff",
    ["僵硬着"] = "stiffening",
    ["僵立"] = "stand rigid",
    ["僵而不死"] = "stiff but not dead",
    ["僵蚕"] = "stiff silkworm",
}

return M
