local M = {}

M.mapping = {
    ["凸优化"] = "convex optimization",
    ["凸凸凹凹"] = "bumpy",
    ["凸凹"] = "convex concave",
    ["凸出"] = "protrude",
    ["凸出部分"] = "protrusion",
    ["凸分解"] = "convex decomposition",
    ["凸印"] = "emboss printing",
    ["凸圆鹿角珊瑚"] = "bubble coral",
    ["凸多边形"] = "convex polygon",
    ["凸形多面水母"] = "convex polyhydra",
    ["凸显"] = "highlight",
    ["凸显出"] = "highlight",
    ["凸杓蛤"] = "convex spoon clam",
    ["凸点"] = "bump",
    ["凸版"] = "relief printing",
    ["凸版印刷"] = "letterpress",
    ["凸环"] = "convex ring",
    ["凸现"] = "emerge",
    ["凸的"] = "convex",
    ["凸窗"] = "bay window",
    ["凸纹"] = "embossed",
    ["凸缘"] = "flange",
    ["凸缘叉"] = "flange fork",
    ["凸背毛须隐翅虫"] = "convex back rove beetle",
    ["凸角"] = "protruding corner",
    ["凸起"] = "bulge",
    ["凸起来"] = "bulge out",
    ["凸轮"] = "cam",
    ["凸轮轴"] = "camshaft",
    ["凸轮轴位置感知器"] = "camshaft sensor",
    ["凸边"] = "convex edge",
    ["凸透"] = "convex",
    ["凸透镜"] = "convex lens",
    ["凸镜"] = "convex lens",
    ["凸阵扫描"] = "convex scanning",
    ["凸面"] = "convex",
    ["凸面镜"] = "convex mirror",
    ["凸颊宽鞘茧蜂"] = "convex-cheeked braconid",
}

return M
