local M = {}

M.mapping = {
    ["厌世"] = "pessimism",
    ["厌世主义"] = "pessimism",
    ["厌世者"] = "misanthrope",
    ["厌了"] = "tired",
    ["厌倦"] = "weariness",
    ["厌倦了"] = "tired of",
    ["厌倦于"] = "weary of",
    ["厌吃"] = "loss of appetite",
    ["厌女"] = "misogyny",
    ["厌女症"] = "misogyny",
    ["厌学"] = "school aversion",
    ["厌弃"] = "disdain",
    ["厌恨"] = "detest",
    ["厌恶"] = "disgust",
    ["厌恶感"] = "disgust",
    ["厌恶治疗"] = "aversion treatment",
    ["厌恶疗法"] = "aversion therapy",
    ["厌恶透了"] = "utterly disgusted",
    ["厌憎"] = "detest",
    ["厌战"] = "war-weariness",
    ["厌战情绪"] = "war-weariness sentiment",
    ["厌故喜新"] = "love novelty",
    ["厌旧"] = "dislike the old",
    ["厌氧"] = "anaerobic",
    ["厌氧微生物"] = "anaerobic microorganism",
    ["厌氧菌"] = "anaerobic bacteria",
    ["厌烦"] = "annoyed",
    ["厌烦感"] = "feeling of annoyance",
    ["厌烦透顶"] = "utterly fed up",
    ["厌男"] = "misandry",
    ["厌腻"] = "fed up",
    ["厌薄"] = "disdain",
    ["厌见桃株笑"] = "dislike seeing peach smiles",
    ["厌闻饫听"] = "tired of hearing",
    ["厌食"] = "anorexia",
    ["厌食症"] = "anorexia",
    ["厌食的"] = "anorexic",
}

return M
