local M = {}

M.mapping = {
    ["卑下"] = "lowly",
    ["卑之无甚高论"] = "nothing extraordinary",
    ["卑俗"] = "vulgar",
    ["卑劣"] = "base",
    ["卑劣地"] = "basely",
    ["卑劣手段"] = "base means",
    ["卑劣的"] = "base",
    ["卑尔根"] = "bergen",
    ["卑尔根大学"] = "university of bergen",
    ["卑己自牧"] = "humble",
    ["卑庳"] = "lowly",
    ["卑弥呼"] = "himiko",
    ["卑微"] = "humble",
    ["卑微的人"] = "humble person",
    ["卑怯"] = "cowardly",
    ["卑怯管叶虫"] = "cowardly tube leaf worm",
    ["卑恭"] = "humble",
    ["卑污"] = "base",
    ["卑琐"] = "petty",
    ["卑礼厚币"] = "humble gifts",
    ["卑职"] = "your humble servant",
    ["卑论侪俗"] = "vulgar discourse",
    ["卑谄足恭"] = "fawning and obsequious",
    ["卑谦自牧"] = "humble and self-restrained",
    ["卑贱"] = "lowly",
    ["卑贱的人"] = "wretch",
    ["卑贱者"] = "lowborn",
    ["卑身屈体"] = "bend body",
    ["卑身贱体"] = "humble body",
    ["卑躬屈己"] = "humble oneself",
    ["卑躬屈膝"] = "bow and scrape",
    ["卑辞"] = "humble words",
    ["卑鄙"] = "despicable",
    ["卑鄙小人"] = "despicable person",
    ["卑鄙手段"] = "despicable means",
    ["卑鄙无耻"] = "shameless",
    ["卑鄙的人"] = "despicable person",
    ["卑鄙者"] = "despicable person",
    ["卑鄙龌龊"] = "sordid",
    ["卑陬失色"] = "ashamed",
}

return M
