local M = {}

M.mapping = {
    ["弘一大师"] = "master hongyi",
    ["弘一法师"] = "master hongyi",
    ["弘业期货"] = "hongye futures",
    ["弘信期货"] = "hongxin futures",
    ["弘光帝"] = "emperor hongguang",
    ["弘农郡"] = "hongnong commandery",
    ["弘历"] = "hongli",
    ["弘善胡同"] = "hongshan hutong",
    ["弘奖风流"] = "encourage talent",
    ["弘姓"] = "hong surname",
    ["弘扬"] = "promote",
    ["弘扬中华文化"] = "promote chinese culture",
    ["弘扬中国精神"] = "promote chinese spirit",
    ["弘扬五四精神"] = "promote may fourth spirit",
    ["弘扬传统"] = "promote tradition",
    ["弘扬传统文化"] = "promote traditional culture",
    ["弘扬务实求真精神"] = "promote pragmatic and truth-seeking spirit",
    ["弘扬宪法"] = "promote the constitution",
    ["弘扬爱国主义"] = "promote patriotism",
    ["弘扬革命精神"] = "promote revolutionary spirit",
    ["弘文馆"] = "hongwen hall",
    ["弘毅"] = "hongyi",
    ["弘毅宽厚"] = "broad-minded and generous",
    ["弘治"] = "hongzhi era",
    ["弘法"] = "promote buddhism",
    ["弘泽城"] = "hongze city",
    ["弘济时艰"] = "alleviate difficulties",
    ["弘燕名居"] = "hongyan famous residence",
    ["弘燕桥"] = "hongyan bridge",
    ["弘燕桥东"] = "east of hongyan bridge",
    ["弘燕站"] = "hongyan station",
    ["弘燕路"] = "hongyan road",
    ["弘燕路小区"] = "hongyan road residential area",
    ["弘爱医院"] = "hongai hospital",
    ["弘盛精工"] = "hongsheng precision",
    ["弘福寺"] = "hongfu temple",
    ["弘誓大愿"] = "great vow",
    ["弘讯科技"] = "hongxun technology",
    ["弘达明尚"] = "hongda mingshang",
    ["弘道"] = "promote dao",
    ["弘阳广场"] = "hongyang plaza",
}

return M
