local M = {}

M.mapping = {
    ["堕入"] = "fall into",
    ["堕入情网"] = "fall in love",
    ["堕其奸计"] = "fall into their trap",
    ["堕地"] = "fall to the ground",
    ["堕天使"] = "fallen angel",
    ["堕天神"] = "fallen god",
    ["堕指裂肤"] = "frostbite",
    ["堕星村"] = "fallen star village",
    ["堕星湖"] = "fallen star lake",
    ["堕楼"] = "fall from building",
    ["堕海"] = "fall into the sea",
    ["堕溷飘茵"] = "fall into misfortune or rise to fortune",
    ["堕珥遗簪"] = "dropped earrings and lost hairpins",
    ["堕胎"] = "multiple births",
    ["堕胎药"] = "abortion pill",
    ["堕落"] = "degenerate",
    ["堕落为"] = "become",
    ["堕落之手"] = "hand of corruption",
    ["堕落之毒"] = "venom of corruption",
    ["堕落之牙"] = "fang of corruption",
    ["堕落之舌"] = "tongue of corruption",
    ["堕落了"] = "fallen",
    ["堕落到"] = "degenerate into",
    ["堕落千金"] = "fallen heiress",
    ["堕落天使"] = "fallen angel",
    ["堕落手套"] = "gloves of corruption",
    ["堕落斗篷"] = "cloak of corruption",
    ["堕落的人"] = "fallen person",
    ["堕落的司祭"] = "fallen priest",
    ["堕落的恶魔书"] = "book of fallen demons",
    ["堕落者"] = "the fallen",
    ["堕落腐化"] = "corruption and decay",
    ["堕落镰刀"] = "scythe of corruption",
    ["堕落长袍"] = "robe of corruption",
    ["堕落长靴"] = "boots of corruption",
    ["堕落首级"] = "head of corruption",
    ["堕马"] = "fall from horse",
}

return M
