local M = {}

M.mapping = {
    ["啊不"] = "ah no",
    ["啊不知道"] = "ah don't know",
    ["啊什么"] = "what",
    ["啊什么啊"] = "what what",
    ["啊他"] = "ata",
    ["啊你"] = "ani",
    ["啊呀"] = "aya",
    ["啊呜"] = "awu",
    ["啊咋"] = "aza",
    ["啊哈"] = "aha",
    ["啊哟"] = "ayo",
    ["啊啊"] = "ah",
    ["啊啊啊"] = "ahh",
    ["啊啊啊啊"] = "ahhh",
    ["啊啦"] = "ala",
    ["啊喂"] = "awei",
    ["啊嗯"] = "ah um",
    ["啊嗷"] = "aow",
    ["啊她"] = "ata",
    ["啊好"] = "ah good",
    ["啊对"] = "ah right",
    ["啊怪我"] = "blame me",
    ["啊我"] = "awo",
    ["啊日"] = "ari",
    ["啊是"] = "yes",
    ["啊有"] = "ayou",
    ["啊服啦"] = "afula",
    ["啊的"] = "ah de",
    ["啊这"] = "azhe",
    ["啊这儿"] = "azheer",
    ["啊飘"] = "a piao",
}

return M
