local M = {}

M.mapping = {
    ["剃个光头"] = "shave head",
    ["剃了"] = "shaved",
    ["剃了个光头"] = "shaved bald",
    ["剃光"] = "shave",
    ["剃光头"] = "bald",
    ["剃光头发"] = "bald",
    ["剃净"] = "shaved",
    ["剃刀"] = "razor",
    ["剃刀党"] = "razor gang",
    ["剃刀岭"] = "razor ridge",
    ["剃刀峡谷"] = "razor canyon",
    ["剃刀沼泽"] = "razorfen",
    ["剃刀沼泽野猪人"] = "razorfen boar",
    ["剃刀高地"] = "razor hill",
    ["剃刀鲸"] = "razor whale",
    ["剃去"] = "shave off",
    ["剃发"] = "shave head",
    ["剃发令"] = "hair shaving order",
    ["剃头"] = "haircut",
    ["剃头刀"] = "razor",
    ["剃头挑子一头热"] = "one-sided",
    ["剃度"] = "tonsure",
    ["剃得"] = "shave well",
    ["剃掉"] = "shave off",
    ["剃毛"] = "shaving",
    ["剃毛器"] = "shaver",
    ["剃眉毛"] = "eyebrow shaving",
    ["剃胎发"] = "shave fetal hair",
    ["剃除"] = "shave off",
    ["剃须"] = "shave",
    ["剃须刀"] = "razor",
    ["剃须啫喱"] = "shaving gel",
    ["剃须泡"] = "shaving foam",
}

return M
