local M = {}

M.mapping = {
    ["巫医"] = "witch doctor",
    ["巫医乐师百工之人"] = "shamans, musicians, and artisans",
    ["巫启贤"] = "eric moo",
    ["巫女"] = "witch",
    ["巫妖"] = "lich",
    ["巫妖斗篷"] = "lich cloak",
    ["巫婆"] = "witch",
    ["巫山"] = "wushan",
    ["巫山一段云"] = "a cloud over wushan",
    ["巫山云雨"] = "wushan clouds rain",
    ["巫山十二峰"] = "twelve peaks of wushan",
    ["巫山县"] = "wushan county",
    ["巫山巫峡气萧森"] = "wushan wuxia bleak",
    ["巫山洛水"] = "wushan luoshui",
    ["巫山神女"] = "goddess of wushan",
    ["巫山神女庙"] = "goddess of wushan temple",
    ["巫峡"] = "wu gorge",
    ["巫峡棺山"] = "coffin mountain wu gorge",
    ["巫峡镇"] = "wuxia town",
    ["巫师"] = "wizard",
    ["巫师一"] = "witcher one",
    ["巫师三"] = "the witcher 3",
    ["巫师二"] = "the witcher 2",
    ["巫师四"] = "the witcher 4",
    ["巫师帽"] = "wu shimin",
    ["巫师棋"] = "wizard chess",
    ["巫族"] = "witch clan",
    ["巫术"] = "witchcraft",
    ["巫术外衣"] = "witchcraft robe",
    ["巫术学院"] = "witchcraft academy",
    ["巫术法杖"] = "witchcraft staff",
    ["巫术迷信"] = "witchcraft superstition",
    ["巫术项链"] = "witchcraft necklace",
    ["巫术魔法杖"] = "witchcraft magic staff",
    ["巫毒教"] = "voodoo",
    ["巫溪县"] = "wuxi county",
    ["巫神"] = "witch god",
    ["巫继学"] = "wu jixue",
    ["巫蛊"] = "witchcraft",
    ["巫蛊之祸"] = "witchcraft disaster",
}

return M
