local M = {}

M.mapping = {
    ["务使"] = "ensure",
    ["务农"] = "farming",
    ["务农息民"] = "farm and rest people",
    ["务去陈言"] = "avoid clichés",
    ["务实"] = "pragmatic",
    ["务实创新"] = "pragmatic innovation",
    ["务实合作"] = "practical cooperation",
    ["务实型"] = "practical type",
    ["务实工作"] = "practical work",
    ["务实性"] = "practicality",
    ["务实求新"] = "pragmatic innovation",
    ["务实精神"] = "pragmatic spirit",
    ["务实行动"] = "practical action",
    ["务实高效"] = "pragmatic and efficient",
    ["务川仡佬族苗族自治县"] = "wuchuan gelao and miao autonomous county",
    ["务川县"] = "wuchuan county",
    ["务工"] = "migrant work",
    ["务工人员"] = "migrant workers",
    ["务工者"] = "migrant worker",
    ["务工青年"] = "migrant youth",
    ["务必"] = "must",
    ["务必于"] = "must by",
    ["务必要"] = "must",
    ["务必认真"] = "be diligent",
    ["务期"] = "strive for",
    ["务本"] = "focus on basics",
    ["务正"] = "focus on duty",
    ["务求"] = "strive",
    ["务江乡"] = "wujiang township",
    ["务虚"] = "discuss principles",
    ["务要"] = "must",
    ["务请"] = "please",
    ["务须"] = "must",
}

return M
