local M = {}

M.mapping = {
    ["尝一下"] = "taste",
    ["尝一尝"] = "taste",
    ["尝不出"] = "can't taste",
    ["尝不出味"] = "can't taste flavor",
    ["尝个"] = "try a",
    ["尝乐道"] = "taste joy road",
    ["尝了"] = "tasted",
    ["尝了个遍"] = "tasted everything",
    ["尝出"] = "taste out",
    ["尝到"] = "taste",
    ["尝到了"] = "tasted",
    ["尝到甜头"] = "reap benefits",
    ["尝吗"] = "taste",
    ["尝味"] = "taste",
    ["尝咸淡"] = "taste for saltiness",
    ["尝尝"] = "taste",
    ["尝尝吧"] = "try it",
    ["尝尝味道"] = "taste the flavor",
    ["尝尝鲜"] = "try something new",
    ["尝尽"] = "taste all",
    ["尝新"] = "taste new",
    ["尝点"] = "try some",
    ["尝甜头"] = "taste sweetness",
    ["尝百草"] = "tasted hundred herbs",
    ["尝胆"] = "taste gall",
    ["尝胆卧薪"] = "taste gall sleep on firewood",
    ["尝胆眠薪"] = "taste gall sleep on firewood",
    ["尝见一蜘蛛"] = "once saw a spider",
    ["尝试"] = "attempt",
    ["尝试为寡人为之"] = "try to do it for me",
    ["尝试做"] = "try doing",
    ["尝试性"] = "tentative",
    ["尝试用"] = "try using",
    ["尝试着"] = "trying",
    ["尝过"] = "tasted",
    ["尝过吗"] = "tried it",
    ["尝遍"] = "tasted all",
    ["尝酥饼"] = "taste crispy cake",
    ["尝鲜"] = "taste fresh",
}

return M
