local M = {}

M.mapping = {
    ["庭上"] = "court above",
    ["庭下如积水空明"] = "courtyard clear as water",
    ["庭中"] = "court",
    ["庭中有奇树"] = "tree in courtyard",
    ["庭内"] = "in the courtyard",
    ["庭前"] = "before the court",
    ["庭前会议制度"] = "pretrial conference system",
    ["庭前芍药妖无格"] = "peonies lack charm",
    ["庭卡乡"] = "tingka township",
    ["庭园"] = "garden",
    ["庭堂"] = "court hall",
    ["庭外"] = "out of court",
    ["庭外和解"] = "out-of-court settlement",
    ["庭审"] = "court hearing",
    ["庭审中"] = "during trial",
    ["庭审结束"] = "trial concluded",
    ["庭开花"] = "courtyard blooms",
    ["庭有枇杷树"] = "loquat tree in courtyard",
    ["庭树巢鹦鹉"] = "tree nests parrot",
    ["庭草春深绶带长"] = "long ribbon-like grass",
    ["庭训"] = "family precepts",
    ["庭轩寂寞近清明"] = "lonely courtyard near qingming",
    ["庭辩"] = "court debate",
    ["庭长"] = "chief judge",
    ["庭院"] = "courtyard",
    ["庭院大蜗牛"] = "garden snail",
    ["庭院式"] = "courtyard style",
    ["庭院暗雨乍歇"] = "rain stops in courtyard",
    ["庭院深深"] = "deep courtyard",
    ["庭院深深深几许"] = "deep courtyard",
    ["庭院灯"] = "garden light",
    ["庭院经济"] = "courtyard economy",
    ["庭院里"] = "in courtyard",
    ["庭除"] = "courtyard",
    ["庭雪到腰埋不死"] = "snow buried waist-deep",
    ["庭香园"] = "tingxiang garden",
}

return M
