local M = {}

M.mapping = {
    ["妥不妥"] = "proper or not",
    ["妥为"] = "properly",
    ["妥为安排"] = "proper arrangement",
    ["妥了"] = "settled",
    ["妥了歌"] = "settled song",
    ["妥便"] = "proper stool",
    ["妥切"] = "appropriate",
    ["妥协"] = "compromise",
    ["妥协性"] = "compromising nature",
    ["妥协的"] = "compromising",
    ["妥协的人"] = "compromiser",
    ["妥否"] = "acceptable or not",
    ["妥善"] = "proper",
    ["妥善保管"] = "proper storage",
    ["妥善处理"] = "proper handling",
    ["妥善处置"] = "proper disposal",
    ["妥善安排"] = "proper arrangement",
    ["妥善安置"] = "proper placement",
    ["妥善解决"] = "proper resolution",
    ["妥坝乡"] = "tuoba township",
    ["妥坝县"] = "tuoba county",
    ["妥妥"] = "proper",
    ["妥妥够"] = "plenty",
    ["妥妥够了"] = "enough",
    ["妥妥够用"] = "sufficient",
    ["妥妥帖帖"] = "neatly",
    ["妥妥当当"] = "properly",
    ["妥妥的"] = "solid",
    ["妥实"] = "reliable",
    ["妥布拉霉素"] = "tobramycin",
    ["妥布霉素"] = "tobramycin",
    ["妥布霉素滴眼液"] = "tobramycin eye drops",
    ["妥帖"] = "appropriate",
    ["妥当"] = "proper",
    ["妥当的"] = "proper",
    ["妥洽"] = "amicable",
    ["妥首帖耳"] = "docile",
}

return M
