local M = {}

M.mapping = {
    ["叙事"] = "narration",
    ["叙事体"] = "narrative style",
    ["叙事性"] = "narrative quality",
    ["叙事文"] = "narrative text",
    ["叙事曲"] = "ballade",
    ["叙事歌曲"] = "ballad",
    ["叙事诗"] = "narrative poem",
    ["叙事诗人"] = "narrative poet",
    ["叙亲"] = "relate",
    ["叙伦"] = "narrative ethics",
    ["叙写"] = "narration",
    ["叙军"] = "syrian army",
    ["叙利亚"] = "xu li ya",
    ["叙利亚人"] = "xu li ya ren",
    ["叙利亚共和国"] = "xu li ya gong he guo",
    ["叙利亚刺尾蜥"] = "xu li ya ci wei xi",
    ["叙利亚野驴"] = "xu li ya ye lv",
    ["叙利亚队"] = "xu li ya dui",
    ["叙别"] = "farewell",
    ["叙功"] = "merit recognition",
    ["叙叙"] = "chatting",
    ["叙家常"] = "chat family",
    ["叙府陈年糟蛋"] = "xufu aged egg",
    ["叙德皆仲尼"] = "virtues like confucius",
    ["叙拉古"] = "syracuse",
    ["叙旧"] = "reminisce",
    ["叙永县"] = "xuyong county",
    ["叙用"] = "narrative use",
    ["叙话"] = "chat",
    ["叙说"] = "recount",
    ["叙说着"] = "recounting",
    ["叙谈"] = "chat",
    ["叙述"] = "narrative",
    ["叙述中"] = "in narration",
    ["叙述了"] = "narrated",
    ["叙述性"] = "descriptive",
    ["叙述着"] = "narrating",
    ["叙述者"] = "narrator",
    ["叙道"] = "narrate",
}

return M
