local M = {}

M.mapping = {
    ["吡咯"] = "pyrrole",
    ["吡咯啉"] = "pyrroline",
    ["吡咯烷酮"] = "pyrrolidone",
    ["吡哆胺"] = "pyridoxamine",
    ["吡哆醇"] = "pyridoxine",
    ["吡哆醛"] = "pyridoxal",
    ["吡哌酸"] = "pipemidic acid",
    ["吡唑"] = "pyrazole",
    ["吡唑酮"] = "pyrazolone",
    ["吡啶"] = "pyridine",
    ["吡啶基"] = "pyridyl",
    ["吡啶基醋酸汞"] = "mercuric pyridylacetate",
    ["吡啶甲酸"] = "picolinic acid",
    ["吡啶酮"] = "pyridone",
    ["吡喃"] = "pyran",
    ["吡喃糖"] = "pyranose",
    ["吡喹酮"] = "praziquantel",
    ["吡喹酮片"] = "praziquantel tablet",
    ["吡嗪"] = "pyrazine",
    ["吡嗪酰胺"] = "pyrazinamide",
    ["吡嘧司特钾"] = "pemirolast potassium",
    ["吡拉西坦"] = "piracetam",
    ["吡拉西坦片"] = "piracetam tablet",
    ["吡柔比星"] = "pirarubicin",
    ["吡格列酮"] = "pioglitazone",
    ["吡硫醇"] = "pyritinol",
    ["吡罗昔康"] = "piroxicam",
    ["吡罗昔康片"] = "piroxicam tablets",
    ["吡美莫司"] = "pimecrolimus",
    ["吡虫啉"] = "imidacloprid",
    ["吡诺克辛"] = "pirenoxine",
    ["吡诺克辛钠滴眼液"] = "pirenoxine sodium eye drops",
    ["吡贝地尔"] = "piribedil",
}

return M
