local M = {}

M.mapping = {
    ["婴儿"] = "infant",
    ["婴儿健脾散"] = "infant spleen-strengthening powder",
    ["婴儿出生"] = "birth of baby",
    ["婴儿哭声"] = "baby cry",
    ["婴儿坏疽性皮炎"] = "infantile gangrenous dermatitis",
    ["婴儿奶粉"] = "infant formula",
    ["婴儿安片"] = "infant tranquilizer tablet",
    ["婴儿床"] = "crib",
    ["婴儿时代"] = "baby era",
    ["婴儿时期"] = "infant period",
    ["婴儿期"] = "infancy",
    ["婴儿标志"] = "baby sign",
    ["婴儿死亡"] = "infant death",
    ["婴儿死亡率"] = "infant mortality rate",
    ["婴儿猝死综合征"] = "sudden infant death syndrome",
    ["婴儿用品"] = "baby products",
    ["婴儿的全套服装"] = "baby layette",
    ["婴儿符号"] = "baby symbol",
    ["婴儿素"] = "infant powder",
    ["婴儿装"] = "baby clothes",
    ["婴儿车"] = "baby carriage",
    ["婴儿长"] = "infant length",
    ["婴儿鞋"] = "baby shoes",
    ["婴儿食品"] = "baby food",
    ["婴城固守"] = "defend city",
    ["婴孩"] = "infant",
    ["婴孩期"] = "infancy",
    ["婴幼"] = "infant",
    ["婴幼儿"] = "infants",
    ["婴幼儿奶粉"] = "infant formula",
    ["婴幼护肤"] = "infant skincare",
    ["婴方喜"] = "infant joy",
    ["婴灵恶泣"] = "the unborn",
    ["婴猴"] = "bushbaby",
    ["婴猴属"] = "galago",
    ["婴童"] = "infant",
    ["婴语单词表"] = "baby word list",
    ["婴语达人"] = "baby language expert",
    ["婴金铁受辱"] = "infant jin humiliated",
    ["婴鳞获罪"] = "offended by infant scales",
}

return M
