local M = {}

M.mapping = {
    ["剖决"] = "analyze",
    ["剖分"] = "divide",
    ["剖宫产"] = "c-section",
    ["剖尸"] = "autopsy",
    ["剖开"] = "cut open",
    ["剖心"] = "bare one's heart",
    ["剖心坼肝"] = "heartfelt",
    ["剖心析胆"] = "open-hearted",
    ["剖成"] = "split",
    ["剖断"] = "decide",
    ["剖明"] = "clarify",
    ["剖析"] = "analyze",
    ["剖析入微"] = "detailed analysis",
    ["剖析肝胆"] = "bare one's soul",
    ["剖烦析滞"] = "solve complexities",
    ["剖白"] = "confession",
    ["剖胆倾心"] = "open-hearted",
    ["剖腹"] = "abdominal incision",
    ["剖腹产"] = "cesarean",
    ["剖腹产切口钳"] = "cesarean forceps",
    ["剖腹产剪"] = "cesarean scissors",
    ["剖腹手术"] = "laparotomy",
    ["剖腹探查术"] = "exploratory laparotomy",
    ["剖腹明心"] = "bare one's heart",
    ["剖腹术"] = "abdominal surgery",
    ["剖腹自医"] = "self-surgery",
    ["剖腹藏珠"] = "sacrifice essentials",
    ["剖蓓舒"] = "probiotic",
    ["剖视"] = "sectional inspection",
    ["剖视图"] = "cutaway view",
    ["剖解"] = "dissect",
    ["剖辨"] = "discriminate",
    ["剖释"] = "interpret",
    ["剖露"] = "reveal",
    ["剖面"] = "section",
    ["剖面图"] = "sectional view",
}

return M
