local M = {}

M.mapping = {
    ["嘎东镇"] = "gadong town",
    ["嘎了"] = "dead",
    ["嘎什根乡"] = "gashengen township",
    ["嘎吱"] = "creak",
    ["嘎呀河"] = "gaya river",
    ["嘎咕"] = "gagu",
    ["嘎咕嘎"] = "gagu ga",
    ["嘎哒"] = "click",
    ["嘎嘎"] = "gaga",
    ["嘎嘎声"] = "quack",
    ["嘎嘎胡同"] = "gaga hutong",
    ["嘎嘣"] = "snap",
    ["嘎嘣脆"] = "crispy snap",
    ["嘎噔"] = "thud",
    ["嘎塔乡"] = "gata township",
    ["嘎子"] = "gazi",
    ["嘎巴"] = "crack",
    ["嘎巴儿"] = "crust",
    ["嘎措乡"] = "gacuo township",
    ["嘎斯"] = "gas",
    ["嘎木乡"] = "gamu township",
    ["嘎查"] = "gacha",
    ["嘎渣儿"] = "gazhar",
    ["嘎玛乡"] = "gama township",
    ["嘎玛贡桑"] = "gamagongsang",
    ["嘎玛贡桑街道"] = "gamagongsang street",
    ["嘎的"] = "gadi",
    ["嘎立立"] = "gali li",
    ["嘎美乡"] = "gamei township",
    ["嘎调"] = "gadiao",
    ["嘎达梅林"] = "gada meilin",
    ["嘎达苏种畜场"] = "gadasu breeding farm",
    ["嘎鱼"] = "gayu",
}

return M
