local M = {}

M.mapping = {
    ["岭上"] = "mountain ridge",
    ["岭下"] = "below the ridge",
    ["岭下山"] = "lingxia mountain",
    ["岭东乡"] = "lingdong township",
    ["岭东区"] = "lingdong district",
    ["岭兜村"] = "lingdou village",
    ["岭北"] = "north of ridge",
    ["岭南"] = "lingnan",
    ["岭南万户皆春色"] = "lingnan is full of spring",
    ["岭南学院"] = "lingnan college",
    ["岭南控股"] = "lingnan holdings",
    ["岭南文化"] = "lingnan culture",
    ["岭南村"] = "lingnan village",
    ["岭南派"] = "lingnan school",
    ["岭南股份"] = "lingnan shares",
    ["岭南路"] = "lingnan road",
    ["岭南路西口"] = "west entrance of lingnan road",
    ["岭后村"] = "linghou village",
    ["岭回归"] = "ridge regression",
    ["岭坂"] = "ridge slope",
    ["岭坡"] = "ridge slope",
    ["岭外音书断"] = "no news beyond mountains",
    ["岭头"] = "ridge",
    ["岭头坪"] = "lingtouping",
    ["岭头村"] = "lingtou village",
    ["岭子镇"] = "lingzi town",
    ["岭尾"] = "mountain tail",
    ["岭山"] = "lingshan",
    ["岭峤"] = "ridge peak",
    ["岭峰林场"] = "lingfeng forest farm",
    ["岭排"] = "ridge row",
    ["岭树重遮千里目"] = "ridge trees block distant views",
    ["岭背"] = "ridge back",
    ["岭脚下"] = "foot of hill",
    ["岭脚村"] = "lingjiao village",
    ["岭西"] = "west of mountains",
    ["岭西村"] = "lingxi village",
    ["岭西街道"] = "lingxi street",
}

return M
