local M = {}

M.mapping = {
    ["檀健次"] = "tan jianci",
    ["檀山"] = "tanshan",
    ["檀州家园社区"] = "tanzhou jiayuan community",
    ["檀心玉凤"] = "sandalwood jade phoenix",
    ["檀扇鸭掌"] = "sandalwood fan duck feet",
    ["檀木"] = "sandalwood",
    ["檀木料"] = "sandalwood material",
    ["檀木村"] = "tanmu village",
    ["檀木林"] = "tanmu forest",
    ["檀木港"] = "tanmu port",
    ["檀木甲"] = "tanmu armor",
    ["檀村"] = "tancun",
    ["檀板"] = "sandalwood clappers",
    ["檀林村"] = "tanlin village",
    ["檀树村"] = "sandalwood village",
    ["檀老师"] = "teacher tan",
    ["檀自新"] = "tan zixin",
    ["檀营"] = "tanying",
    ["檀营地区"] = "tanying area",
    ["檀营社区"] = "tanying community",
    ["檀越"] = "donor",
    ["檀道济"] = "tan daoji",
    ["檀郎"] = "lover",
    ["檀郎谢女"] = "talented couple",
    ["檀香"] = "sandalwood",
    ["檀香园"] = "sandalwood garden",
    ["檀香山"] = "honolulu",
    ["檀香扇"] = "sandalwood fan",
    ["檀香拂尘"] = "sandalwood duster",
    ["檀香木"] = "sandalwood",
    ["檀香树"] = "sandalwood tree",
    ["檀香油"] = "sandalwood oil",
    ["檀香皂"] = "sandalwood soap",
    ["檀香苑"] = "sandalwood court",
    ["檀香苑小区"] = "sandalwood court community",
    ["檀黎斗"] = "dan kuroto",
}

return M
