local M = {}

M.mapping = {
    ["搓一搓"] = "rub a bit",
    ["搓下"] = "rub off",
    ["搓下来"] = "rub down",
    ["搓丝机"] = "thread rolling machine",
    ["搓丝板"] = "threading die",
    ["搓了搓"] = "rubbed",
    ["搓几下"] = "rub a few times",
    ["搓动"] = "rub",
    ["搓吗"] = "rub",
    ["搓干净"] = "scrub clean",
    ["搓弄"] = "fondle",
    ["搓成"] = "rub into",
    ["搓手"] = "rub hands",
    ["搓手顿脚"] = "rub hands and stamp feet",
    ["搓捻"] = "twist",
    ["搓揉"] = "knead",
    ["搓揉着"] = "kneading",
    ["搓搓"] = "rub",
    ["搓搓小手"] = "rub little hands",
    ["搓板"] = "washboard",
    ["搓汤圆"] = "make glutinous rice balls",
    ["搓泥"] = "rub off dirt",
    ["搓洗"] = "scrub wash",
    ["搓澡"] = "body scrub",
    ["搓澡工"] = "body scrubber",
    ["搓着"] = "rubbing",
    ["搓粉团朱"] = "rub powder and rouge",
    ["搓紧"] = "twist tight",
    ["搓纸轮"] = "paper feed roller",
    ["搓绳"] = "twist rope",
    ["搓绵扯絮"] = "rub cotton and silk",
    ["搓背"] = "back scrubbing",
    ["搓脚"] = "foot rubbing",
    ["搓衣"] = "wash clothes",
    ["搓衣板"] = "washboard",
    ["搓麻"] = "mahjong",
    ["搓麻将"] = "play mahjong",
}

return M
