local M = {}

M.mapping = {
    ["楔叶"] = "wedge leaf",
    ["楔叶地种蝇"] = "wedge-leaf root fly",
    ["楔叶纲"] = "wedge-leaf class",
    ["楔嘴雀"] = "wedge-billed finch",
    ["楔子"] = "wedge",
    ["楔尾伯劳"] = "wedge-tailed shrike",
    ["楔尾刀翅蜂鸟"] = "wedge-tailed sabrewing",
    ["楔尾山蜂鸟"] = "wedge-tailed hillstar",
    ["楔尾绿鸠"] = "wedge-tailed green pigeon",
    ["楔尾草鹀"] = "wedge-tailed bunting",
    ["楔尾草鹀属"] = "emberizoides",
    ["楔尾雕"] = "wedge-tailed eagle",
    ["楔尾鸥"] = "wedge-tailed gull",
    ["楔尾鹰"] = "wedge-tailed eagle",
    ["楔形"] = "wedge-shaped",
    ["楔形古虫"] = "ancient wedge worm",
    ["楔形文字"] = "cuneiform",
    ["楔形文字法"] = "cuneiform law",
    ["楔形斧蛤"] = "wedge clam",
    ["楔形棘赤刀鱼"] = "wedge-shaped knife fish",
    ["楔形毛蕨"] = "wedge fern",
    ["楔形翼钟水母"] = "wedge-shaped bell jellyfish",
    ["楔形销"] = "wedge pin",
    ["楔形马拉芋螺"] = "wedge malan cone",
    ["楔斑汝尺蛾"] = "eupithecia virgaureata",
    ["楔条缘花天牛"] = "flower longhorn beetle",
    ["楔状缺损"] = "wedge-shaped defect",
    ["楔突芒异蝽"] = "megymenum gracilicorne",
    ["楔突追寄蝇"] = "exorista cuneata",
    ["楔翼总目"] = "sphenisciformes",
    ["楔花鮨䲢"] = "wedge flower bass",
    ["楔角切叶蜂"] = "megachile",
    ["楔齿蜥类"] = "sphenodontia",
    ["楔齿龙"] = "sphenacodon",
}

return M
