local M = {}

M.mapping = {
    ["扇一扇"] = "fan once",
    ["扇了"] = "fanned",
    ["扇了扇"] = "fanned",
    ["扇你"] = "slap you",
    ["扇动"] = "flap",
    ["扇动着"] = "flapping",
    ["扇动翅膀"] = "flap wings",
    ["扇区"] = "sector",
    ["扇区号"] = "sector number",
    ["扇区数"] = "number of sectors",
    ["扇叶"] = "fan blade",
    ["扇坠"] = "fan pendant",
    ["扇子"] = "fan",
    ["扇子崖"] = "fan cliff",
    ["扇尾啄果鸟"] = "fan-tailed berrypecker",
    ["扇尾杜鹃"] = "fantail cuckoo",
    ["扇尾芦莺"] = "fan-tailed warbler",
    ["扇尾贾丁氏鹦鹉"] = "jardine's parrot",
    ["扇席温枕"] = "fan mat warm pillow",
    ["扇形"] = "fan-shaped",
    ["扇形泰勒灯鱼"] = "fanfin anglerfish",
    ["扇形统计图"] = "pie chart",
    ["扇形角"] = "fan angle",
    ["扇斑异丽盲蝽"] = "spotted mirid bug",
    ["扇枕温席"] = "fan pillow warm mat",
    ["扇枕温衾"] = "fan pillow warm bedding",
    ["扇枕温被"] = "fan pillow warm quilt",
    ["扇状"] = "fan-shaped",
    ["扇着"] = "fanning",
    ["扇脸"] = "slap face",
    ["扇贝"] = "scallop",
    ["扇贝科"] = "pectinidae",
    ["扇贝肉"] = "scallop meat",
    ["扇车"] = "winnowing machine",
    ["扇面"] = "fan surface",
    ["扇面儿"] = "fan face",
    ["扇面美人"] = "fan beauty",
    ["扇风"] = "fan wind",
    ["扇骨"] = "fan ribs",
    ["扇骨子"] = "fan ribs",
    ["扇骨里"] = "fan ribs lane",
}

return M
