local M = {}

M.mapping = {
    ["栽下"] = "planted",
    ["栽下去"] = "plant down",
    ["栽下来"] = "planted down",
    ["栽了"] = "planted",
    ["栽了个跟头"] = "took a tumble",
    ["栽了跟头"] = "fell down",
    ["栽倒"] = "fall down",
    ["栽入"] = "plunge",
    ["栽在"] = "framed",
    ["栽培"] = "cultivation",
    ["栽培品种"] = "cultivar",
    ["栽培学"] = "cultivation science",
    ["栽培技术"] = "cultivation technique",
    ["栽培植物"] = "cultivated plant",
    ["栽培法"] = "cultivation method",
    ["栽培者"] = "cultivator",
    ["栽子"] = "seedling",
    ["栽插"] = "planting",
    ["栽树"] = "planting trees",
    ["栽桑"] = "plant mulberry",
    ["栽植"] = "planting",
    ["栽种"] = "planting",
    ["栽秧"] = "transplant rice",
    ["栽绒"] = "tufted",
    ["栽花"] = "plant flowers",
    ["栽花种草"] = "gardening",
    ["栽苗"] = "plant seedlings",
    ["栽赃"] = "frame-up",
    ["栽赃陷害"] = "frame",
    ["栽跟头"] = "trip and fall",
    ["栽进"] = "fall into",
    ["栽进去"] = "fall in",
    ["栽面"] = "lose face",
}

return M
