local M = {}

M.mapping = {
    ["攒一攒"] = "save up",
    ["攒三集五"] = "gather in threes and fives",
    ["攒下"] = "save up",
    ["攒下钱"] = "save money",
    ["攒不了"] = "can't accumulate",
    ["攒不出"] = "can't save",
    ["攒了"] = "saved",
    ["攒了攒"] = "saved up",
    ["攒动"] = "swarm",
    ["攒劲"] = "energetic",
    ["攒劲儿得很"] = "extremely energetic",
    ["攒劲得很"] = "very energetic",
    ["攒够"] = "save enough",
    ["攒够了"] = "saved enough",
    ["攒射"] = "concentrated fire",
    ["攒尖"] = "pointed roof",
    ["攒底"] = "bottom accumulation",
    ["攒机"] = "assemble computer",
    ["攒林茶"] = "zanlin tea",
    ["攒点"] = "save up",
    ["攒的"] = "saved",
    ["攒的钱"] = "saved money",
    ["攒盒"] = "assembled box",
    ["攒盒一品"] = "assembled box first grade",
    ["攒眉"] = "knit brows",
    ["攒眉苦脸"] = "knit brows in distress",
    ["攒眉蹙额"] = "knit brows and frown",
    ["攒着"] = "saving",
    ["攒竹"] = "zanzhu point",
    ["攒竹穴"] = "zanzhu acupoint",
    ["攒簇"] = "cluster together",
    ["攒聚"] = "gather",
    ["攒金卢橘坞"] = "gold-saving loquat grove",
    ["攒钱"] = "save money",
    ["攒钱罐"] = "piggy bank",
    ["攒锋聚镝"] = "gather weapons",
    ["攒集"] = "gather",
    ["攒零合整"] = "gather bits into whole",
}

return M
