local M = {}

M.mapping = {
    ["框上"] = "on frame",
    ["框中"] = "in frame",
    ["框中输入"] = "input in frame",
    ["框住"] = "frame",
    ["框内"] = "inside frame",
    ["框图"] = "block diagram",
    ["框子"] = "frame",
    ["框定"] = "define",
    ["框架"] = "framework",
    ["框架下"] = "under framework",
    ["框架使用"] = "framework usage",
    ["框架公约"] = "framework convention",
    ["框架图"] = "framework diagram",
    ["框架应用"] = "framework application",
    ["框架开发"] = "framework development",
    ["框架推荐"] = "framework recommendation",
    ["框架搭建"] = "framework setup",
    ["框架整合"] = "framework integration",
    ["框架模式"] = "framework pattern",
    ["框架理解"] = "framework understanding",
    ["框架理论"] = "framework theory",
    ["框架研究"] = "framework research",
    ["框架结构"] = "framework structure",
    ["框架解析"] = "framework analysis",
    ["框架讲解"] = "framework explanation",
    ["框架设计"] = "framework design",
    ["框架语法"] = "framework syntax",
    ["框格"] = "grid",
    ["框框"] = "box",
    ["框框套套"] = "boxes and sets",
    ["框框条条"] = "boxes and strips",
    ["框计算"] = "box computing",
    ["框选"] = "box selection",
}

return M
