local M = {}

M.mapping = {
    ["斩下"] = "chop down",
    ["斩下来"] = "chopped down",
    ["斩乱麻"] = "cut the knot",
    ["斩了"] = "beheaded",
    ["斩于"] = "behead",
    ["斩人"] = "beheader",
    ["斩仇"] = "avenge",
    ["斩仓"] = "cut losses",
    ["斩六将"] = "slay six generals",
    ["斩关夺隘"] = "break through",
    ["斩击"] = "slash",
    ["斩刀"] = "chopper",
    ["斩去"] = "cut off",
    ["斩女"] = "woman-killer",
    ["斩女香"] = "woman-killer scent",
    ["斩女香水"] = "woman-killer perfume",
    ["斩妖"] = "demon slaying",
    ["斩妖行"] = "demon hunter",
    ["斩将"] = "slay generals",
    ["斩尽杀绝"] = "kill all",
    ["斩断"] = "sever",
    ["斩星魔剑"] = "starrend",
    ["斩杀"] = "slay",
    ["斩波器"] = "chopper",
    ["斩男"] = "man-killer",
    ["斩男色"] = "man-killer color",
    ["斩神刀"] = "god slayer sword",
    ["斩立决"] = "immediate execution",
    ["斩竿揭木"] = "cut poles and raise wood",
    ["斩绞监候"] = "beheading with reprieve",
    ["斩缞"] = "cut mourning clothes",
    ["斩草"] = "cut grass",
    ["斩草除根"] = "root out",
    ["斩获"] = "win",
    ["斩落"] = "chop down",
    ["斩钉截铁"] = "resolute",
    ["斩除"] = "eradicate",
    ["斩首"] = "decapitation",
    ["斩首示众"] = "public beheading",
    ["斩首行动"] = "decapitation strike",
    ["斩魔刀"] = "demon-slaying sword",
    ["斩鱼圆"] = "fish ball",
}

return M
