local M = {}

M.mapping = {
    ["摊丁入亩"] = "land tax reform",
    ["摊上"] = "encounter",
    ["摊下来"] = "spread down",
    ["摊主"] = "vendor",
    ["摊书傲百城"] = "boast books rival cities",
    ["摊书拥百城"] = "embrace books rival cities",
    ["摊了"] = "spread",
    ["摊了摊"] = "spread",
    ["摊了摊手"] = "shrugged",
    ["摊位"] = "stall",
    ["摊位上"] = "on the stall",
    ["摊位前"] = "in front of the stall",
    ["摊位费"] = "stall fee",
    ["摊儿"] = "stand",
    ["摊入"] = "allocate",
    ["摊到"] = "allocate to",
    ["摊售"] = "street vending",
    ["摊在"] = "spread",
    ["摊场"] = "threshing ground",
    ["摊子"] = "setup",
    ["摊子口"] = "stall entrance",
    ["摊平"] = "average down",
    ["摊开"] = "spread out",
    ["摊开双手"] = "spread hands",
    ["摊手"] = "throw up hands",
    ["摊放"] = "spread",
    ["摊晒"] = "sun-cure",
    ["摊档"] = "stall",
    ["摊派"] = "apportion",
    ["摊点"] = "stall",
    ["摊烧饼"] = "bake pancakes",
    ["摊牌"] = "showdown",
    ["摊着"] = "spreading",
    ["摊破浣溪沙"] = "broken silk-washing stream",
    ["摊群"] = "stall group",
    ["摊薄"] = "dilution",
    ["摊贩"] = "vendor",
    ["摊铺"] = "pave",
    ["摊铺机"] = "paver",
    ["摊销"] = "amortization",
    ["摊鸡蛋"] = "scrambled eggs",
}

return M
