local M = {}

M.mapping = {
    ["椒园乡"] = "jiaoyuan township",
    ["椒园村"] = "jiaoyuan village",
    ["椒子街"] = "jiaozijie",
    ["椒房街"] = "jiaofang street",
    ["椒江"] = "jiaojiang",
    ["椒江中医院"] = "jiaojiang hospital of traditional chinese medicine",
    ["椒江区"] = "jiaojiang district",
    ["椒江县"] = "jiaojiang county",
    ["椒江大桥"] = "jiaojiang bridge",
    ["椒江大酒店"] = "jiaojiang hotel",
    ["椒河鳗"] = "pepper river eel",
    ["椒油扁豆"] = "green beans with chili oil",
    ["椒油茭白"] = "water bamboo with chili oil",
    ["椒油银耳"] = "tremella with chili oil",
    ["椒焚桂折"] = "pepper burned and cinnamon broken",
    ["椒盐"] = "salt and pepper",
    ["椒盐八宝鸡"] = "salt and pepper eight-treasure chicken",
    ["椒盐卷饼"] = "pretzel",
    ["椒盐大虾"] = "salt and pepper prawns",
    ["椒盐排条"] = "salt and pepper pork strips",
    ["椒盐排骨"] = "salt and pepper pork ribs",
    ["椒盐桃片"] = "salt and pepper peach slices",
    ["椒盐海豹蛇"] = "salt and pepper sea snake",
    ["椒盐牛仔骨"] = "salt and pepper beef ribs",
    ["椒盐粽子"] = "salt and pepper zongzi",
    ["椒盐肘子"] = "salt and pepper pork elbow",
    ["椒盐肚尖"] = "salt and pepper pork tripe tip",
    ["椒盐花卷"] = "salt and pepper flower rolls",
    ["椒盐葱油饼"] = "salt and pepper scallion pancake",
    ["椒盐虾"] = "salt and pepper shrimp",
    ["椒盐虾仁"] = "salt and pepper shrimp",
    ["椒盐蹄膀"] = "salt and pepper pork knuckle",
    ["椒盐锅盔"] = "salt and pepper guokui",
    ["椒盐锅魁"] = "salt and pepper guokui",
    ["椒盐馓子"] = "salt and pepper sanzi",
    ["椒盐麻饼"] = "salt and pepper sesame cake",
    ["椒粒炒嫩蛋"] = "scrambled eggs with pepper grains",
    ["椒饼灸"] = "pepper cake moxibustion",
    ["椒香"] = "peppery aroma",
    ["椒麻堂会"] = "pepper and hemp hall meeting",
    ["椒麻鸡"] = "spicy chicken",
    ["椒麻鸡片"] = "sliced spicy chicken",
}

return M
