local M = {}

M.mapping = {
    ["敷一下"] = "apply a bit",
    ["敷上"] = "apply on",
    ["敷了"] = "applied",
    ["敷于患处"] = "apply to affected area",
    ["敷于脸上"] = "apply to face",
    ["敷出"] = "apply",
    ["敷在"] = "applied to",
    ["敷张扬厉"] = "exaggerate and publicize",
    ["敷敷衍衍"] = "perfunctory",
    ["敷料"] = "dressing",
    ["敷料镊"] = "dressing forceps",
    ["敷毛巾"] = "apply towel",
    ["敷水镇"] = "fushui town",
    ["敷用"] = "apply",
    ["敷的"] = "applied",
    ["敷着"] = "applying",
    ["敷粉"] = "applying powder",
    ["敷脸"] = "face mask",
    ["敷药"] = "apply medicine",
    ["敷衍"] = "perfunctory",
    ["敷衍了事"] = "do things perfunctorily",
    ["敷衍塞责"] = "perform duties perfunctorily",
    ["敷衍搪塞"] = "evade and be perfunctory",
    ["敷衍着"] = "perfunctorily",
    ["敷衍门面"] = "maintain appearances",
    ["敷设"] = "lay",
    ["敷设在"] = "laid in",
    ["敷设方式"] = "laying method",
    ["敷贴"] = "apply",
    ["敷贴法"] = "application method",
    ["敷过"] = "applied",
    ["敷陈"] = "elaborate",
    ["敷面"] = "apply facial mask",
}

return M
