local M = {}

M.mapping = {
    ["惟与蜘蛛乞巧丝"] = "only beg silk from spiders",
    ["惟刑之恤"] = "mercy in punishment",
    ["惟力是视"] = "strength-based",
    ["惟口兴戎"] = "words provoke war",
    ["惟口起羞"] = "words cause shame",
    ["惟吾德馨"] = "my virtue is fragrance",
    ["惟善为宝"] = "virtue is precious",
    ["惟大人为能格君心之非"] = "only the virtuous can rectify the ruler's heart",
    ["惟妙惟肖"] = "lifelike",
    ["惟将终夜长开眼"] = "sleepless nights",
    ["惟庚寅吾以降"] = "born in gengyin",
    ["惟恐琼楼玉宇"] = "fear jade tower",
    ["惟愿孩儿愚且鲁"] = "only wish my child dull and simple",
    ["惟日为岁"] = "days as years",
    ["惟智者为能以小事大"] = "only wise serve greater",
    ["惟有一堪赏"] = "only one worthy of admiration",
    ["惟有乳下孙"] = "only nursing grandchild",
    ["惟有幽人自来去"] = "only hermits come and go",
    ["惟有柳湖万株柳"] = "only willow lake",
    ["惟有楼前流水"] = "only building stream",
    ["惟有泪千行"] = "only tears",
    ["惟有门前镜湖水"] = "only the mirror lake water",
    ["惟有饮者留其名"] = "only drinkers leave their names",
    ["惟梁孝王都"] = "only liang xiaowang capital",
    ["惟楚有才"] = "wei chu you cai",
    ["惟江上之清风"] = "river breeze",
    ["惟爱你"] = "only love you",
    ["惟终"] = "only end",
    ["惟肖惟妙"] = "lifelike",
    ["惟草木之零落兮"] = "mourning fallen plants",
    ["惟解漫天作雪飞"] = "only snowflakes fly",
    ["惟贤知贤"] = "only the virtuous know virtue",
    ["惟闻钟磬音"] = "only hear bell sound",
    ["惟陈言之务去"] = "eliminate cliches",
}

return M
