local M = {}

M.mapping = {
    ["扔上"] = "throw up",
    ["扔下"] = "throw down",
    ["扔下去"] = "throw down",
    ["扔下来"] = "throw down",
    ["扔下楼"] = "throw downstairs",
    ["扔不了"] = "cannot throw",
    ["扔个"] = "throw one",
    ["扔了"] = "threw",
    ["扔出"] = "throw out",
    ["扔出去"] = "throw away",
    ["扔出来"] = "throw out",
    ["扔到"] = "throw to",
    ["扔去"] = "throw to",
    ["扔向"] = "throw at",
    ["扔回"] = "throw back",
    ["扔在"] = "throw at",
    ["扔垃圾"] = "throw trash",
    ["扔完"] = "finish throwing",
    ["扔开"] = "throw away",
    ["扔弃"] = "discard",
    ["扔手雷"] = "throw grenade",
    ["扔掉"] = "discard",
    ["扔掉的"] = "discarded",
    ["扔沙包"] = "throw sandbag",
    ["扔炸弹"] = "throw bomb",
    ["扔烟"] = "throw cigarette",
    ["扔烟头"] = "throw cigarette butt",
    ["扔的"] = "thrown",
    ["扔的东西"] = "thrown items",
    ["扔的啥"] = "what was thrown",
    ["扔石头"] = "throw stone",
    ["扔箱鼠"] = "box-throwing mouse",
    ["扔给"] = "throw to",
    ["扔给我"] = "throw to me",
    ["扔起来"] = "throw up",
    ["扔过来"] = "throw over",
    ["扔进"] = "throw into",
    ["扔钱"] = "throw money",
    ["扔铅球"] = "shot put",
    ["扔雪"] = "throw snow",
    ["扔鞋"] = "shoe throwing",
}

return M
