local M = {}

M.mapping = {
    ["滞产"] = "prolonged labor",
    ["滞压"] = "stagnation",
    ["滞后"] = "lag",
    ["滞后性"] = "hysteresis",
    ["滞后效应"] = "hysteresis effect",
    ["滞后时间"] = "lag time",
    ["滞后期"] = "lag phase",
    ["滞后自交"] = "delayed selfing",
    ["滞塞"] = "clogged",
    ["滞报金"] = "late declaration fee",
    ["滞期费"] = "demurrage",
    ["滞止"] = "stagnation",
    ["滞水"] = "stagnant water",
    ["滞洪"] = "flood detention",
    ["滞洪区"] = "detention basin",
    ["滞涨"] = "stagflation",
    ["滞涩"] = "stagnant",
    ["滞港"] = "port congestion",
    ["滞留"] = "detention",
    ["滞留不归"] = "overstay",
    ["滞留人员"] = "stranded persons",
    ["滞留旅客"] = "stranded passengers",
    ["滞留时间"] = "retention time",
    ["滞留者"] = "stranded",
    ["滞空"] = "hang time",
    ["滞纳"] = "overdue",
    ["滞纳税款"] = "overdue tax",
    ["滞纳金"] = "late fee",
    ["滞缓"] = "stagnation",
    ["滞而不通"] = "stagnant",
    ["滞育"] = "diapause",
    ["滞胀"] = "stagflation",
    ["滞销"] = "unsalable",
    ["滞销产品"] = "unsalable products",
    ["滞销品"] = "unsalable items",
    ["滞销货"] = "unsalable goods",
}

return M
