local M = {}

M.mapping = {
    ["捷克"] = "czech",
    ["捷克人"] = "czech people",
    ["捷克共和国"] = "czech republic",
    ["捷克式"] = "czech style",
    ["捷克斯洛伐克"] = "czechoslovakia",
    ["捷克斯洛伐克社会主义共和国经济法典"] = "economic code of the czechoslovak socialist republic",
    ["捷克爱乐乐团"] = "czech philharmonic orchestra",
    ["捷克狼犬"] = "czechoslovakian wolfdog",
    ["捷克语"] = "czech language",
    ["捷克队"] = "czech team",
    ["捷克馆"] = "czech pavilion",
    ["捷利股份"] = "jieli shares",
    ["捷安特"] = "giant",
    ["捷并思"] = "jebisi",
    ["捷径"] = "shortcut",
    ["捷径窘步"] = "shortcut leads to difficulty",
    ["捷径终南"] = "shortcut to zhongnan",
    ["捷报"] = "victory report",
    ["捷报频传"] = "frequent victory reports",
    ["捷拉奥拉"] = "zeraora",
    ["捷星"] = "jetstar",
    ["捷申办"] = "quick application",
    ["捷胜"] = "quick victory",
    ["捷芙丝"] = "jeffs",
    ["捷讯"] = "good news",
    ["捷豹"] = "jaguar",
    ["捷足"] = "swift foot",
    ["捷足先登"] = "the swift-footed arrive first",
    ["捷达"] = "jetta",
    ["捷达春天"] = "jetta spring",
    ["捷达王"] = "jetta king",
    ["捷达车"] = "jetta car",
    ["捷迅"] = "swift news",
    ["捷运"] = "rapid transit",
    ["捷运局"] = "rapid transit bureau",
    ["捷运系统"] = "rapid transit system",
    ["捷雷不及掩耳"] = "lightning fast",
    ["捷音"] = "victory news",
}

return M
