local M = {}

M.mapping = {
    ["憋不住"] = "can't hold it",
    ["憋不住了"] = "can't hold it anymore",
    ["憋不住地"] = "uncontrollably",
    ["憋不住尿"] = "can't hold urine",
    ["憋不住想"] = "can't help thinking",
    ["憋不住时"] = "when can't hold it",
    ["憋不住气"] = "can't hold breath",
    ["憋不住的"] = "unable to hold it",
    ["憋不住笑"] = "can't help laughing",
    ["憋不住话"] = "can't keep a secret",
    ["憋了"] = "held back",
    ["憋住"] = "hold back",
    ["憋住气"] = "hold your breath",
    ["憋出"] = "hold back",
    ["憋出一句"] = "blurt out a sentence",
    ["憋口气"] = "hold your breath",
    ["憋回去"] = "hold it in",
    ["憋回去了"] = "held it in",
    ["憋在"] = "hold in",
    ["憋在心里"] = "bottled up inside",
    ["憋大招"] = "hold back a big move",
    ["憋尿"] = "hold urine",
    ["憋屈"] = "frustrated",
    ["憋得"] = "hold back",
    ["憋得住"] = "can hold it",
    ["憋得像"] = "hold back like",
    ["憋得慌"] = "feel suffocated",
    ["憋死"] = "suffocate",
    ["憋死了"] = "suffocating",
    ["憋死你"] = "suffocate you",
    ["憋气"] = "hold breath",
    ["憋气窝火"] = "suppressed anger",
    ["憋着"] = "hold back",
    ["憋着呢"] = "holding back",
    ["憋笑"] = "hold back laughter",
    ["憋红"] = "flush",
    ["憋足"] = "hold back",
    ["憋足了劲"] = "gathered strength",
    ["憋足劲"] = "gather strength",
    ["憋闷"] = "depressed",
}

return M
