local M = {}

M.mapping = {
    ["晃一下"] = "shake once",
    ["晃一晃"] = "shake",
    ["晃两下"] = "sway a couple of times",
    ["晃了"] = "swayed",
    ["晃了两晃"] = "swayed twice",
    ["晃了晃"] = "swayed a bit",
    ["晃倒"] = "ankle breaker",
    ["晃动"] = "shake",
    ["晃动着"] = "shaking",
    ["晃去"] = "swing away",
    ["晃头"] = "head shaking",
    ["晃得"] = "swing so",
    ["晃得像"] = "swing like",
    ["晃得比"] = "swing more than",
    ["晃悠"] = "sway",
    ["晃摇"] = "swaying",
    ["晃晃"] = "swaying",
    ["晃晃悠悠"] = "swaying leisurely",
    ["晃晃摇摇"] = "swaying and shaking",
    ["晃晃荡荡"] = "swaying unsteadily",
    ["晃来"] = "sway over",
    ["晃来晃去"] = "swaying back and forth",
    ["晃板"] = "wobble board",
    ["晃点"] = "deceive",
    ["晃眼"] = "dazzling",
    ["晃着"] = "swaying",
    ["晃瞎"] = "dazzling",
    ["晃瞎人眼"] = "dazzling to the eyes",
    ["晃瞎眼"] = "dazzling",
    ["晃脑"] = "wag head",
    ["晃腿"] = "leg shaking",
    ["晃荡"] = "swing",
    ["晃荡绝壁横"] = "swing cliff traverse",
    ["晃蜂鳃虱"] = "swing bee gill louse",
    ["晃起来"] = "swing",
}

return M
