local M = {}

M.mapping = {
    ["搅一搅"] = "stir a little",
    ["搅乱"] = "disrupt",
    ["搅乱了"] = "disrupted",
    ["搅了搅"] = "stirred",
    ["搅动"] = "stir",
    ["搅动着"] = "stirring",
    ["搅匀"] = "stir evenly",
    ["搅和"] = "stir",
    ["搅团"] = "stirred dough",
    ["搅局"] = "disrupt",
    ["搅局者"] = "disruptor",
    ["搅屎"] = "stir shit",
    ["搅屎棍"] = "shit-stirrer",
    ["搅弄"] = "stir",
    ["搅得"] = "stir up",
    ["搅得周天寒彻"] = "stir up the sky cold",
    ["搅扰"] = "disturb",
    ["搅拌"] = "stir",
    ["搅拌器"] = "stirrer",
    ["搅拌均匀"] = "mix well",
    ["搅拌时间"] = "mixing time",
    ["搅拌机"] = "mixer",
    ["搅拌着"] = "stirring",
    ["搅拌站"] = "mixing station",
    ["搅拌装置"] = "mixing device",
    ["搅拌车"] = "concrete mixer",
    ["搅棒"] = "stirring rod",
    ["搅浑"] = "stir muddy",
    ["搅混"] = "mix up",
    ["搅碎"] = "crush",
    ["搅缠"] = "entangle",
    ["搅肚蛆肠"] = "stir belly maggot intestines",
    ["搅醋丝"] = "stir vinegar shreds",
    ["搅闹"] = "disturbance",
}

return M
