local M = {}

M.mapping = {
    ["捂一捂"] = "cover for a while",
    ["捂一点"] = "cover a little",
    ["捂上嘴巴"] = "cover mouth",
    ["捂上耳朵"] = "cover ears",
    ["捂不暖"] = "cannot warm up",
    ["捂了捂"] = "covered a bit",
    ["捂住"] = "cover",
    ["捂住口鼻"] = "cover mouth and nose",
    ["捂住嘴巴"] = "cover mouth",
    ["捂住眼"] = "cover eyes",
    ["捂住眼睛"] = "cover eyes",
    ["捂住耳朵"] = "cover ears",
    ["捂嘴"] = "cover mouth",
    ["捂嘴巴"] = "cover mouth",
    ["捂嘴笑"] = "covering mouth laugh",
    ["捂得"] = "wude",
    ["捂得慌"] = "wudehuang",
    ["捂捂盖盖"] = "cover up",
    ["捂热"] = "warm up",
    ["捂盖子"] = "cover up",
    ["捂盘"] = "hold back goods",
    ["捂眼"] = "cover eyes",
    ["捂眼睛"] = "cover eyes",
    ["捂着"] = "covering",
    ["捂着呢"] = "covering",
    ["捂着嘴"] = "covering mouth",
    ["捂着嘴巴"] = "covering mouth",
    ["捂着嘴笑"] = "giggling",
    ["捂着耳朵"] = "covering ears",
    ["捂着肚子"] = "holding belly",
    ["捂着钱"] = "holding money",
    ["捂紧"] = "hold tight",
    ["捂耳"] = "cover ears",
    ["捂耳朵"] = "cover ears",
    ["捂肚子"] = "hold belly",
    ["捂胸口"] = "clutching chest",
    ["捂脸"] = "cover face",
    ["捂腰"] = "hold waist",
    ["捂被子"] = "cover with quilt",
    ["捂鼻子"] = "cover nose",
}

return M
