local M = {}

M.mapping = {
    ["汝不知夫螳螂乎"] = "do you not know the mantis",
    ["汝不能舍吾"] = "you cannot leave me",
    ["汝之不惠"] = "your folly",
    ["汝体吾此心"] = "share my sentiment",
    ["汝南"] = "runan",
    ["汝南县"] = "runan county",
    ["汝南晨鸡"] = "runan morning cock",
    ["汝南王"] = "prince of runan",
    ["汝南街"] = "runan street",
    ["汝南郡"] = "runan county",
    ["汝城"] = "rucheng",
    ["汝城县"] = "rucheng county",
    ["汝城板鸭"] = "rucheng pressed duck",
    ["汝安则为之"] = "do as you please",
    ["汝岱"] = "ru dai",
    ["汝州"] = "ruzhou",
    ["汝州市"] = "ruzhou city",
    ["汝幸而偶我"] = "you're lucky to have me",
    ["汝成人耶"] = "are you human",
    ["汝拉布鲁诺猎犬"] = "jura bruno hound",
    ["汝斯芬"] = "ru sphinx",
    ["汝果欲学诗"] = "if you learn poetry",
    ["汝河"] = "ru river",
    ["汝瓷"] = "ru porcelain",
    ["汝瓷小镇"] = "ru porcelain town",
    ["汝看此书时"] = "as you read this",
    ["汝窑"] = "ru ware",
    ["汝等"] = "you all",
    ["汝辈"] = "you people",
    ["汝阳"] = "ruyang",
    ["汝阳三斗始朝天"] = "ruyang legend",
    ["汝阳县"] = "ruyang county",
    ["汝阳王"] = "prince ruyang",
    ["汝阴"] = "ruyin",
}

return M
