local M = {}

M.mapping = {
    ["昼伏夜出"] = "nocturnal",
    ["昼伏夜行"] = "travel by night",
    ["昼光"] = "daylight",
    ["昼出耘田夜绩麻"] = "farm by day, spin by night",
    ["昼吟宵哭"] = "day wail night weep",
    ["昼夜"] = "day and night",
    ["昼夜不停"] = "non-stop day and night",
    ["昼夜不分"] = "no distinction between day and night",
    ["昼夜不息"] = "unceasing day and night",
    ["昼夜兼程"] = "travel day and night",
    ["昼夜兼行"] = "march day and night",
    ["昼夜各有宜"] = "each has its time",
    ["昼夜垂直移动"] = "diurnal vertical migration",
    ["昼夜平分"] = "equinox",
    ["昼夜温差"] = "diurnal temperature variation",
    ["昼夜的"] = "diurnal",
    ["昼夜节律"] = "circadian rhythm",
    ["昼夜颠倒"] = "day-night reversal",
    ["昼干夕惕"] = "diligent day and night",
    ["昼度夜思"] = "day ponder night think",
    ["昼思夜想"] = "daydream",
    ["昼日"] = "daytime",
    ["昼日三接"] = "three audiences a day",
    ["昼日昼夜"] = "day and night",
    ["昼盲"] = "day blindness",
    ["昼短夜长"] = "short day long night",
    ["昼短苦夜长"] = "short day bitter long night",
    ["昼耕夜诵"] = "study at night",
    ["昼警夕惕"] = "vigilant day and night",
    ["昼警暮巡"] = "day patrol night watch",
    ["昼锦之荣"] = "honor of return",
    ["昼锦荣还"] = "glorious return",
    ["昼长夜短"] = "long days and short nights",
    ["昼间"] = "daytime",
    ["昼阴夜阳"] = "dark day bright night",
}

return M
