local M = {}

M.mapping = {
    ["涌上"] = "surge",
    ["涌上心头"] = "overwhelm",
    ["涌上心来"] = "flood",
    ["涌上来"] = "well up",
    ["涌入"] = "pour",
    ["涌冰湖"] = "ice push lake",
    ["涌出"] = "gush out",
    ["涌出无"] = "no gush",
    ["涌出来"] = "gush out",
    ["涌到"] = "surge to",
    ["涌动"] = "surge",
    ["涌动着"] = "surge",
    ["涌去"] = "surge",
    ["涌向"] = "surge toward",
    ["涌来"] = "surged",
    ["涌泉"] = "yongquan",
    ["涌泉寺"] = "yongquan temple",
    ["涌泉湖"] = "yongquan lake",
    ["涌泉相报"] = "return favor",
    ["涌泉穴"] = "yongquan point",
    ["涌流"] = "flow",
    ["涌浪"] = "swell",
    ["涌溢"] = "overflow",
    ["涌溪"] = "yongxi",
    ["涌溪火青"] = "yongxi fire green",
    ["涌溪火青茶"] = "yongxi fire green tea",
    ["涌潮"] = "tidal bore",
    ["涌现"] = "emerge",
    ["涌现出"] = "emerge",
    ["涌现出来"] = "emerge",
    ["涌至"] = "surge to",
    ["涌起"] = "surge",
    ["涌进"] = "flood",
    ["涌进来"] = "flood in",
    ["涌金立交"] = "yongjin interchange",
    ["涌金门"] = "yongjin gate",
}

return M
