local M = {}

M.mapping = {
    ["揽上"] = "take on",
    ["揽下"] = "take on",
    ["揽下来"] = "take on",
    ["揽不了"] = "can't handle",
    ["揽住"] = "hold",
    ["揽你"] = "embrace you",
    ["揽储"] = "deposit taking",
    ["揽入"] = "bring into",
    ["揽名责实"] = "demand reality",
    ["揽在"] = "holding",
    ["揽存"] = "deposit",
    ["揽客"] = "solicit customers",
    ["揽工"] = "hire labor",
    ["揽总"] = "oversee",
    ["揽承"] = "undertake",
    ["揽收"] = "collection",
    ["揽明月"] = "embrace the moon",
    ["揽星河"] = "embrace the galaxy",
    ["揽月"] = "moon embrace",
    ["揽月阁"] = "moon pavilion",
    ["揽权"] = "power grab",
    ["揽权怙势"] = "grasp power",
    ["揽权纳贿"] = "take bribes",
    ["揽活"] = "job hunting",
    ["揽活儿"] = "job hunting",
    ["揽着"] = "holding",
    ["揽紧"] = "hold tight",
    ["揽胜"] = "range rover",
    ["揽茹蕙以掩涕兮"] = "gather herbs to wipe tears",
    ["揽裙脱丝履"] = "lift skirt",
    ["揽货"] = "freight forwarding",
    ["揽辔中原"] = "unify central plains",
    ["揽辔澄清"] = "clarify ambitions",
    ["揽辔登车"] = "mount chariot",
    ["揽过"] = "blame",
    ["揽饭"] = "rice dish",
}

return M
