local M = {}

M.mapping = {
    ["栉兜甲萤"] = "comb-clawed firefly",
    ["栉刺单萤"] = "comb-spined lanternfish",
    ["栉刺灯笼鱼"] = "comb-spined lanternfish",
    ["栉口目"] = "ctenostomata",
    ["栉壳虫属"] = "genus pholadidae",
    ["栉孔扇贝"] = "scallop",
    ["栉孔白睛鰕虎鱼"] = "white-eyed goby",
    ["栉棘灯笼鱼"] = "lanternfish",
    ["栉棘骨螺"] = "murex",
    ["栉棘龙"] = "dinosaur",
    ["栉比"] = "close",
    ["栉比鳞差"] = "close together",
    ["栉比鳞次"] = "row upon row",
    ["栉比鳞臻"] = "densely packed",
    ["栉水母动物"] = "ctenophore",
    ["栉水母动物门"] = "ctenophora",
    ["栉江珧"] = "comb pen shell",
    ["栉沐"] = "grooming",
    ["栉沐风雨"] = "brave wind and rain",
    ["栉盲环毛蚓"] = "pheretima",
    ["栉花竹芋"] = "calathea",
    ["栉虫亚目"] = "phacopina",
    ["栉虫目"] = "phacopida",
    ["栉蚕"] = "comb silkworm",
    ["栉角滑大蚊"] = "comb-footed crane fly",
    ["栉角蛉科"] = "nemopteridae",
    ["栉贝"] = "scallop",
    ["栉足华种蝇"] = "stenomicra spinigera",
    ["栉锯盖鱼"] = "comb saw cover fish",
    ["栉非洲攀鲈"] = "african climbing perch",
    ["栉风沐雨"] = "brave wind and rain",
    ["栉齿刺尾鱼"] = "surgeonfish",
    ["栉齿细莴苣"] = "lactuca setosa",
    ["栉齿锯鳐"] = "pristis",
    ["栉齿鲸"] = "ziphiid",
}

return M
