local M = {}

M.mapping = {
    ["患上"] = "suffer from",
    ["患上了"] = "suffered from",
    ["患不知人也"] = "worried about not knowing people",
    ["患了"] = "suffered",
    ["患儿"] = "sick child",
    ["患其不能也"] = "return car",
    ["患处"] = "affected area",
    ["患得患失"] = "worry about gains and losses",
    ["患感冒"] = "catch a cold",
    ["患有"] = "suffer from",
    ["患狂犬病"] = "rabies",
    ["患生所忽"] = "neglect leads to disaster",
    ["患生肘腋"] = "disaster arises from within",
    ["患病"] = "fall ill",
    ["患病后"] = "after illness",
    ["患病率"] = "morbidity",
    ["患病的"] = "sick",
    ["患病者"] = "patient",
    ["患癌"] = "cancer",
    ["患的"] = "suffering from",
    ["患的是"] = "suffering from",
    ["患精神病"] = "suffer from mental illness",
    ["患结肠癌"] = "suffer from colon cancer",
    ["患者"] = "patient",
    ["患者家"] = "patient's family",
    ["患者选择"] = "patient choice",
    ["患肺结核"] = "suffer from tuberculosis",
    ["患至呼天"] = "cry for help when disaster strikes",
    ["患苦"] = "suffering",
    ["患过伤风"] = "had a cold",
    ["患部"] = "affected part",
    ["患难"] = "couple in adversity",
    ["患难与共"] = "friendship in adversity",
    ["患难之交"] = "official's purse",
    ["患难夫妻"] = "adversity reveals true feelings",
    ["患难相恤"] = "huannan first avenue",
    ["患难相救"] = "sympathy in hardship",
    ["患难见真情"] = "adversity reveals true friends",
    ["患难见知己"] = "help in distress",
    ["患麻疹"] = "measles",
}

return M
