local M = {}

M.mapping = {
    ["梳乎厘"] = "soufflé",
    ["梳了"] = "combed",
    ["梳头"] = "comb hair",
    ["梳头发"] = "comb hair",
    ["梳妆"] = "dress up",
    ["梳妆台"] = "dresser",
    ["梳妆打扮"] = "dress and adorn",
    ["梳妆楼"] = "dressing tower",
    ["梳妆盒"] = "dressing case",
    ["梳妆镜"] = "dressing mirror",
    ["梳子"] = "comb",
    ["梳子百页"] = "comb shutter",
    ["梳得像"] = "combed like",
    ["梳成"] = "combed into",
    ["梳拢"] = "combing",
    ["梳排序"] = "comb sort",
    ["梳文栉字"] = "comb words",
    ["梳棉"] = "carding",
    ["梳棉机"] = "carding machine",
    ["梳毛"] = "grooming",
    ["梳洗"] = "grooming",
    ["梳洗一番"] = "freshen up",
    ["梳洗打扮"] = "dress up",
    ["梳状"] = "comb-like",
    ["梳状疣毛轮虫"] = "trichodina pediculus",
    ["梳状革囊星虫"] = "comb sipunculid",
    ["梳理"] = "comb",
    ["梳理了一遍"] = "combed through",
    ["梳理方案"] = "comb plan",
    ["梳理机"] = "carding machine",
    ["梳理表"] = "comb table",
    ["梳着"] = "combing",
    ["梳篦"] = "comb",
    ["梳篦式"] = "comb-like",
    ["梳辫子"] = "braid hair",
    ["梳过"] = "combed",
    ["梳飞跃寄蝇"] = "trichopoda plumosa",
    ["梳齿"] = "comb teeth",
}

return M
