local M = {}

M.mapping = {
    ["滥交"] = "promiscuity",
    ["滥伐"] = "deforestation",
    ["滥伐林木"] = "illegal deforestation",
    ["滥伐林木罪"] = "crime of illegal deforestation",
    ["滥发"] = "excessive issuance",
    ["滥吏赃官"] = "corrupt officials",
    ["滥垦"] = "over-reclamation",
    ["滥套"] = "cliche",
    ["滥套子"] = "hackneyed",
    ["滥官污吏"] = "corrupt officials",
    ["滥情"] = "promiscuity",
    ["滥捕"] = "overfishing",
    ["滥收"] = "excessive charges",
    ["滥收费"] = "exorbitant fees",
    ["滥施"] = "abuse",
    ["滥服"] = "overuse",
    ["滥杀"] = "wanton killing",
    ["滥杀无辜"] = "kill innocents",
    ["滥权"] = "abuse of power",
    ["滥炸"] = "excessive bombing",
    ["滥用"] = "abuse",
    ["滥用代理权"] = "abuse of agency",
    ["滥用市场支配地位"] = "abuse of market dominance",
    ["滥用权力"] = "abuse of power",
    ["滥用职权"] = "abuse of authority",
    ["滥用职权罪"] = "crime of abuse of authority",
    ["滥用行政权力"] = "abuse of administrative power",
    ["滥砍滥伐"] = "deforestation",
    ["滥竽充数"] = "pass off as competent",
    ["滥竽自耻"] = "ashamed of incompetence",
    ["滥觞"] = "origin",
    ["滥觞所出"] = "source of origin",
    ["滥调"] = "hackneyed tune",
    ["滥赌鬼"] = "compulsive gambler",
    ["滥造粗制"] = "crudely made",
    ["滥饮"] = "excessive drinking",
}

return M
