local M = {}

M.mapping = {
    ["惜分飞"] = "cherish parting",
    ["惜别"] = "farewell",
    ["惜力"] = "cherish strength",
    ["惜名"] = "cherish reputation",
    ["惜命"] = "cherish life",
    ["惜哉时不遇"] = "alas, untimely",
    ["惜售"] = "reluctant to sell",
    ["惜墨如金"] = "sparing of ink",
    ["惜字公庄"] = "xizi public village",
    ["惜字如金"] = "cherish words like gold",
    ["惜字宫南街"] = "south xizi palace street",
    ["惜字宫街"] = "xizi palace street",
    ["惜客好义"] = "hospitable",
    ["惜怜"] = "cherish pity",
    ["惜时"] = "cherish time",
    ["惜时如金"] = "cherish time",
    ["惜春"] = "cherish spring",
    ["惜春长怕花开早"] = "fear early blooms cherish spring",
    ["惜月下铠"] = "cherish moon armor",
    ["惜月护臂"] = "moon-guard bracers",
    ["惜月盔"] = "moon-guard helmet",
    ["惜福"] = "cherish blessings",
    ["惜福街道"] = "xifu street",
    ["惜秦皇汉武"] = "admiring qin emperor and han wu",
    ["惜红衣"] = "cherish red robe",
    ["惜缘"] = "cherish fate",
    ["惜老怜贫"] = "cherish the old",
    ["惜花"] = "cherish flowers",
    ["惜花芷"] = "cherish flowers",
    ["惜薪司"] = "xixinsi",
    ["惜财如命"] = "cherish wealth like life",
    ["惜败"] = "narrow defeat",
    ["惜购"] = "reluctant to buy",
    ["惜贷"] = "reluctant to lend",
    ["惜阴"] = "cherish time",
    ["惜阴里"] = "xiyin li",
}

return M
