local M = {}

M.mapping = {
    ["惯了"] = "used to",
    ["惯于"] = "accustomed to",
    ["惯于怀疑"] = "habitually suspicious",
    ["惯于欺骗"] = "habitually deceitful",
    ["惯例"] = "convention",
    ["惯偷"] = "habitual thief",
    ["惯养"] = "spoil",
    ["惯匪"] = "bandit",
    ["惯坏"] = "spoil",
    ["惯家"] = "habitual expert",
    ["惯常"] = "usual",
    ["惯性"] = "inertia",
    ["惯性力"] = "inertial force",
    ["惯性定律"] = "law of inertia",
    ["惯性导航"] = "inertial navigation",
    ["惯性漂移"] = "inertia drift",
    ["惯性矩"] = "moment of inertia",
    ["惯技"] = "habitual trick",
    ["惯有"] = "inherent",
    ["惯溺"] = "spoiling",
    ["惯犯"] = "recidivist",
    ["惯用"] = "habitual",
    ["惯用伎俩"] = "common trick",
    ["惯用法"] = "usage",
    ["惯用的伎俩"] = "usual trick",
    ["惯用语"] = "idiom",
    ["惯的"] = "habitual",
    ["惯着"] = "indulged",
    ["惯称"] = "common name",
    ["惯窃"] = "habitual theft",
    ["惯纵"] = "indulge",
    ["惯贼"] = "habitual thief",
    ["惯量"] = "inertia",
}

return M
