local M = {}

M.mapping = {
    ["渴不饮盗泉"] = "thirsty no drink stolen spring",
    ["渴不饮盗泉水"] = "thirsty no drink stolen spring water",
    ["渴乐宁胶囊"] = "kelenin capsules",
    ["渴了"] = "thirsty",
    ["渴吗"] = "thirsty",
    ["渴尘万斛"] = "extreme thirst",
    ["渴待"] = "eagerly await",
    ["渴得"] = "thirsty",
    ["渴心生尘"] = "dust forms from thirsty heart",
    ["渴念"] = "longing",
    ["渴想"] = "thirsty for",
    ["渴慕"] = "longing",
    ["渴望"] = "desire",
    ["渴望工程"] = "desire project",
    ["渴望得到"] = "crave",
    ["渴望激情"] = "desire passion",
    ["渴望爱情"] = "desire love",
    ["渴望的"] = "eager",
    ["渴望着"] = "longing",
    ["渴死"] = "thirsty to death",
    ["渴死了"] = "so thirsty",
    ["渴死我了"] = "so thirsty",
    ["渴求"] = "thirst",
    ["渴盼"] = "eagerly hope",
    ["渴盼着"] = "longing",
    ["渴着呢"] = "thirsty",
    ["渴睡"] = "thirsty sleep",
    ["渴者易为饮"] = "easy to quench thirst",
    ["渴者易饮"] = "thirst easily quenched",
    ["渴而掘井"] = "dig a well when thirsty",
    ["渴而穿井"] = "dig well when thirsty",
    ["渴饮月窟冰"] = "thirsty drink moon cave ice",
    ["渴骥怒猊"] = "thirsty steed angry beast",
    ["渴鹿奔泉"] = "thirsty deer runs to spring",
}

return M
