local M = {}

M.mapping = {
    ["椎体"] = "vertebral body",
    ["椎体骨凿椎"] = "vertebral chisel",
    ["椎前间隙"] = "prevertebral space",
    ["椎动脉"] = "vertebral artery",
    ["椎动脉型颈椎病"] = "vertebral artery cervical spondylosis",
    ["椎名"] = "shiina",
    ["椎名桔平"] = "shiina kippei",
    ["椎名法子"] = "shiina noriko",
    ["椎名由奈"] = "shiina yuna",
    ["椎名空"] = "shiina sora",
    ["椎埋狗窃"] = "petty theft",
    ["椎埋穿掘"] = "grave robbing",
    ["椎基底动脉"] = "vertebrobasilar artery",
    ["椎天抢地"] = "beat heaven and earth",
    ["椎孔"] = "vertebral foramen",
    ["椎尾水轮虫"] = "rotifer",
    ["椎心顿足"] = "beat chest and stamp feet",
    ["椎心饮泣"] = "sob bitterly",
    ["椎板"] = "lamina",
    ["椎板剥离器"] = "lamina dissector",
    ["椎板咬骨钳"] = "lamina rongeur",
    ["椎板骨凿"] = "lamina chisel",
    ["椎管"] = "spinal canal",
    ["椎管内肿瘤切除术"] = "spinal tumor removal",
    ["椎管内麻醉"] = "spinal anesthesia",
    ["椎管狭窄"] = "spinal stenosis",
    ["椎管造影"] = "myelography",
    ["椎管锉"] = "spinal file",
    ["椎膺顿足"] = "beat chest and stamp feet",
    ["椎锋陷阵"] = "charge into formation",
    ["椎锋陷陈"] = "charge into battle",
    ["椎间孔"] = "intervertebral foramen",
    ["椎间盘"] = "intervertebral disc",
    ["椎间盘变性"] = "disc degeneration",
    ["椎间盘手术用环锯"] = "disc rongeur",
    ["椎间盘突出"] = "disc herniation",
    ["椎间盘脱出"] = "disc prolapse",
    ["椎间盘造影"] = "discography",
    ["椎间隙"] = "intervertebral space",
    ["椎骨"] = "vertebra",
    ["椎鼓鸣钟天下闻"] = "beat drum and ring bell heard by the world",
}

return M
