local M = {}

M.mapping = {
    ["栖凤"] = "phoenix perch",
    ["栖凤楼"] = "phoenix tower",
    ["栖凤渡"] = "phoenix ford",
    ["栖凤路"] = "phoenix road",
    ["栖化新村"] = "qihua new village",
    ["栖宿"] = "lodging",
    ["栖居"] = "dwell",
    ["栖居于"] = "inhabit",
    ["栖山路"] = "qishan road",
    ["栖息"] = "perch",
    ["栖息地"] = "habitat",
    ["栖息处"] = "perching place",
    ["栖息环境"] = "habitat environment",
    ["栖息着"] = "inhabited by",
    ["栖息谷"] = "habitat valley",
    ["栖所"] = "habitat",
    ["栖木"] = "perch",
    ["栖栖"] = "perch",
    ["栖栖遑遑"] = "restless",
    ["栖止"] = "perch",
    ["栖禽"] = "perching birds",
    ["栖身"] = "dwell",
    ["栖身之地"] = "dwelling place",
    ["栖身之处"] = "shelter",
    ["栖身之所"] = "habitat",
    ["栖霞"] = "qixia",
    ["栖霞区"] = "qixia district",
    ["栖霞区技术经济开发区"] = "qixia district technical economic development zone",
    ["栖霞县"] = "qixia county",
    ["栖霞寺"] = "qixia temple",
    ["栖霞山"] = "qixia mountain",
    ["栖霞山庄"] = "qixia villa",
    ["栖霞市"] = "qixia city",
    ["栖霞市国土资源局"] = "qixia city land and resources bureau",
    ["栖霞街"] = "qixia street",
}

return M
