local M = {}

M.mapping = {
    ["息事"] = "settle dispute",
    ["息事宁人"] = "patch up a quarrel",
    ["息兵"] = "ceasefire",
    ["息兵罢战"] = "end war",
    ["息冢"] = "xi tomb",
    ["息冢乡"] = "xi tomb township",
    ["息冢镇"] = "xi tomb town",
    ["息县油酥"] = "xixian pastry",
    ["息喘"] = "asthma relief",
    ["息塘村"] = "xitang village",
    ["息壤"] = "fertile soil",
    ["息工待岗"] = "wait for work",
    ["息差"] = "interest margin",
    ["息影"] = "retire from public life",
    ["息怒"] = "calm",
    ["息怒停瞋"] = "pacify",
    ["息息"] = "breath",
    ["息息相关"] = "closely related",
    ["息息相通"] = "interconnected",
    ["息我以衰老"] = "rest in my old age",
    ["息斯敏"] = "hismanal",
    ["息机园"] = "rest garden",
    ["息止"] = "cessation of interest",
    ["息烽县"] = "xifeng county",
    ["息率"] = "interest rate",
    ["息票"] = "coupon",
    ["息红泪"] = "xi honglei",
    ["息肉"] = "polyp",
    ["息肉纽扣"] = "polyp button",
    ["息肩"] = "rest",
    ["息肩弛担"] = "lay down burdens",
    ["息讼"] = "settle lawsuit",
    ["息诉"] = "drop lawsuit",
    ["息迹静处"] = "quiet retreat",
    ["息陬乡"] = "xizou township",
}

return M
