local M = {}

M.mapping = {
    ["揉一揉"] = "rub",
    ["揉了"] = "rubbed",
    ["揉了揉"] = "rubbed again",
    ["揉你"] = "knead you",
    ["揉出"] = "knead out",
    ["揉到"] = "knead to",
    ["揉动"] = "kneading",
    ["揉匀"] = "knead evenly",
    ["揉合"] = "knead",
    ["揉奶"] = "knead breast",
    ["揉弄"] = "fondle",
    ["揉成"] = "knead into",
    ["揉成一团"] = "crumple",
    ["揉按"] = "kneading",
    ["揉按穴位"] = "acupressure points",
    ["揉捏"] = "kneading",
    ["揉捏法"] = "kneading method",
    ["揉捏着"] = "kneading",
    ["揉捻"] = "rolling and twisting",
    ["揉揉"] = "rub",
    ["揉揉眼睛"] = "rub eyes",
    ["揉搓"] = "rub",
    ["揉搓着"] = "rubbing",
    ["揉摸"] = "knead and touch",
    ["揉木为耒"] = "knead wood into plow",
    ["揉皱"] = "crumple",
    ["揉眵抹泪"] = "wipe away tears",
    ["揉着"] = "rubbing",
    ["揉破黄金万点轻"] = "golden petals crushed",
    ["揉碎"] = "crumble",
    ["揉碎在浮藻间"] = "crumbled among floating algae",
    ["揉穴"] = "acupoint massage",
    ["揉穴位"] = "acupressure",
    ["揉糖馒头"] = "kneaded sugar bun",
    ["揉纹机"] = "texturing machine",
    ["揉肩"] = "shoulder rub",
    ["揉胸"] = "breast massage",
    ["揉面"] = "knead dough",
    ["揉面团"] = "knead dough",
    ["揉面粉"] = "knead flour",
}

return M
