local M = {}

M.mapping = {
    ["浩丰科技"] = "haofeng technology",
    ["浩克"] = "hulk",
    ["浩劫"] = "catastrophe",
    ["浩南"] = "hao nan",
    ["浩叹"] = "deep sigh",
    ["浩大"] = "good at fighting",
    ["浩大的"] = "how dare you",
    ["浩如烟海"] = "vast as sea",
    ["浩宁达"] = "hao ningda",
    ["浩平"] = "hao ping",
    ["浩方"] = "haofang",
    ["浩明"] = "hao ming",
    ["浩气"] = "noble spirit",
    ["浩气凛然"] = "awe-inspiring righteousness",
    ["浩气英风"] = "heroic spirit and brave style",
    ["浩气长存"] = "noble spirit lives forever",
    ["浩汗无涯"] = "vast and boundless",
    ["浩沙杯"] = "haosha cup",
    ["浩浩"] = "vast",
    ["浩浩汤汤"] = "vast and mighty",
    ["浩浩渊渊"] = "vast and deep",
    ["浩浩荡荡"] = "vast and mighty",
    ["浩浩送中秋"] = "haohao sends mid-autumn",
    ["浩海小区"] = "haohai residential area",
    ["浩渺"] = "vast",
    ["浩瀚"] = "vast",
    ["浩瀚星空"] = "vast starry sky",
    ["浩然"] = "vast",
    ["浩然与溟涬同科"] = "vastness and chaos",
    ["浩然之气"] = "noble spirit",
    ["浩然天地间"] = "vast universe",
    ["浩然正气"] = "noble spirit",
    ["浩特"] = "hot",
    ["浩繁"] = "vast and numerous",
    ["浩耦丝"] = "hao ousi",
    ["浩若烟海"] = "vast as smoke",
    ["浩茫"] = "vast",
    ["浩荡"] = "easy to be",
    ["浩荡寄南征"] = "good homemaker",
    ["浩荡离愁白日斜"] = "good to",
    ["浩饶山乡"] = "haorao township",
}

return M
