local M = {}

M.mapping = {
    ["浴佛"] = "buddha bathing",
    ["浴佛节"] = "buddha bathing festival",
    ["浴兰汤兮沐芳"] = "bathe in orchid fragrance",
    ["浴具"] = "bath gear",
    ["浴凫飞鹭"] = "ducks and egrets",
    ["浴场"] = "bathhouse",
    ["浴堂"] = "bathhouse",
    ["浴女"] = "bathing woman",
    ["浴室"] = "bathroom",
    ["浴室征婚门"] = "scandal",
    ["浴室用品"] = "bathroom supplies",
    ["浴室里"] = "in the bathroom",
    ["浴室镜"] = "bathroom mirror",
    ["浴巾"] = "towel",
    ["浴帘"] = "shower curtain",
    ["浴帽"] = "shower cap",
    ["浴德池"] = "bath of virtue",
    ["浴房"] = "shower room",
    ["浴柜"] = "bath cabinet",
    ["浴桶"] = "bathtub",
    ["浴槽"] = "bathtub",
    ["浴池"] = "bathhouse",
    ["浴液"] = "bath liquid",
    ["浴火凤凰"] = "phoenix",
    ["浴火重生"] = "rebirth",
    ["浴球"] = "bath ball",
    ["浴疗"] = "balneotherapy",
    ["浴盆"] = "bathtub",
    ["浴盐"] = "bath salt",
    ["浴缸"] = "bathtub",
    ["浴缸里"] = "in bathtub",
    ["浴罩"] = "bath cover",
    ["浴血"] = "bloody",
    ["浴衣"] = "yukata",
    ["浴袍"] = "bathrobe",
    ["浴足"] = "foot bath",
    ["浴霸"] = "bath heater",
    ["浴鹄湾"] = "yuhu bay",
}

return M
