local M = {}

M.mapping = {
    ["漆上"] = "paint on",
    ["漆出"] = "painted",
    ["漆包线"] = "enameled wire",
    ["漆匠"] = "lacquerer",
    ["漆厂"] = "paint factory",
    ["漆器"] = "lacquerware",
    ["漆园有傲吏"] = "proud official in qiyuan",
    ["漆女忧鲁"] = "qi worries lu",
    ["漆姑草"] = "sagina",
    ["漆封"] = "lacquer seal",
    ["漆尾夜蛾"] = "lacquer-tail moth",
    ["漆工"] = "lacquer worker",
    ["漆布"] = "oilcloth",
    ["漆成"] = "paint",
    ["漆柚"] = "lacquer pomelo",
    ["漆树"] = "lacquer tree",
    ["漆桶"] = "paint bucket",
    ["漆桶底脱"] = "bottomless pit",
    ["漆油炒米酒"] = "fried rice wine",
    ["漆油炖鸡"] = "stewed chicken",
    ["漆油茶"] = "butter tea",
    ["漆漆"] = "pitch-dark",
    ["漆琪生"] = "qi qisheng",
    ["漆画"] = "lacquer painting",
    ["漆皮"] = "patent leather",
    ["漆线雕"] = "lacquer thread carving",
    ["漆膜"] = "paint film",
    ["漆蜡妙食"] = "lacquer wax delicacy",
    ["漆过"] = "painted",
    ["漆道征"] = "qi daozheng",
    ["漆酚"] = "urushiol",
    ["漆雕"] = "lacquer carving",
    ["漆面"] = "paint",
    ["漆面保护膜"] = "paint protection film",
    ["漆黑"] = "pitch black",
    ["漆黑一团"] = "utterly dark",
    ["漆黑一片"] = "pitch-dark",
    ["漆黑水晶球"] = "black crystal ball",
    ["漆黑的"] = "pitch-black",
    ["漆黑鹿角锹形虫"] = "dorcus titanus",
}

return M
