local M = {}

M.mapping = {
    ["悔不当初"] = "regret past actions",
    ["悔不当时留住"] = "regret not keeping at the time",
    ["悔不该"] = "regret shouldn't have",
    ["悔之不及"] = "acknowledgement slip",
    ["悔之亡及"] = "too late for regrets",
    ["悔之何及"] = "wave away",
    ["悔之已晚"] = "too late for regrets",
    ["悔之无及"] = "too late for regrets",
    ["悔之晚矣"] = "too late for regrets",
    ["悔之莫及"] = "too late for regrets",
    ["悔作商人妇"] = "regret being a merchant's wife",
    ["悔其少作"] = "regret early works",
    ["悔婚"] = "break engagement",
    ["悔当初"] = "regret past",
    ["悔恨"] = "regret",
    ["悔恨不已"] = "endless regret",
    ["悔恨交加"] = "filled with regret",
    ["悔恨岭"] = "regret ridge",
    ["悔恨的泪"] = "tears of regret",
    ["悔悟"] = "repentance",
    ["悔意"] = "regret",
    ["悔改"] = "repent",
    ["悔改自新"] = "repent and reform",
    ["悔教夫婿觅封侯"] = "regret teaching husband to seek fame",
    ["悔梦石"] = "dream regret stone",
    ["悔棋"] = "regret move",
    ["悔痛"] = "remorse",
    ["悔着呢"] = "huizhen building",
    ["悔约"] = "kaguya",
    ["悔罪"] = "repentance",
    ["悔罪者"] = "penitent",
    ["悔罪自新"] = "repent and reform",
    ["悔读南华"] = "regret reading nanhua",
    ["悔过"] = "repent",
    ["悔过书"] = "statement of repentance",
    ["悔过自忏"] = "repent and confess",
    ["悔过自新"] = "repent and start anew",
    ["悔过自责"] = "repent and blame oneself",
}

return M
