local M = {}

M.mapping = {
    ["梯子"] = "ladder",
    ["梯山架壑"] = "scale mountains",
    ["梯山栈谷"] = "climb cliffs",
    ["梯度"] = "gradient",
    ["梯度下降"] = "gradient descent",
    ["梯度下降法"] = "gradient descent method",
    ["梯度下降算法"] = "gradient descent algorithm",
    ["梯度化"] = "gradientize",
    ["梯度法"] = "gradient method",
    ["梯形"] = "trapezoid",
    ["梯形图"] = "ladder diagram",
    ["梯形校正"] = "keystone correction",
    ["梯形法则"] = "trapezoidal rule",
    ["梯形积分"] = "trapezoidal integration",
    ["梯形铲"] = "trapezoid shovel",
    ["梯恩梯"] = "tnt",
    ["梯愚入圣"] = "ascendancy",
    ["梯斑墨食蚜蝇"] = "eristalis arbustorum",
    ["梯次"] = "echelon",
    ["梯次分明"] = "clear echelon",
    ["梯河"] = "cascade",
    ["梯状"] = "ladder-like",
    ["梯田"] = "terraces",
    ["梯矩阵"] = "matrix",
    ["梯级"] = "step",
    ["梯级开发"] = "step development",
    ["梯级式"] = "stepped",
    ["梯纹艳苔蛾"] = "miltochrista striata",
    ["梯荣阶禄"] = "rank and wealth",
    ["梯门"] = "ladder door",
    ["梯队"] = "echelon",
    ["梯队式"] = "echelon-style",
    ["梯阵式"] = "echelon",
    ["梯阶"] = "ladder",
}

return M
