local M = {}

M.mapping = {
    ["沪上"] = "shanghai",
    ["沪东"] = "hu dong",
    ["沪东新村"] = "hu dong xin cun",
    ["沪军"] = "shanghai army",
    ["沪剧"] = "shanghai opera",
    ["沪北"] = "north shanghai",
    ["沪南"] = "south shanghai",
    ["沪南公路"] = "hunan highway",
    ["沪嘉高速公路"] = "hujia expressway",
    ["沪城环路"] = "hucheng loop",
    ["沪太路"] = "hutai road",
    ["沪宁"] = "shanghai-nanjing",
    ["沪宁线"] = "shanghai-nanjing line",
    ["沪宁铁路"] = "shanghai-nanjing railway",
    ["沪市"] = "shanghai stock exchange",
    ["沪式巧果"] = "shanghai-style qiaoguo",
    ["沪指"] = "shanghai index",
    ["沪昌特钢"] = "huchang special steel",
    ["沪星村"] = "huxing village",
    ["沪杭"] = "shanghai-hangzhou",
    ["沪杭公路"] = "shanghai-hangzhou highway",
    ["沪杭铁路"] = "shanghai-hangzhou railway",
    ["沪松路"] = "husong road",
    ["沪淞公路"] = "husong highway",
    ["沪深"] = "shanghai and shenzhen",
    ["沪深股市"] = "shanghai and shenzhen stock markets",
    ["沪渝高速"] = "shanghai-chongqing expressway",
    ["沪港杯"] = "shanghai-hong kong cup",
    ["沪科"] = "huke",
    ["沪综指"] = "shanghai composite index",
    ["沪美"] = "shanghai-usa",
    ["沪芦高速公路"] = "hulu expressway",
    ["沪苏通"] = "shanghai-suzhou-nantong",
    ["沪菜"] = "shanghai cuisine",
    ["沪蓉高速"] = "shanghai-chengdu expressway",
    ["沪西"] = "huxi",
    ["沪语"] = "shanghai dialect",
    ["沪铜"] = "shanghai copper",
    ["沪闵路"] = "humin road",
    ["沪青平"] = "huqingping",
    ["沪青平公路"] = "huqingping highway",
}

return M
