local M = {}

M.mapping = {
    ["拐上"] = "turn onto",
    ["拐个弯"] = "turn a corner",
    ["拐个弯儿"] = "turn a corner",
    ["拐了"] = "turned",
    ["拐了个弯"] = "turned a corner",
    ["拐了个弯儿"] = "turned a corner",
    ["拐入"] = "turn into",
    ["拐到"] = "turn to",
    ["拐卖"] = "trafficking",
    ["拐卖人口"] = "human trafficking",
    ["拐卖儿童"] = "child trafficking",
    ["拐卖妇女"] = "trafficking of women",
    ["拐卖妇女儿童"] = "trafficking of women and children",
    ["拐卖婴儿"] = "infant trafficking",
    ["拐卖者"] = "trafficker",
    ["拐去"] = "take away",
    ["拐啦"] = "turn",
    ["拐子"] = "swindler",
    ["拐带"] = "abduct",
    ["拐弯"] = "turn",
    ["拐弯处"] = "at the turn",
    ["拐弯抹角"] = "beat about the bush",
    ["拐杖"] = "cane",
    ["拐杖糖"] = "candy cane",
    ["拐来"] = "bring over",
    ["拐枣"] = "hovenia",
    ["拐枣树街"] = "hovenia tree street",
    ["拐棍"] = "walking stick",
    ["拐棍儿"] = "walking stick",
    ["拐棒"] = "walking stick",
    ["拐棒胡同"] = "walking stick hutong",
    ["拐点"] = "inflection point",
    ["拐着"] = "turning",
    ["拐脖儿"] = "elbow",
    ["拐角"] = "corner",
    ["拐角处"] = "at the corner",
    ["拐角马"] = "knight",
    ["拐走"] = "abduct",
    ["拐跑"] = "run off with",
    ["拐过"] = "turn past",
    ["拐进"] = "turn into",
    ["拐骗"] = "swindle",
}

return M
