local M = {}

M.mapping = {
    ["朴俊奎"] = "park jun-kyu",
    ["朴刀"] = "podao",
    ["朴勇宇"] = "park yongwoo",
    ["朴厚"] = "simple and honest",
    ["朴变色夜蛾"] = "eudocima homaena",
    ["朴学"] = "textual criticism",
    ["朴实"] = "simple",
    ["朴实作风"] = "simple style",
    ["朴实无华"] = "simple and unadorned",
    ["朴实的"] = "simple",
    ["朴拙"] = "rustic",
    ["朴振英"] = "jyp",
    ["朴树"] = "hackberry",
    ["朴树朴盾木虱"] = "hackberry psyllid",
    ["朴槿惠"] = "park geun-hye",
    ["朴正熙"] = "park chunghee",
    ["朴永训"] = "park yonghun",
    ["朴海日"] = "park hae-il",
    ["朴炡禹"] = "park jungwoo",
    ["朴直"] = "honest",
    ["朴相勉"] = "park sang-myun",
    ["朴真熙"] = "park jinhee",
    ["朴硝"] = "mirabilite",
    ["朴素"] = "simple",
    ["朴素唯物主义"] = "naive materialism",
    ["朴素大方"] = "simple and elegant",
    ["朴素无华"] = "simple and unadorned",
    ["朴素的"] = "simple",
    ["朴素而天下莫能与之争美"] = "simplicity is unequaled",
    ["朴素贝叶斯"] = "naive bayes",
    ["朴美宣"] = "park mi-sun",
    ["朴茂"] = "simple and vigorous",
    ["朴茨茅斯"] = "portsmouth",
    ["朴茨茅斯条约"] = "portsmouth treaty",
    ["朴讷"] = "simple and reticent",
    ["朴诗妍"] = "vote count",
    ["朴质"] = "simple",
    ["朴赞郁"] = "park chanwook",
    ["朴趾源"] = "park jiwon",
    ["朴长体茧蜂"] = "braconid wasp",
    ["朴陋"] = "simple and crude",
    ["朴雅"] = "simple and elegant",
}

return M
