local M = {}

M.mapping = {
    ["浇上"] = "pour on",
    ["浇下"] = "pour down",
    ["浇了"] = "poured",
    ["浇了个透"] = "soaked through",
    ["浇入"] = "pour into",
    ["浇冷水"] = "pour cold water",
    ["浇到"] = "pour onto",
    ["浇口"] = "gate",
    ["浇在"] = "pour on",
    ["浇地"] = "irrigate land",
    ["浇头"] = "topping",
    ["浇底乡"] = "jiaodi township",
    ["浇愁"] = "drown sorrows",
    ["浇料"] = "pouring material",
    ["浇水"] = "water",
    ["浇水施肥"] = "water and fertilize",
    ["浇汁"] = "sauce",
    ["浇汁煎鱼段"] = "fried fish with sauce",
    ["浇汁鱼"] = "fish with sauce",
    ["浇注"] = "casting",
    ["浇注速度"] = "pouring speed",
    ["浇洒"] = "sprinkle",
    ["浇湿"] = "waterlogged",
    ["浇漓"] = "decadent",
    ["浇灌"] = "irrigation",
    ["浇灭"] = "extinguish",
    ["浇熄"] = "extinguish",
    ["浇筑"] = "pouring",
    ["浇花"] = "water flowers",
    ["浇薄"] = "superficial",
    ["浇透"] = "water thoroughly",
    ["浇铸"] = "casting",
    ["浇铸工"] = "caster",
}

return M
