local M = {}

M.mapping = {
    ["樊丽明"] = "fan liming",
    ["樊亦敏"] = "fan yimin",
    ["樊凯杰"] = "fan kaijie",
    ["樊哙"] = "fan kuai",
    ["樊哙从良坐"] = "fan kuai sat down beside liang",
    ["樊哙侧其盾以撞"] = "fan kuai tilted his shield to ram",
    ["樊哙覆其盾于地"] = "fan kuai overturned his shield on the ground",
    ["樊城区"] = "fancheng district",
    ["樊增祥"] = "fan zengxiang",
    ["樊姓"] = "surname fan",
    ["樊学峰"] = "fan xuefeng",
    ["樊家寨"] = "fanjiazhai",
    ["樊家寺"] = "fanjiasi",
    ["樊家川乡"] = "fanjiachuan township",
    ["樊家村北站"] = "fanjiacun north station",
    ["樊川"] = "fanchuan",
    ["樊庄村"] = "fanzhuang village",
    ["樊志松"] = "fan zhizhong",
    ["樊春晖"] = "fan chunhui",
    ["樊晓丹"] = "fan xiaodan",
    ["樊村河乡"] = "fancunhe township",
    ["樊梨花"] = "fan lihua",
    ["樊江关"] = "fanjiangguan",
    ["樊洼路"] = "fanwa road",
    ["樊笼"] = "cage",
    ["樊篱"] = "fence",
    ["樊粹庭"] = "fan cuiting",
    ["樊羊路北口"] = "north entrance of fanyang road",
    ["樊西巷"] = "fanxi lane",
    ["樊记肉加馍"] = "fanji meat sandwich",
    ["樊记腊汁肉"] = "fanji cured meat",
    ["樊迟从游于舞雩之下"] = "fan chi follows youwu",
    ["樊迟请学稼"] = "fan chi asks to learn farming",
    ["樊钟秀"] = "fan zhongxiu",
}

return M
