local M = {}

M.mapping = {
    ["涡喷"] = "turbojet",
    ["涡喷发动机"] = "turbojet engine",
    ["涡扇"] = "turbofan",
    ["涡扇发动机"] = "turbofan engine",
    ["涡旋"] = "vortex",
    ["涡旋式"] = "vortex type",
    ["涡旋形"] = "vortex shape",
    ["涡桨"] = "turboprop",
    ["涡桨发动机"] = "turboprop engine",
    ["涡河"] = "wo river",
    ["涡流"] = "eddy current",
    ["涡流管"] = "vortex tube",
    ["涡电流"] = "eddy current",
    ["涡管"] = "vortex tube",
    ["涡纹"] = "whorl",
    ["涡虫"] = "planarian",
    ["涡虫类动物"] = "turbellarian",
    ["涡街流量计"] = "vortex flow meter",
    ["涡轮"] = "turbine",
    ["涡轮喷气"] = "turbojet",
    ["涡轮喷气式"] = "turbojet",
    ["涡轮喷气式发动机"] = "turbojet engine",
    ["涡轮增压"] = "turbocharging",
    ["涡轮手机"] = "turbine phone",
    ["涡轮机"] = "turbine",
    ["涡轮流量计"] = "turbine flowmeter",
    ["涡轮牙钻机"] = "turbine dental drill",
    ["涡轮螺旋桨飞机"] = "turboprop aircraft",
    ["涡轮螺桨"] = "turboprop",
    ["涡轮螺桨式"] = "turboprop",
    ["涡轮螺桨式发动机"] = "turboprop engine",
    ["涡轮轴"] = "turboshaft",
    ["涡轮轴发动机"] = "turboshaft engine",
    ["涡轮风扇"] = "turbofan",
    ["涡轮风扇式"] = "turbofan type",
    ["涡轮风扇式发动机"] = "turbofan",
    ["涡轴"] = "turboshaft",
    ["涡轴发动机"] = "turboshaft engine",
    ["涡阳"] = "guoyang",
    ["涡阳县"] = "guoyang county",
    ["涡阳路"] = "guoyang road",
}

return M
