local M = {}

M.mapping = {
    ["掏一掏"] = "dig out",
    ["掏上了"] = "pull out",
    ["掏不出"] = "cannot afford",
    ["掏不起"] = "cannot afford",
    ["掏了"] = "dug",
    ["掏了出来"] = "pulled out",
    ["掏了掏"] = "fumbled",
    ["掏光"] = "empty out",
    ["掏兜"] = "pick pocket",
    ["掏内脏"] = "eviscerate",
    ["掏出"] = "take out",
    ["掏出了"] = "took out",
    ["掏出来"] = "take out",
    ["掏到"] = "dig out",
    ["掏包"] = "pickpocket",
    ["掏尽"] = "exhaust",
    ["掏底"] = "dig bottom",
    ["掏得起"] = "afford",
    ["掏心"] = "heartfelt",
    ["掏掏"] = "taotao",
    ["掏摸"] = "pickpocket",
    ["掏枪"] = "draw gun",
    ["掏槽"] = "grooving",
    ["掏沙壅河"] = "dig sand to block river",
    ["掏洞"] = "dig hole",
    ["掏球"] = "steal ball",
    ["掏空"] = "hollow out",
    ["掏窟窿"] = "dig holes",
    ["掏粪"] = "sewage cleaning",
    ["掏耳"] = "ear picking",
    ["掏耳勺"] = "ear pick",
    ["掏耳朵"] = "ear cleaning",
    ["掏肺"] = "heart-to-heart",
    ["掏腰包"] = "pay out of pocket",
    ["掏钱"] = "pay",
    ["掏鸟"] = "bird poaching",
    ["掏鸟巢"] = "nest robbing",
    ["掏鸟窝"] = "nest raiding",
    ["掏鸟蛋"] = "egg stealing",
}

return M
