local M = {}

M.mapping = {
    ["援之以手"] = "lend a hand",
    ["援交"] = "compensated dating",
    ["援例"] = "precedent",
    ["援兵"] = "reinforcements",
    ["援军"] = "reinforcements",
    ["援助"] = "aid",
    ["援助中心"] = "aid center",
    ["援助之手"] = "helping hand",
    ["援助于"] = "assist to",
    ["援助交际"] = "compensated dating",
    ["援助制度"] = "aid system",
    ["援助国"] = "donor country",
    ["援助性"] = "assistive",
    ["援助者"] = "helper",
    ["援助计划"] = "aid program",
    ["援助额"] = "aid amount",
    ["援北斗兮酌桂浆"] = "pour osmanthus wine by the big dipper",
    ["援古刺今"] = "cite past for present",
    ["援外"] = "foreign aid",
    ["援外青年志愿者选派和管理暂行办法"] = "volunteer dispatch rules",
    ["援建"] = "aid construction",
    ["援引"] = "cite",
    ["援手"] = "lend a hand",
    ["援敌"] = "aid enemy",
    ["援救"] = "rescue",
    ["援救者"] = "rescuer",
    ["援救队"] = "rescue team",
    ["援朝"] = "aid korea",
    ["援款"] = "aid funds",
    ["援溺振渴"] = "save needy",
    ["援琴鸣弦发清商"] = "pluck the zither and play the clear tune",
    ["援用"] = "invoke",
    ["援疆"] = "aid xinjiang",
    ["援笔"] = "take up pen",
    ["援笔成章"] = "write quickly",
    ["援藏"] = "aid tibet",
    ["援鄂医疗队"] = "hubei medical support team",
    ["援鳖失龟"] = "lose more than gain",
}

return M
