local M = {}

M.mapping = {
    ["琉三路口"] = "liusang intersection",
    ["琉球"] = "ryukyu",
    ["琉球群岛"] = "ryukyu islands",
    ["琉球鬃尾单棘鲀"] = "ryukyu leatherjacket",
    ["琉球黑林鸽"] = "ryukyu wood pigeon",
    ["琉璃"] = "colored glaze",
    ["琉璃一街"] = "liuli first street",
    ["琉璃井"] = "glaze well",
    ["琉璃井社区"] = "liulijing community",
    ["琉璃仙境"] = "glazed fairyland",
    ["琉璃卷叶象鼻虫"] = "glaze leaf weevil",
    ["琉璃厂"] = "liulichang",
    ["琉璃厂社区"] = "liulichang community",
    ["琉璃场"] = "glaze yard",
    ["琉璃坊"] = "glaze workshop",
    ["琉璃寺胡同"] = "liulisi hutong",
    ["琉璃寺镇"] = "liulisi town",
    ["琉璃庙"] = "glaze temple",
    ["琉璃榻"] = "glazed couch",
    ["琉璃河"] = "liuli river",
    ["琉璃河地区"] = "liuli river area",
    ["琉璃河检查站"] = "liuli river checkpoint",
    ["琉璃河检测站"] = "liuli river testing station",
    ["琉璃河水泥厂"] = "liuli river cement plant",
    ["琉璃渠"] = "liuliqu",
    ["琉璃火"] = "glazed fire",
    ["琉璃灯"] = "glazed lamp",
    ["琉璃珠玑"] = "glazed beads",
    ["琉璃瓦"] = "glazed tile",
    ["琉璃百合"] = "glazed lily",
    ["琉璃盏的碎片"] = "shards of glazed cup",
    ["琉璃自然魔杖"] = "glazed natural wand",
    ["琉璃苣"] = "borage",
    ["琉璃苣油"] = "borage oil",
    ["琉璃苣籽"] = "borage seeds",
    ["琉璃苣籽油"] = "borage seed oil",
    ["琉璃藕"] = "glazed lotus root",
    ["琉瓶灌朱"] = "glazed bottle filled with vermilion",
}

return M
