local M = {}

M.mapping = {
    ["码云"] = "gitee",
    ["码位"] = "code point",
    ["码值"] = "code value",
    ["码元"] = "code element",
    ["码元表"] = "code element table",
    ["码元集"] = "code element set",
    ["码农"] = "coder",
    ["码出"] = "ma chu",
    ["码分多址"] = "cdma",
    ["码区"] = "code area",
    ["码单"] = "code list",
    ["码口乡"] = "makou township",
    ["码垛"] = "palletizing",
    ["码垛机"] = "palletizer",
    ["码头"] = "dock",
    ["码头上"] = "on the dock",
    ["码头区"] = "dock area",
    ["码头工人"] = "docker",
    ["码头村"] = "matou village",
    ["码头社区"] = "dock community",
    ["码头费"] = "dock fee",
    ["码好"] = "stacked",
    ["码子"] = "code",
    ["码字"] = "typing",
    ["码放"] = "stack",
    ["码数"] = "size",
    ["码本"] = "codebook",
    ["码洋"] = "sales",
    ["码流"] = "bitstream",
    ["码流分析"] = "bitstream analysis",
    ["码流率"] = "bitrate",
    ["码点"] = "ma dian",
    ["码片"] = "code chip",
    ["码率"] = "bitrate",
    ["码率控制"] = "bitrate control",
    ["码畜"] = "ma chu",
    ["码系统"] = "code system",
    ["码组"] = "code group",
    ["码表"] = "code table",
    ["码长"] = "ma zhang",
}

return M
