local M = {}

M.mapping = {
    ["督促"] = "urge",
    ["督促司"] = "supervisory department",
    ["督促检查"] = "supervisory inspection",
    ["督促程序"] = "supervisory procedure",
    ["督军"] = "military governor",
    ["督办"] = "supervise",
    ["督办件"] = "supervised item",
    ["督办案件"] = "supervise cases",
    ["督学"] = "school inspector",
    ["督察"] = "supervisor",
    ["督察员"] = "supervisor",
    ["督察组"] = "inspection team",
    ["督察长"] = "chief supervisor",
    ["督导"] = "supervision",
    ["督导员"] = "supervisor",
    ["督导室"] = "supervision office",
    ["督导组"] = "supervisory group",
    ["督导评估"] = "supervisory evaluation",
    ["督工"] = "overseer",
    ["督师"] = "supervising troops",
    ["督府"] = "governor's office",
    ["督战"] = "supervise battle",
    ["督抚"] = "governor",
    ["督查"] = "inspect",
    ["督查工作"] = "inspection work",
    ["督标"] = "supervisory standard",
    ["督率"] = "supervising and leading",
    ["督相"] = "supervising minister",
    ["督脉"] = "governing vessel",
    ["督脉灸"] = "governing vessel moxibustion",
    ["督腧穴"] = "dushu point",
    ["督过"] = "supervised",
    ["督造"] = "supervise construction",
    ["督邮"] = "postal inspector",
    ["督阵"] = "supervise battle array",
    ["督院街"] = "duyuan street",
}

return M
