local M = {}

M.mapping = {
    ["熔丝"] = "fuse",
    ["熔于一炉"] = "blend into one",
    ["熔今铸古"] = "combine ancient and modern",
    ["熔体"] = "melt",
    ["熔制"] = "melting",
    ["熔剂"] = "flux",
    ["熔化"] = "melting",
    ["熔化为"] = "melted into",
    ["熔化成"] = "melted into",
    ["熔化炉"] = "melting furnace",
    ["熔化热"] = "heat of fusion",
    ["熔古铸今"] = "fuse ancient and modern",
    ["熔合"] = "fusion",
    ["熔岩"] = "lava",
    ["熔岩之地"] = "land of lava",
    ["熔岩图腾"] = "lava totem",
    ["熔岩神射手"] = "lava sharpshooter",
    ["熔接"] = "welding",
    ["熔接机"] = "welding machine",
    ["熔断"] = "circuit breaker",
    ["熔断器"] = "fuse",
    ["熔断性"] = "fusibility",
    ["熔模铸造"] = "investment casting",
    ["熔渣"] = "slag",
    ["熔炉"] = "furnace",
    ["熔炉芋螺"] = "furnace cone",
    ["熔点"] = "melting point",
    ["熔炼"] = "smelting",
    ["熔炼炉"] = "smelting furnace",
    ["熔焊"] = "fusion welding",
    ["熔盐"] = "molten salt",
    ["熔经铸史"] = "master classics and history",
    ["熔融"] = "melting",
    ["熔融指数"] = "melt flow index",
    ["熔融法"] = "melting method",
    ["熔解"] = "fusion",
    ["熔铝炉"] = "aluminum melting furnace",
    ["熔铸"] = "casting",
    ["熔锡"] = "solder",
}

return M
