local M = {}

M.mapping = {
    ["碗中"] = "in the bowl",
    ["碗仔翅"] = "bowl-shaped shark fin",
    ["碗儿"] = "bowl",
    ["碗内"] = "inside the bowl",
    ["碗勺"] = "bowl and spoon",
    ["碗口"] = "bowl rim",
    ["碗型"] = "bowl type",
    ["碗底"] = "bowl bottom",
    ["碗朝地"] = "bowl upside down",
    ["碗柜"] = "cupboard",
    ["碗橱"] = "cupboard",
    ["碗汁"] = "bowl sauce",
    ["碗沿"] = "bowl rim",
    ["碗状"] = "bowl-shaped",
    ["碗状的"] = "bowl-shaped",
    ["碗盆"] = "bowl and basin",
    ["碗盏"] = "bowl and cup",
    ["碗盘"] = "bowls and plates",
    ["碗碗腔"] = "wanwanqiang",
    ["碗碗香"] = "bowl aroma",
    ["碗碟"] = "dishes",
    ["碗碟橱"] = "dish cabinet",
    ["碗碴儿"] = "broken bowl",
    ["碗窑"] = "bowl kiln",
    ["碗筷"] = "bowls and chopsticks",
    ["碗米坡镇"] = "wanmipo town",
    ["碗粿"] = "rice bowl cake",
    ["碗耳糕"] = "bowl ear cake",
    ["碗莲"] = "bowl lotus",
    ["碗边"] = "bowl edge",
    ["碗里"] = "in the bowl",
    ["碗面"] = "cup noodles",
    ["碗饭"] = "bowl rice",
}

return M
