local M = {}

M.mapping = {
    ["筑了"] = "built",
    ["筑圩"] = "build dike",
    ["筑坝"] = "dam construction",
    ["筑垒"] = "fortify",
    ["筑城"] = "fortify",
    ["筑基"] = "foundation building",
    ["筑堤"] = "build embankment",
    ["筑墙"] = "wall building",
    ["筑宾"] = "zhubin",
    ["筑屋"] = "build house",
    ["筑岩钓渭"] = "fishing in wei",
    ["筑巢"] = "nesting",
    ["筑巢引凤"] = "nesting attracts phoenix",
    ["筑底"] = "bottoming",
    ["筑成"] = "build",
    ["筑有"] = "constructed",
    ["筑桥"] = "bridge building",
    ["筑梦"] = "build dreams",
    ["筑梦公馆"] = "dream mansion",
    ["筑波市"] = "tsukuba city",
    ["筑波科学城"] = "tsukuba science city",
    ["筑波站"] = "tsukuba station",
    ["筑炉"] = "furnace building",
    ["筑牢"] = "strengthen",
    ["筑牢安全防线"] = "strengthen security",
    ["筑牢防线"] = "fortify defenses",
    ["筑舍道傍"] = "building a house by the roadside",
    ["筑起"] = "build up",
    ["筑路"] = "road construction",
    ["筑路工"] = "road worker",
    ["筑路工程"] = "road construction",
    ["筑路机械"] = "road machinery",
    ["筑路队"] = "road crew",
    ["筑造学"] = "casting science",
    ["筑造抓地"] = "traction building",
    ["筑长城"] = "building the great wall",
}

return M
