local M = {}

M.mapping = {
    ["珊儿"] = "shan er",
    ["珊尔丽雪"] = "shan er li xue",
    ["珊屏村"] = "shanping village",
    ["珊瑚"] = "coral",
    ["珊瑚七十味丸"] = "coral 70 pills",
    ["珊瑚凤头"] = "coral crest",
    ["珊瑚台"] = "coral terrace",
    ["珊瑚在网"] = "coral in net",
    ["珊瑚坝"] = "coral dam",
    ["珊瑚姜"] = "coral ginger",
    ["珊瑚宫"] = "coral palace",
    ["珊瑚岛"] = "coral island",
    ["珊瑚戒指"] = "coral ring",
    ["珊瑚映日"] = "coral reflects sunlight",
    ["珊瑚映绿水"] = "coral reflects green water",
    ["珊瑚木难"] = "coral wood",
    ["珊瑚树"] = "coral tree",
    ["珊瑚楼"] = "coral tower",
    ["珊瑚沙水库"] = "coral sand reservoir",
    ["珊瑚海"] = "coral sea",
    ["珊瑚石"] = "coral stone",
    ["珊瑚礁"] = "coral reef",
    ["珊瑚耳环"] = "coral earrings",
    ["珊瑚色"] = "coral color",
    ["珊瑚花"] = "coral flower",
    ["珊瑚藤"] = "coral vine",
    ["珊瑚虫"] = "coral polyp",
    ["珊瑚虫版"] = "coral polyp edition",
    ["珊瑚金钩"] = "coral hook",
    ["珊瑚间木难"] = "coral wood",
    ["珊瑚雪花鸡"] = "coral snowflake chicken",
    ["珊瑚鱼丁"] = "coral fish cubes",
    ["珊瑚鳜鱼"] = "coral mandarin fish",
    ["珊目尔"] = "samuel",
    ["珊莎"] = "sansa",
    ["珊莱尔"] = "sanlair",
    ["珊蝴虫"] = "coral polyp",
    ["珊迪"] = "sandy",
}

return M
