local M = {}

M.mapping = {
    ["硕人其颀"] = "tall and handsome",
    ["硕儒"] = "great scholar",
    ["硕儒村"] = "great scholar village",
    ["硕士"] = "master",
    ["硕士专业学位"] = "master's degree",
    ["硕士学位"] = "master degree",
    ["硕士学生"] = "master student",
    ["硕士招生"] = "master's admission",
    ["硕士文凭"] = "master diploma",
    ["硕士服"] = "master gown",
    ["硕士毕业"] = "master graduate",
    ["硕士班"] = "master class",
    ["硕士生"] = "master student",
    ["硕士研究生"] = "master graduate student",
    ["硕士研究生入学"] = "master admission",
    ["硕士研究生招生"] = "master recruitment",
    ["硕士研究生毕业"] = "master graduate",
    ["硕士论文"] = "master thesis",
    ["硕士课程"] = "master course",
    ["硕士路"] = "master road",
    ["硕壮"] = "strong",
    ["硕大"] = "huge",
    ["硕大无朋"] = "colossal",
    ["硕大无比"] = "gigantic",
    ["硕大的"] = "massive",
    ["硕学"] = "erudite",
    ["硕学通儒"] = "learned scholar",
    ["硕导"] = "phd advisor",
    ["硕望宿德"] = "revered elder",
    ["硕果"] = "fruit",
    ["硕果仅存"] = "sole survivor",
    ["硕果累累"] = "fruitful",
    ["硕泰克"] = "soltek",
    ["硕督镇"] = "shuodu town",
    ["硕集镇"] = "shuoji town",
    ["硕鼠硕鼠"] = "big rats",
}

return M
