local M = {}

M.mapping = {
    ["纠举"] = "impeach",
    ["纠举权"] = "impeachment power",
    ["纠众"] = "gather",
    ["纠偏"] = "correction",
    ["纠合"] = "gang up",
    ["纠察"] = "picket",
    ["纠察员"] = "picket",
    ["纠察队"] = "picket team",
    ["纠正"] = "correct",
    ["纠正不正之风"] = "correct unhealthy tendencies",
    ["纠正偏差"] = "correct deviation",
    ["纠正情况"] = "correction status",
    ["纠正意见"] = "correction",
    ["纠正措施"] = "corrective measures",
    ["纠正错误"] = "correct mistakes",
    ["纠纷"] = "dispute",
    ["纠纷个"] = "dispute",
    ["纠纷案"] = "dispute case",
    ["纠纷案件"] = "dispute cases",
    ["纠结"] = "entangled",
    ["纠缠"] = "entangle",
    ["纠缠不休"] = "incessantly entangled",
    ["纠缠不清"] = "inextricably entangled",
    ["纠缠根须"] = "entangling roots",
    ["纠缠着"] = "entangled",
    ["纠缠者"] = "entangler",
    ["纠缪绳违"] = "correct mistakes and enforce rules",
    ["纠葛"] = "entanglement",
    ["纠错"] = "error correction",
    ["纠错码"] = "error correction code",
    ["纠错能力"] = "error correction capability",
    ["纠集"] = "gather",
    ["纠风"] = "rectify",
    ["纠风办"] = "rectification office",
}

return M
