local M = {}

M.mapping = {
    ["禾下乘凉"] = "cool under the grain",
    ["禾下乘凉梦"] = "dream of cooling under grain",
    ["禾丰布依族苗族乡"] = "hefeng buyi and miao township",
    ["禾兴北路"] = "hexing north road",
    ["禾兴路"] = "hexing road",
    ["禾嘉股份"] = "hejia shares",
    ["禾场"] = "threshing floor",
    ["禾头生耳"] = "ears growing on rice stalks",
    ["禾尼乡"] = "heni township",
    ["禾山乡"] = "heshan township",
    ["禾山街道"] = "heshan street",
    ["禾斛岭垦殖场"] = "hehuling reclamation farm",
    ["禾望电气"] = "hewang electric",
    ["禾木旁"] = "grain radical",
    ["禾欣股份"] = "hexin shares",
    ["禾洞农林场"] = "hedong agricultural and forestry farm",
    ["禾洞镇"] = "hedong town",
    ["禾浩辰"] = "he haochen",
    ["禾滩乡"] = "hetan township",
    ["禾灰翅夜蛾"] = "cereal gray-winged noctuid",
    ["禾生耳"] = "ears grow on grain",
    ["禾生陇亩无东西"] = "grain grows in fields without east or west",
    ["禾田"] = "rice field",
    ["禾田大厦"] = "hetian building",
    ["禾盛新材"] = "hesheng new materials",
    ["禾祥东路"] = "hexiang east road",
    ["禾祥西路"] = "hexiang west road",
    ["禾秆"] = "rice straw",
    ["禾秆鲤"] = "rice straw carp",
    ["禾稻"] = "rice crop",
    ["禾背刺毡蜡蚧"] = "rice scale insect",
    ["禾苗"] = "seedlings",
    ["禾草"] = "grass",
    ["禾虫"] = "river creek",
    ["禾谷"] = "cereal crops",
    ["禾谷园"] = "cereal garden",
    ["禾驮乡"] = "hetuo township",
    ["禾黍故宫"] = "millet palace",
}

return M
