local M = {}

M.mapping = {
    ["笨了"] = "stupid",
    ["笨人"] = "stupid person",
    ["笨伯"] = "fool",
    ["笨哟"] = "silly you",
    ["笨啊"] = "stupid",
    ["笨嘴拙舌"] = "awkward in speech",
    ["笨头笨脑"] = "dull-witted",
    ["笨女人"] = "stupid woman",
    ["笨家伙"] = "clumsy fellow",
    ["笨小孩"] = "foolish child",
    ["笨得像"] = "as stupid as",
    ["笨手笨脚"] = "clumsy",
    ["笨拙"] = "clumsy",
    ["笨月饼"] = "stupid mooncake",
    ["笨死"] = "so stupid",
    ["笨死了"] = "so damn stupid",
    ["笨比"] = "idiot",
    ["笨活儿"] = "hard work",
    ["笨熊"] = "clumsy bear",
    ["笨牛"] = "stupid ox",
    ["笨狗"] = "stupid dog",
    ["笨猪"] = "stupid pig",
    ["笨猫"] = "stupid cat",
    ["笨瓜"] = "idiot",
    ["笨的"] = "stupid",
    ["笨笨"] = "silly",
    ["笨笨森林日志"] = "silly forest log",
    ["笨笨森林日记"] = "silly forest diary",
    ["笨笨熊"] = "silly bear",
    ["笨笨猪"] = "silly pig",
    ["笨笨猫"] = "silly cat",
    ["笨蛋"] = "idiot",
    ["笨货"] = "idiot",
    ["笨贼"] = "stupid thief",
    ["笨重"] = "cumbersome",
    ["笨驴"] = "stupid donkey",
    ["笨鸟"] = "clumsy bird",
    ["笨鸟先飞"] = "slow and steady wins the race",
}

return M
