local M = {}

M.mapping = {
    ["瓶上"] = "on bottle",
    ["瓶中"] = "in the bottle",
    ["瓶中沙"] = "sand in the bottle",
    ["瓶内"] = "inside the bottle",
    ["瓶区鳞跨茧蜂"] = "ichneumon wasp",
    ["瓶口"] = "bottle mouth",
    ["瓶啤"] = "bottled beer",
    ["瓶圆田螺"] = "bottle snail",
    ["瓶塞"] = "bottle stopper",
    ["瓶塞儿"] = "cork",
    ["瓶子"] = "bottle",
    ["瓶子里"] = "in the bottle",
    ["瓶底"] = "bottle bottom",
    ["瓶形隙蛛"] = "bottle-shaped gap spider",
    ["瓶瓶罐罐"] = "pots and pans",
    ["瓶盖"] = "bottle cap",
    ["瓶盖厂"] = "cap factory",
    ["瓶盖子"] = "bottle lid",
    ["瓶砂壳虫"] = "testate amoeba",
    ["瓶罐"] = "bottles and cans",
    ["瓶胆"] = "bottle liner",
    ["瓶花"] = "bottle flower",
    ["瓶装"] = "bottled",
    ["瓶装水"] = "bottled water",
    ["瓶装金针菇"] = "bottled enoki",
    ["瓶身"] = "bottle body",
    ["瓶酒"] = "bottled wine",
    ["瓶里"] = "in bottle",
    ["瓶颈"] = "bottleneck",
    ["瓶颈制约"] = "bottleneck constraint",
    ["瓶颈期"] = "bottleneck period",
    ["瓶鼻鲸"] = "bottlenose whale",
    ["瓶鼻鲸属"] = "hyperoodon",
}

return M
