local M = {}

M.mapping = {
    ["筛一筛"] = "sift",
    ["筛下"] = "undersize",
    ["筛了筛"] = "sifted a bit",
    ["筛余"] = "screen residue",
    ["筛出"] = "screen out",
    ["筛分"] = "screening",
    ["筛分机"] = "screening machine",
    ["筛去"] = "sift out",
    ["筛子"] = "sieve",
    ["筛孔"] = "sieve pore",
    ["筛完"] = "after screening",
    ["筛月亭"] = "moon screening pavilion",
    ["筛板"] = "sieve plate",
    ["筛查"] = "screening",
    ["筛检"] = "screening",
    ["筛毛盆步甲"] = "pogonus chalceus",
    ["筛法求素数"] = "sieve method for primes",
    ["筛洗"] = "screen and wash",
    ["筛渣"] = "screen residue",
    ["筛窦"] = "ethmoid sinus",
    ["筛窦炎"] = "ethmoid sinusitis",
    ["筛窦钳"] = "ethmoid sinus forceps",
    ["筛管"] = "sieve tube",
    ["筛粉机"] = "powder screening machine",
    ["筛糠"] = "sift chaff",
    ["筛素数"] = "sieve primes",
    ["筛网"] = "screen mesh",
    ["筛网厂"] = "screen factory",
    ["筛过"] = "screened",
    ["筛选"] = "filter",
    ["筛选出"] = "filter out",
    ["筛选制度"] = "screening system",
    ["筛选器"] = "filter",
    ["筛选机"] = "screening machine",
    ["筛选模式"] = "filter mode",
    ["筛选法"] = "screening method",
    ["筛选法求素数"] = "sieve method for primes",
    ["筛锣擂鼓"] = "beat gongs and drums",
    ["筛除"] = "screen out",
    ["筛骨"] = "ethmoid bone",
}

return M
