local M = {}

M.mapping = {
    ["瞬刻"] = "instant",
    ["瞬即"] = "instant",
    ["瞬发"] = "instantaneous",
    ["瞬变"] = "transient",
    ["瞬彩"] = "instant color",
    ["瞬态"] = "transient",
    ["瞬态分析"] = "transient analysis",
    ["瞬态响应"] = "transient response",
    ["瞬态电压"] = "transient voltage",
    ["瞬息"] = "instant",
    ["瞬息万变"] = "fast-changing",
    ["瞬息万状"] = "multifarious",
    ["瞬息之间"] = "in a flash",
    ["瞬息千里"] = "a thousand miles in an instant",
    ["瞬息即逝"] = "fleeting",
    ["瞬息间"] = "in an instant",
    ["瞬时"] = "instantaneous",
    ["瞬时值"] = "instantaneous value",
    ["瞬时加速度"] = "instantaneous acceleration",
    ["瞬时故障"] = "transient fault",
    ["瞬时现象"] = "transient phenomenon",
    ["瞬时电流"] = "transient current",
    ["瞬时的"] = "instantaneous",
    ["瞬时速度"] = "instantaneous velocity",
    ["瞬时速率"] = "instantaneous speed",
    ["瞬时错误"] = "transient error",
    ["瞬狱影杀阵"] = "instant prison shadow kill",
    ["瞬目"] = "blink",
    ["瞬目膜带虫"] = "thelazia callipaeda",
    ["瞬秒"] = "instant kill",
    ["瞬移"] = "teleport",
    ["瞬膜"] = "nictitating membrane",
    ["瞬间"] = "moment",
    ["瞬间即逝"] = "fleeting",
    ["瞬间移动"] = "teleport",
    ["瞬间胶"] = "instant glue",
}

return M
