local M = {}

M.mapping = {
    ["秒不了"] = "can't finish in seconds",
    ["秒了"] = "finished",
    ["秒人"] = "instant kill",
    ["秒伤"] = "damage per second",
    ["秒内"] = "within seconds",
    ["秒删"] = "instant delete",
    ["秒到"] = "arrive instantly",
    ["秒发"] = "instant delivery",
    ["秒变"] = "instant change",
    ["秒啦"] = "instant loan",
    ["秒回"] = "instant reply",
    ["秒射"] = "premature ejaculation",
    ["秒开"] = "instant open",
    ["秒懂"] = "instant comprehension",
    ["秒懂百科"] = "instant wiki",
    ["秒批"] = "instant approval",
    ["秒拍"] = "miaopai",
    ["秒拍视频"] = "miaopai video",
    ["秒掉"] = "defeat instantly",
    ["秒掉了"] = "instantly defeated",
    ["秒摆"] = "seconds pendulum",
    ["秒播"] = "instant play",
    ["秒数"] = "seconds",
    ["秒杀"] = "seckill",
    ["秒杀价"] = "seckill price",
    ["秒杀活动"] = "seckill event",
    ["秒杀系统"] = "seckill system",
    ["秒杀脚本"] = "seckill script",
    ["秒杀门"] = "seckill gate",
    ["秒死"] = "instant death",
    ["秒点"] = "precise point",
    ["秒答"] = "instant reply",
    ["秒表"] = "stopwatch",
    ["秒进"] = "instant access",
    ["秒违例"] = "second violation",
    ["秒退"] = "instant refund",
    ["秒选"] = "instant pick",
    ["秒速"] = "speed per second",
    ["秒针"] = "second hand",
    ["秒钟"] = "seconds",
}

return M
