local M = {}

M.mapping = {
    ["率众"] = "leading the crowd",
    ["率偏高"] = "high rate",
    ["率先"] = "take the lead",
    ["率先垂范"] = "lead by example",
    ["率先实现"] = "pioneer achievement",
    ["率先实行"] = "pioneer implementation",
    ["率先宣布"] = "first to announce",
    ["率先推出"] = "pioneer launch",
    ["率兵"] = "lead troops",
    ["率兽食人"] = "tyranny",
    ["率军"] = "lead troops",
    ["率团"] = "lead group",
    ["率团参加"] = "lead delegation",
    ["率土之滨"] = "all under heaven",
    ["率妻子邑人来此绝境"] = "led family to seclusion",
    ["率尔"] = "rashly",
    ["率差"] = "rate difference",
    ["率师"] = "lead troops",
    ["率常"] = "usually",
    ["率很高"] = "high rate",
    ["率性"] = "follow nature",
    ["率性任意"] = "act on whim",
    ["率最高"] = "highest rate",
    ["率然"] = "rashly",
    ["率由旧章"] = "follow old rules",
    ["率直"] = "straightforward",
    ["率真"] = "frank",
    ["率谷"] = "hexagram lv",
    ["率达到"] = "reach a rate",
    ["率部"] = "lead unit",
    ["率队"] = "lead team",
    ["率领"] = "lead",
    ["率领着"] = "leading",
    ["率领部"] = "leading department",
}

return M
