local M = {}

M.mapping = {
    ["狭义"] = "narrow sense",
    ["狭义相对论"] = "special relativity",
    ["狭促"] = "narrow",
    ["狭口"] = "narrow opening",
    ["狭口蛙"] = "narrow-mouthed frog",
    ["狭叶牡丹"] = "narrow-leaved peony",
    ["狭叶红景天"] = "narrow-leaved rhodiola",
    ["狭叶青蒿"] = "narrow-leaved wormwood",
    ["狭小"] = "narrow",
    ["狭小片菊花珊瑚"] = "stenosoma coral",
    ["狭小菲策吸虫"] = "stenosoma fischeri",
    ["狭小露齿螺"] = "stenosoma snail",
    ["狭尾糯鳗"] = "xiaweieel",
    ["狭心症"] = "angina",
    ["狭窄"] = "narrow",
    ["狭窄圆螺"] = "narrow round snail",
    ["狭窄的"] = "narrow",
    ["狭缝"] = "slit",
    ["狭翅鹿子蛾"] = "narrow-winged deer moth",
    ["狭翅黄星弄蝶"] = "narrow-winged yellow star butterfly",
    ["狭膜无齿角蝉"] = "membracid",
    ["狭航道"] = "narrow channel",
    ["狭跗地种蝇"] = "seed maggot",
    ["狭路"] = "narrow path",
    ["狭路相逢"] = "confrontation",
    ["狭路相逢勇者胜"] = "fortune favors the bold",
    ["狭路相遇"] = "narrow encounter",
    ["狭长"] = "narrow and long",
    ["狭长地带"] = "narrow strip",
    ["狭长木盲蝽"] = "narrow wood bug",
    ["狭隘"] = "narrow",
    ["狭隘性"] = "narrowness",
    ["狭颅症"] = "craniosynostosis",
    ["狭颅鼠兔"] = "narrow-skulled pika",
    ["狭颧棘蝇"] = "narrow-faced stable fly",
    ["狭鳞庸鲽"] = "narrow flounder",
    ["狭黄缘青步甲"] = "carabus hummelii",
}

return M
