local M = {}

M.mapping = {
    ["牢不可拔"] = "firmly rooted",
    ["牢不可破"] = "impregnable",
    ["牢中"] = "in prison",
    ["牢什古子"] = "antique",
    ["牢厂"] = "prison factory",
    ["牢固"] = "firm",
    ["牢固度"] = "firmness",
    ["牢固树立"] = "firmly establish",
    ["牢固的"] = "solid",
    ["牢固确立"] = "firmly establish",
    ["牢头"] = "jailer",
    ["牢头狱霸"] = "jail tyrant",
    ["牢实"] = "solid",
    ["牢底"] = "prison bottom",
    ["牢度"] = "fastness",
    ["牢房"] = "prison cell",
    ["牢牢"] = "firmly",
    ["牢牢把握"] = "firm grasp",
    ["牢牢抓住"] = "grip tightly",
    ["牢牢掌握"] = "master firmly",
    ["牢牢控制"] = "tight control",
    ["牢狱"] = "prison",
    ["牢狱之灾"] = "prison disaster",
    ["牢甲利兵"] = "well-armed troops",
    ["牢稳"] = "firm",
    ["牢笼"] = "cage",
    ["牢落陆离"] = "desolate and varied",
    ["牢记"] = "keep in mind",
    ["牢记于心"] = "engraved in mind",
    ["牢记初心"] = "remember the original aspiration",
    ["牢记初心使命"] = "remember the mission",
    ["牢记历史"] = "remember history",
    ["牢记嘱托"] = "remember the entrustment",
    ["牢记在心"] = "keep in heart",
    ["牢记心中"] = "engraved in heart",
    ["牢里"] = "in jail",
    ["牢门"] = "lao men",
    ["牢靠"] = "reliable",
    ["牢骚"] = "complaint",
    ["牢骚太盛防肠断"] = "too much complaint harms the heart",
    ["牢骚满腹"] = "full of complaints",
    ["牢骚话"] = "complaining words",
}

return M
