local M = {}

M.mapping = {
    ["盆中"] = "in the basin",
    ["盆倾瓮倒"] = "upset and pouring",
    ["盆儿"] = "pot",
    ["盆儿胡同"] = "penr hutong",
    ["盆内"] = "inside the basin",
    ["盆友"] = "friend",
    ["盆唇华鲮"] = "labiobarbus",
    ["盆地"] = "basin",
    ["盆子"] = "basin",
    ["盆底"] = "basin bottom",
    ["盆景"] = "bonsai",
    ["盆景作品"] = "bonsai works",
    ["盆景园"] = "bonsai garden",
    ["盆景土"] = "bonsai soil",
    ["盆景场"] = "bonsai field",
    ["盆景猫"] = "bonsai cat",
    ["盆景花卉"] = "bonsai flowers",
    ["盆景配件"] = "bonsai accessories",
    ["盆朝天"] = "upside down",
    ["盆栽"] = "potted plant",
    ["盆栽植物"] = "potted plant",
    ["盆汤"] = "basin soup",
    ["盆浴"] = "bath in a tub",
    ["盆满钵满"] = "full to the brim",
    ["盆满钵盈"] = "overflowing",
    ["盆炎净片"] = "penyanjing tablet",
    ["盆炎净胶囊"] = "penyanjing capsule",
    ["盆炎净颗粒"] = "penyanjing granule",
    ["盆盆罐罐"] = "pots and pans",
    ["盆盆虾"] = "basin shrimp",
    ["盆腔"] = "pelvic",
    ["盆腔囊肿"] = "pelvic cyst",
    ["盆腔炎"] = "pelvic inflammation",
    ["盆腔脓肿"] = "pelvic abscess",
    ["盆花"] = "potted flower",
    ["盆菜"] = "potted dish",
    ["盆角齿"] = "bevel gear",
    ["盆里"] = "in the basin",
    ["盆骨"] = "pelvis",
}

return M
