local M = {}

M.mapping = {
    ["缴一缴"] = "pay a little",
    ["缴不出"] = "cannot pay",
    ["缴不起"] = "cannot afford to pay",
    ["缴付"] = "payment",
    ["缴入"] = "pay into",
    ["缴出"] = "surrender",
    ["缴回"] = "surrender",
    ["缴存"] = "deposit",
    ["缴存额"] = "deposit amount",
    ["缴库"] = "pay into treasury",
    ["缴枪"] = "surrender weapons",
    ["缴枪不杀"] = "surrender your weapons and we won't kill you",
    ["缴械"] = "disarm",
    ["缴械投降"] = "surrender and disarm",
    ["缴欠"] = "pay arrears",
    ["缴款"] = "payment",
    ["缴款书"] = "payment book",
    ["缴款凭证"] = "payment voucher",
    ["缴款单"] = "payment slip",
    ["缴款通知"] = "payment notice",
    ["缴清"] = "pay off",
    ["缴租"] = "pay rent",
    ["缴税"] = "pay tax",
    ["缴纳"] = "pay",
    ["缴纳个人所得税"] = "pay personal income tax",
    ["缴纳了"] = "paid",
    ["缴纳关税"] = "pay customs duty",
    ["缴纳罚款"] = "pay a penalty",
    ["缴纳罚金"] = "pay a fine",
    ["缴获"] = "capture",
    ["缴费"] = "payment",
    ["缴费单"] = "payment slip",
    ["缴费成功"] = "payment successful",
    ["缴费期"] = "payment period",
    ["缴费通知"] = "payment notice",
    ["缴足"] = "pay in full",
    ["缴销"] = "cancel",
    ["缴齐"] = "pay in full",
}

return M
