local M = {}

M.mapping = {
    ["粪产碱杆菌"] = "alcaligenes faecalis",
    ["粪便"] = "feces",
    ["粪便检查"] = "fecal examination",
    ["粪凼"] = "manure pit",
    ["粪卟啉"] = "coproporphyrin",
    ["粪卟啉原"] = "coproporphyrinogen",
    ["粪厂"] = "manure factory",
    ["粪口途径"] = "fecal-oral route",
    ["粪固醇"] = "coprostanol",
    ["粪土"] = "dung",
    ["粪土不如"] = "worse than dung",
    ["粪土之墙"] = "wall of dung",
    ["粪土当年万户侯"] = "dung to the marquises",
    ["粪土当年万户候"] = "dung to the marquises",
    ["粪场"] = "manure yard",
    ["粪坑"] = "cesspit",
    ["粪堆"] = "dung heap",
    ["粪尿"] = "excrement and urine",
    ["粪桶"] = "manure bucket",
    ["粪水"] = "sewage",
    ["粪池"] = "manure pit",
    ["粪污"] = "manure",
    ["粪球"] = "dung ball",
    ["粪球儿"] = "dung ball",
    ["粪瘘"] = "fecal fistula",
    ["粪石"] = "bezoar",
    ["粪筐"] = "manure basket",
    ["粪箕子"] = "dung basket",
    ["粪耙"] = "dung rake",
    ["粪耙子"] = "manure fork",
    ["粪肥"] = "manure",
    ["粪胆素"] = "stercobilin",
    ["粪胆素原"] = "stercobilinogen",
    ["粪臭素"] = "skatole",
    ["粪车"] = "manure cart",
}

return M
