local M = {}

M.mapping = {
    ["糟丘是蓬莱"] = "paradise",
    ["糟了"] = "damn it",
    ["糟坊"] = "brewery",
    ["糟坊巷"] = "brewery lane",
    ["糟害"] = "damaged",
    ["糟得很"] = "terrible",
    ["糟心"] = "annoying",
    ["糟改"] = "ruin",
    ["糟毛豆"] = "pickled edamame",
    ["糟油口条"] = "pickled pork tongue",
    ["糟烩鞭笋"] = "braised bamboo shoots",
    ["糟煨冬笋"] = "braised bamboo shoots",
    ["糟熘"] = "stewed in rice wine",
    ["糟熘鱼片"] = "stewed fish slices",
    ["糟田螺"] = "spoiled field snail",
    ["糟粕"] = "dross",
    ["糟粕所传非粹美"] = "impure",
    ["糟糕"] = "terrible",
    ["糟糕了"] = "awful",
    ["糟糕透了"] = "horrible",
    ["糟糕透顶"] = "disastrous",
    ["糟糠"] = "husks",
    ["糟糠不厌"] = "never tire of husks",
    ["糟糠之妻"] = "wife of husks",
    ["糟糠之妻不下堂"] = "never abandon wife of husks",
    ["糟老头"] = "old codger",
    ["糟肉"] = "preserved meat",
    ["糟豆腐"] = "fermented tofu",
    ["糟践"] = "waste",
    ["糟蹋"] = "waste",
    ["糟蹋东西"] = "waste things",
    ["糟蹋了"] = "wasted",
    ["糟辣脆皮鱼"] = "crispy fish with chili",
    ["糟透"] = "terrible",
    ["糟透了"] = "absolutely terrible",
    ["糟鱼"] = "pickled fish",
    ["糟鸡糟肉"] = "pickled chicken and meat",
    ["糟鸭"] = "preserved duck",
}

return M
