local M = {}

M.mapping = {
    ["窑主"] = "kiln owner",
    ["窑内"] = "inside kiln",
    ["窑前村"] = "yaoqian village",
    ["窑厂"] = "kiln factory",
    ["窑变"] = "kiln transformation",
    ["窑口"] = "kiln mouth",
    ["窑场村"] = "yaochang village",
    ["窑坑"] = "kiln pit",
    ["窑坡"] = "yaopo",
    ["窑坡山"] = "yaopo mountain",
    ["窑坪乡"] = "yaoping township",
    ["窑埠古镇"] = "yaobu ancient town",
    ["窑头乡"] = "yaotou township",
    ["窑头村"] = "yaotou village",
    ["窑姐"] = "prostitute",
    ["窑姐儿"] = "courtesan",
    ["窑子"] = "brothel",
    ["窑子头乡"] = "yaozitou township",
    ["窑山花园"] = "yaoshan garden",
    ["窑岭"] = "yaoling",
    ["窑工"] = "kiln worker",
    ["窑洞"] = "cave dwelling",
    ["窑洼湖桥"] = "yaowa lake bridge",
    ["窑洼湖桥东"] = "yaowa lake bridge east",
    ["窑湾"] = "yaowan",
    ["窑湾街道"] = "yaowan street",
    ["窑滩间吸鳅"] = "cave loach",
    ["窑火"] = "kiln fire",
    ["窑灰"] = "kiln dust",
    ["窑炉"] = "kiln",
    ["窑里"] = "in kiln",
    ["窑里村"] = "yaoli village",
    ["窑门"] = "kiln door",
    ["窑院村"] = "yao yuan village",
    ["窑顶"] = "kiln roof",
}

return M
