local M = {}

M.mapping = {
    ["矫世励俗"] = "reform society and encourage customs",
    ["矫世厉俗"] = "reform society and strict customs",
    ["矫世变俗"] = "reform society and change customs",
    ["矫健"] = "vigorous",
    ["矫健敏捷"] = "vigorous and agile",
    ["矫制矫诏"] = "forged decree",
    ["矫命"] = "counterfeit order",
    ["矫国更俗"] = "rectify state and change customs",
    ["矫国革俗"] = "rectify state and reform customs",
    ["矫尾厉角"] = "arrogant and aggressive",
    ["矫形"] = "orthopedics",
    ["矫形器"] = "orthosis",
    ["矫形器师"] = "orthotist",
    ["矫形外科"] = "orthopedic surgery",
    ["矫形外科手术器械"] = "orthopedic surgical instruments",
    ["矫形鞋"] = "orthopedic shoes",
    ["矫形骨科"] = "orthopedic surgery",
    ["矫形骨科手术器械"] = "orthopedic surgical instruments",
    ["矫情"] = "pretentious",
    ["矫捷"] = "agile",
    ["矫揉造作"] = "affected and artificial",
    ["矫时慢物"] = "arrogant and aloof",
    ["矫枉过中"] = "moderate correction",
    ["矫枉过当"] = "overcorrection",
    ["矫枉过正"] = "overcorrection",
    ["矫正"] = "correct",
    ["矫正器"] = "orthosis",
    ["矫正方法"] = "correction method",
    ["矫正术"] = "orthodontics",
    ["矫正机"] = "straightening machine",
    ["矫正社会工作"] = "correctional social work",
    ["矫正运动"] = "corrective exercise",
    ["矫治"] = "correction",
    ["矫治器"] = "orthodontic appliance",
    ["矫治心理学"] = "correctional psychology",
    ["矫激奇诡"] = "eccentric and strange",
    ["矫菌桂以纫蕙兮"] = "string orchids with cinnamon",
    ["矫言伪行"] = "hypocritical words and deeds",
    ["矫诏"] = "forged edict",
    ["矫饰"] = "affectation",
    ["矫饰伪行"] = "affectation and hypocrisy",
}

return M
