local M = {}

M.mapping = {
    ["纱丽"] = "sari",
    ["纱丽服"] = "sari dress",
    ["纱仓真菜"] = "sakura mana",
    ["纱似的"] = "gauzy",
    ["纱厂"] = "cotton mill",
    ["纱厂路"] = "cotton mill road",
    ["纱围巾"] = "scarf",
    ["纱场"] = "yarn field",
    ["纱奈"] = "sana",
    ["纱巾"] = "scarf",
    ["纱巾草履竹疏衣"] = "scarf straw sandals bamboo robe",
    ["纱布"] = "gauze",
    ["纱布剥离钳"] = "gauze stripping forceps",
    ["纱布条"] = "gauze strip",
    ["纱布绷带剪"] = "gauze bandage scissors",
    ["纱帐"] = "mosquito net",
    ["纱帽"] = "gauze cap",
    ["纱帽北街"] = "shamao north street",
    ["纱帽村"] = "shamao village",
    ["纱帽笼头"] = "gauze cap and bridle",
    ["纱帽街"] = "shamao street",
    ["纱幕"] = "gauze curtain",
    ["纱橱"] = "screen cupboard",
    ["纱灯"] = "gauze lantern",
    ["纱窗"] = "window screen",
    ["纱窗几度春光暮"] = "spring dusk through screen",
    ["纱窗醉梦中"] = "drunken dream by screen",
    ["纱笼"] = "sarong",
    ["纱筒"] = "yarn tube",
    ["纱纱原百合"] = "yuri sashihara",
    ["纱线"] = "yarn",
    ["纱织"] = "saori",
    ["纱罗"] = "gauze",
    ["纱罩"] = "gauze cover",
    ["纱衣"] = "gauze clothes",
    ["纱袍"] = "gauze robe",
    ["纱裙"] = "tulle skirt",
    ["纱锭"] = "spindle",
    ["纱门"] = "screen door",
}

return M
