local M = {}

M.mapping = {
    ["竖中指"] = "flip the bird",
    ["竖井"] = "shaft",
    ["竖列"] = "vertical column",
    ["竖向"] = "fox under tree",
    ["竖在"] = "erected",
    ["竖子"] = "fool",
    ["竖子不足与谋"] = "fools are not worth consulting",
    ["竖子成名"] = "a fool gains fame",
    ["竖屏"] = "portrait screen",
    ["竖弯钩"] = "hook stroke",
    ["竖弯钩儿"] = "hook stroke",
    ["竖得比"] = "stand taller than",
    ["竖心"] = "vertical heart",
    ["竖心旁"] = "vertical heart radical",
    ["竖排"] = "vertical layout",
    ["竖放"] = "vertical placement",
    ["竖条"] = "verticalstripes",
    ["竖构图"] = "portrait orientation",
    ["竖沟"] = "vertical groove",
    ["竖版"] = "portrait",
    ["竖琴"] = "harp",
    ["竖琴骨螺"] = "harp shell",
    ["竖直"] = "vertical",
    ["竖眉瞪眼"] = "glare angrily",
    ["竖着"] = "standing",
    ["竖着呢"] = "vertical",
    ["竖窑"] = "shaft kiln",
    ["竖立"] = "erect",
    ["竖立着"] = "erect",
    ["竖立起来"] = "erect",
    ["竖笛"] = "recorder",
    ["竖管"] = "standpipe",
    ["竖纹"] = "vertical lines",
    ["竖线"] = "rat-tail fish family",
    ["竖蜻蜓"] = "handstand",
    ["竖行"] = "vertical line",
    ["竖起"] = "erect",
    ["竖起了"] = "stood up",
    ["竖起来"] = "stand up",
}

return M
