local M = {}

M.mapping = {
    ["罢了"] = "enough",
    ["罢休"] = "give up",
    ["罢免"] = "impeach",
    ["罢免权"] = "right of recall",
    ["罢免案"] = "impeachment case",
    ["罢兵"] = "cease hostilities",
    ["罢园"] = "garden closure",
    ["罢如江海凝清光"] = "stop like the sea congealing clear light",
    ["罢官"] = "dismissal from office",
    ["罢官亦由人"] = "dismissal also depends on people",
    ["罢宴"] = "banquet boycott",
    ["罢工"] = "strike",
    ["罢工权"] = "right to strike",
    ["罢工者"] = "striker",
    ["罢市"] = "market strike",
    ["罢战"] = "cease war",
    ["罢手"] = "stop",
    ["罢教"] = "teaching strike",
    ["罢斥"] = "dismiss",
    ["罢朝"] = "dismiss court",
    ["罢极之本"] = "source of physical strength",
    ["罢演"] = "performance boycott",
    ["罢笔"] = "stop writing",
    ["罢练"] = "boycott training",
    ["罢考"] = "boycott exams",
    ["罢职"] = "dismissal",
    ["罢训"] = "training boycott",
    ["罢论"] = "abandoned discussion",
    ["罢讼"] = "stop lawsuit",
    ["罢诉"] = "drop lawsuit",
    ["罢课"] = "boycott classes",
    ["罢赛"] = "boycott",
    ["罢黜"] = "dismiss",
    ["罢黜百家"] = "dismiss hundred schools",
}

return M
