local M = {}

M.mapping = {
    ["禅世雕龙"] = "chan shi diao long",
    ["禅位"] = "abdicate",
    ["禅修"] = "zen practice",
    ["禅僧"] = "zen monk",
    ["禅功"] = "zen skill",
    ["禅味"] = "zen flavor",
    ["禅城"] = "chancheng",
    ["禅城区政府"] = "chancheng district government",
    ["禅堂"] = "zen hall",
    ["禅境"] = "zen state",
    ["禅学"] = "zen studies",
    ["禅宗"] = "zen buddhism",
    ["禅定"] = "zen meditation",
    ["禅家"] = "zen family",
    ["禅寺"] = "zen temple",
    ["禅师"] = "zen master",
    ["禅心"] = "zen mind",
    ["禅思"] = "zen meditation",
    ["禅悟"] = "zen enlightenment",
    ["禅意"] = "zen meaning",
    ["禅房"] = "zen room",
    ["禅房花木深"] = "deep flowers and trees in zen room",
    ["禅机"] = "zen opportunity",
    ["禅杖"] = "monk's staff",
    ["禅林"] = "zen forest",
    ["禅理"] = "zen principle",
    ["禅絮沾泥"] = "zen floss沾泥",
    ["禅让"] = "abdicate",
    ["禅语"] = "zen saying",
    ["禅趣"] = "zen interest",
    ["禅道上"] = "on zentao",
    ["禅道编号"] = "zentao number",
    ["禅门"] = "zen gate",
    ["禅院"] = "zen temple",
}

return M
