local M = {}

M.mapping = {
    ["绒促性素"] = "fault tolerance",
    ["绒叶肖竹芋"] = "calathea zebrina",
    ["绒尾象鼻虫"] = "fuzzy weevil",
    ["绒山羊"] = "cashmere goat",
    ["绒布"] = "flannel",
    ["绒庄新村"] = "rongzhuang new village",
    ["绒毛"] = "fuzz",
    ["绒毛仿银杏蟹"] = "ginkgo velvet crab",
    ["绒毛弄蝶"] = "velvet skipper",
    ["绒毛状"] = "villous",
    ["绒毛状腺瘤"] = "villous adenoma",
    ["绒毛玩具"] = "plush toy",
    ["绒毛的"] = "fuzzy",
    ["绒毛膜"] = "chorion",
    ["绒毛膜上皮癌"] = "chorioepithelioma",
    ["绒毛膜促性腺激素"] = "hcg",
    ["绒毛膜癌"] = "choriocarcinoma",
    ["绒毡层"] = "tapetum",
    ["绒毯"] = "blanket",
    ["绒球花"] = "pompon flower",
    ["绒盖"] = "velvet cap",
    ["绒盖乡"] = "ronggai township",
    ["绒纹线鳞鲀"] = "fuzzy filefish",
    ["绒线"] = "yarn",
    ["绒线刺绣"] = "yarn embroidery",
    ["绒线胡同"] = "yarn hutong",
    ["绒线衣"] = "sweater",
    ["绒绣"] = "wool embroidery",
    ["绒羽"] = "down feather",
    ["绒花"] = "velvet flower",
    ["绒衣"] = "sweater",
    ["绒裤"] = "sweatpants",
    ["绒辖乡"] = "rongxia township",
    ["绒面"] = "suede",
    ["绒鸡待哺"] = "hungry chicks",
}

return M
