local M = {}

M.mapping = {
    ["绞丝"] = "silk thread",
    ["绞丝儿"] = "silk radical",
    ["绞丝儿旁"] = "silk radical side",
    ["绞丝底"] = "silk base",
    ["绞丝旁"] = "silk radical",
    ["绞切蜂"] = "cutting bee",
    ["绞刑"] = "hanging",
    ["绞刑台"] = "scaffold",
    ["绞刑场"] = "gallows",
    ["绞刑架"] = "gallows",
    ["绞刑架下的报告"] = "report from under the gallows",
    ["绞合线"] = "stranded wire",
    ["绞孔胃螺"] = "gastroptychia sinensis",
    ["绞尽"] = "exhaust",
    ["绞尽脑汁"] = "rack one's brains",
    ["绞成"] = "twist into",
    ["绞断"] = "sever",
    ["绞杀"] = "strangulation",
    ["绞架"] = "gallows",
    ["绞死"] = "hang",
    ["绞烂"] = "mash",
    ["绞痛"] = "colic",
    ["绞盘"] = "winch",
    ["绞盘机"] = "winch machine",
    ["绞碎"] = "mince",
    ["绞窄性肠梗阻"] = "strangulated intestinal obstruction",
    ["绞索"] = "noose",
    ["绞紧"] = "tighten",
    ["绞纱"] = "yarn",
    ["绞线"] = "stranded wire",
    ["绞缠"] = "entangle",
    ["绞肉"] = "minced meat",
    ["绞肉机"] = "meat grinder",
    ["绞股蓝"] = "gynostemma pentaphyllum",
    ["绞股蓝总苷片"] = "gynostemma pentaphyllum total glycosides tablet",
    ["绞脑汁"] = "rack one's brains",
    ["绞脸"] = "face threading",
    ["绞起"] = "hoist",
    ["绞车"] = "winch",
    ["绞馅机"] = "meat grinder",
}

return M
