local M = {}

M.mapping = {
    ["炭儿胡同"] = "tan'er hutong",
    ["炭包"] = "charcoal bag",
    ["炭化"] = "char",
    ["炭厂村"] = "tancang village",
    ["炭墼"] = "charcoal briquette",
    ["炭子冲"] = "tanzichong",
    ["炭市街"] = "coal market street",
    ["炭库乡"] = "tanku township",
    ["炭棒"] = "carbon rod",
    ["炭渣"] = "charcoal residue",
    ["炭火"] = "charcoal fire",
    ["炭火盆"] = "brazier",
    ["炭灰色"] = "charcoal gray",
    ["炭炉"] = "charcoal stove",
    ["炭烧"] = "charcoal grilled",
    ["炭烧咖啡"] = "charcoal coffee",
    ["炭烧啤酒"] = "charcoal beer",
    ["炭烧鱼串"] = "grilled fish skewers",
    ["炭烧鱼段"] = "grilled fish fillet",
    ["炭画"] = "charcoal drawing",
    ["炭疽"] = "anthrax",
    ["炭疽杆菌"] = "bacillus anthracis",
    ["炭疽活疫苗"] = "anthrax vaccine",
    ["炭疽热"] = "anthrax",
    ["炭疽病"] = "anthrax",
    ["炭疽病毒"] = "anthrax virus",
    ["炭疽菌"] = "anthrax bacteria",
    ["炭的同素异形体"] = "carbon allotropes",
    ["炭的结构"] = "carbon structure",
    ["炭盆"] = "charcoal brazier",
    ["炭窑"] = "charcoal kiln",
    ["炭窑渠"] = "charcoal kiln ditch",
    ["炭笔"] = "charcoal pencil",
    ["炭精"] = "carbon black",
    ["炭精棒"] = "carbon rod",
    ["炭菌热"] = "anthrax fever",
    ["炭蛆病"] = "anthrax",
    ["炭黑"] = "carbon black",
    ["炭黑突肩花天牛"] = "carbon black beetle",
}

return M
