local M = {}

M.mapping = {
    ["缅北"] = "northern myanmar",
    ["缅北原矛头蝮"] = "protobothrops kelomohy",
    ["缅北短腿蟾"] = "burmese short-legged toad",
    ["缅因"] = "maine",
    ["缅因州"] = "maine state",
    ["缅怀"] = "cherish memory",
    ["缅怀先辈"] = "remember ancestors",
    ["缅怀往事"] = "reminisce",
    ["缅怀英烈"] = "remember heroes",
    ["缅怀革命"] = "commemorate revolution",
    ["缅怀革命先烈"] = "honor revolutionary martyrs",
    ["缅思"] = "remembrance",
    ["缅想"] = "reminisce",
    ["缅甸"] = "myanmar",
    ["缅甸人"] = "burmese",
    ["缅甸公司法"] = "myanmar companies act",
    ["缅甸刀腹茧蜂"] = "braconid wasp",
    ["缅甸副双边鱼"] = "ambassid fish",
    ["缅甸北"] = "northern myanmar",
    ["缅甸环宇海龙"] = "ringed pipefish",
    ["缅甸玻璃鱼"] = "glassfish",
    ["缅甸联邦"] = "union of myanmar",
    ["缅甸联邦共和国"] = "republic of the union of myanmar",
    ["缅甸腹囊海龙"] = "pipefish",
    ["缅甸莽"] = "burmese python",
    ["缅甸蜜蜂猫"] = "burmese bee cat",
    ["缅甸语"] = "burmese language",
    ["缅甸贝"] = "burmese shell",
    ["缅甸贝属"] = "burmesia",
    ["缅甸长背魮"] = "longback barb",
    ["缅甸队"] = "myanmar team",
    ["缅钢刀"] = "myanmar steel knife",
    ["缅陆"] = "burmese tortoise",
}

return M
