local M = {}

M.mapping = {
    ["畏之如虎"] = "fear like a tiger",
    ["畏光"] = "photophobia",
    ["畏冷"] = "fear cold",
    ["畏友"] = "respected friend",
    ["畏圣人之言"] = "fear the words of the sages",
    ["畏天者保其国"] = "those who fear heaven protect their country",
    ["畏寒"] = "chills",
    ["畏忌"] = "fear and avoid",
    ["畏怯"] = "timidity",
    ["畏怯不前"] = "hesitate",
    ["畏惧"] = "fear",
    ["畏惧感"] = "fear",
    ["畏惧的"] = "fearful",
    ["畏敌如虎"] = "fear enemies like tigers",
    ["畏新园蛛"] = "neoscona adianta",
    ["畏日"] = "fear sun",
    ["畏服"] = "awe",
    ["畏死"] = "fear death",
    ["畏畏缩缩"] = "timid",
    ["畏缩"] = "shrink",
    ["畏缩不前"] = "hesitate",
    ["畏缩的"] = "timid",
    ["畏罪"] = "fear of punishment",
    ["畏罪潜逃"] = "abscond to avoid punishment",
    ["畏罪自杀"] = "suicide to escape punishment",
    ["畏老偏惊节"] = "fear aging",
    ["畏葸"] = "timid",
    ["畏葸不前"] = "too timid to advance",
    ["畏途"] = "dangerous road",
    ["畏途巉岩不可攀"] = "dangerous cliffs unclimbable",
    ["畏避"] = "avoid",
    ["畏难"] = "daunted",
    ["畏难情绪"] = "fear of difficulty",
    ["畏首畏尾"] = "timid",
}

return M
