local M = {}

M.mapping = {
    ["瓷业"] = "porcelain industry",
    ["瓷像"] = "porcelain portrait",
    ["瓷公鸡"] = "porcelain rooster",
    ["瓷具"] = "porcelain ware",
    ["瓷博会"] = "this part",
    ["瓷厂"] = "porcelain factory",
    ["瓷器"] = "porcelain",
    ["瓷器厂"] = "porcelain factory",
    ["瓷器活"] = "porcelain work",
    ["瓷土"] = "kaolin",
    ["瓷壶"] = "porcelain pot",
    ["瓷套"] = "porcelain sleeve",
    ["瓷娃娃"] = "porcelain doll",
    ["瓷实"] = "solid",
    ["瓷杯"] = "porcelain cup",
    ["瓷板"] = "porcelain plate",
    ["瓷漆"] = "enamel",
    ["瓷片"] = "porcelain shard",
    ["瓷牙"] = "porcelain tooth",
    ["瓷瓶"] = "porcelain vase",
    ["瓷的"] = "porcelain",
    ["瓷盆"] = "porcelain basin",
    ["瓷盘"] = "porcelain plate",
    ["瓷砖"] = "ceramic tile",
    ["瓷碗"] = "porcelain bowl",
    ["瓷碟"] = "porcelain dish",
    ["瓷窑"] = "porcelain kiln",
    ["瓷粉"] = "porcelain powder",
    ["瓷缸"] = "porcelain vat",
    ["瓷罐"] = "porcelain jar",
    ["瓷胎"] = "porcelain body",
    ["瓷花瓶"] = "porcelain vase",
    ["瓷贴面"] = "porcelain veneer",
    ["瓷都"] = "porcelain capital",
    ["瓷釉"] = "porcelain glaze",
    ["瓷雕"] = "porcelain carving",
}

return M
