local M = {}

M.mapping = {
    ["祁东县"] = "qidong county",
    ["祁剧"] = "qi opera",
    ["祁县"] = "qi county",
    ["祁坤"] = "qi kun",
    ["祁奚举午"] = "qi xi recommends wu",
    ["祁奚举子"] = "qi xi recommends son",
    ["祁奚之举"] = "qi xi's recommendation",
    ["祁姓"] = "qi surname",
    ["祁安路"] = "qi'an road",
    ["祁家坟"] = "qijiafen",
    ["祁家堡"] = "qijiapu",
    ["祁家湾"] = "qijiawan",
    ["祁家豁子"] = "qijiahuozi",
    ["祁家集镇"] = "qijiaji town",
    ["祁寒"] = "severe cold",
    ["祁山"] = "qi mountain",
    ["祁彪佳"] = "qi biaojia",
    ["祁曼"] = "qiman",
    ["祁溪之举"] = "qi xi's recommendation",
    ["祁王"] = "prince qi",
    ["祁王府"] = "qiwang mansion",
    ["祁禄山镇"] = "qilu mountain town",
    ["祁红"] = "keemun",
    ["祁红茶"] = "keemun tea",
    ["祁致中"] = "qi zhizhong",
    ["祁连"] = "qilian",
    ["祁连县"] = "qilian county",
    ["祁连山"] = "qilian mountain",
    ["祁连山脉"] = "qilian mountain range",
    ["祁连山路"] = "qilian mountain road",
    ["祁连新村"] = "qilian new village",
    ["祁连路"] = "qilian road",
    ["祁连镇"] = "qilian town",
    ["祁门"] = "qimen",
    ["祁门县"] = "qimen county",
    ["祁阳"] = "qiyang",
    ["祁阳县"] = "qiyang county",
    ["祁顺"] = "qi shun",
}

return M
