local M = {}

M.mapping = {
    ["焚书"] = "book burning",
    ["焚书坑儒"] = "burning books and burying scholars",
    ["焚化"] = "incineration",
    ["焚化炉"] = "incinerator",
    ["焚化者"] = "incinerator",
    ["焚如之祸"] = "fire disaster",
    ["焚尸"] = "cremate",
    ["焚尸灭迹"] = "destroy evidence",
    ["焚尸炉"] = "crematorium",
    ["焚巢捣穴"] = "burn nest and destroy den",
    ["焚巢荡穴"] = "burn nest and destroy den",
    ["焚心"] = "burning heart",
    ["焚掠"] = "burning looting",
    ["焚文书而酷刑法"] = "burn books and enforce harsh laws",
    ["焚木村"] = "burnwood village",
    ["焚林之求"] = "demand burning forests",
    ["焚林竭泽"] = "burn forests drain ponds",
    ["焚林而狩"] = "burn forests hunting",
    ["焚林而猎"] = "burn forests for hunting",
    ["焚林而畋"] = "burn forests farming",
    ["焚枯食淡"] = "live frugally",
    ["焚毁"] = "burning down",
    ["焚烧"] = "incineration",
    ["焚烧厂"] = "incineration plant",
    ["焚烧场"] = "incineration site",
    ["焚烧炉"] = "incinerator",
    ["焚琴煮鹤"] = "burn zither for fuel",
    ["焚琴鬻鹤"] = "burn zither for fuel",
    ["焚符破玺"] = "burning talismans and breaking seals",
    ["焚膏继晷"] = "burning the midnight oil",
    ["焚舟破釜"] = "burn boats and break cauldrons",
    ["焚芝锄蕙"] = "burn orchids and hoe fragrant herbs",
    ["焚薮而田"] = "burn fields",
    ["焚身"] = "self-immolation",
    ["焚风"] = "foehn",
    ["焚香"] = "burn incense",
    ["焚香入宴"] = "burn incense for banquet",
    ["焚香列鼎"] = "burn incense and set up tripods",
    ["焚香引幽步"] = "burn incense and walk quietly",
    ["焚香扫地"] = "burn incense and sweep floor",
    ["焚香顶礼"] = "burn incense and bow",
}

return M
