local M = {}

M.mapping = {
    ["箭伤"] = "arrow wound",
    ["箭厂"] = "arrow factory",
    ["箭厂胡同"] = "arrow factory hutong",
    ["箭口"] = "arrow notch",
    ["箭在弦上"] = "arrow on the bowstring",
    ["箭在弦上不得不发"] = "arrow on the bowstring must be shot",
    ["箭垛"] = "arrow crenel",
    ["箭垛子"] = "arrow crenel",
    ["箭头"] = "arrow",
    ["箭头键"] = "arrow keys",
    ["箭小鰕虎鱼"] = "gobiusculus flavescens",
    ["箭尾"] = "arrow tail",
    ["箭弓山"] = "jiangong mountain",
    ["箭形角杯水母"] = "ceratocorys horrida",
    ["箭形长颌鱼"] = "mormyrops anguilloides",
    ["箭手"] = "archer",
    ["箭扣长城"] = "jiankou great wall",
    ["箭擦"] = "arrow scrape",
    ["箭无空发"] = "no arrow misses its target",
    ["箭无虚发"] = "every shot tells",
    ["箭术"] = "archery",
    ["箭杆"] = "arrow shaft",
    ["箭杆胡同"] = "arrow shaft hutong",
    ["箭根薯"] = "tacca chantrieri",
    ["箭楼"] = "arrow tower",
    ["箭步"] = "lunge",
    ["箭毛"] = "arrow hair",
    ["箭牌"] = "arrow brand",
    ["箭牌洁具"] = "arrow brand sanitary ware",
    ["箭的射程"] = "arrow range",
    ["箭矢"] = "arrow",
    ["箭穿雁嘴"] = "arrow piercing goose beak",
    ["箭竹"] = "arrow bamboo",
    ["箭箭"] = "arrow",
    ["箭箭中的"] = "every arrow hits the target",
    ["箭镞"] = "arrowhead",
    ["箭雨"] = "arrow rain",
    ["箭靶"] = "target",
    ["箭靶中心"] = "bullseye",
    ["箭靶子"] = "target",
    ["箭鱼"] = "swordfish",
}

return M
