local M = {}

M.mapping = {
    ["琥乙红霉素"] = "erythromycin ethylsuccinate",
    ["琥乙红霉素片"] = "erythromycin ethylsuccinate tablets",
    ["琥乙红霉素胶囊"] = "erythromycin ethylsuccinate capsules",
    ["琥牢山"] = "hulao mountain",
    ["琥珀"] = "amber",
    ["琥珀体"] = "amber body",
    ["琥珀屋"] = "amber room",
    ["琥珀川"] = "amber river",
    ["琥珀戒指"] = "amber ring",
    ["琥珀抑制"] = "amber suppression",
    ["琥珀护腕"] = "amber bracers",
    ["琥珀拾芥"] = "amber attracts mustard",
    ["琥珀树"] = "amber tree",
    ["琥珀桃仁"] = "amber walnuts",
    ["琥珀氯霉素"] = "chloramphenicol succinate",
    ["琥珀石"] = "amber stone",
    ["琥珀突变"] = "amber mutation",
    ["琥珀胆碱"] = "succinylcholine",
    ["琥珀腰带"] = "amber belt",
    ["琥珀色"] = "amber color",
    ["琥珀还睛丸"] = "hupo huanjing pill",
    ["琥珀酰明胶"] = "succinylated gelatin",
    ["琥珀酰明胶注射液"] = "succinylated gelatin injection",
    ["琥珀酸"] = "succinic acid",
    ["琥珀酸二钠"] = "disodium succinate",
    ["琥珀酸亚铁"] = "ferrous succinate",
    ["琥珀酸氧化酶"] = "succinate oxidase",
    ["琥珀酸海螺"] = "succinic acid conch",
    ["琥珀酸美托洛尔"] = "metoprolol succinate",
    ["琥珀酸美托洛尔缓释片"] = "metoprolol succinate sustained-release tablets",
    ["琥珀项链"] = "amber necklace",
    ["琥珀风暴"] = "amber storm",
    ["琥珀鸽蛋"] = "amber pigeon egg",
}

return M
