local M = {}

M.mapping = {
    ["瑶井玉绳相对晓"] = "jade rope opposite dawn",
    ["瑶台"] = "jade terrace",
    ["瑶台有路"] = "path to jade terrace",
    ["瑶台村"] = "yaotai village",
    ["瑶台玉露"] = "jade dew",
    ["瑶坞村"] = "yaowu village",
    ["瑶坪"] = "yaoping",
    ["瑶姬"] = "fairy",
    ["瑶家"] = "yao family",
    ["瑶山"] = "yaoshan",
    ["瑶山瑶族乡"] = "yaoshan township",
    ["瑶峰镇"] = "yao feng town",
    ["瑶族"] = "yao ethnicity",
    ["瑶族粑粑"] = "yao rice cake",
    ["瑶族风情园"] = "yao customs park",
    ["瑶林玉树"] = "jade trees",
    ["瑶林琼树"] = "jade trees",
    ["瑶民"] = "yao people",
    ["瑶池"] = "jade pool",
    ["瑶池天将"] = "jade pool general",
    ["瑶池女使"] = "jade pool envoy",
    ["瑶池春"] = "yaochi spring",
    ["瑶池贯月"] = "jade pool moon",
    ["瑶海"] = "yaohai",
    ["瑶海区"] = "yaohai district",
    ["瑶海区工业园"] = "yaohai district industrial park",
    ["瑶淼"] = "yao miao",
    ["瑶溪"] = "yao xi",
    ["瑶环路"] = "yao huan road",
    ["瑶琳仙境"] = "yaolin fairyland",
    ["瑶琳路"] = "yaolin road",
    ["瑶琴"] = "guzheng",
    ["瑶琼村"] = "yaoqiong village",
    ["瑶瑶"] = "yaoyao",
    ["瑶草"] = "magic herb",
    ["瑶草琪花"] = "exotic flowers",
    ["瑶草琪葩"] = "rare herbs",
    ["瑶螈"] = "salamander",
    ["瑶麓瑶族乡"] = "yaolu yao township",
}

return M
