local M = {}

M.mapping = {
    ["罐中"] = "in the jar",
    ["罐体"] = "tank body",
    ["罐儿肉"] = "jar meat",
    ["罐儿胡同"] = "jar hutong",
    ["罐儿蹄"] = "jar trotter",
    ["罐儿野鸡"] = "jar pheasant",
    ["罐儿鹌鹑"] = "jar quail",
    ["罐内"] = "inside the tank",
    ["罐口"] = "can opening",
    ["罐坝乡"] = "guanba township",
    ["罐头"] = "canned food",
    ["罐头厂"] = "cannery",
    ["罐头嘴镇"] = "canned mouth town",
    ["罐头梨"] = "canned pear",
    ["罐头瓶"] = "can jar",
    ["罐头盒"] = "can",
    ["罐头食品"] = "canned food",
    ["罐子"] = "jar",
    ["罐子乡"] = "guanzi township",
    ["罐子汤"] = "jar soup",
    ["罐子窑镇"] = "guanziyao town",
    ["罐焖大虾"] = "closed-door disciple",
    ["罐焖牛舌"] = "braised spring chicken in a pot",
    ["罐焖猪肉"] = "close the door to catch the thief",
    ["罐焖笋鸡"] = "close down business",
    ["罐焖里脊"] = "braised ox tongue in a pot",
    ["罐焖鱼"] = "braised pork in a pot",
    ["罐焖鱼唇"] = "closed-door doctrine",
    ["罐焖鳜鱼"] = "braised chicken in a pot",
    ["罐焖鸡"] = "braised tenderloin in a pot",
    ["罐焖鸭"] = "braised fish in a pot",
    ["罐盖"] = "jar lid",
    ["罐笼"] = "guanlong village",
    ["罐罐"] = "jar",
    ["罐罐茶"] = "jar tea",
    ["罐罐蒸馍"] = "jar steamed bun",
    ["罐罐豆花"] = "jar tofu pudding",
    ["罐茶"] = "canned tea",
    ["罐装"] = "canned",
    ["罐装食品"] = "canned food",
    ["罐车"] = "tank truck",
}

return M
