local M = {}

M.mapping = {
    ["烩三丝鱼翅"] = "braised three-shred shark fin",
    ["烩丸子"] = "braised meatballs",
    ["烩乌龟蛋"] = "braised turtle eggs",
    ["烩南荠"] = "braised water chestnuts",
    ["烩小吃"] = "braised snacks",
    ["烩散丹"] = "braised tripe",
    ["烩明珠"] = "braised pearls",
    ["烩水果"] = "stewed fruit",
    ["烩海参"] = "braised sea cucumber",
    ["烩牛肉"] = "braised beef",
    ["烩番薯"] = "braised sweet potato",
    ["烩白杂碎"] = "braised white offal",
    ["烩白菜"] = "braised cabbage",
    ["烩羊杂碎"] = "braised sheep offal",
    ["烩肉饭"] = "braised meat rice",
    ["烩肥肠"] = "braised intestines",
    ["烩脐肚"] = "braised tripe",
    ["烩腰丁儿"] = "braised kidney dices",
    ["烩节子"] = "stewed festival dish",
    ["烩茄子"] = "braised eggplant",
    ["烩菜"] = "step back",
    ["烩虾仁"] = "braised shrimp",
    ["烩蜜枣"] = "braised jujube",
    ["烩蜜桃"] = "braised peach",
    ["烩蟹肉"] = "braised crab meat",
    ["烩豌豆"] = "braised peas",
    ["烩酸燕儿"] = "stewed sour swallow",
    ["烩酸菜"] = "stewed sour cabbage",
    ["烩酸蕾"] = "stewed sour bud",
    ["烩金银丝"] = "stewed gold and silver threads",
    ["烩银丝"] = "braised silver shreds",
    ["烩银丝儿"] = "braised silver shreds",
    ["烩银耳"] = "braised tremella",
    ["烩面"] = "braised noodles",
    ["烩饭"] = "fried rice",
    ["烩饼"] = "braised pancake",
    ["烩鸭四宝"] = "braised duck four treasures",
    ["烩鸭腰儿"] = "braised duck kidney",
    ["烩麻食"] = "braised mash",
}

return M
