local M = {}

M.mapping = {
    ["篮下"] = "under basket",
    ["篮协"] = "basketball association",
    ["篮圈"] = "basket rim",
    ["篮坛"] = "basketball circle",
    ["篮子"] = "basket",
    ["篮子里"] = "in the basket",
    ["篮板"] = "backboard",
    ["篮板王"] = "rebound king",
    ["篮板球"] = "rebound",
    ["篮架"] = "basketball stand",
    ["篮框"] = "basket frame",
    ["篮球"] = "basketball",
    ["篮球之父"] = "father of basketball",
    ["篮球员"] = "basketball player",
    ["篮球场"] = "basketball court",
    ["篮球场上"] = "on the basketball court",
    ["篮球教练"] = "basketball coach",
    ["篮球服"] = "basketball jersey",
    ["篮球架"] = "basketball hoop",
    ["篮球比赛"] = "basketball game",
    ["篮球界"] = "basketball world",
    ["篮球联赛"] = "basketball league",
    ["篮球赛"] = "basketball match",
    ["篮球运动"] = "basketball sport",
    ["篮球运动员"] = "basketball player",
    ["篮球队"] = "basketball team",
    ["篮球鞋"] = "basketball shoes",
    ["篮球飞人"] = "slam dunk",
    ["篮球馆"] = "basketball gym",
    ["篮球鸽蛋"] = "basketball pigeon egg",
    ["篮筐"] = "basket hoop",
    ["篮网"] = "nets",
    ["篮网队"] = "brooklyn nets",
    ["篮色狮子头"] = "blue lionhead",
}

return M
