local M = {}

M.mapping = {
    ["笼不住"] = "unable to cage",
    ["笼中"] = "in cage",
    ["笼中之鸟"] = "bird in a cage",
    ["笼中鸟"] = "caged bird",
    ["笼中鸡"] = "caged chicken",
    ["笼仔饭"] = "steamed rice in bamboo basket",
    ["笼养"] = "caged",
    ["笼内"] = "inside cage",
    ["笼嘴"] = "muzzle",
    ["笼四脚篮虫"] = "cage-footed basket worm",
    ["笼天地于形内"] = "contain heaven and earth",
    ["笼头"] = "faucet",
    ["笼子"] = "cage",
    ["笼子里"] = "inside the cage",
    ["笼屉"] = "steamer basket",
    ["笼山络野"] = "longshan luoye",
    ["笼底"] = "cage bottom",
    ["笼新"] = "longxin",
    ["笼火"] = "lantern fire",
    ["笼盖"] = "cover",
    ["笼盖四野"] = "cover the wilds",
    ["笼着手"] = "hands in sleeves",
    ["笼禽槛兽"] = "caged birds and beasts",
    ["笼竹和烟滴露梢"] = "bamboo tips dripping dew",
    ["笼笼统统"] = "general",
    ["笼络"] = "win over",
    ["笼络人心"] = "win hearts",
    ["笼络好"] = "win over well",
    ["笼统"] = "general",
    ["笼罩"] = "shroud",
    ["笼罩在"] = "shrouded in",
    ["笼罩着"] = "shrouding",
    ["笼而统之"] = "generalize",
    ["笼舍"] = "cage",
    ["笼茶"] = "caged tea",
    ["笼街喝道"] = "street parade",
    ["笼里"] = "in cage",
    ["笼钩"] = "cage hook",
    ["笼鸟"] = "caged bird",
}

return M
