local M = {}

M.mapping = {
    ["碘伏"] = "povidone-iodine",
    ["碘佛醇"] = "ioversol",
    ["碘克沙醇"] = "iodixanol",
    ["碘化"] = "iodination",
    ["碘化氢"] = "hydrogen iodide",
    ["碘化汞"] = "mercuric iodide",
    ["碘化油"] = "iodized oil",
    ["碘化物"] = "iodide",
    ["碘化酪氨酸"] = "iodotyrosine",
    ["碘化钙"] = "calcium iodide",
    ["碘化钠"] = "sodium iodide",
    ["碘化钾"] = "potassium iodide",
    ["碘化钾片"] = "potassium iodide tablet",
    ["碘化铊"] = "thallium iodide",
    ["碘化铵"] = "ammonium iodide",
    ["碘化银"] = "silver iodide",
    ["碘塞罗宁"] = "liothyronine",
    ["碘尿嘧啶"] = "iodouracil",
    ["碘帕醇"] = "iopamidol",
    ["碘普罗胺"] = "iopromide",
    ["碘普罗胺注射液"] = "iopromide injection",
    ["碘比醇"] = "iobitridol",
    ["碘油造影"] = "iodized oil radiography",
    ["碘海醇"] = "iohexol",
    ["碘甘油"] = "iodine glycerin",
    ["碘番酸"] = "iopanoic acid",
    ["碘的"] = "iodine",
    ["碘盐"] = "iodized salt",
    ["碘缺乏"] = "iodine deficiency",
    ["碘缺乏病"] = "iodine deficiency disorder",
    ["碘苯甲酸钠"] = "sodium iodobenzoate",
    ["碘解磷定"] = "pralidoxime iodide",
    ["碘酊"] = "iodine tincture",
    ["碘酒"] = "iodine tincture",
    ["碘酸"] = "iodic acid",
    ["碘酸钾"] = "potassium iodate",
    ["碘钨灯"] = "iodine tungsten lamp",
    ["碘镓灯"] = "iodine gallium lamp",
}

return M
