local M = {}

M.mapping = {
    ["祈使句"] = "imperative sentence",
    ["祈使语气"] = "imperative mood",
    ["祈山村"] = "qishan village",
    ["祈年"] = "pray for harvest",
    ["祈年大街北口"] = "north entrance of qinian street",
    ["祈年大街南口"] = "south entrance of qinian street",
    ["祈年殿"] = "hall of prayer for good harvests",
    ["祈愿"] = "wish",
    ["祈愿板"] = "wish board",
    ["祈愿池"] = "wishing well",
    ["祈晴祷雨"] = "pray for clear skies and rain",
    ["祈望"] = "pray",
    ["祈求"] = "pray",
    ["祈求平安"] = "pray for peace",
    ["祈灵"] = "pray for spirit",
    ["祈盼"] = "pray hope",
    ["祈祷"] = "pray",
    ["祈祷之刃"] = "blade of prayer",
    ["祈祷书"] = "prayer book",
    ["祈祷会"] = "prayer meeting",
    ["祈祷头盔"] = "prayer helmet",
    ["祈祷室"] = "prayer room",
    ["祈祷戒指"] = "prayer ring",
    ["祈祷手镯"] = "prayer bracelet",
    ["祈祷文"] = "prayer",
    ["祈祷着"] = "praying",
    ["祈祷者"] = "prayer",
    ["祈祷项链"] = "prayer necklace",
    ["祈福"] = "pray blessing",
    ["祈福墙"] = "prayer wall",
    ["祈福奥运"] = "pray olympics",
    ["祈福灯"] = "prayer lantern",
    ["祈禳"] = "prayer",
    ["祈签"] = "prayer drawing",
    ["祈请使"] = "envoy of petition",
    ["祈雨"] = "rain prayer",
    ["祈雪灵祝"] = "prayer for snow",
    ["祈风石刻群"] = "wind prayer carvings",
}

return M
