local M = {}

M.mapping = {
    ["犀全龟科"] = "rhinoclemmydidae",
    ["犀利"] = "sharp",
    ["犀利妹"] = "sharp girl",
    ["犀利姐"] = "sharp sister",
    ["犀咝蝰"] = "rhinoceros viper",
    ["犀尾优剑螽"] = "excellent sword katydid",
    ["犀浦"] = "xipu",
    ["犀浦路口"] = "xipu intersection",
    ["犀浦酱油"] = "xipu soy sauce",
    ["犀照牛渚"] = "xi shines on niuzhu",
    ["犀牛"] = "rhinoceros",
    ["犀牛变色龙"] = "rhinoceros chameleon",
    ["犀牛坪"] = "rhinoceros flat",
    ["犀牛望月"] = "rhinoceros gazes at moon",
    ["犀牛甲虫"] = "rhinoceros beetle",
    ["犀牛角"] = "rhinoceros horn",
    ["犀牛鸟"] = "rhinoceros bird",
    ["犀目𫚔"] = "rhino-eye fish",
    ["犀箸厌饫久未下"] = "rhinoceros chopsticks",
    ["犀羚解毒丸"] = "rhino-antelope detox pill",
    ["犀蟌科"] = "platycnemididae",
    ["犀角"] = "rhinoceros horn",
    ["犀角化毒丸"] = "rhinoceros horn detox pill",
    ["犀角地黄丸"] = "rhinoceros horn rehmannia pill",
    ["犀角地黄汤"] = "rhinoceros horn rehmannia decoction",
    ["犀角烛怪"] = "rhinoceros horn candle monster",
    ["犀角蝉"] = "rhinoceros horn cicada",
    ["犀角金线鲅"] = "rhinoceros horn golden threadfin",
    ["犀角金龟"] = "rhinoceros beetle",
    ["犀轮虫"] = "rotifer",
    ["犀金龟"] = "rhinoceros beetle",
    ["犀金龟科"] = "dynastinae",
    ["犀顶龟文"] = "rhino top turtle pattern",
    ["犀颅玉颊"] = "sharp brows jade cheeks",
    ["犀鳕科"] = "grenadiers",
    ["犀鸟"] = "hornbill",
    ["犀鸟亚科"] = "bucerotinae",
    ["犀鸟目"] = "bucerotiformes",
}

return M
