local M = {}

M.mapping = {
    ["绥中"] = "suizhong",
    ["绥中北"] = "suizhong north",
    ["绥中县"] = "suizhong county",
    ["绥中路"] = "suizhong road",
    ["绥化"] = "suihua",
    ["绥化县"] = "suihua county",
    ["绥化地区"] = "suihua region",
    ["绥化市"] = "suihua city",
    ["绥化市第一医院"] = "suihua first hospital",
    ["绥北"] = "suibei",
    ["绥宁"] = "suining",
    ["绥宁县"] = "suining county",
    ["绥宁路"] = "suining road",
    ["绥德县"] = "suide county",
    ["绥服"] = "pacified territory",
    ["绥棱"] = "suiling",
    ["绥棱县"] = "suiling county",
    ["绥江"] = "suijiang",
    ["绥江县"] = "suijiang county",
    ["绥江道"] = "suijiang road",
    ["绥滨"] = "suibin",
    ["绥滨县"] = "suibin county",
    ["绥芬"] = "suifen",
    ["绥芬河"] = "suifen river",
    ["绥芬河市"] = "suifenhe city",
    ["绥芬河滩头鱼"] = "suifenhe beach fish",
    ["绥西"] = "suixi",
    ["绥远"] = "suiyuan",
    ["绥阳"] = "suiyang",
    ["绥阳县"] = "suiyang county",
    ["绥阳空心面"] = "suiyang hollow noodles",
    ["绥靖"] = "pacification",
    ["绥靖主义"] = "appeasement",
    ["绥靖公署"] = "pacification office",
    ["绥靖政策"] = "appeasement policy",
}

return M
