local M = {}

M.mapping = {
    ["牌九"] = "pai gow",
    ["牌价"] = "list price",
    ["牌位"] = "memorial tablet",
    ["牌儿"] = "card",
    ["牌前"] = "in front of the sign",
    ["牌匾"] = "plaque",
    ["牌友"] = "card friend",
    ["牌号"] = "brand",
    ["牌品"] = "card quality",
    ["牌坊"] = "memorial archway",
    ["牌坊回族满族乡"] = "paifang hui and manchu township",
    ["牌坊湾"] = "paifang bay",
    ["牌坊群"] = "archway group",
    ["牌坊面"] = "paifang noodles",
    ["牌型"] = "hand pattern",
    ["牌好"] = "good cards",
    ["牌子"] = "brand",
    ["牌子好"] = "good brand",
    ["牌局"] = "card game",
    ["牌山"] = "mahjong wall",
    ["牌手"] = "card player",
    ["牌技"] = "card skills",
    ["牌效"] = "tile efficiency",
    ["牌桌"] = "card table",
    ["牌楼"] = "decorated archway",
    ["牌楼路"] = "pailou road",
    ["牌点"] = "card points",
    ["牌照"] = "license",
    ["牌照板"] = "license plate",
    ["牌照框"] = "license frame",
    ["牌照灯护板"] = "license lamp guard",
    ["牌照税"] = "license tax",
    ["牌牛仔裤"] = "brand jeans",
    ["牌示"] = "signboard",
    ["牌类"] = "card games",
    ["牌类游戏"] = "card games",
    ["牌组"] = "deck",
    ["牌证"] = "license cert",
    ["牌赌"] = "gambling",
    ["牌面"] = "face value",
    ["牌风"] = "mahjong wind",
}

return M
