local M = {}

M.mapping = {
    ["茄团"] = "eggplant ball",
    ["茄子"] = "eggplant",
    ["茄子三明治"] = "eggplant sandwich",
    ["茄子晒炉肉"] = "sun-dried eggplant pork",
    ["茄子河"] = "qiezi river",
    ["茄子河区"] = "qiezihe district",
    ["茄子炖鸡汤"] = "eggplant chicken stew",
    ["茄子煮花甲"] = "eggplant clam boil",
    ["茄子茶黄螨"] = "eggplant mite",
    ["茄子酱"] = "eggplant sauce",
    ["茄尼醇"] = "solanesol",
    ["茄形碘泡虫"] = "qie xing dian pao chong",
    ["茄果类"] = "solanaceous fruits",
    ["茄汁"] = "tomato sauce",
    ["茄汁斑鱼块"] = "tomato fish chunks",
    ["茄汁明虾"] = "tomato prawns",
    ["茄汁烩鱼片"] = "tomato braised fish",
    ["茄汁牛扒"] = "tomato steak",
    ["茄汁牛肉汤"] = "tomato beef soup",
    ["茄汁猪排"] = "tomato pork chop",
    ["茄汁菜包"] = "tomato stuffed cabbage",
    ["茄汁薯枣"] = "tomato date potatoes",
    ["茄汁鱼卷"] = "tomato fish roll",
    ["茄汁鱼罐头"] = "tomato fish can",
    ["茄汁鳕鱼"] = "tomato cod",
    ["茄汁鸡肉"] = "tomato chicken",
    ["茄汤焗香鸡"] = "baked chicken in tomato soup",
    ["茄瓜"] = "eggplant",
    ["茄皮紫"] = "eggplant purple",
    ["茄盒"] = "eggplant box",
    ["茄色"] = "eggplant color",
    ["茄色楼"] = "eggplant building",
    ["茄花紫"] = "eggplant purple",
    ["茄蓝丹纱"] = "qielan dansha",
    ["茄鲞"] = "preserved eggplant",
    ["茄黄斑螟蛾"] = "eggplant yellow-spotted moth",
}

return M
