local M = {}

M.mapping = {
    ["袖上"] = "on sleeve",
    ["袖中"] = "in sleeve",
    ["袖中忽见三行字"] = "sudden words in sleeve",
    ["袖口"] = "cuff",
    ["袖头"] = "cuff",
    ["袖套"] = "sleeve cover",
    ["袖子"] = "sleeve",
    ["袖子里"] = "in the sleeve",
    ["袖手"] = "folded arms",
    ["袖手旁观"] = "stand by",
    ["袖手无言味最长"] = "silent depth",
    ["袖扣"] = "cufflinks",
    ["袖标"] = "armband",
    ["袖狗"] = "sleeve dog",
    ["袖珍"] = "pocket",
    ["袖珍书"] = "miniature book",
    ["袖珍国"] = "microstate",
    ["袖珍型"] = "pocket",
    ["袖珍式"] = "pocket-sized",
    ["袖珍本"] = "pocketbook",
    ["袖珍版"] = "pocket edition",
    ["袖珍狗"] = "teacup dog",
    ["袖珍英汉法律词典"] = "pocket english-chinese law dictionary",
    ["袖章"] = "armband",
    ["袖筒"] = "sleeve",
    ["袖箍"] = "cufflink",
    ["袖管"] = "sleeve",
    ["袖箭"] = "dagger",
    ["袖粉蝶亚科"] = "dismorphiinae",
    ["袖缠云"] = "sleeve cloud",
    ["袖袪"] = "sleeve cuff",
    ["袖里"] = "sleeve",
    ["袖里乾坤"] = "universe in sleeve",
    ["袖钉"] = "cufflink",
    ["袖镖"] = "sleeve dart",
    ["袖长"] = "sleeve length",
}

return M
