local M = {}

M.mapping = {
    ["膏丸"] = "ointment pill",
    ["膏剂"] = "paste preparation",
    ["膏唇岐舌"] = "glossy lips forked tongue",
    ["膏唇试舌"] = "glossy lips test tongue",
    ["膏子"] = "paste",
    ["膏子哥"] = "paste brother",
    ["膏桐"] = "tung oil tree",
    ["膏梁之性"] = "nature of the rich",
    ["膏梁厚味"] = "rich and flavorful food",
    ["膏梁锦绣"] = "rich and splendid",
    ["膏梁锦锈"] = "rich and splendid",
    ["膏油"] = "grease",
    ["膏泽"] = "beneficial rain",
    ["膏泽脂香"] = "fragrant grease",
    ["膏火"] = "fuel",
    ["膏烛以明自煎"] = "candle consumes itself to give light",
    ["膏状"] = "paste",
    ["膏盲之病"] = "incurable disease",
    ["膏粱"] = "fine grain",
    ["膏粱之子"] = "son of the rich",
    ["膏粱之性"] = "nature of the rich",
    ["膏粱年少"] = "young and rich",
    ["膏粱纨绔"] = "rich and idle",
    ["膏肓"] = "vital region",
    ["膏肓之病"] = "incurable disease",
    ["膏肓腧"] = "gaohuang shu point",
    ["膏腴"] = "fertile",
    ["膏腴之地"] = "fertile land",
    ["膏腴之壤"] = "fertile soil",
    ["膏腴贵游"] = "wealthy nobles",
    ["膏药"] = "plaster",
    ["膏药旗"] = "plaster flag",
    ["膏蟹"] = "mud crab",
    ["膏血"] = "blood and sweat",
    ["膏霜"] = "cream",
    ["膏面染须聊自欺"] = "painted face dyed beard deceive self",
}

return M
