local M = {}

M.mapping = {
    ["聂元梓"] = "nie yuanzi",
    ["聂凤智"] = "nie fengzhi",
    ["聂华苓"] = "nie hualing",
    ["聂卫平"] = "nie weiping",
    ["聂各庄"] = "niegezhuang",
    ["聂各庄南"] = "niegezhuang south",
    ["聂唐乡"] = "nie tang township",
    ["聂士成"] = "nie shicheng",
    ["聂夷中"] = "nie yizhong",
    ["聂姓"] = "nie surname",
    ["聂家村乡"] = "niejiacun township",
    ["聂家湾"] = "niejiawan",
    ["聂小雨"] = "nie xiaoyu",
    ["聂庄"] = "nie zhuang",
    ["聂拉斯"] = "ner'zhul",
    ["聂拉木"] = "nyalam",
    ["聂拉木县"] = "nyalam county",
    ["聂拉木双斜卷蛾"] = "nyalam moth",
    ["聂拉木巨蟹蛛"] = "nyalam giant crab spider",
    ["聂拉木角胸肖叶甲"] = "nyalam leaf beetle",
    ["聂政"] = "nie zheng",
    ["聂斯脱利派"] = "nestorianism",
    ["聂日雄乡"] = "nie ri xiong township",
    ["聂杰铭"] = "nie jieming",
    ["聂氏无刺鲼"] = "nie's stingray",
    ["聂海胜"] = "nie haisheng",
    ["聂猛"] = "nie meng",
    ["聂耳"] = "nie er",
    ["聂荣县"] = "nie rong county",
    ["聂荣臻"] = "nie rongzhen",
    ["聂营镇"] = "nieying town",
    ["聂豹"] = "nie bao",
    ["聂赫留朵夫"] = "nekhludoff",
    ["聂远"] = "nie yuan",
    ["聂铁文"] = "nie tie wen",
    ["聂隐娘"] = "nie yinniang",
    ["聂风"] = "nie feng",
    ["聂鲁达"] = "neruda",
}

return M
