local M = {}

M.mapping = {
    ["账上"] = "on account",
    ["账下"] = "under account",
    ["账内"] = "internal account",
    ["账内物资"] = "internal supplies",
    ["账册"] = "account book",
    ["账册在哪里"] = "where is the account book",
    ["账务"] = "accounting",
    ["账务处理"] = "account processing",
    ["账务调整"] = "account adjustment",
    ["账单"] = "bill",
    ["账号"] = "account",
    ["账号交易"] = "account trading",
    ["账号密码"] = "account password",
    ["账外"] = "off-book",
    ["账外物资"] = "off-book materials",
    ["账外经营"] = "off-book operations",
    ["账外账"] = "off-book account",
    ["账外资金"] = "off-book funds",
    ["账实核对"] = "account verification",
    ["账户"] = "account",
    ["账户上"] = "on account",
    ["账户余额"] = "account balance",
    ["账户卡"] = "account card",
    ["账户名"] = "account name",
    ["账户名称"] = "account name",
    ["账户就"] = "account is",
    ["账户表"] = "account table",
    ["账户锁定"] = "account locked",
    ["账房"] = "accountant",
    ["账房先生"] = "accountant",
    ["账本"] = "account book",
    ["账款"] = "account",
    ["账目"] = "accounts",
    ["账目总表"] = "general ledger",
    ["账目表"] = "account sheet",
    ["账簿"] = "ledger",
    ["账表"] = "account book",
    ["账面"] = "book value",
    ["账面价值"] = "carrying value",
    ["账面余额"] = "book balance",
    ["账面值"] = "book value",
    ["账项"] = "account item",
}

return M
