local M = {}

M.mapping = {
    ["赠与"] = "donation",
    ["赠与合同"] = "donation contract",
    ["赠与税"] = "gift tax",
    ["赠书"] = "book donation",
    ["赠予"] = "bestow",
    ["赠人"] = "give to others",
    ["赠元六兄林宗"] = "gift yuan liuxiong linzong",
    ["赠别"] = "farewell gift",
    ["赠券"] = "coupon",
    ["赠卫八处士"] = "to wei the recluse",
    ["赠卫尉张卿二首"] = "to chamberlain zhang",
    ["赠君一法决狐疑"] = "method to resolve doubts",
    ["赠君无语竹夫人"] = "silent bamboo wife gift",
    ["赠品"] = "freebie",
    ["赠品多"] = "many freebies",
    ["赠奖"] = "prize giveaway",
    ["赠妾双明珠"] = "gift twin pearls",
    ["赠嵩山焦炼师"] = "to master jiao of songshan",
    ["赠我予白"] = "give me white",
    ["赠本"] = "gift copy",
    ["赠楚州郭使君"] = "to governor guo of chuzhou",
    ["赠款"] = "grant",
    ["赠汪伦"] = "to wang lun",
    ["赠物"] = "gift",
    ["赠白马王彪"] = "gift to baima prince biao",
    ["赠礼"] = "gift",
    ["赠礼品"] = "give presents",
    ["赠票"] = "complimentary ticket",
    ["赠科乡"] = "zengke township",
    ["赠答"] = "exchange gifts",
    ["赠给"] = "give to",
    ["赠芍采兰"] = "present peony and gather orchid",
    ["赠花卿"] = "present flowers to qing",
    ["赠言"] = "parting words",
    ["赠送"] = "give",
    ["赠送了"] = "gave",
    ["赠送礼品"] = "gift giving",
    ["赠错"] = "gift error",
    ["赠阅"] = "complimentary",
    ["赠阅发行"] = "complimentary distribution",
    ["赠黄山胡公求白鹇"] = "present to huangshan hu gong for white pheasant",
}

return M
