local M = {}

M.mapping = {
    ["耀光"] = "glory light",
    ["耀光三刺角蝉"] = "glory light three-spined treehopper",
    ["耀光希尔德康吉鳗"] = "glory light hildebrandt's conger",
    ["耀兴"] = "yao xing",
    ["耀华创建大厦"] = "yaohua creation building",
    ["耀华玻璃"] = "yaohua glass",
    ["耀华西餐厅"] = "yaohua western restaurant",
    ["耀华路"] = "yaohua road",
    ["耀唇指"] = "glossy lips",
    ["耀夜萤"] = "glowing night firefly",
    ["耀宇"] = "yao yu",
    ["耀尾魮"] = "glowtail fish",
    ["耀州"] = "yaozhou",
    ["耀州窑"] = "yaozhou kiln",
    ["耀彬"] = "yaobin",
    ["耀我中华"] = "glorify china",
    ["耀斑"] = "flare",
    ["耀斑玉栏杆"] = "flare balustrade",
    ["耀日"] = "shining sun",
    ["耀星眶灯鱼"] = "diaphus splendidus",
    ["耀棠"] = "yaotang",
    ["耀武"] = "flaunt power",
    ["耀武扬威"] = "swagger",
    ["耀武胡同"] = "yaowu hutong",
    ["耀江大酒店"] = "yaojiang grand hotel",
    ["耀江广厦"] = "yaojiang plaza",
    ["耀江福村"] = "yaojiang lucky village",
    ["耀炬龙属"] = "lambeosaurus",
    ["耀白鲑"] = "whitefish",
    ["耀皮玻璃"] = "yaopi glass",
    ["耀目"] = "dazzling",
    ["耀眼"] = "dazzling",
    ["耀眼夺目"] = "eye-catching",
    ["耀眼底灯鱼"] = "diaphus suborbitalis",
    ["耀眼的"] = "dazzling",
    ["耀祖"] = "glorify ancestors",
    ["耀祖荣宗"] = "honor ancestors",
    ["耀群"] = "shine group",
    ["耀邦"] = "yaobang",
    ["耀隆集团"] = "yaolong group",
}

return M
