local M = {}

M.mapping = {
    ["肚丝"] = "shredded tripe",
    ["肚中"] = "in the stomach",
    ["肚兜"] = "bellyband",
    ["肚子"] = "belly",
    ["肚子上"] = "on the belly",
    ["肚子像"] = "stomach like",
    ["肚子响"] = "stomach rumbling",
    ["肚子响了"] = "stomach rumbled",
    ["肚子疼"] = "stomachache",
    ["肚子痛"] = "stomachache",
    ["肚子里"] = "in the belly",
    ["肚子里咽"] = "swallow in the belly",
    ["肚子饿了"] = "hungry",
    ["肚带"] = "bellyband",
    ["肚束三篾"] = "tightening the belly with three bamboo strips",
    ["肚片"] = "sliced tripe",
    ["肚疼"] = "stomachache",
    ["肚痛"] = "stomach pain",
    ["肚痛健胃整肠丸"] = "stomach pain and stomach medicine",
    ["肚皮"] = "belly",
    ["肚皮舞"] = "belly dance",
    ["肚皮里点灯笼"] = "lantern in the belly",
    ["肚肠"] = "intestines",
    ["肚胀"] = "abdominal distension",
    ["肚脐"] = "belly button",
    ["肚脐眼"] = "belly button",
    ["肚腩"] = "belly fat",
    ["肚腹"] = "abdomen",
    ["肚里"] = "in the stomach",
    ["肚里打稿"] = "drafting in mind",
    ["肚里泪下"] = "shedding tears inside",
    ["肚里生荆棘"] = "thorns growing in the stomach",
    ["肚里落泪"] = "shedding tears inside",
    ["肚里蛔虫"] = "mind reader",
    ["肚量"] = "tolerance",
}

return M
