local M = {}

M.mapping = {
    ["耕之灵"] = "spirit of cultivation",
    ["耕云播雨"] = "sow clouds and rain",
    ["耕作"] = "cultivation",
    ["耕作制度"] = "farming system",
    ["耕作学"] = "agronomy",
    ["耕具"] = "farming tools",
    ["耕地"] = "cultivated land",
    ["耕地保护"] = "cultivated land protection",
    ["耕地占用税"] = "cultivated land occupation tax",
    ["耕地占补平衡考核办法"] = "cultivated land occupation and compensation balance assessment method",
    ["耕地机"] = "cultivator",
    ["耕地面积"] = "cultivated land area",
    ["耕夫"] = "farmer",
    ["耕夫召募逐楼船"] = "farmers recruited to man the tower ships",
    ["耕夫让畔"] = "farmers yield borders",
    ["耕牛"] = "farm cattle",
    ["耕牛遍地走"] = "cattle everywhere",
    ["耕田"] = "plow fields",
    ["耕田而食"] = "plow fields and eat",
    ["耕畜"] = "farm animal",
    ["耕种"] = "cultivate",
    ["耕种从此起"] = "cultivation begins from here",
    ["耕稼"] = "farming",
    ["耕稼陶渔"] = "farming, pottery, fishing",
    ["耕管"] = "cultivation management",
    ["耕织"] = "farming and weaving",
    ["耕翻"] = "plow",
    ["耕者"] = "cultivator",
    ["耕者有其田"] = "land to the tiller",
    ["耕耘"] = "cultivate",
    ["耕耘处中田"] = "cultivate in the middle field",
    ["耕耘树艺"] = "cultivate and plant",
    ["耕耘着"] = "cultivating",
    ["耕耘者"] = "cultivator",
    ["耕读"] = "farming and studying",
}

return M
