local M = {}

M.mapping = {
    ["膜分离"] = "membrane separation",
    ["膜厚计"] = "coating thickness gauge",
    ["膜口目"] = "hymenostomatida",
    ["膜囊尖锥虫"] = "apical conoid membrane sac",
    ["膜固思达"] = "moguoside",
    ["膜壳绦虫属"] = "hymenolepis",
    ["膜层"] = "film layer",
    ["膜性肾病"] = "membranous nephropathy",
    ["膜技术"] = "membrane technology",
    ["膜拜"] = "worship",
    ["膜拟单栏虫"] = "simulated single-column organism",
    ["膜整合锥"] = "membrane cone",
    ["膜材"] = "membrane material",
    ["膜法师"] = "spellcaster",
    ["膜泡"] = "vesicle",
    ["膜消化"] = "membrane digestion",
    ["膜炎"] = "meningitis",
    ["膜片"] = "diaphragm",
    ["膜片式制动气室"] = "diaphragm brake chamber",
    ["膜片弹簧离合器"] = "diaphragm spring clutch",
    ["膜片箝位技术"] = "patch clamp technique",
    ["膜片钳"] = "patch clamp",
    ["膜状"] = "membranous",
    ["膜状二段海鞘"] = "didemnum membranaceum",
    ["膜状苔藓虫"] = "membranipora",
    ["膜电位"] = "membrane potential",
    ["膜电容"] = "membrane capacitance",
    ["膜电导"] = "membrane conductance",
    ["膜管"] = "membrane tube",
    ["膜组件"] = "membrane module",
    ["膜翅目"] = "hymenoptera",
    ["膜翅目青蜂科"] = "chrysididae",
    ["膜联蛋白"] = "annexin",
    ["膜节虫"] = "membrane joint worm",
    ["膜蛋白"] = "membrane protein",
    ["膜蛤"] = "membrane clam",
    ["膜蛤文化"] = "membrane clam culture",
    ["膜袋虫属"] = "cystidium",
    ["膜质才女虫"] = "membrane worm",
    ["膜过滤"] = "membrane filtration",
    ["膜颅"] = "membrane skull",
    ["膜颅间关节"] = "intermembranous joint",
}

return M
