local M = {}

M.mapping = {
    ["舟中"] = "boat middle",
    ["舟人夜语觉潮生"] = "boatmen talk at night sensing the tide",
    ["舟子"] = "boatman",
    ["舟山"] = "zhoushan",
    ["舟山东路"] = "zhoushan east road",
    ["舟山中院"] = "zhoushan intermediate court",
    ["舟山医院"] = "zhoushan hospital",
    ["舟山岛"] = "zhoushan island",
    ["舟山市"] = "zhoushan city",
    ["舟山市军人抚恤优待实施办法"] = "zhoushan military pension implementation",
    ["舟山市发展和改革委员会"] = "zhoushan development and reform commission",
    ["舟山港"] = "zhoushan port",
    ["舟山群岛"] = "zhoushan archipelago",
    ["舟山路"] = "zhoushan road",
    ["舟曲"] = "zhouqu",
    ["舟曲县"] = "zhouqu county",
    ["舟桥"] = "pontoon bridge",
    ["舟楫"] = "boat",
    ["舟楫恐失坠"] = "fear of boat sinking",
    ["舟楫控吴人"] = "boats control wu people",
    ["舟水之喻"] = "boat-water analogy",
    ["舟状头"] = "scaphocephaly",
    ["舟群乡"] = "zhouqun township",
    ["舟舆"] = "boat and cart",
    ["舟船"] = "boat",
    ["舟船如野渡"] = "boats like a wild ferry",
    ["舟蛾"] = "notodontid",
    ["舟蛾科"] = "notodontidae",
    ["舟蛾脊茧蜂"] = "rogas notodontae",
    ["舟蛾赤眼蜂"] = "trichogramma notodontae",
    ["舟行"] = "boat travel",
    ["舟行明镜中"] = "boat in mirror",
    ["舟车"] = "boat and cart",
    ["舟车之利"] = "advantage of transportation",
    ["舟车劳累"] = "travel weariness",
    ["舟车劳顿"] = "travel fatigue",
    ["舟车半天下"] = "boats and carts half the world",
    ["舟雪洒寒灯"] = "snow on boat, cold lamp",
    ["舟骨"] = "scaphoid",
}

return M
