local M = {}

M.mapping = {
    ["荔园小学"] = "liyuan primary school",
    ["荔城区"] = "licheng district",
    ["荔子已丹吾发白"] = "lizi turns red while my hair turns white",
    ["荔山村"] = "lychee mountain village",
    ["荔景园"] = "lychee garden",
    ["荔村"] = "licun",
    ["荔枝"] = "lychee",
    ["荔枝公园"] = "lychee park",
    ["荔枝巷"] = "lychee lane",
    ["荔枝干"] = "dried lychee",
    ["荔枝林"] = "lychee forest",
    ["荔枝果"] = "lychee",
    ["荔枝树"] = "lychee tree",
    ["荔枝核"] = "lychee seed",
    ["荔枝罐头"] = "canned lychee",
    ["荔枝肉"] = "lychee pork",
    ["荔枝节"] = "lychee festival",
    ["荔枝花园"] = "lychee garden",
    ["荔枝茶"] = "lychee tea",
    ["荔枝菌"] = "lychee mushroom",
    ["荔枝蜜"] = "lychee honey",
    ["荔枝酥"] = "lychee pastry",
    ["荔枝鱿鱼"] = "lychee squid",
    ["荔枝鱿鱼卷"] = "lychee squid roll",
    ["荔波县"] = "libo county",
    ["荔浦"] = "lipu",
    ["荔浦县"] = "lipu county",
    ["荔浦芋"] = "lipu taro",
    ["荔湾"] = "liwan",
    ["荔湾区"] = "liwan district",
    ["荔湾渔唱"] = "liwan fishing song",
    ["荔湾湖"] = "liwan lake",
    ["荔湾路"] = "liwan road",
    ["荔溪乡"] = "lixi township",
    ["荔联街"] = "lilian street",
    ["荔联街道"] = "lilian subdistrict",
    ["荔花鼻窦炎片"] = "lihua sinusitis tablet",
    ["荔香公园"] = "lixiang park",
    ["荔香街"] = "lixiang street",
    ["荔香路"] = "lixiang road",
}

return M
