local M = {}

M.mapping = {
    ["菠菜"] = "spinach",
    ["菠菜丸子汤"] = "spinach meatball soup",
    ["菠菜卧果"] = "spinach poached egg",
    ["菠菜排骨银鱼羹"] = "spinach pork ribs whitebait soup",
    ["菠菜炒牛柳"] = "spinach stir-fried beef tenderloin",
    ["菠菜炒生鱼片"] = "spinach stir-fried raw fish slices",
    ["菠菜煎饼"] = "spinach pancake",
    ["菠菜猪肝汤"] = "spinach and pork liver soup",
    ["菠菜蛋蓉"] = "spinach egg puree",
    ["菠菜金钩豆腐汤"] = "spinach golden hook tofu soup",
    ["菠菜香油汤"] = "spinach sesame oil soup",
    ["菠菜鸡煲"] = "spinach chicken pot",
    ["菠菜鸡蛋汤"] = "spinach egg soup",
    ["菠萝"] = "pineapple",
    ["菠萝丁"] = "pineapple dices",
    ["菠萝冻"] = "pineapple jelly",
    ["菠萝包"] = "pineapple bun",
    ["菠萝圆片"] = "pineapple round slices",
    ["菠萝屋"] = "pineapple house",
    ["菠萝山"] = "pineapple mountain",
    ["菠萝币"] = "pineapple coin",
    ["菠萝树"] = "pineapple tree",
    ["菠萝橙子美白汁"] = "pineapple orange whitening juice",
    ["菠萝汁"] = "pineapple juice",
    ["菠萝沙拉"] = "pineapple salad",
    ["菠萝派"] = "pineapple pie",
    ["菠萝炒圣鱼"] = "pineapple fried holy fish",
    ["菠萝罐头"] = "canned pineapple",
    ["菠萝芒果消脂水"] = "pineapple mango fat-reducing water",
    ["菠萝苦瓜鸡"] = "pineapple bitter melon chicken",
    ["菠萝蔬果汁"] = "pineapple vegetable juice",
    ["菠萝虾仁炒饭"] = "pineapple shrimp fried rice",
    ["菠萝蛋白酶"] = "bromelain",
    ["菠萝西红柿鲜活汁"] = "pineapple tomato fresh juice",
    ["菠萝西芹清脂水"] = "pineapple celery lipid-clearing water",
    ["菠萝软糖"] = "pineapple soft candy",
    ["菠萝面包"] = "pineapple bread",
    ["菠萝鸡丁"] = "pineapple chicken dices",
    ["菠萝龙眼鱼"] = "pineapple longan fish",
    ["菠饺鱼肚"] = "spinach dumpling fish maw",
}

return M
