local M = {}

M.mapping = {
    ["膨体纱"] = "bulk yarn",
    ["膨化"] = "puffed",
    ["膨化机"] = "puffing machine",
    ["膨化食品"] = "puffed snacks",
    ["膨化鳗片"] = "puffed eel slices",
    ["膨大"] = "expand",
    ["膨大前嵴蚌"] = "hyriopsis schlegelii",
    ["膨大吻额蛛"] = "hylyphantes graminicola",
    ["膨大海"] = "sterculia lychnophora",
    ["膨宽缘萤叶甲"] = "broad-margined leaf beetle",
    ["膨松剂"] = "leavening agent",
    ["膨润土"] = "bentonite",
    ["膨涨阀"] = "swell valve",
    ["膨肚杯形珊瑚"] = "bubble cup coral",
    ["膨胀"] = "expansion",
    ["膨胀剂"] = "expanding agent",
    ["膨胀力"] = "expansion force",
    ["膨胀开"] = "expand",
    ["膨胀性"] = "expansibility",
    ["膨胀性生长"] = "expansile growth",
    ["膨胀水泥"] = "expansive cement",
    ["膨胀水箱"] = "expansion tank",
    ["膨胀率"] = "expansion rate",
    ["膨胀的"] = "expanded",
    ["膨胀的心"] = "expanded heart",
    ["膨胀的爱心"] = "expanded love",
    ["膨胀系数"] = "expansion coefficient",
    ["膨胀螺丝"] = "expansion screw",
    ["膨胀螺栓"] = "expansion bolt",
    ["膨胀起来"] = "expand",
    ["膨胀运动"] = "expansion movement",
    ["膨胀阀"] = "expansion valve",
    ["膨脝"] = "bloated",
}

return M
