local M = {}

M.mapping = {
    ["荡为寒烟"] = "dissipate into cold mist",
    ["荡人心魄"] = "captivating",
    ["荡出"] = "swing out",
    ["荡口"] = "dangkou",
    ["荡口古镇"] = "dangkou ancient town",
    ["荡女"] = "promiscuous woman",
    ["荡妇"] = "slut",
    ["荡子"] = "wanderer",
    ["荡子天涯归棹远"] = "wanderer far from home",
    ["荡子行不归"] = "wanderer does not return",
    ["荡尽"] = "exhaust",
    ["荡平"] = "pacify",
    ["荡悠"] = "swing",
    ["荡悠悠"] = "swinging gently",
    ["荡摇浮世生万象"] = "swaying in the floating world creates myriad phenomena",
    ["荡来荡去"] = "swing back and forth",
    ["荡气回肠"] = "soul-stirring",
    ["荡海拔山"] = "move mountains",
    ["荡涤"] = "cleanse",
    ["荡漾"] = "ripple",
    ["荡漾游子情"] = "rippling wanderer's feelings",
    ["荡漾着"] = "rippling",
    ["荡然"] = "vanished",
    ["荡然无存"] = "completely vanished",
    ["荡然无遗"] = "utterly vanished",
    ["荡然肆志"] = "carefree and unrestrained",
    ["荡着"] = "swinging",
    ["荡着呢"] = "swinging it",
    ["荡神志"] = "disturbing the mind",
    ["荡秋千"] = "swing on a swing",
    ["荡胸生层云"] = "clouds billowing in the chest",
    ["荡舟"] = "boat rowing",
    ["荡荡"] = "vast",
    ["荡荡之勋"] = "merit of vastness",
    ["荡荡巍巍"] = "vast and majestic",
    ["荡荡默默"] = "vast and silent",
    ["荡起"] = "swing up",
    ["荡过"] = "swept over",
    ["荡除"] = "eliminate",
}

return M
