local M = {}

M.mapping = {
    ["苟且"] = "drift along",
    ["苟且偷安"] = "seek ease and comfort",
    ["苟且偷生"] = "drag out an ignoble existence",
    ["苟了"] = "dragged on",
    ["苟从"] = "blindly follow",
    ["苟住"] = "hold on",
    ["苟余心之端直兮"] = "if my heart is upright",
    ["苟余情其信姱以练要兮"] = "if my feelings are truly beautiful and refined",
    ["苟余情其信芳"] = "if my feelings are truly fragrant",
    ["苟免"] = "barely escape",
    ["苟全"] = "barely preserve",
    ["苟全性命"] = "barely preserve life",
    ["苟全性命于乱世"] = "barely preserve life in troubled times",
    ["苟合"] = "illicit intercourse",
    ["苟同"] = "agree",
    ["苟命"] = "spare life",
    ["苟存"] = "barely exist",
    ["苟存残喘"] = "barely survive",
    ["苟安"] = "seek temporary ease",
    ["苟安一隅"] = "seek temporary ease in a corner",
    ["苟家坡"] = "goujia slope",
    ["苟家滩"] = "goujiata",
    ["苟延"] = "linger",
    ["苟延一息"] = "linger with one breath",
    ["苟延危端"] = "linger in danger",
    ["苟延喘息"] = "linger on",
    ["苟延残喘"] = "linger on",
    ["苟延残息"] = "linger on",
    ["苟得用此下土"] = "if i can use this land",
    ["苟志于仁矣"] = "if one aspires to benevolence",
    ["苟无济代心"] = "if no ambition to aid the world",
    ["苟有用我者"] = "if someone would use me",
    ["苟正其身矣"] = "if one rectifies oneself",
    ["苟活"] = "drag out an ignoble existence",
    ["苟能"] = "if possible",
    ["苟能制侵陵"] = "if can stop invasion",
    ["苟非吾之所有"] = "if not mine",
}

return M
