local M = {}

M.mapping = {
    ["蝶之毒"] = "butterfly's poison",
    ["蝶儿"] = "butterfly",
    ["蝶兰"] = "phalaenopsis",
    ["蝶化庄周"] = "butterfly transformation",
    ["蝶化庄生"] = "butterfly transformation",
    ["蝶卵"] = "butterfly egg",
    ["蝶变"] = "butterfly change",
    ["蝶尾墨龙睛"] = "butterfly tail black dragon eye",
    ["蝶山"] = "butterfly mountain",
    ["蝶山区"] = "die shan district",
    ["蝶式"] = "butterfly style",
    ["蝶形"] = "butterfly shape",
    ["蝶形花"] = "butterfly-shaped flower",
    ["蝶形螺母"] = "butterfly nut",
    ["蝶形领带"] = "butterfly tie",
    ["蝶影"] = "butterfly shadow",
    ["蝶影刺月"] = "butterfly shadow stabs the moon",
    ["蝶怨蛩凄"] = "butterfly's resentment and cricket's sorrow",
    ["蝶恋"] = "butterfly love",
    ["蝶恋花"] = "butterfly loves flower",
    ["蝶恋花·答李淑一"] = "butterfly loves flower · reply to li shuyi",
    ["蝶恋蜂狂"] = "butterfly love and bee madness",
    ["蝶意莺情"] = "butterfly's intention and oriole's affection",
    ["蝶栖石竹银交关"] = "butterfly resting on stone bamboo silver intersection",
    ["蝶泳"] = "butterfly stroke",
    ["蝶泳赛"] = "butterfly stroke race",
    ["蝶窦"] = "sphenoid sinus",
    ["蝶类"] = "butterfly species",
    ["蝶绕绣衣花"] = "butterflies around embroidered clothes and flowers",
    ["蝶群"] = "butterfly swarm",
    ["蝶舞"] = "butterfly dance",
    ["蝶花百合"] = "butterfly lily",
    ["蝶蛹"] = "butterfly pupa",
    ["蝶衣"] = "butterfly wings",
    ["蝶阀"] = "butterfly valve",
    ["蝶阀厂"] = "butterfly valve factory",
    ["蝶鞍"] = "sella turcica",
    ["蝶飞儿"] = "die fei er",
    ["蝶飞花舞"] = "butterfly flying and flowers dancing",
    ["蝶骨"] = "sphenoid bone",
}

return M
