local M = {}

M.mapping = {
    ["蚁䴕"] = "antcreeper",
    ["蚁丘"] = "ant hill",
    ["蚁人"] = "ant-man",
    ["蚁冢"] = "ant hill",
    ["蚁卵"] = "ant egg",
    ["蚁后"] = "queen ant",
    ["蚁哥正传"] = "a bug's life",
    ["蚁垤"] = "anthill",
    ["蚁封盘马"] = "ant mound horse track",
    ["蚁封穴雨"] = "ants predict rain",
    ["蚁巢"] = "ant nest",
    ["蚁形甲"] = "ant-like beetle",
    ["蚁拥蜂攒"] = "swarming like ants and bees",
    ["蚁族"] = "ant tribe",
    ["蚁族之歌"] = "song of the ant tribe",
    ["蚁民"] = "ants-like people",
    ["蚁溃鼠骇"] = "panic-stricken",
    ["蚁狮"] = "antlion",
    ["蚁王"] = "ant king",
    ["蚁甲"] = "ant beetle",
    ["蚁穴"] = "ant nest",
    ["蚁穴溃堤"] = "ant nest collapses dam",
    ["蚁穴自封"] = "self-sealed ant nest",
    ["蚁群"] = "ant colony",
    ["蚁群算法"] = "ant colony algorithm",
    ["蚁萃螽集"] = "swarm",
    ["蚁蚕"] = "silkworm",
    ["蚁走感"] = "formication",
    ["蚁酒"] = "ant wine",
    ["蚁酸"] = "formic acid",
    ["蚁附蜂屯"] = "swarm like ants",
    ["蚁陈固涩口服液"] = "yichen guse oral liquid",
    ["蚁鼻之缺"] = "tiny flaw",
    ["蚁鼻币"] = "ant nose coin",
    ["蚁鼻钱"] = "ant nose coin",
}

return M
