local M = {}

M.mapping = {
    ["裴佳欣"] = "pei jiaxin",
    ["裴元庆"] = "pei yuanqing",
    ["裴元绍"] = "pei yuanshao",
    ["裴南苇"] = "pei nanwei",
    ["裴多菲"] = "petőfi",
    ["裴如海"] = "peiru hai",
    ["裴姓"] = "surname pei",
    ["裴婷婷"] = "peitingting",
    ["裴家"] = "pei family",
    ["裴家埪村"] = "peijia kang village",
    ["裴家官庄"] = "peijia guanzhuang",
    ["裴家桥"] = "peijia bridge",
    ["裴家湾"] = "peijia bay",
    ["裴岭村"] = "peiling village",
    ["裴庄乡"] = "peizhuang township",
    ["裴庆华"] = "pei qinghua",
    ["裴庆虎"] = "pei qinghu",
    ["裴应章"] = "pei yingzhang",
    ["裴度"] = "pei du",
    ["裴怀亮"] = "pei huailiang",
    ["裴恩才"] = "pei encai",
    ["裴文中"] = "peiwenzhong",
    ["裴斗娜"] = "bae doona",
    ["裴斯泰洛齐"] = "pestalozzi",
    ["裴昌会"] = "pei changhui",
    ["裴景福"] = "pei jingfu",
    ["裴村村委会"] = "peicun village committee",
    ["裴松之"] = "peisong zhi",
    ["裴氏"] = "peishi",
    ["裴涩琪"] = "bae seul-ki",
    ["裴王建"] = "peiwangjian",
    ["裴琳"] = "pei lin",
    ["裴秀"] = "pei xiu",
    ["裴绪"] = "pei xu",
    ["裴行俭"] = "pei xingjian",
    ["裴远颖"] = "pei yuanying",
    ["裴连奴"] = "pei liannu",
    ["裴金佳"] = "pei jinjia",
    ["裴钰"] = "pei yu",
}

return M
