local M = {}

M.mapping = {
    ["趁乱"] = "take advantage of the chaos",
    ["趁人"] = "take advantage",
    ["趁人不备"] = "catch off guard",
    ["趁人之危"] = "exploit others",
    ["趁他"] = "take him",
    ["趁你"] = "take advantage of you",
    ["趁便"] = "at one's convenience",
    ["趁势"] = "seize the opportunity",
    ["趁势落篷"] = "strike while the iron is hot",
    ["趁圩"] = "visit market",
    ["趁墒"] = "take advantage of soil moisture",
    ["趁她"] = "take her",
    ["趁它"] = "take it",
    ["趁我"] = "take me",
    ["趁手"] = "handy",
    ["趁早"] = "as early as possible",
    ["趁机"] = "seize the opportunity",
    ["趁此"] = "take this opportunity",
    ["趁此机会"] = "seize this opportunity",
    ["趁没人"] = "while no one is around",
    ["趁火打劫"] = "loot a burning house",
    ["趁火打劫之计"] = "strategy of looting a burning house",
    ["趁火打劫计"] = "loot a burning house strategy",
    ["趁火抢劫"] = "loot a burning house",
    ["趁热"] = "while hot",
    ["趁热打铁"] = "strike while hot",
    ["趁熟"] = "ripe",
    ["趁现在"] = "seize the moment",
    ["趁着"] = "taking advantage of",
    ["趁空"] = "seize the opportunity",
    ["趁虚"] = "take advantage",
    ["趁虚而入"] = "take advantage",
    ["趁这个"] = "take this",
    ["趁钱"] = "make money",
    ["趁风使柁"] = "trim one's sails",
    ["趁风使舵"] = "trim one's sails",
    ["趁风使船"] = "sail with the wind",
    ["趁风转帆"] = "trim one's sails",
    ["趁风转篷"] = "trim one's sails",
}

return M
