local M = {}

M.mapping = {
    ["聪儿"] = "cong'er",
    ["聪喝识"] = "intelligent drinking recognition",
    ["聪悟"] = "intelligent",
    ["聪悟过人"] = "exceptionally intelligent",
    ["聪慧"] = "intelligent",
    ["聪慧过人"] = "exceptionally intelligent",
    ["聪敏"] = "clever",
    ["聪明"] = "smart",
    ["聪明一世"] = "smart for a lifetime",
    ["聪明不是挂在嘴上"] = "smartness is not just talk",
    ["聪明人"] = "smart person",
    ["聪明伶俐"] = "clever and quick-witted",
    ["聪明俊俏"] = "smart and handsome",
    ["聪明出众"] = "exceptionally smart",
    ["聪明勇敢"] = "smart and brave",
    ["聪明反被聪明误"] = "cleverness may overreach itself",
    ["聪明可爱"] = "smart and cute",
    ["聪明地"] = "smartly",
    ["聪明女人"] = "smart woman",
    ["聪明家"] = "clever person",
    ["聪明才智"] = "intelligence and wisdom",
    ["聪明智慧"] = "wisdom and intelligence",
    ["聪明智能"] = "intelligence and wisdom",
    ["聪明机灵"] = "clever and quick-witted",
    ["聪明正直"] = "wise and upright",
    ["聪明的"] = "smart",
    ["聪明的召唤兽"] = "smart summon",
    ["聪明盖世"] = "unparalleled intelligence",
    ["聪明睿哲"] = "wise and philosophical",
    ["聪明睿智"] = "wise and intelligent",
    ["聪明睿达"] = "wise and perceptive",
    ["聪明绝顶"] = "extremely intelligent",
    ["聪明能干"] = "smart and capable",
    ["聪明英毅"] = "smart and heroic",
    ["聪明误"] = "misled by cleverness",
    ["聪明起来"] = "become smart",
    ["聪明过人"] = "exceptionally smart",
    ["聪明透顶"] = "extremely smart",
    ["聪明难"] = "smartness is hard",
    ["聪颖"] = "intelligent",
    ["聪颖过人"] = "exceptionally intelligent",
}

return M
