local M = {}

M.mapping = {
    ["蹲一蹲"] = "squat once",
    ["蹲下"] = "squat down",
    ["蹲下去"] = "squat down",
    ["蹲下来"] = "squat down",
    ["蹲不下来"] = "cannot squat",
    ["蹲不住"] = "cannot hold squat",
    ["蹲了"] = "squatted",
    ["蹲了下去"] = "squatted down",
    ["蹲了蹲"] = "squatted a bit",
    ["蹲伏"] = "crouch",
    ["蹲便器"] = "squat toilet",
    ["蹲到"] = "squat until",
    ["蹲厕"] = "squat toilet",
    ["蹲厕所"] = "use toilet",
    ["蹲在"] = "squat at",
    ["蹲地"] = "squat on ground",
    ["蹲地上"] = "squat on ground",
    ["蹲坐"] = "squat",
    ["蹲坐在"] = "squatting on",
    ["蹲坑"] = "squat toilet",
    ["蹲大牢"] = "in prison",
    ["蹲好了"] = "squat ready",
    ["蹲妹"] = "squatting girl",
    ["蹲守"] = "stakeout",
    ["蹲得比"] = "squat lower than",
    ["蹲点"] = "spot check",
    ["蹲班"] = "repeat grade",
    ["蹲班房"] = "in jail",
    ["蹲监狱"] = "serve time",
    ["蹲着"] = "squatting",
    ["蹲着呢"] = "squatting",
    ["蹲腿"] = "squat leg",
    ["蹲膘"] = "fatten up",
    ["蹲苗"] = "seedling squatting",
    ["蹲起"] = "squat and rise",
    ["蹲跳"] = "squat jump",
    ["蹲蹲"] = "squat",
    ["蹲蹲苗"] = "seedling squatting",
    ["蹲过"] = "have squatted",
    ["蹲防"] = "crouch defense",
    ["蹲马步"] = "horse stance",
}

return M
