local M = {}

M.mapping = {
    ["肛乳头炎"] = "anal papillitis",
    ["肛乳头肥大"] = "anal papilla hypertrophy",
    ["肛交"] = "anal sex",
    ["肛周"] = "perianal",
    ["肛周炎"] = "perianal inflammation",
    ["肛周脓肿"] = "perianal abscess",
    ["肛塞"] = "anal plug",
    ["肛康穆库利片"] = "gangkang mukuli tablet",
    ["肛拭子"] = "anal swab",
    ["肛提肌"] = "levator ani muscle",
    ["肛瘘"] = "anal fistula",
    ["肛管"] = "anal canal",
    ["肛管损伤"] = "anal canal injury",
    ["肛管炎"] = "anal canal inflammation",
    ["肛管癌"] = "anal canal cancer",
    ["肛管直肠癌"] = "anal canal rectal cancer",
    ["肛肠"] = "anorectal",
    ["肛肠医院"] = "anorectal hospital",
    ["肛肠病"] = "anorectal disease",
    ["肛肠科"] = "anorectal department",
    ["肛膜"] = "anal membrane",
    ["肛表"] = "anal thermometer",
    ["肛裂"] = "anal fissure",
    ["肛褶蛙肽"] = "anal fold peptide",
    ["肛道"] = "anal canal",
    ["肛门"] = "anus",
    ["肛门外括约肌"] = "external anal sphincter",
    ["肛门失禁"] = "anal incontinence",
    ["肛门息肉"] = "anal polyp",
    ["肛门括约肌"] = "anal sphincter",
    ["肛门指检"] = "digital rectal exam",
    ["肛门探针"] = "anal probe",
    ["肛门湿疣"] = "anal warts",
    ["肛门狭窄"] = "anal stenosis",
    ["肛门瘙痒"] = "anal itching",
    ["肛门管"] = "anal tube",
    ["肛门袋"] = "ostomy bag",
    ["肛门镜"] = "anoscope",
    ["肛门镜检查"] = "anoscopy",
    ["肛门闭锁"] = "anal atresia",
    ["肛隐窝炎"] = "anal cryptitis",
    ["肛鳞"] = "anal scales",
}

return M
