local M = {}

M.mapping = {
    ["菌丝"] = "hypha",
    ["菌丝体"] = "mycelium",
    ["菌体"] = "bacterial cell",
    ["菌体抗原"] = "somatic antigen",
    ["菌体蛋白"] = "bacterial protein",
    ["菌体蛋白粉"] = "bacterial protein powder",
    ["菌味鲜"] = "mushroom flavor fresh",
    ["菌子"] = "mushroom",
    ["菌托"] = "volva",
    ["菌柄"] = "stipe",
    ["菌株"] = "bacterial strain",
    ["菌核"] = "sclerotium",
    ["菌根"] = "mycorrhiza",
    ["菌毛"] = "pilus",
    ["菌毛抗原"] = "pilus antigen",
    ["菌毛蛋白"] = "pilin protein",
    ["菌液"] = "bacterial liquid",
    ["菌物"] = "fungi",
    ["菌环"] = "annulus",
    ["菌痢"] = "bacillary dysentery",
    ["菌盖"] = "pileus",
    ["菌种"] = "strain",
    ["菌类"] = "fungi",
    ["菌素"] = "bacteriocin",
    ["菌素类"] = "bacteriocins",
    ["菌群"] = "microbiota",
    ["菌群失调"] = "dysbiosis",
    ["菌肥"] = "bacterial fertilizer",
    ["菌胶团"] = "zoogloea",
    ["菌膜"] = "bacterial film",
    ["菌苔"] = "bacterial lawn",
    ["菌苗"] = "vaccine",
    ["菌菇"] = "mushroom",
    ["菌落"] = "colony",
    ["菌落形成"] = "colony formation",
    ["菌落形成单位"] = "colony forming unit",
    ["菌落总数"] = "total colony count",
    ["菌落计数器"] = "colony counter",
    ["菌边村"] = "junbian village",
}

return M
