local M = {}

M.mapping = {
    ["脊中穴"] = "jizhong acupoint",
    ["脊柱"] = "spine",
    ["脊柱侧弯"] = "scoliosis",
    ["脊柱侧弯矫正钳"] = "scoliosis correction forceps",
    ["脊柱内固定器材"] = "spinal internal fixation devices",
    ["脊柱变形"] = "spinal deformity",
    ["脊柱后凸"] = "kyphosis",
    ["脊柱炎"] = "spondylitis",
    ["脊梁"] = "backbone",
    ["脊梁骨"] = "backbone",
    ["脊椎"] = "vertebra",
    ["脊椎动物"] = "vertebrate",
    ["脊椎炎"] = "spondylitis",
    ["脊椎病"] = "spinal disease",
    ["脊椎神经"] = "spinal nerve",
    ["脊椎骨"] = "vertebra",
    ["脊檩"] = "ridge purlin",
    ["脊液"] = "spinal fluid",
    ["脊瓦"] = "tile factory",
    ["脊盾棘胫长蝽"] = "spined shield bug",
    ["脊神经"] = "spinal nerve",
    ["脊索"] = "notochord",
    ["脊索动物"] = "chordate",
    ["脊索动物门"] = "chordata",
    ["脊索瘤"] = "chordoma",
    ["脊纹澳虎"] = "ridge-patterned australian tiger",
    ["脊线"] = "ridge line",
    ["脊背"] = "back",
    ["脊骨"] = "spine",
    ["脊骨堡"] = "spine castle",
    ["脊髓"] = "spinal cord",
    ["脊髓动物"] = "vertebrate",
    ["脊髓损伤"] = "spinal cord injury",
    ["脊髓灰质炎"] = "polio",
    ["脊髓灰质炎病毒"] = "poliovirus",
    ["脊髓炎"] = "myelitis",
    ["脊鳞"] = "dorsal scale",
}

return M
