local M = {}

M.mapping = {
    ["腌一腌"] = "marinate",
    ["腌了腌"] = "pickled",
    ["腌制"] = "pickle",
    ["腌制品"] = "preserved food",
    ["腌咸肉"] = "salted meat",
    ["腌成"] = "glorify",
    ["腌榨菜"] = "pickled mustard",
    ["腌水芥皮"] = "pickled mustard skin",
    ["腌泡"] = "marinate",
    ["腌泡汁"] = "marinade",
    ["腌海雀"] = "fermented seabird",
    ["腌渍"] = "pickle",
    ["腌渍品"] = "pickled products",
    ["腌牛脚筋"] = "pickled beef tendon",
    ["腌猪肉"] = "cured pork",
    ["腌笃鲜"] = "yan du xian",
    ["腌肉"] = "bacon",
    ["腌腊"] = "preserved",
    ["腌腊八蒜"] = "preserved garlic",
    ["腌腊肉"] = "preserved meat",
    ["腌臜"] = "filthy",
    ["腌苤蓝丝儿"] = "pickled kohlrabi shreds",
    ["腌菜"] = "pickles",
    ["腌菜豆腐"] = "pickled tofu",
    ["腌萝卜干"] = "pickled radish",
    ["腌货"] = "salted goods",
    ["腌过"] = "pickled",
    ["腌酸菜"] = "pickled cabbage",
    ["腌酸鱼"] = "pickled sour fish",
    ["腌鱼"] = "salted fish",
    ["腌鱼肉"] = "salted fish",
    ["腌鲜鳜鱼"] = "salted mandarin fish",
    ["腌黄瓜"] = "pickled cucumber",
}

return M
