local M = {}

M.mapping = {
    ["贱不贱"] = "cheap or not",
    ["贱不贱呀"] = "cheap or not",
    ["贱买贵卖"] = "buy cheap sell dear",
    ["贱人"] = "bitch",
    ["贱价"] = "cheap price",
    ["贱价出售"] = "bargain sale",
    ["贱入贵出"] = "buy low, sell high",
    ["贱养"] = "raise poorly",
    ["贱内"] = "my wife",
    ["贱卖"] = "sell cheap",
    ["贱命"] = "cheap life",
    ["贱啊"] = "cheap ah",
    ["贱女"] = "cheap woman",
    ["贱女人"] = "cheap woman",
    ["贱奴"] = "cheap slave",
    ["贱妾"] = "humble concubine",
    ["贱妾何聊生"] = "why should humble concubine live",
    ["贱妾留空房"] = "humble concubine in empty room",
    ["贱妾茕茕守空房"] = "humble concubine lonely in empty room",
    ["贱婢"] = "lowly maid",
    ["贱样"] = "despicable look",
    ["贱民"] = "untouchable",
    ["贱物"] = "cheap goods",
    ["贱男"] = "cheap man",
    ["贱畜"] = "lowly animal",
    ["贱的"] = "cheap",
    ["贱相"] = "cheap look",
    ["贱种"] = "low breed",
    ["贱籍"] = "lowly status",
    ["贱货"] = "bitch",
    ["贱贱"] = "cheap",
    ["贱贱的"] = "cheap",
    ["贱金属"] = "base metal",
    ["贱骨头"] = "cheap bone",
}

return M
