local M = {}

M.mapping = {
    ["蚌埠"] = "bengbu",
    ["蚌埠人"] = "bengbu people",
    ["蚌埠分行"] = "bengbu branch",
    ["蚌埠医学院"] = "bengbu medical college",
    ["蚌埠南"] = "bengbu south",
    ["蚌埠地区"] = "bengbu area",
    ["蚌埠坦克学院"] = "bengbu tank academy",
    ["蚌埠学院"] = "bengbu university",
    ["蚌埠市"] = "bengbu city",
    ["蚌埠市人民政府"] = "bengbu municipal government",
    ["蚌埠市公安局"] = "bengbu public security bureau",
    ["蚌埠市委"] = "bengbu municipal committee",
    ["蚌埠市怀远县"] = "huaiyuan county bengbu",
    ["蚌埠市政府"] = "bengbu city government",
    ["蚌埠市淮上区"] = "huaishang district bengbu",
    ["蚌埠市禹会区"] = "yuhui district bengbu",
    ["蚌埠市蚌山区"] = "bengshan district bengbu",
    ["蚌埠市龙子湖区"] = "longzihu district bengbu",
    ["蚌埠怀远"] = "bengbu huaiyuan",
    ["蚌埠新闻网"] = "bengbu news",
    ["蚌埠日报"] = "bengbu daily",
    ["蚌埠道"] = "bengbu road",
    ["蚌壳"] = "clam shell",
    ["蚌山区"] = "bangshan district",
    ["蚌珠"] = "pearl from mussel",
    ["蚌病成珠"] = "pearl from oyster's ailment",
    ["蚌病生珠"] = "pearl from oyster's ailment",
    ["蚌目"] = "unionoida",
    ["蚌类"] = "clams",
    ["蚌肉"] = "clam meat",
    ["蚌谷乡"] = "bangu township",
    ["蚌鹬争衡"] = "clam and snipe struggle",
    ["蚌鹬相持"] = "clam and snipe locked in fight",
}

return M
