local M = {}

M.mapping = {
    ["译一译"] = "translate",
    ["译不出"] = "untranslatable",
    ["译不出来"] = "untranslatable",
    ["译丛"] = "translation series",
    ["译为"] = "translated",
    ["译介"] = "translation",
    ["译作"] = "translation",
    ["译典通"] = "translation dictionary",
    ["译制"] = "dubbing",
    ["译制片"] = "dubbed film",
    ["译名"] = "translated name",
    ["译员"] = "interpreter",
    ["译成"] = "translated",
    ["译成密码"] = "encrypt",
    ["译成电码"] = "encoded",
    ["译文"] = "translation",
    ["译本"] = "translation",
    ["译林"] = "translation forest",
    ["译林出版社"] = "yilin publishing house",
    ["译注"] = "translation notes",
    ["译电"] = "decode",
    ["译电员"] = "code clerk",
    ["译码"] = "decode",
    ["译码器"] = "decoder",
    ["译稿"] = "translation draft",
    ["译笔"] = "translation style",
    ["译者"] = "translator",
    ["译者注"] = "translator's note",
    ["译自"] = "translated from",
    ["译著"] = "translation work",
    ["译谱"] = "transcribe",
    ["译述"] = "translation",
    ["译音"] = "transliteration",
}

return M
