local M = {}

M.mapping = {
    ["耶克"] = "yake",
    ["耶克斯"] = "yakes",
    ["耶利内克"] = "jelinek",
    ["耶利哥蝎"] = "jericho scorpion",
    ["耶利米书"] = "book of jeremiah",
    ["耶加雪菲"] = "yirgacheffe",
    ["耶和华"] = "yahweh",
    ["耶娘妻子走相送"] = "parents see off",
    ["耶尼尔"] = "yenir",
    ["耶弗他"] = "jephthah",
    ["耶律"] = "yelu",
    ["耶律大石"] = "yelu dashi",
    ["耶律延禧"] = "yelu yanxi",
    ["耶律德光"] = "yelu de guang",
    ["耶律楚材"] = "yelu chucai",
    ["耶律洪基"] = "yelu hongji",
    ["耶律贤"] = "yelu xian",
    ["耶律阮"] = "yelu ruan",
    ["耶律阿保机"] = "yelu abaoji",
    ["耶律隆绪"] = "yelu longxu",
    ["耶斯莫拉"] = "yes mola",
    ["耶氏圆鲀"] = "yesso puffer",
    ["耶氏背斜眼鳚"] = "y-beaked blenny",
    ["耶环蛱蝶"] = "yehuan butterfly",
    ["耶稣"] = "jesus",
    ["耶稣基督"] = "jesus christ",
    ["耶稣教"] = "protestantism",
    ["耶米熊"] = "yemi bear",
    ["耶罗岛大蜥蜴"] = "hierro giant lizard",
    ["耶茨"] = "wild hedgehog",
    ["耶诞树珊瑚"] = "christmas tree coral",
    ["耶路撒冷"] = "jerusalem",
    ["耶路撒冷地"] = "jerusalem land",
    ["耶鲁"] = "yale",
    ["耶鲁大学"] = "yale university",
}

return M
