local M = {}

M.mapping = {
    ["裹上"] = "wrap",
    ["裹不住"] = "cannot wrap",
    ["裹严实"] = "wrap tightly",
    ["裹乱"] = "cause trouble",
    ["裹了"] = "wrapped",
    ["裹住"] = "wrapped",
    ["裹在"] = "wrapped in",
    ["裹好"] = "wrap well",
    ["裹尸"] = "shroud",
    ["裹尸布"] = "shroud",
    ["裹布"] = "wrapping cloth",
    ["裹得"] = "wrapped",
    ["裹得严严实实"] = "tightly wrapped",
    ["裹得像"] = "wrapped like",
    ["裹成球"] = "wrapped into a ball",
    ["裹扎"] = "wrapping",
    ["裹挟"] = "coerce",
    ["裹挟下"] = "under coercion",
    ["裹挟着"] = "coercing",
    ["裹满"] = "covered with",
    ["裹烧茭白"] = "wrapped roasted water bamboo",
    ["裹着"] = "wrapped",
    ["裹着被子"] = "wrapped in quilt",
    ["裹粉"] = "coated powder",
    ["裹粮坐甲"] = "carry provisions and sit in armor",
    ["裹紧"] = "wrap tightly",
    ["裹胁"] = "coerce",
    ["裹胸"] = "wrap chest",
    ["裹脚"] = "foot binding",
    ["裹脚布"] = "footbinding cloth",
    ["裹腿"] = "leg wrappings",
    ["裹蒸粽"] = "wrapped rice dumpling",
    ["裹起来"] = "wrapped up",
    ["裹足"] = "foot binding",
    ["裹足不前"] = "foot binding not moving forward",
    ["裹进"] = "wrap into",
    ["裹饭而往食之"] = "wrap rice and go eat",
}

return M
