local M = {}

M.mapping = {
    ["诈伤"] = "feign injury",
    ["诈伪"] = "fraud",
    ["诈保"] = "insurance fraud",
    ["诈取"] = "defraud",
    ["诈取豪夺"] = "extortion",
    ["诈和"] = "false win",
    ["诈哑佯聋"] = "pretend deaf",
    ["诈唬"] = "bluff",
    ["诈尸"] = "corpse fraud",
    ["诈捐"] = "donation fraud",
    ["诈术"] = "deception",
    ["诈欺和解罪"] = "fraudulent reconciliation",
    ["诈欺游戏"] = "liar game",
    ["诈死"] = "feign death",
    ["诈痴不颠"] = "feign madness",
    ["诈称"] = "false claim",
    ["诈语"] = "deceit",
    ["诈败"] = "feigned defeat",
    ["诈跳岩鳚"] = "deceptive blenny",
    ["诈金花"] = "bluff poker",
    ["诈降"] = "feign surrender",
    ["诈骗"] = "fraud",
    ["诈骗他人钱财"] = "defraud others' money",
    ["诈骗伎俩"] = "fraud tricks",
    ["诈骗团伙"] = "fraud gang",
    ["诈骗案"] = "fraud case",
    ["诈骗案件"] = "fraud cases",
    ["诈骗犯"] = "fraudster",
    ["诈骗犯罪研究"] = "fraud crime research",
    ["诈骗短信"] = "scam message",
    ["诈骗罪"] = "fraud crime",
    ["诈骗罪与金融诈骗罪研究"] = "research on fraud and financial fraud",
    ["诈骗者"] = "scammer",
    ["诈骗行为"] = "fraudulent behavior",
    ["诈骗钱财"] = "defraud money",
    ["诈骗集团"] = "fraud ring",
}

return M
