local M = {}

M.mapping = {
    ["蠢了"] = "stupid",
    ["蠢事"] = "stupid thing",
    ["蠢人"] = "fool",
    ["蠢动"] = "stir",
    ["蠢头蠢脑"] = "stupid head stupid brain",
    ["蠢如鹿豕"] = "stupid as deer pig",
    ["蠢屄"] = "stupid cunt",
    ["蠢得像"] = "stupid as",
    ["蠢才"] = "idiot",
    ["蠢拙"] = "clumsy and stupid",
    ["蠢材"] = "idiot",
    ["蠢然思动"] = "stupidly thinking of moving",
    ["蠢爸爸"] = "stupid dad",
    ["蠢物"] = "stupid thing",
    ["蠢狗"] = "stupid dog",
    ["蠢猪"] = "stupid pig",
    ["蠢猫"] = "stupid cat",
    ["蠢的"] = "stupid",
    ["蠢笨"] = "stupid",
    ["蠢笨的"] = "stupid",
    ["蠢若木鸡"] = "stupid as wooden chicken",
    ["蠢萌"] = "cute and silly",
    ["蠢蛇"] = "stupid snake",
    ["蠢蛋"] = "idiot",
    ["蠢蠢"] = "stupid",
    ["蠢蠢思动"] = "stupidly think of moving",
    ["蠢蠢欲动"] = "ready to move",
    ["蠢话"] = "stupid talk",
    ["蠢货"] = "idiot",
    ["蠢迪检押"] = "foolish and restrained",
    ["蠢逼"] = "stupid cunt",
    ["蠢驴"] = "idiot",
    ["蠢鸟"] = "stupid bird",
}

return M
