local M = {}

M.mapping = {
    ["荧光"] = "fluorescence",
    ["荧光乌贼"] = "firefly squid",
    ["荧光假单胞菌"] = "pseudomonas fluorescens",
    ["荧光免疫分析仪"] = "fluoroimmunoassay analyzer",
    ["荧光分光光度计"] = "spectrofluorometer",
    ["荧光坠子"] = "fluorescent pendant",
    ["荧光增白剂"] = "optical brightener",
    ["荧光小褐鳕"] = "hoki",
    ["荧光屏"] = "screen",
    ["荧光性"] = "fluorescence",
    ["荧光探针"] = "fluorescent probe",
    ["荧光摄影装置"] = "fluorescence photography device",
    ["荧光显微镜"] = "fluorescence microscope",
    ["荧光染料"] = "fluorescent dye",
    ["荧光棒"] = "glow stick",
    ["荧光油墨"] = "fluorescent ink",
    ["荧光法"] = "fluorometry",
    ["荧光海"] = "bioluminescent bay",
    ["荧光灯"] = "fluorescent lamp",
    ["荧光猪"] = "glowing pig",
    ["荧光笔"] = "highlighter",
    ["荧光粉"] = "phosphor powder",
    ["荧光素"] = "fluorescein",
    ["荧光素钠"] = "sodium fluorescein",
    ["荧光蝎"] = "fluorescent scorpion",
    ["荧光裳凤蝶"] = "fluorescent butterfly",
    ["荧光闪烁"] = "lumos",
    ["荧屏"] = "screen",
    ["荧屏上"] = "on screen",
    ["荧幕"] = "screen",
    ["荧幕上"] = "on screen",
    ["荧惑"] = "mars",
    ["荧烛"] = "candlelight",
    ["荧烛末光"] = "faint light",
    ["荧荧"] = "flickering",
    ["荧闪粉蝶"] = "glitter butterfly",
    ["荧鳞五花琉金"] = "calico ryukin",
    ["荧鳞蝶尾鱼"] = "butterfly tail fish",
}

return M
