local M = {}

M.mapping = {
    ["辨不出"] = "cannot discern",
    ["辨不清"] = "unclear",
    ["辨伪"] = "discern forgery",
    ["辨出"] = "identify",
    ["辨别"] = "distinguish",
    ["辨别不出来"] = "cannot distinguish",
    ["辨别不清"] = "unclear distinction",
    ["辨别出来"] = "identify out",
    ["辨别力"] = "discrimination",
    ["辨别方向"] = "orient",
    ["辨别是非"] = "discern right",
    ["辨别真假"] = "tell real",
    ["辨如悬河"] = "eloquent debate",
    ["辨才无碍"] = "unimpeded eloquence",
    ["辨敌术"] = "enemy identification",
    ["辨日炎凉"] = "debate on the sun's heat",
    ["辨明"] = "clarify",
    ["辨明是非"] = "distinguish right from wrong",
    ["辨材须待七年期"] = "judge material in seven years",
    ["辨析"] = "analysis",
    ["辨析题"] = "analysis question",
    ["辨正"] = "correct",
    ["辨清"] = "clarify",
    ["辨物居方"] = "discern things and settle accordingly",
    ["辨络脉"] = "identify collaterals",
    ["辨色"] = "color discrimination",
    ["辨若悬河"] = "eloquent as a hanging river",
    ["辨认"] = "identify",
    ["辨认出"] = "recognize",
    ["辨认出来"] = "make out",
    ["辨认着"] = "identifying",
    ["辨证"] = "differentiate",
    ["辨证施治"] = "treatment based on differentiation",
    ["辨证论治"] = "treatment based on differentiation",
    ["辨识"] = "recognition",
    ["辨读"] = "interpret",
    ["辨音"] = "sound discrimination",
}

return M
