local M = {}

M.mapping = {
    ["谦以下士"] = "humble to scholars",
    ["谦光自抑"] = "modest restraint",
    ["谦冲"] = "modest and unassuming",
    ["谦卑"] = "humble",
    ["谦卑是荣誉的基础"] = "humility is the foundation of honor",
    ["谦卦"] = "qian gua",
    ["谦受益"] = "modesty brings benefit",
    ["谦和"] = "modest",
    ["谦大爷"] = "qian daye",
    ["谦妃"] = "consort qian",
    ["谦恭"] = "humble",
    ["谦恭地"] = "humbly",
    ["谦恭有礼"] = "polite and respectful",
    ["谦恭虚己"] = "modest and humble",
    ["谦慎"] = "modest",
    ["谦抑原则"] = "leniency principle",
    ["谦抑性原则"] = "principle of leniency",
    ["谦称"] = "humble term",
    ["谦虚"] = "modest",
    ["谦虚敬慎"] = "modest and respectful",
    ["谦虚有礼"] = "modest and polite",
    ["谦虚谨慎"] = "modest and prudent",
    ["谦让"] = "modesty",
    ["谦让未遑"] = "too modest to accept",
    ["谦词"] = "humble words",
    ["谦诚"] = "humble and sincere",
    ["谦谦"] = "modest",
    ["谦谦下士"] = "humble scholar",
    ["谦谦君子"] = "modest gentleman",
    ["谦躬下士"] = "humble and courteous",
    ["谦辞"] = "humble speech",
    ["谦退"] = "modest retreat",
    ["谦逊"] = "humble",
    ["谦逊下士"] = "humble and respectful",
    ["谦逊地"] = "humbly",
    ["谦逊有礼"] = "humble and polite",
    ["谦逊的"] = "humble",
    ["谦顺"] = "humble and obedient",
}

return M
