local M = {}

M.mapping = {
    ["舔一舔"] = "give a lick",
    ["舔不着"] = "cannot lick",
    ["舔了"] = "licked",
    ["舔了舔"] = "licked lick",
    ["舔他"] = "lick him",
    ["舔你"] = "lick you",
    ["舔到"] = "lick to",
    ["舔去"] = "lick off",
    ["舔吃"] = "licking",
    ["舔吧"] = "lick bar",
    ["舔啦"] = "licked",
    ["舔她"] = "lick her",
    ["舔屁股"] = "bootlicking",
    ["舔屏"] = "screen licking",
    ["舔干净"] = "lick clean",
    ["舔弄"] = "licking play",
    ["舔得"] = "licked",
    ["舔掉"] = "lick off",
    ["舔毛"] = "grooming",
    ["舔狗"] = "simp",
    ["舔着"] = "licking",
    ["舔碗"] = "lick bowl",
    ["舔笔"] = "lick pen",
    ["舔耳"] = "ear licking",
    ["舔脚"] = "foot licking",
    ["舔舌抹嘴"] = "lick lips",
    ["舔舐"] = "lick",
    ["舔舐伤口"] = "lick wounds",
    ["舔舔"] = "lick",
    ["舔过"] = "licked",
    ["舔逼"] = "lick pussy",
    ["舔遍"] = "lick everywhere",
    ["舔阴"] = "cunnilingus",
    ["舔食"] = "lick food",
}

return M
