local M = {}

M.mapping = {
    ["胰十二指肠切除术"] = "pancreaticoduodenectomy",
    ["胰头癌"] = "pancreatic head cancer",
    ["胰子"] = "soap",
    ["胰岛"] = "pancreatic islet",
    ["胰岛移植"] = "islet transplantation",
    ["胰岛素"] = "insulin",
    ["胰岛素抗体"] = "insulin antibody",
    ["胰岛素昏迷"] = "insulin coma",
    ["胰岛素样生长因子"] = "insulin-like growth factor",
    ["胰岛素注射液"] = "insulin injection",
    ["胰岛素泵"] = "insulin pump",
    ["胰岛素瘤"] = "insulinoma",
    ["胰岛素释放试验"] = "insulin release test",
    ["胰岛细胞瘤"] = "islet cell tumor",
    ["胰液"] = "pancreatic juice",
    ["胰淀粉酶"] = "pancreatic amylase",
    ["胰激肽原酶"] = "kallidinogenase",
    ["胰激肽原酶肠溶片"] = "kallidinogenase enteric-coated tablet",
    ["胰瘘"] = "pancreatic fistula",
    ["胰癌"] = "pancreatic cancer",
    ["胰结石"] = "pancreatic stone",
    ["胰胀"] = "pancreatic distension",
    ["胰脂酶"] = "pancreatic lipase",
    ["胰脏"] = "pancreas",
    ["胰腺"] = "pancreas",
    ["胰腺囊肿"] = "pancreatic cyst",
    ["胰腺损伤"] = "pancreatic injury",
    ["胰腺炎"] = "pancreatitis",
    ["胰腺瘤"] = "pancreatic tumor",
    ["胰腺癌"] = "pancreatic cancer",
    ["胰腺破裂"] = "pancreatic rupture",
    ["胰腺移植"] = "pancreas transplant",
    ["胰腺肿瘤"] = "pancreatic tumor",
    ["胰腺脓肿"] = "pancreatic abscess",
    ["胰蛋白酶"] = "trypsin",
    ["胰蛋白酶原"] = "trypsinogen",
    ["胰酶"] = "pancreatin",
    ["胰酶肠溶片"] = "pancreatin enteric-coated tablets",
    ["胰酶肠溶胶囊"] = "pancreatin enteric-coated capsules",
    ["胰高糖素"] = "glucagon",
}

return M
