local M = {}

M.mapping = {
    ["膝上"] = "on the lap",
    ["膝上王文度"] = "wang wendu on the lap",
    ["膝下"] = "under the knee",
    ["膝下有黄金"] = "gold under knee",
    ["膝下荒凉"] = "childless",
    ["膝交叉韧带"] = "cruciate ligament",
    ["膝关"] = "knee joint",
    ["膝关节"] = "knee joint",
    ["膝关节息肉钳"] = "knee polyp forceps",
    ["膝关节损伤"] = "knee joint injury",
    ["膝关节病"] = "knee joint disease",
    ["膝关节结核"] = "knee joint tuberculosis",
    ["膝关节置换术"] = "knee replacement",
    ["膝关节脱位"] = "knee dislocation",
    ["膝关节韧带手术剪"] = "knee ligament scissors",
    ["膝内翻"] = "genu varum",
    ["膝卷叶象"] = "leaf-rolling weevil",
    ["膝外翻"] = "genu valgum",
    ["膝头"] = "knee",
    ["膝形涡蛛"] = "knee-shaped whirl spider",
    ["膝曲眼虫"] = "euglena geniculata",
    ["膝枕"] = "lap pillow",
    ["膝沟藻"] = "gonyaulax",
    ["膝盖"] = "knee",
    ["膝盖骨"] = "kneecap",
    ["膝眼"] = "knee hollow",
    ["膝眼穴"] = "xiyan acupoint",
    ["膝离断假肢"] = "knee disarticulation prosthesis",
    ["膝行"] = "crawl on knees",
    ["膝行蒲伏"] = "crawl on knees and prostrate",
    ["膝语蛇行"] = "kneeling and crawling",
    ["膝超伸"] = "knee hyperextension",
    ["膝跳反应"] = "knee-jerk reflex",
    ["膝过伸"] = "knee hyperextension",
    ["膝部"] = "knee",
    ["膝阳关"] = "xiyang pass",
    ["膝龙"] = "knee dragon",
}

return M
