local M = {}

M.mapping = {
    ["闸东"] = "zha dong",
    ["闸刀"] = "knife switch",
    ["闸刀开关"] = "knife switch",
    ["闸前街"] = "zhaqian street",
    ["闸北"] = "zhabei",
    ["闸北公园"] = "zhabei park",
    ["闸北区"] = "zhabei district",
    ["闸北水厂"] = "zhabei waterworks",
    ["闸北电厂"] = "zhabei power plant",
    ["闸口"] = "sluice",
    ["闸口街道"] = "sluice street",
    ["闸坝"] = "sluice dam",
    ["闸坡束腰蟹"] = "somanniathelphusa zhanpo",
    ["闸头"] = "lock head",
    ["闸弄口"] = "zhanongkou",
    ["闸弄口站"] = "zhanongkou station",
    ["闸机"] = "gate machine",
    ["闸杆"] = "gate rod",
    ["闸板"] = "sluice gate",
    ["闸板阀"] = "gate valve",
    ["闸桥"] = "zhaqiao",
    ["闸槛"] = "sill",
    ["闸殷路"] = "zhayin road",
    ["闸河"] = "zhahe river",
    ["闸流管"] = "thyratron",
    ["闸瓦"] = "brake shoe",
    ["闸皮"] = "brake shoe",
    ["闸盒"] = "fuse box",
    ["闸站"] = "lock station",
    ["闸线"] = "brake cable",
    ["闸西"] = "zha xi",
    ["闸门"] = "sluice gate",
    ["闸阀"] = "gate valve",
}

return M
