local M = {}

M.mapping = {
    ["雍丘"] = "yongqiu",
    ["雍也可使南面"] = "yong also south",
    ["雍南"] = "yongnan",
    ["雍县"] = "yong county",
    ["雍和"] = "harmony",
    ["雍和宫"] = "yonghegong",
    ["雍和宫桥"] = "yonghegong bridge",
    ["雍和宫桥东"] = "bridge east",
    ["雍和宫桥北"] = "bridge north",
    ["雍和宫站"] = "yonghegong station",
    ["雍奴"] = "yongnu",
    ["雍姓"] = "yong surname",
    ["雍家村"] = "yongjia village",
    ["雍容"] = "dignified",
    ["雍容不迫"] = "graceful",
    ["雍容典雅"] = "refined",
    ["雍容华贵"] = "luxurious",
    ["雍容大度"] = "magnanimous",
    ["雍容大雅"] = "elegant",
    ["雍州"] = "yongzhou",
    ["雍忠玮"] = "yong zhongwei",
    ["雍景台"] = "regal terrace",
    ["雍景轩"] = "regal court",
    ["雍正"] = "yongzheng",
    ["雍正帝"] = "emperor yongzheng",
    ["雍正年间"] = "yongzheng era",
    ["雍正皇帝"] = "emperor yongzheng",
    ["雍王府"] = "prince yong's mansion",
    ["雍睦"] = "harmony",
    ["雍荣尔雅"] = "cultured",
    ["雍荣闲雅"] = "leisurely",
    ["雍荣雅步"] = "stately",
    ["雍门刎首"] = "yongmen beheads",
}

return M
