local M = {}

M.mapping = {
    ["邱会作"] = "hui-zuo qiu",
    ["邱先生"] = "mr. qiu",
    ["邱关源"] = "qiu guanyuan",
    ["邱北"] = "qiubei",
    ["邱北县"] = "qiubei county",
    ["邱县"] = "qiu county",
    ["邱国栋"] = "qiu guodong",
    ["邱城镇"] = "qiucheng town",
    ["邱太三"] = "chiu tai-san",
    ["邱姓"] = "qiu surname",
    ["邱娥国"] = "qiu eguo",
    ["邱家庄"] = "qiujiazhuang",
    ["邱家店"] = "qiujiadian",
    ["邱家湾"] = "qiuwan",
    ["邱家祠"] = "qiu ancestral hall",
    ["邱家胡同"] = "qiu hutong",
    ["邱家院子"] = "qiu courtyard",
    ["邱少云"] = "qiu shaoyun",
    ["邱屋"] = "qiu house",
    ["邱岳峰"] = "qiu yuefeng",
    ["邱峻"] = "qiu jun",
    ["邱建辉"] = "qiu jianhui",
    ["邱心志"] = "qiu xinzhi",
    ["邱意浓"] = "qiu yi nong",
    ["邱文华"] = "qiu wenhua",
    ["邱昭良"] = "qiu zhaoliang",
    ["邱晓华"] = "qiu xiaohua",
    ["邱村村"] = "qiucun village",
    ["邱某"] = "qiu mou",
    ["邱氏列齿蛇鳗"] = "qiu's snake eel",
    ["邱泽"] = "roy chiu",
    ["邱淑贞"] = "chow shu-chun",
    ["邱清泉"] = "qiu qingquan",
    ["邱琦雯"] = "qiu qiwen",
    ["邱瑞"] = "qiu rui",
    ["邱立成"] = "qiu licheng",
    ["邱良功母节孝坊"] = "qiu lianggong's mother's chastity arch",
    ["邱蔚六"] = "qiu weiliu",
    ["邱震海"] = "qiu zhenhai",
}

return M
