local M = {}

M.mapping = {
    ["雀仁乡"] = "queren township",
    ["雀儿"] = "little bird",
    ["雀儿肠肚"] = "petty",
    ["雀啄脉"] = "bird-peck pulse",
    ["雀喧鸠聚"] = "birds chirping",
    ["雀噪"] = "bird noise",
    ["雀圣"] = "mahjong master",
    ["雀姬"] = "sparrow princess",
    ["雀子"] = "freckle",
    ["雀小脏全"] = "small sparrow, complete organs",
    ["雀屏中选"] = "chosen",
    ["雀巢"] = "nestle",
    ["雀巢公司"] = "nestle company",
    ["雀巢冰咖啡"] = "nescafe iced coffee",
    ["雀巢咖啡"] = "nescafe",
    ["雀巢怡养"] = "nestle health science",
    ["雀巢淡奶油"] = "nestle light cream",
    ["雀巢鸟窝"] = "bird's nest",
    ["雀巢黑椒牛柳"] = "nestle black pepper beef",
    ["雀形目"] = "passeriformes",
    ["雀斑"] = "freckles",
    ["雀献金环"] = "sparrow offers golden ring",
    ["雀目"] = "night blindness",
    ["雀目鼠步"] = "timid",
    ["雀盲眼"] = "night blindness",
    ["雀舌形"] = "tongue-shaped",
    ["雀舌黄杨"] = "boxwood",
    ["雀角之忿"] = "sparrow's anger",
    ["雀跃"] = "jump joyfully",
    ["雀跃不已"] = "ceaseless joy",
    ["雀马鱼龙"] = "birds and fish",
    ["雀魂"] = "mahjong soul",
    ["雀魂麻将"] = "mahjong soul",
    ["雀鸟"] = "small bird",
    ["雀鹛"] = "alcippe",
    ["雀鹰"] = "sparrowhawk",
    ["雀麦"] = "bromus",
    ["雀鼠之争"] = "sparrow-rat dispute",
}

return M
