local M = {}

M.mapping = {
    ["骆冰"] = "luo bing",
    ["骆姓"] = "luo surname",
    ["骆家塘"] = "luojiatang",
    ["骆家庄"] = "luojia village",
    ["骆宾基"] = "luo binji",
    ["骆宾王"] = "luo binwang",
    ["骆岗站"] = "luogang station",
    ["骆岭村"] = "luoling village",
    ["骆峪乡"] = "luo yu township",
    ["骆市镇"] = "luoshi town",
    ["骆庄乡"] = "luozhuang township",
    ["骆建佑"] = "loh kean yew",
    ["骆爽"] = "luo shuang",
    ["骆玉珠"] = "luo yuzhu",
    ["骆玉笙"] = "luo yusheng",
    ["骆王宇"] = "luo wangyu",
    ["骆秉章"] = "luo bingzhang",
    ["骆老"] = "luo lao",
    ["骆轶航"] = "luo yihang",
    ["骆达华"] = "kenny lok",
    ["骆马湖"] = "luoma lake",
    ["骆驼"] = "camel",
    ["骆驼凤凰螺"] = "camel conch",
    ["骆驼刺"] = "camel thorn",
    ["骆驼圈子开发区"] = "camel circle development zone",
    ["骆驼奶"] = "camel milk",
    ["骆驼峰"] = "camel hump",
    ["骆驼桥"] = "camel bridge",
    ["骆驼湖"] = "camel lake",
    ["骆驼湾"] = "camel bay",
    ["骆驼牌"] = "camel brand",
    ["骆驼电瓶"] = "camel battery",
    ["骆驼科动物"] = "camelid",
    ["骆驼绒"] = "camel hair",
    ["骆驼背"] = "camel back",
    ["骆驼草"] = "camel thorn",
    ["骆驼蓬"] = "camel sage",
    ["骆驼虫"] = "camel worm",
    ["骆驼趾"] = "camel toe",
    ["骆驼队"] = "camel team",
    ["骆驼黄"] = "camel yellow",
}

return M
