local M = {}

M.mapping = {
    ["骚乱"] = "riot",
    ["骚乱性"] = "riotous",
    ["骚人"] = "poet",
    ["骚人可煞无情思"] = "heartless poet",
    ["骚人墨客"] = "literati",
    ["骚人词客"] = "literary figures",
    ["骚人逸客"] = "reclusive poet",
    ["骚体"] = "poetic style",
    ["骚动"] = "unrest",
    ["骚包"] = "flamboyant",
    ["骚呢"] = "so sexy",
    ["骚味"] = "gamey smell",
    ["骚味儿"] = "odor",
    ["骚啊"] = "so annoying",
    ["骚女"] = "flirty girl",
    ["骚妇"] = "loose woman",
    ["骚子营"] = "soldier camp",
    ["骚客"] = "poet",
    ["骚屄"] = "cunt",
    ["骚年"] = "young rebel",
    ["骚得"] = "horny",
    ["骚情赋骨"] = "romantic charm",
    ["骚扰"] = "harass",
    ["骚扰电话"] = "nuisance call",
    ["骚扰者"] = "harasser",
    ["骚扰行为"] = "harassment",
    ["骚气"] = "flamboyant",
    ["骚浪"] = "wanton",
    ["骚然"] = "restless",
    ["骚瑞"] = "sorry",
    ["骚男"] = "flirty man",
    ["骚的"] = "sexy",
    ["骚穴"] = "erogenous zone",
    ["骚翁墨客"] = "poet",
    ["骚话"] = "dirty talk",
    ["骚货"] = "slut",
    ["骚逼"] = "slut",
    ["骚闹"] = "rowdy",
}

return M
