local M = {}

M.mapping = {
    ["逗乐"] = "amuse",
    ["逗乐儿"] = "amusing",
    ["逗了"] = "teased",
    ["逗人"] = "amusing",
    ["逗他"] = "tease her",
    ["逗你"] = "tease you",
    ["逗你玩"] = "just teasing",
    ["逗你的"] = "just kidding",
    ["逗傻子"] = "tease a fool",
    ["逗傻子玩"] = "play with a fool",
    ["逗傻子玩呢"] = "just playing with a fool",
    ["逗号"] = "comma",
    ["逗号立方"] = "comma cube",
    ["逗号表达式"] = "comma expression",
    ["逗号运算符"] = "comma operator",
    ["逗哏"] = "comic banter",
    ["逗她"] = "all damn",
    ["逗弄"] = "tease",
    ["逗弄着"] = "teasing",
    ["逗引"] = "tease",
    ["逗得"] = "amusing",
    ["逗惹"] = "tease",
    ["逗我"] = "tease me",
    ["逗我玩呢"] = "just kidding",
    ["逗斑青步甲"] = "chlaenius varricollis",
    ["逗死了"] = "all send",
    ["逗点"] = "comma",
    ["逗狗"] = "tease dog",
    ["逗猫"] = "tease cat",
    ["逗猫猫"] = "tease kitty",
    ["逗留"] = "stay",
    ["逗留不进"] = "linger without advancing",
    ["逗留点"] = "stay point",
    ["逗着"] = "teasing",
    ["逗笑"] = "amuse",
    ["逗耍"] = "doulu temple",
    ["逗趣"] = "amusing",
    ["逗趣儿"] = "funny",
    ["逗逗"] = "tease",
    ["逗逼"] = "funny guy",
    ["逗闷子"] = "joking around",
}

return M
