local M = {}

M.mapping = {
    ["逸乐"] = "pleasure",
    ["逸仙名居"] = "yixian residence",
    ["逸仙路"] = "yixian road",
    ["逸以待劳"] = "rest to fight",
    ["逸兴云飞"] = "soaring spirits",
    ["逸兴横飞"] = "overflowing with enthusiasm",
    ["逸兴遄飞"] = "high spirits",
    ["逸出"] = "escape",
    ["逸升佳苑"] = "yisheng jiayuan",
    ["逸去长针线虫"] = "escape long nematode",
    ["逸品"] = "rare treasure",
    ["逸品轩"] = "yipin xuan",
    ["逸夫会议中心"] = "yifu conference center",
    ["逸夫剧场"] = "yifu theater",
    ["逸夫技术科学楼"] = "yifu tech science building",
    ["逸居城"] = "leisure city",
    ["逸居而无教"] = "live idle without education",
    ["逸态横生"] = "graceful",
    ["逸房地产"] = "yi real estate",
    ["逸散"] = "dissipation",
    ["逸景佲居"] = "yijing mingju",
    ["逸景苑"] = "yijing court",
    ["逸民"] = "hermit",
    ["逸泉山庄"] = "yiquan villa",
    ["逸海"] = "yihai",
    ["逸群"] = "outstanding",
    ["逸群绝伦"] = "peerless",
    ["逸豫可以亡身"] = "pleasure ruins",
    ["逸趣"] = "leisurely charm",
    ["逸趣横生"] = "full of charm",
    ["逸辈殊伦"] = "exceptional talent",
    ["逸都路"] = "yidu road",
    ["逸都路东"] = "yidu road east",
    ["逸闻琐事"] = "trivial anecdotes",
    ["逸闻趣事"] = "anecdotes",
    ["逸韵高致"] = "elegance",
    ["逸风"] = "breeze",
    ["逸飞"] = "yi fei",
}

return M
