local M = {}

M.mapping = {
    ["韭园沟乡"] = "jiuyuangou township",
    ["韭园镇"] = "jiuyuan town",
    ["韭花"] = "chive flowers",
    ["韭菜"] = "leek",
    ["韭菜包"] = "leek bun",
    ["韭菜包子"] = "leek stuffed bun",
    ["韭菜合子"] = "leek pocket",
    ["韭菜园"] = "leek garden",
    ["韭菜园路"] = "leek garden road",
    ["韭菜墨鱼丝"] = "shredded cuttlefish with leek",
    ["韭菜庄乡"] = "leek village township",
    ["韭菜拌核桃"] = "leek with walnut",
    ["韭菜根蛆"] = "leek root maggot",
    ["韭菜炒河虾"] = "leek with river shrimp",
    ["韭菜炒绿豆芽"] = "leek with mung bean sprouts",
    ["韭菜炒肉"] = "leek with meat",
    ["韭菜炒莴笋丝"] = "leek with lettuce shreds",
    ["韭菜炒黄鳝"] = "leek with eel",
    ["韭菜盒"] = "leek box",
    ["韭菜籽"] = "leek seed",
    ["韭菜粿"] = "leek cake",
    ["韭菜肉丝豆芽"] = "stir-fried shredded pork with leek and bean sprouts",
    ["韭菜花"] = "leek flower",
    ["韭菜花豆豉炒肉末"] = "stir-fried minced pork with leek flower and fermented beans",
    ["韭菜萝卜纤体汤"] = "leek and radish slimming soup",
    ["韭菜虾仁"] = "shrimp with leek",
    ["韭菜跳盲蝽"] = "leek plant bug",
    ["韭菜迟眼蕈蚊"] = "leek fly",
    ["韭菜鲜鱿"] = "fresh squid with leek",
    ["韭萤叶甲"] = "leek leaf beetle",
    ["韭黄"] = "blanched leek",
    ["韭黄炒蛋"] = "scrambled eggs with chives",
    ["韭黄肉丝"] = "shredded pork with chives",
}

return M
