local M = {}

M.mapping = {
    ["颅中沟"] = "middle cranial fossa",
    ["颅中窝"] = "middle cranial fossa",
    ["颅内"] = "intracranial",
    ["颅内动脉瘤"] = "intracranial aneurysm",
    ["颅内动静脉畸形"] = "intracranial avm",
    ["颅内占位性病变"] = "intracranial space-occupying lesion",
    ["颅内压"] = "intracranial pressure",
    ["颅内压升高"] = "increased icp",
    ["颅内压增高"] = "raised icp",
    ["颅内压监护仪"] = "icp monitor",
    ["颅内高压"] = "intracranial hypertension",
    ["颅前窝"] = "anterior cranial fossa",
    ["颅后窝"] = "posterior fossa",
    ["颅咽管瘤"] = "craniopharyngioma",
    ["颅底骨折"] = "skull base fracture",
    ["颅形拟绵蟹"] = "schizophrys aspera",
    ["颅接型"] = "cranial connection type",
    ["颅痛宁颗粒"] = "lutoning granules",
    ["颅盖"] = "calvaria",
    ["颅神经"] = "cranial nerve",
    ["颅神经损害"] = "cranial nerve damage",
    ["颅脑"] = "cranium",
    ["颅脑损伤"] = "cranial injury",
    ["颅腔"] = "cranial cavity",
    ["颅裂"] = "cranial fissure",
    ["颅间关节"] = "cranial joint",
    ["颅骨"] = "skull",
    ["颅骨修补术"] = "cranioplasty",
    ["颅骨线形骨折"] = "skull linear fracture",
    ["颅骨缺损"] = "skull defect",
    ["颅骨钻"] = "skull drill",
    ["颅骨骨折"] = "skull fracture",
    ["颅骨骨瘤"] = "skull osteoma",
}

return M
