local M = {}

M.mapping = {
    ["驴儿"] = "donkey",
    ["驴友"] = "backpacker",
    ["驴叫"] = "donkey bray",
    ["驴唇"] = "donkey lips",
    ["驴唇不对马嘴"] = "irrelevant",
    ["驴唇马嘴"] = "nonsensical",
    ["驴头"] = "donkey head",
    ["驴头不对马嘴"] = "irrelevant",
    ["驴头狼"] = "donkey wolf",
    ["驴头长颌鱼"] = "donkey head fish",
    ["驴子"] = "donkey",
    ["驴子潘趣"] = "donkey punch",
    ["驴年马月"] = "donkey year and horse month",
    ["驴打滚"] = "donkey rolling",
    ["驴打滚儿"] = "donkey rolling",
    ["驴板肠"] = "donkey intestine",
    ["驴牌"] = "donkey brand",
    ["驴生笄角"] = "donkey grows horns",
    ["驴皮影"] = "donkey shadow play",
    ["驴皮胶"] = "donkey-hide gelatin",
    ["驴羚"] = "lechwe",
    ["驴耳"] = "donkey ear",
    ["驴耳鲍螺"] = "donkey ear abalone",
    ["驴肉"] = "donkey meat",
    ["驴肉火烧"] = "donkey meat burger",
    ["驴肉馆"] = "donkey meat restaurant",
    ["驴肝肺"] = "donkey liver and lungs",
    ["驴肾"] = "donkey kidney",
    ["驴背"] = "donkey back",
    ["驴脸"] = "donkey face",
    ["驴行"] = "donkey travel",
    ["驴行天下"] = "donkey travel",
    ["驴蹄草"] = "marsh marigold",
    ["驴车"] = "donkey cart",
    ["驴驹"] = "donkey foal",
    ["驴骡"] = "hinny",
    ["驴鸣犬吠"] = "braying of donkeys and barking of dogs",
}

return M
