local M = {}

M.mapping = {
    ["霉变"] = "mildew",
    ["霉味"] = "musty",
    ["霉天"] = "moldy weather",
    ["霉天敌"] = "mold enemy",
    ["霉头"] = "bad luck",
    ["霉女"] = "mold girl",
    ["霉巾夜蛾"] = "moth species",
    ["霉干菜"] = "preserved vegetable",
    ["霉干菜烧肉"] = "preserved vegetable braised pork",
    ["霉斑"] = "mold",
    ["霉毛隧蜂"] = "moldy-haired bee",
    ["霉气"] = "bad luck",
    ["霉烂"] = "moldy",
    ["霉病"] = "mildew",
    ["霉素"] = "mycin",
    ["霉腐味"] = "musty smell",
    ["霉臭"] = "musty",
    ["霉菌"] = "mold",
    ["霉菌性"] = "fungal",
    ["霉菌性外耳道炎"] = "fungal otitis externa",
    ["霉菌性肺炎"] = "fungal pneumonia",
    ["霉菌性角膜炎"] = "fungal keratitis",
    ["霉菌感染"] = "fungal infection",
    ["霉菌病"] = "mycosis",
    ["霉裙剑夜蛾"] = "moth species",
    ["霉豆渣"] = "moldy bean dregs",
    ["霉豆渣毛霉"] = "rhizopus moldy dregs",
    ["霉身裸胸鯙"] = "naked moray",
    ["霉运"] = "bad luck",
    ["霉酚酸"] = "mycophenolic acid",
    ["霉雨"] = "moldy rain",
    ["霉霉"] = "taylor swift",
    ["霉黄后窗网蛾"] = "window moth",
    ["霉黄毒蛾"] = "yellow-tail moth",
}

return M
