local M = {}

M.mapping = {
    ["铭万网"] = "mingwang net",
    ["铭刻"] = "engrave",
    ["铭刻在心"] = "engraved in heart",
    ["铭功路街道"] = "minggong road subdistrict",
    ["铭勋悉太公"] = "merit record",
    ["铭嘴髑髅贝"] = "inscribed mouth skull shell",
    ["铭家车"] = "mingjia car",
    ["铭心"] = "engraved in heart",
    ["铭心刻骨"] = "deeply engraved",
    ["铭感"] = "grateful",
    ["铭感不忘"] = "eternally grateful",
    ["铭文"] = "inscription",
    ["铭旌"] = "funeral banner",
    ["铭普光磁"] = "mingpu optoelectronic",
    ["铭湖"] = "inscribed lake",
    ["铭熙"] = "mingxi",
    ["铭爱"] = "eternal love",
    ["铭牌"] = "celebrity woman",
    ["铭牌机"] = "nameplate machine",
    ["铭珊"] = "mingshan",
    ["铭瑶网"] = "mingyao network",
    ["铭篆"] = "inscribed seal",
    ["铭肤镂骨"] = "engraved in memory",
    ["铭记"] = "engrave",
    ["铭记不忘"] = "never forget",
    ["铭记于心"] = "engraved in the heart",
    ["铭记初心"] = "remember the mission",
    ["铭记历史"] = "remember history",
    ["铭记在心"] = "keep in mind",
    ["铭记着"] = "remembering",
    ["铭诸五内"] = "engraved inside",
    ["铭诸心腑"] = "engraved in heart",
    ["铭诸肺腑"] = "engraved deeply",
    ["铭都雅苑"] = "mingdu yayuan",
    ["铭雄明"] = "mingxiongming",
    ["铭雅苑"] = "mingya garden",
}

return M
