local M = {}

M.mapping = {
    ["阔人"] = "wealthy",
    ["阔什塔格乡"] = "kuoshitage township",
    ["阔什萨特玛乡"] = "kuoshixatm township",
    ["阔以"] = "can",
    ["阔佬"] = "tycoon",
    ["阔依其乡"] = "kuoyiqi township",
    ["阔别"] = "long separation",
    ["阔别多年"] = "years apart",
    ["阔剑"] = "broadsword",
    ["阔叶"] = "broadleaf",
    ["阔叶林"] = "broadleaf forest",
    ["阔叶树"] = "broadleaf tree",
    ["阔唇凤凰螺"] = "broad-lipped conch",
    ["阔嘴"] = "broadbill",
    ["阔太"] = "rich wife",
    ["阔少"] = "rich kid",
    ["阔少爷"] = "young master",
    ["阔得像"] = "as wide as",
    ["阔斯特克乡"] = "kuositeke township",
    ["阔楯粪金龟"] = "broad-shielded dung beetle",
    ["阔步"] = "stride",
    ["阔步前行"] = "march forward",
    ["阔步前进"] = "stride forward",
    ["阔步向前"] = "stride forward",
    ["阔气"] = "lavish",
    ["阔洪奇乡"] = "kuohongqi township",
    ["阔筋膜张肌"] = "tensor fasciae latae",
    ["阔绰"] = "lavish",
    ["阔胸禾犀金龟"] = "eophileurus sp.",
    ["阔船蛸"] = "argonaut",
    ["阔论"] = "broad discussion",
    ["阔谈高论"] = "lofty talk",
    ["阔边帽"] = "wide-brimmed hat",
    ["阔野"] = "open field",
    ["阔顿牛仔"] = "cowden jeans",
    ["阔鼻小目"] = "broad nose small eyes",
}

return M
