local M = {}

M.mapping = {
    ["邀一下"] = "invite once",
    ["邀一邀"] = "invite invite",
    ["邀买"] = "buy support",
    ["邀人"] = "invite",
    ["邀会"] = "invite meeting",
    ["邀你"] = "invite you",
    ["邀准"] = "invite approval",
    ["邀击"] = "intercept",
    ["邀功"] = "seek credit",
    ["邀功希宠"] = "curry favor",
    ["邀功请赏"] = "seek rewards",
    ["邀名射利"] = "seek fame and profit",
    ["邀好友"] = "invite friends",
    ["邀宠"] = "seek favor",
    ["邀您"] = "invite you",
    ["邀我登云台"] = "invite me to yuntai",
    ["邀我至田家"] = "invite me to the farm",
    ["邀明月"] = "invite the moon",
    ["邀月唱"] = "sing to moon",
    ["邀约"] = "invitation",
    ["邀请"] = "invite",
    ["邀请书"] = "letter of invitation",
    ["邀请了"] = "invited",
    ["邀请人"] = "inviter",
    ["邀请他"] = "invite him",
    ["邀请信"] = "invitation letter",
    ["邀请函"] = "invitation",
    ["邀请卡"] = "invitation card",
    ["邀请她"] = "invite her",
    ["邀请新人"] = "invite newcomers",
    ["邀请新用户"] = "invite new users",
    ["邀请码"] = "invitation code",
    ["邀请者"] = "inviter",
    ["邀请赛"] = "invitational",
    ["邀赏"] = "seek reward",
    ["邀集"] = "invite",
}

return M
