local M = {}

M.mapping = {
    ["郎不郎秀不秀"] = "neither fish nor fowl",
    ["郎中"] = "doctor",
    ["郎乡"] = "lang village",
    ["郎今欲渡缘何事"] = "why do you want to cross today",
    ["郎前白发"] = "gray hair before husband",
    ["郎各庄"] = "langgezhuang",
    ["郎各庄西"] = "langgezhuang west",
    ["郎君"] = "husband",
    ["郎咸平"] = "lang xianping",
    ["郎咸平说"] = "lang xianping says",
    ["郎士元"] = "lang shiyuan",
    ["郎姓"] = "lang surname",
    ["郎官"] = "court official",
    ["郎家园"] = "langjia garden",
    ["郎家桥"] = "langjia bridge",
    ["郎家胡同"] = "langjia hutong",
    ["郎山路"] = "langshan road",
    ["郎岱镇"] = "langdai town",
    ["郎庄村"] = "langzhuang village",
    ["郎廷极"] = "lang tingji",
    ["郎当"] = "ragged",
    ["郎当岁"] = "young age",
    ["郎德鹅"] = "landes goose",
    ["郎情妾意"] = "mutual affection",
    ["郎才女貌"] = "perfect match",
    ["郎朗"] = "lang lang",
    ["郎木寺"] = "langmusi",
    ["郎村村"] = "lang village",
    ["郎溪"] = "langxi",
    ["郎溪县"] = "langxi county",
    ["郎溪路"] = "langxi road",
    ["郎溪银鱼"] = "langxi whitebait",
    ["郎的诱惑"] = "wolf's temptation",
    ["郎绍安"] = "lang shao'an",
    ["郎舅"] = "brother-in-law",
    ["郎葆辰"] = "lang baochen",
    ["郎西村"] = "langxi village",
    ["郎辛庄"] = "langxinzhuang",
    ["郎酒"] = "lang liquor",
    ["郎骑竹马来"] = "childhood sweethearts",
    ["郎鹤焱"] = "lang heyan",
}

return M
