local M = {}

M.mapping = {
    ["鹏举"] = "peng ju",
    ["鹏兴路"] = "pengxinglu",
    ["鹏华动力"] = "penghua dynamix",
    ["鹏华收益"] = "penghua income",
    ["鹏博士"] = "peng boshi",
    ["鹏哥"] = "peng ge",
    ["鹏城"] = "shenzhen",
    ["鹏城花园"] = "pengcheng garden",
    ["鹏头村"] = "pengtou village",
    ["鹏山工贸学校"] = "pengshan industry and trade school",
    ["鹏峰"] = "pengfeng",
    ["鹏抟九天"] = "pengtuanjiutian",
    ["鹏抟九霄"] = "pengtuanjiuxiao",
    ["鹏抟鹢退"] = "pengtuanyitui",
    ["鹏欣丽都"] = "pengxinlidu",
    ["鹏润家园"] = "pengrun jiayuan",
    ["鹏游蝶梦"] = "fantastic dream",
    ["鹏溪村"] = "pengxicun",
    ["鹏益花园"] = "pengyi garden",
    ["鹏程"] = "pengcheng",
    ["鹏程一路"] = "pengcheng 1st road",
    ["鹏程万里"] = "bright future",
    ["鹏程三路"] = "pengcheng 3rd road",
    ["鹏程二路"] = "pengcheng 2nd road",
    ["鹏程五路"] = "pengcheng 5th road",
    ["鹏程四路"] = "pengcheng 4th road",
    ["鹏程杯"] = "pengcheng cup",
    ["鹏路翱翔"] = "soar high",
    ["鹏辉"] = "penghui",
    ["鹏辉能源"] = "penghui energy",
    ["鹏达路"] = "pengda road",
    ["鹏霄万里"] = "pengxiaowanli",
    ["鹏飞"] = "pengfei",
    ["鹏鹏"] = "peng peng",
}

return M
