local M = {}

M.mapping = {
    ["驰书"] = "send a letter",
    ["驰去"] = "gallop away",
    ["驰名"] = "famous",
    ["驰名世界"] = "world-famous",
    ["驰名中外"] = "famous at home and abroad",
    ["驰名于世"] = "famous in the world",
    ["驰名商标"] = "famous trademark",
    ["驰名天下"] = "famous worldwide",
    ["驰名当世"] = "famous in the world",
    ["驰声走誉"] = "spread reputation",
    ["驰宝路"] = "chibao road",
    ["驰宝马"] = "drive bmw",
    ["驰往"] = "rush to",
    ["驰志伊吾"] = "aspire to achieve",
    ["驰思"] = "think of afar",
    ["驰思遐想"] = "let thoughts wander",
    ["驰援"] = "rush to aid",
    ["驰来"] = "gallop over",
    ["驰电"] = "lightning fast",
    ["驰目"] = "gaze",
    ["驰突"] = "charge forward",
    ["驰莎洛"] = "chishaluo",
    ["驰行"] = "gallop",
    ["驰誉"] = "famous",
    ["驰过"] = "speed past",
    ["驰逐"] = "chase",
    ["驰野"] = "wild gallop",
    ["驰风掣电"] = "swift as wind and lightning",
    ["驰风骋雨"] = "gallop through wind and rain",
    ["驰马试剑"] = "horse riding and sword testing",
    ["驰驱"] = "gallop",
    ["驰骋"] = "gallop",
    ["驰骋于"] = "gallop in",
    ["驰骋天下之至坚"] = "gallop through the world's hardest",
    ["驰骋疆场"] = "gallop on battlefield",
    ["驰骋纵横"] = "gallop freely",
    ["驰骛"] = "gallop",
    ["驰骤"] = "gallop",
    ["驰高骛远"] = "aim high but lack ability",
}

return M
