local M = {}

M.mapping = {
    ["颐东苑"] = "yidong garden",
    ["颐中烟草"] = "yizhong tobacco",
    ["颐之时"] = "time of enjoyment",
    ["颐养"] = "nourish",
    ["颐养之家"] = "elderly care home",
    ["颐养天年"] = "live out one's life in peace",
    ["颐卦"] = "nourishment hexagram",
    ["颐和医院"] = "yihe hospital",
    ["颐和园"] = "summer palace",
    ["颐和园北宫门"] = "summer palace north gate",
    ["颐和园南门"] = "summer palace south gate",
    ["颐和园新建宫门"] = "summer palace new palace gate",
    ["颐和园西门"] = "summer palace west gate",
    ["颐和园路"] = "summer palace road",
    ["颐和园路东口"] = "summer palace road east entrance",
    ["颐和宾馆"] = "yihe hotel",
    ["颐和山庄"] = "yihe villa",
    ["颐和山庄南口"] = "yihe villa south",
    ["颐和花园"] = "yihe garden",
    ["颐和路"] = "yihe road",
    ["颐家春天"] = "yijia spring",
    ["颐寿药店"] = "yishou pharmacy",
    ["颐指如意"] = "command at will",
    ["颐指气使"] = "bossy",
    ["颐指进退"] = "command freely",
    ["颐泉汇"] = "yiquan hui",
    ["颐泽花园"] = "yize garden",
    ["颐源居"] = "yiyuan residence",
    ["颐澳湾"] = "yi ao bay",
    ["颐神养寿"] = "prolong life",
    ["颐神养性"] = "cultivate nature",
    ["颐神养气"] = "nourish spirit",
    ["颐达"] = "yida",
    ["颐高"] = "ego",
    ["颐高数码"] = "ego digital",
    ["颐龄"] = "yiling age",
}

return M
