local M = {}

M.mapping = {
    ["饶不了"] = "won't spare",
    ["饶丰镇"] = "raofeng town",
    ["饶乐府"] = "raolefu",
    ["饶了"] = "spared",
    ["饶了我吧"] = "spare me",
    ["饶人"] = "forgiving",
    ["饶命"] = "spare life",
    ["饶国华"] = "rao guohua",
    ["饶埠镇"] = "raobu town",
    ["饶头"] = "bonus",
    ["饶姓"] = "rao surname",
    ["饶宗颐"] = "rao zongyi",
    ["饶州"] = "raozhou",
    ["饶平"] = "rao ping",
    ["饶平县"] = "raoping county",
    ["饶恕"] = "forgive",
    ["饶是如此"] = "even so",
    ["饶是少年须白头"] = "youth white hair",
    ["饶有"] = "abundant",
    ["饶有兴味"] = "delighted",
    ["饶有兴致"] = "enthusiastic",
    ["饶有兴趣"] = "interested",
    ["饶有风趣"] = "amusing",
    ["饶毓泰"] = "rao yutai",
    ["饶河"] = "raohe",
    ["饶河县"] = "raohe county",
    ["饶漱石"] = "rao shushi",
    ["饶燕婷"] = "rao yanting",
    ["饶益"] = "benefit",
    ["饶舌"] = "rap",
    ["饶舌歌"] = "rap song",
    ["饶舌的"] = "talkative",
    ["饶虫"] = "pinworm",
    ["饶阳"] = "raoyang",
    ["饶阳县"] = "raoyang county",
    ["饶颖"] = "rao ying",
    ["饶鹏"] = "rao peng",
}

return M
