local M = {}

M.mapping = {
    ["陷下"] = "sink",
    ["陷下去"] = "sink down",
    ["陷于"] = "trapped in",
    ["陷于困境"] = "in困境",
    ["陷于绝境"] = "in dire straits",
    ["陷于缧绁"] = "in缧绁",
    ["陷入"] = "fall into",
    ["陷入了"] = "fell into",
    ["陷入僵局"] = "deadlock",
    ["陷入困境"] = "in trouble",
    ["陷入泥坑"] = "stuck in mud",
    ["陷入混乱"] = "chaos",
    ["陷入爱河"] = "fall in love",
    ["陷入重围"] = "surrounded",
    ["陷在"] = "trapped in",
    ["陷坑"] = "pitfall",
    ["陷害"] = "frame",
    ["陷害忠良"] = "frame loyal officials",
    ["陷没"] = "subsidence",
    ["陷波"] = "trap wave",
    ["陷波器"] = "wave trap",
    ["陷溺"] = "sink into",
    ["陷落"] = "collapse",
    ["陷落的"] = "collapsed",
    ["陷落计中"] = "fall into trap",
    ["陷身"] = "trapped",
    ["陷进"] = "fall into",
    ["陷进去"] = "get stuck",
    ["陷阱"] = "trap",
    ["陷阱多"] = "many traps",
    ["陷阱系"] = "trap system",
    ["陷阵"] = "charge into battle",
    ["陷阵之志"] = "will to charge",
}

return M
