local M = {}

M.mapping = {
    ["锻件"] = "forging",
    ["锻冶"] = "forging",
    ["锻刀"] = "forge a knife",
    ["锻刀村"] = "forge village",
    ["锻制"] = "forged",
    ["锻压"] = "forging",
    ["锻压厂"] = "forging plant",
    ["锻压机"] = "forging press",
    ["锻压机床"] = "forging machine tool",
    ["锻压机床厂"] = "forging machine tool plant",
    ["锻压机械"] = "forging machinery",
    ["锻压设备"] = "forging equipment",
    ["锻工"] = "forger",
    ["锻工术"] = "forging technique",
    ["锻打"] = "forge",
    ["锻接"] = "forge welding",
    ["锻模"] = "forging die",
    ["锻炉"] = "forge",
    ["锻炼"] = "exercise",
    ["锻炼之吏"] = "exercise official",
    ["锻炼意志"] = "exercise will",
    ["锻炼机会"] = "exercise opportunity",
    ["锻炼标准"] = "exercise standard",
    ["锻炼法"] = "exercise method",
    ["锻炼罗织"] = "exercise and frame",
    ["锻炼自己"] = "exercise oneself",
    ["锻炼身体"] = "exercise body",
    ["锻炼队伍"] = "train team",
    ["锻烧"] = "calcination",
    ["锻焊"] = "forge welding",
    ["锻轧"] = "forge rolling",
    ["锻造"] = "forging",
    ["锻造公司"] = "forging company",
    ["锻造厂"] = "forging plant",
    ["锻造工"] = "forger",
    ["锻钢"] = "forged steel",
    ["锻铁"] = "wrought iron",
    ["锻铜"] = "wrought copper",
    ["锻铸"] = "forging and casting",
    ["锻锤"] = "forging hammer",
}

return M
