local M = {}

M.mapping = {
    ["霞云岭"] = "xiayun ridge",
    ["霞云岭村"] = "xiayun ridge village",
    ["霞云村"] = "xiayun village",
    ["霞光"] = "sunlight",
    ["霞光万道"] = "myriad rays of sunlight",
    ["霞光村"] = "xiaguang village",
    ["霞光满天"] = "sky filled with sunlight",
    ["霞光社区"] = "xiaguang community",
    ["霞光街"] = "xiaguang street",
    ["霞光道"] = "xiaguang road",
    ["霞光里社区"] = "xiaguangli community",
    ["霞凝新港"] = "xia ning new port",
    ["霞园"] = "xia yuan",
    ["霞坡"] = "xiapovillage",
    ["霞城村"] = "xiacheng village",
    ["霞姐"] = "sister xia",
    ["霞姿月韵"] = "graceful and charming",
    ["霞山区"] = "xiashan district",
    ["霞山村"] = "xiashan village",
    ["霞峰村"] = "xiafeng village",
    ["霞帔"] = "embroidered cape",
    ["霞庭村"] = "xiating village",
    ["霞彩"] = "rosy clouds",
    ["霞明玉映"] = "radiant and elegant",
    ["霞泉村"] = "xiaquan village",
    ["霞浦县"] = "xiapu county",
    ["霞浯"] = "xia wu",
    ["霞浯社区"] = "xiawu community",
    ["霞淮社区"] = "xiahuai community",
    ["霞湖世家"] = "xiahu世家",
    ["霞溪村"] = "xiaxi village",
    ["霞照波心锦裹山"] = "sunset glow on waves and mountains",
    ["霞石"] = "xiashi",
    ["霞碧村"] = "xiabi village",
    ["霞美村"] = "xiamei village",
    ["霞美社区"] = "xiamei community",
    ["霞西村"] = "xiaxi village",
    ["霞飞"] = "feixia",
    ["霞飞路"] = "rue chauffeur",
}

return M
