local M = {}

M.mapping = {
    ["锯了"] = "sawed",
    ["锯全丽鱼"] = "sawfish",
    ["锯刀"] = "saw knife",
    ["锯唇瓢鰕虎鱼"] = "sawlip goby",
    ["锯子"] = "saw",
    ["锯尾隆背蚤"] = "notropis chrysocephalus",
    ["锯工"] = "sawyer",
    ["锯床"] = "sawing machine",
    ["锯开"] = "saw open",
    ["锯成"] = "sawed",
    ["锯拟胸须夜蛾"] = "false underwing moth",
    ["锯掉"] = "saw off",
    ["锯断"] = "saw off",
    ["锯木"] = "sawing",
    ["锯木厂"] = "sawmill",
    ["锯木场"] = "lumber mill",
    ["锯木机杀妻案"] = "sawmill wife murder case",
    ["锯末"] = "sawdust",
    ["锯材"] = "lumber",
    ["锯条"] = "saw blade",
    ["锯架"] = "sawhorse",
    ["锯树"] = "saw tree",
    ["锯毛鼻蚕"] = "sawtooth nose worm",
    ["锯片"] = "saw blade",
    ["锯痕"] = "saw mark",
    ["锯缘圆龟"] = "saw-edged turtle",
    ["锯缘灰蝶"] = "saw-edged butterfly",
    ["锯缘真剑水蚤"] = "eucyclops serrulatus",
    ["锯缘陆龟"] = "saw-edged tortoise",
    ["锯角豆芫菁"] = "blister beetle",
    ["锯鳐"] = "sawfish",
    ["锯鳞冰杜父鱼"] = "saw-scaled sculpin",
    ["锯齿"] = "serrated",
    ["锯齿奇花"] = "serrated flower",
    ["锯齿暗礁"] = "serrated reef",
    ["锯齿楯形提灯虫"] = "serrated lanternfish",
    ["锯齿状"] = "serrated",
    ["锯齿的"] = "serrated",
    ["锯齿真剑水蚤"] = "serrated copepod",
    ["锯齿矛"] = "serrated spear",
    ["锯齿缘"] = "serrated edge",
    ["锯齿鳞钩虾"] = "serrated amphipod",
}

return M
