local M = {}

M.mapping = {
    ["黔东南"] = "qiandongnan",
    ["黔东南小香鸡"] = "qiandongnan small fragrant chicken",
    ["黔东南州"] = "qiandongnan prefecture",
    ["黔东南苗族侗族自治州"] = "qiandongnan miao and dong autonomous prefecture",
    ["黔东南苗族侗族自治州中院"] = "qiandongnan intermediate court",
    ["黔中天"] = "qian zhongtian",
    ["黔之驴"] = "donkey of guizhou",
    ["黔凯涤"] = "qiankaidi",
    ["黔剧"] = "qianju opera",
    ["黔南"] = "qiannan",
    ["黔南州"] = "qiannan prefecture",
    ["黔南布依族苗族自治州"] = "qiannan buyei and miao autonomous prefecture",
    ["黔南布依族苗族自治州中院"] = "qiannan intermediate court",
    ["黔县"] = "qian county",
    ["黔双胜蛛"] = "qianshuangsheng spider",
    ["黔桂铁路"] = "qian-gui railway",
    ["黔江"] = "qianjiang",
    ["黔江区"] = "qianjiang district",
    ["黔江县"] = "qianjiang county",
    ["黔江土家族苗族自治县"] = "qianjiang tujia and miao autonomous county",
    ["黔江小南海"] = "qianjiang xiaonanhai",
    ["黔江隐势瓢虫"] = "qianjiang cryptic ladybug",
    ["黔源电力"] = "qianyuan power",
    ["黔灵公园"] = "qianling park",
    ["黔突暖席"] = "busy and warm",
    ["黔西"] = "qianxi",
    ["黔西南"] = "qianxinan",
    ["黔西南州"] = "qianxinan prefecture",
    ["黔西南布依族苗族自治州中院"] = "qianxinan intermediate people's court",
    ["黔西县"] = "qianxi county",
    ["黔阳"] = "qianyang",
    ["黔阳县"] = "qianyang county",
    ["黔阳土白蚁"] = "qianyang termite",
    ["黔首"] = "common people",
    ["黔驴"] = "guizhou donkey",
    ["黔驴之计"] = "guizhou donkey's trick",
    ["黔驴技孤"] = "limited skills",
    ["黔驴技尽"] = "exhausted skills",
    ["黔驴技穷"] = "at wit's end",
    ["黔鳄"] = "guizhou crocodile",
    ["黔黎"] = "qian li",
}

return M
