local M = {}

M.mapping = {
    ["鄂伦春"] = "oronchon",
    ["鄂伦春族"] = "oronchon ethnic group",
    ["鄂伦春自治旗"] = "oronchon autonomous banner",
    ["鄂军"] = "e jun",
    ["鄂县"] = "e county",
    ["鄂城"] = "echeng",
    ["鄂城区"] = "echeng district",
    ["鄂城县"] = "echeng county",
    ["鄂城墩"] = "echeng mound",
    ["鄂姓"] = "e surname",
    ["鄂尔多斯"] = "ordos",
    ["鄂尔多斯市"] = "ordos city",
    ["鄂尔多斯路街道"] = "ordos road street",
    ["鄂尔多斯高原"] = "ordos plateau",
    ["鄂尔奇"] = "eorchi",
    ["鄂尔泰"] = "ortai",
    ["鄂州"] = "ezhou",
    ["鄂州中院"] = "ezhou intermediate court",
    ["鄂州市"] = "ezhou city",
    ["鄂州市中医院"] = "ezhou hospital of traditional chinese medicine",
    ["鄂州街"] = "ezhou street",
    ["鄂托克"] = "otog",
    ["鄂托克前旗"] = "otog front banner",
    ["鄂托克旗"] = "otog banner",
    ["鄂托克鸟"] = "otog bird",
    ["鄂武商"] = "ewushang",
    ["鄂毕河"] = "ob river",
    ["鄂温克"] = "evenki",
    ["鄂温克族"] = "evenki ethnic group",
    ["鄂温克旗"] = "evenki banner",
    ["鄂温克自治旗"] = "evenki autonomous banner",
    ["鄂王"] = "king e",
    ["鄂省巷"] = "esheng lane",
    ["鄂蚕四号"] = "e silkworm no. 4",
    ["鄂西"] = "western hubei",
    ["鄂西北"] = "northwest hubei",
    ["鄂豫皖"] = "hubei-henan-anhui",
    ["鄂钢"] = "egang",
    ["鄂霍次克冰杜父鱼"] = "okhotsk ice sculpin",
    ["鄂霍次克海"] = "sea of okhotsk",
    ["鄂霍次克短吻狮子"] = "okhotsk short-nosed lion",
    ["鄂霍茨克隐棘杜父"] = "okhotsk hidden-spine sculpin",
}

return M
