local M = {}

M.mapping = {
    ["遁世"] = "seclusion",
    ["遁世幽居"] = "live in seclusion",
    ["遁世无闷"] = "seclusion without boredom",
    ["遁世离俗"] = "retire from society",
    ["遁世遗荣"] = "retire from fame and wealth",
    ["遁世隐居"] = "live in seclusion",
    ["遁俗无闷"] = "seclusion without boredom",
    ["遁光不耀"] = "conceal brilliance",
    ["遁入"] = "retreat into",
    ["遁入空门"] = "retire from the world",
    ["遁名改作"] = "change name and work",
    ["遁地"] = "burrow",
    ["遁天之刑"] = "heaven's punishment",
    ["遁天倍情"] = "go against heaven and reason",
    ["遁形"] = "vanish",
    ["遁形远世"] = "hide from the world",
    ["遁形长臂蟹"] = "phimochirus遁形",
    ["遁藏"] = "hide",
    ["遁词"] = "quibble",
    ["遁走"] = "flee",
    ["遁身远迹"] = "hide far away",
    ["遁辞知其所穷"] = "evasion reveals limit",
    ["遁迹"] = "seclusion",
    ["遁迹匿影"] = "hide from public view",
    ["遁迹方外"] = "retire from the world",
    ["遁迹桑门"] = "become a monk",
    ["遁迹潜形"] = "go into hiding",
    ["遁迹销声"] = "vanish without a trace",
    ["遁迹黄冠"] = "become a taoist",
    ["遁逃"] = "flee",
    ["遁逸无闷"] = "seclusion without boredom",
    ["遁阴匿景"] = "hide from the world",
    ["遁隐"] = "seclusion",
}

return M
