local M = {}

M.mapping = {
    ["饥一顿"] = "starve one meal",
    ["饥不择食"] = "too hungry to be choosy",
    ["饥不暇食"] = "too hungry to eat",
    ["饥不欲食"] = "too hungry to eat",
    ["饥不遑食"] = "too hungry to eat",
    ["饥寒"] = "hunger and cold",
    ["饥寒交凑"] = "afflicted by hunger and cold",
    ["饥寒交至"] = "hunger and cold arrive",
    ["饥寒交迫"] = "suffering from hunger and cold",
    ["饥来吃饭"] = "eat when hungry",
    ["饥民"] = "famine victims",
    ["饥渴"] = "hunger and thirst",
    ["饥渴症"] = "polydipsia",
    ["饥焰中烧"] = "burning with hunger",
    ["饥疲沮丧"] = "hungry and discouraged",
    ["饥穰"] = "famine",
    ["饥者易为食"] = "hunger makes food tasty",
    ["饥者易食"] = "hungry people eat easily",
    ["饥而忘食"] = "forget food when hungry",
    ["饥肠"] = "hungry stomach",
    ["饥肠辘辘"] = "hungry stomach growls",
    ["饥肠雷动"] = "hungry stomach rumbles",
    ["饥肠雷鸣"] = "hungry stomach thunders",
    ["饥色"] = "hungry look",
    ["饥荒"] = "famine",
    ["饥餐天上雪"] = "hungry eat snow from the sky",
    ["饥餐渴饮"] = "hungry eat, thirsty drink",
    ["饥饱"] = "hunger and satiety",
    ["饥饱劳役"] = "hunger, satiety, and forced labor",
    ["饥饿"] = "hunger",
    ["饥饿性酮症"] = "starvation ketosis",
    ["饥饿感"] = "hunger pangs",
    ["饥饿的"] = "hungry",
    ["饥饿线"] = "hunger line",
    ["饥馁"] = "hunger",
    ["饥馑"] = "famine",
    ["饥驱叩门"] = "driven by hunger to knock",
}

return M
