local M = {}

M.mapping = {
    ["鲍俊凯"] = "bao junkai",
    ["鲍勃"] = "bob",
    ["鲍叔牙"] = "bao shuya",
    ["鲍墟乡"] = "baoxu township",
    ["鲍天琦"] = "bao tianqi",
    ["鲍姆加登"] = "baumgarten",
    ["鲍姓"] = "surname bao",
    ["鲍威尔"] = "powell",
    ["鲍子知我"] = "baozi knows me",
    ["鲍官屯镇"] = "baoguantun town",
    ["鲍家庄"] = "baojia village",
    ["鲍家桥"] = "baojia bridge",
    ["鲍家渡"] = "baojia ferry",
    ["鲍尔"] = "bauer",
    ["鲍尔默"] = "ballmer",
    ["鲍岳桥"] = "baoyueqiao",
    ["鲍店镇"] = "baodian town",
    ["鲍廷博"] = "bao tingbo",
    ["鲍德熹"] = "peter pau",
    ["鲍德里亚"] = "baudrillard",
    ["鲍振华"] = "baozhenhua",
    ["鲍曼"] = "baumann",
    ["鲍桑葵"] = "bosanquet",
    ["鲍比"] = "bobby",
    ["鲍氏铲吻犁头鳐"] = "bobbit worm",
    ["鲍汁"] = "abalone sauce",
    ["鲍汁百龄菇"] = "abalone sauce mushroom",
    ["鲍法尔"] = "bofar",
    ["鲍狄埃"] = "eugène pottier",
    ["鲍珊菊"] = "bao shanju",
    ["鲍球形病毒"] = "bovine polyomavirus",
    ["鲍罗廷"] = "borodin",
    ["鲍老"] = "baolao",
    ["鲍邱河"] = "baoqiu river",
    ["鲍里斯"] = "boris",
    ["鲍鱼"] = "abalone",
    ["鲍鱼之次"] = "second to abalone",
    ["鲍鱼之肆"] = "abalone shop",
    ["鲍鱼公主"] = "abalone princess",
    ["鲍鱼罐头"] = "canned abalone",
    ["鲍鱼菇"] = "abalone mushroom",
    ["鲍鱼鸡翼"] = "abalone chicken wings",
}

return M
