local M = {}

M.mapping = {
    ["驼子"] = "hunchback",
    ["驼峰"] = "hump",
    ["驼峰大鹦嘴鱼"] = "humphead parrotfish",
    ["驼峰山"] = "hump mountain",
    ["驼峰路"] = "hump road",
    ["驼峰鼻"] = "hump nose",
    ["驼得像"] = "hump like",
    ["驼房营"] = "tuofangying",
    ["驼房营村"] = "tuofangying village",
    ["驼毛"] = "camel hair",
    ["驼着背"] = "hunchback",
    ["驼绒"] = "camel hair",
    ["驼群"] = "camel herd",
    ["驼背"] = "hunchback",
    ["驼背三刺角蝉"] = "humpback treehopper",
    ["驼背带龙占丽鱼"] = "humpback lates",
    ["驼背树"] = "humpback tree",
    ["驼背棘𩽾𩾌"] = "humpback anglerfish",
    ["驼背潜鱼"] = "humpback pearlfish",
    ["驼背独指乌鲂"] = "humpback dory",
    ["驼背狭鰕虎鱼"] = "humpback goby",
    ["驼背真三棱箱鲀"] = "humpback boxfish",
    ["驼背短吻长尾鳕"] = "humpback grenadier",
    ["驼背躄鱼"] = "humpback anglerfish",
    ["驼背隆哲水蚤"] = "humpback copepod",
    ["驼背鮨丽鱼"] = "humpback cichlid",
    ["驼背鲈扁鮨"] = "humpback grouper",
    ["驼腰子镇"] = "tuoyaozhi town",
    ["驼腹壁泥蜂"] = "crabro腹壁泥蜂",
    ["驼色"] = "camel",
    ["驼茶肖叶甲"] = "camellia leaf beetle",
    ["驼褐裘"] = "camel brown fur",
    ["驼角胸肖叶甲"] = "camel leaf beetle",
    ["驼角蝉"] = "camel cicada",
    ["驼蹄鸡"] = "camel-foot chicken",
    ["驼金龟"] = "golden scarab",
    ["驼金龟科"] = "golden scarab family",
    ["驼铃"] = "camel bell",
    ["驼颈鹦嘴鱼"] = "parrotfish",
    ["驼鹿"] = "moose",
    ["驼鹿头"] = "moose head",
    ["驼鹿脸"] = "moose face",
}

return M
