local M = {}

M.mapping = {
    ["酿之成美酒"] = "brew into fine wine",
    ["酿倭瓜"] = "stuffed pumpkin",
    ["酿冬瓜"] = "stuffed winter melon",
    ["酿冬瓜圈"] = "stuffed winter melon rings",
    ["酿出"] = "brew out",
    ["酿制"] = "brew",
    ["酿尖椒"] = "stuffed chili",
    ["酿山药"] = "stuffed yam",
    ["酿成"] = "brew",
    ["酿成千顷稻花香"] = "brew vast rice fields fragrant",
    ["酿成大错"] = "make a big mistake",
    ["酿枇杷"] = "stuffed loquat",
    ["酿泉为酒"] = "brew spring into wine",
    ["酿海参"] = "stuffed sea cucumber",
    ["酿白兰瓜"] = "brewed white orchid melon",
    ["酿皮"] = "fermented noodles",
    ["酿皮子"] = "fermented noodle sheets",
    ["酿祸"] = "cause disaster",
    ["酿茄斗"] = "stuffed eggplant cup",
    ["酿藕"] = "stuffed lotus root",
    ["酿西红柿"] = "stuffed tomato",
    ["酿豆腐"] = "stuffed tofu",
    ["酿造"] = "brew",
    ["酿造厂"] = "brewery",
    ["酿造学"] = "zymurgy",
    ["酿造者"] = "brewer",
    ["酿造酒"] = "brewed wine",
    ["酿酒"] = "brew wine",
    ["酿酒厂"] = "winery",
    ["酿酒原料"] = "brewing ingredients",
    ["酿酒师"] = "brewer",
    ["酿银瓜"] = "brewed silver melon",
    ["酿雪梨"] = "brewed snow pear",
    ["酿青椒"] = "stuffed green pepper",
    ["酿馅小牛胸口"] = "stuffed veal breast",
    ["酿馅西葫芦"] = "stuffed zucchini",
    ["酿馅鱼"] = "stuffed fish",
    ["酿馅鸡"] = "stuffed chicken",
    ["酿馅鸡蛋"] = "stuffed eggs",
}

return M
