local M = {}

M.mapping = {
    ["霜严衣带断"] = "frost breaks the belt",
    ["霜儿"] = "shuang er",
    ["霜冰"] = "frost ice",
    ["霜冻"] = "frost",
    ["霜刀石"] = "frostblade stone",
    ["霜刃未曾试"] = "frost blade untested",
    ["霜叶"] = "frosty leaves",
    ["霜叶红于二月花"] = "frosty leaves redder than february flowers",
    ["霜天"] = "shuangtian",
    ["霜害"] = "frost damage",
    ["霜寒刺骨"] = "biting cold",
    ["霜晨"] = "frosty morning",
    ["霜月"] = "frosty moon",
    ["霜期"] = "frost period",
    ["霜气横秋"] = "frosty autumn",
    ["霜江夜清澄"] = "clear night by frosty river",
    ["霜火"] = "frostfire",
    ["霜灾"] = "frost disaster",
    ["霜状"] = "frost-like",
    ["霜狼氏族"] = "frostwolf clan",
    ["霜甲术"] = "frost armor",
    ["霜白"] = "frosty white",
    ["霜絮"] = "frost floc",
    ["霜花"] = "frost flowers",
    ["霜落熊升树"] = "frost falls bear climbs tree",
    ["霜语峡谷"] = "frostwhisper gorge",
    ["霜重鼓寒声不起"] = "frost-heavy drum cold soundless",
    ["霜降"] = "frost descent",
    ["霜降山水清"] = "clear landscape after frost",
    ["霜雪"] = "frost and snow",
    ["霜霉病"] = "downy mildew",
    ["霜霜"] = "shuangshuang",
    ["霜霰"] = "frost and sleet",
    ["霜露"] = "frost and dew",
    ["霜青"] = "frost green",
    ["霜风"] = "frosty wind",
    ["霜飔"] = "shuangsi",
    ["霜鬃巨魔要塞"] = "frostmane troll fortress",
    ["霜鸟"] = "frost bird",
}

return M
