local M = {}

M.mapping = {
    ["颁个"] = "award one",
    ["颁予"] = "confer",
    ["颁令"] = "issue an order",
    ["颁发"] = "issue",
    ["颁发了"] = "issued",
    ["颁发奖品"] = "award prize",
    ["颁发奖杯"] = "present trophy",
    ["颁发奖牌"] = "award medal",
    ["颁发奖状"] = "award certificate",
    ["颁发奖金"] = "award bonus",
    ["颁发机构"] = "issuing authority",
    ["颁发营业执照"] = "issue business license",
    ["颁发证书"] = "issue certificate",
    ["颁奖"] = "award",
    ["颁奖仪式"] = "awards ceremony",
    ["颁奖会"] = "awards meeting",
    ["颁奖典礼"] = "awards ceremony",
    ["颁奖广场"] = "awards square",
    ["颁奖晚会"] = "awards evening",
    ["颁奖盛典"] = "awards gala",
    ["颁奖礼中"] = "during awards ceremony",
    ["颁布"] = "promulgate",
    ["颁布了"] = "promulgated",
    ["颁布于"] = "promulgated in",
    ["颁布后"] = "after promulgation",
    ["颁布实施"] = "promulgated and implemented",
    ["颁布法令"] = "promulgate decree",
    ["颁布法律"] = "promulgate law",
    ["颁布者"] = "promulgator",
    ["颁授"] = "confer",
    ["颁旨"] = "issue decree",
    ["颁白者不负戴于道路矣"] = "the grey-haired do not carry burdens on the road",
    ["颁给"] = "award to",
    ["颁行"] = "promulgate",
    ["颁证"] = "issue certificate",
    ["颁证机构"] = "certification body",
    ["颁诏"] = "issue decree",
    ["颁赏胡同"] = "bansang hutong",
    ["颁赐"] = "bestow",
    ["颁赠"] = "bestow",
}

return M
