local M = {}

M.mapping = {
    ["骄人"] = "proud achievement",
    ["骄人成绩"] = "outstanding achievements",
    ["骄佚奢淫"] = "extravagance",
    ["骄侈暴佚"] = "arrogant and extravagant",
    ["骄侈淫佚"] = "arrogant and licentious",
    ["骄傲"] = "pride",
    ["骄傲使人落后"] = "pride leads to fall",
    ["骄傲地"] = "proudly",
    ["骄傲情绪"] = "pride emotion",
    ["骄傲放纵"] = "arrogant indulgence",
    ["骄傲月"] = "pride month",
    ["骄傲的"] = "proud",
    ["骄傲的少年"] = "proud youth",
    ["骄傲自大"] = "arrogant",
    ["骄傲自满"] = "complacent",
    ["骄兵"] = "arrogant troops",
    ["骄兵必败"] = "pride goes before fall",
    ["骄兵悍将"] = "arrogant generals",
    ["骄固"] = "arrogant and stubborn",
    ["骄奢"] = "luxury",
    ["骄奢放逸"] = "extravagant",
    ["骄奢淫逸"] = "decadent",
    ["骄女"] = "proud daughter",
    ["骄娇二气"] = "arrogance and delicacy",
    ["骄子"] = "favorite son",
    ["骄恣"] = "arrogant and willful",
    ["骄悍"] = "arrogant and fierce",
    ["骄慢"] = "arrogant",
    ["骄横"] = "arrogant and domineering",
    ["骄横奢侈"] = "arrogant and extravagant",
    ["骄横的"] = "arrogant",
    ["骄气"] = "arrogance",
    ["骄淫奢侈"] = "extravagant and dissipated",
    ["骄狂"] = "arrogant",
    ["骄矜"] = "arrogant",
    ["骄纵"] = "arrogant and indulgent",
    ["骄躁"] = "arrogant and impatient",
    ["骄阳"] = "blazing sun",
    ["骄阳似我"] = "blazing sun like me",
    ["骄阳似火"] = "blazing sun like fire",
    ["骄阳化为霖"] = "blazing sun turns to rain",
    ["骄阳如火"] = "blazing sun like fire",
}

return M
