local M = {}

M.mapping = {
    ["锐不可当"] = "unstoppable",
    ["锐不可挡"] = "invincible",
    ["锐减"] = "sharp decline",
    ["锐利"] = "sharp",
    ["锐利度"] = "sharpness",
    ["锐利无比"] = "razor-sharp",
    ["锐利武器"] = "sharp weapon",
    ["锐利的"] = "sharp",
    ["锐化"] = "sharpen",
    ["锐化边缘"] = "sharpen edges",
    ["锐卒勿攻"] = "do not attack sharp troops",
    ["锐增"] = "sharp increase",
    ["锐度"] = "sharpness",
    ["锐志"] = "resolve",
    ["锐意"] = "determined",
    ["锐意改革"] = "determined reform",
    ["锐意进取"] = "determined progress",
    ["锐挫望绝"] = "despair",
    ["锐挫气索"] = "discouraged",
    ["锐敏"] = "acute",
    ["锐明技术"] = "ruiming technology",
    ["锐步"] = "reebok",
    ["锐气"] = "vigor",
    ["锐气益壮"] = "growing vigor",
    ["锐痛"] = "sharp pain",
    ["锐眼"] = "sharp eye",
    ["锐科激光"] = "raycus laser",
    ["锐角"] = "acute angle",
    ["锐角三角形"] = "acute triangle",
    ["锐评"] = "sharp review",
    ["锐进"] = "sharp advance",
    ["锐雯"] = "riven",
    ["锐骐多功能商用车"] = "rich multi-purpose vehicle",
    ["锐龙"] = "ryzen",
}

return M
