local M = {}

M.mapping = {
    ["邢东新区"] = "xingdong new area",
    ["邢以群"] = "xing yiqun",
    ["邢侗"] = "xing dong",
    ["邢傲伟"] = "xing aowei",
    ["邢克垒"] = "xing kelei",
    ["邢其毅"] = "xing qiyi",
    ["邢口镇"] = "xingkou town",
    ["邢台"] = "xingtai",
    ["邢台中院"] = "xingtai intermediate court",
    ["邢台县"] = "xingtai county",
    ["邢台市"] = "xingtai city",
    ["邢台市桥东区"] = "qiaodong district, xingtai",
    ["邢台轧辊"] = "xingtai roll",
    ["邢台道口烧鸡"] = "xingtai daokou roast chicken",
    ["邢各庄"] = "xinggezhuang",
    ["邢各庄北站"] = "xinggezhuang north station",
    ["邢各庄南站"] = "xinggezhuang south station",
    ["邢各庄村"] = "xinggezhuang village",
    ["邢国辉"] = "xing guohui",
    ["邢夫人"] = "lady xing",
    ["邢家坞村"] = "xingjiawu village",
    ["邢家桥"] = "xingjia bridge",
    ["邢家要乡"] = "xingjiayao township",
    ["邢慧娜"] = "xing huina",
    ["邢文军"] = "xing wenjun",
    ["邢晓瑶"] = "xing xiaoyao",
    ["邢晗铭"] = "xing hanming",
    ["邢海军"] = "xing haijun",
    ["邢澍"] = "xing shu",
    ["邢福义"] = "xing fuyi",
    ["邢端"] = "xing duan",
    ["邢质斌"] = "xing zhibin",
    ["邢邑镇"] = "xingyi town",
    ["邢黄牛腐干"] = "xing huangniu dried tofu",
}

return M
