local M = {}

M.mapping = {
    ["镶上"] = "inlay",
    ["镶了"] = "inlaid",
    ["镶入"] = "inlay",
    ["镶在"] = "inlaid",
    ["镶宝石"] = "gem-set",
    ["镶嵌"] = "inlay",
    ["镶嵌工艺"] = "inlay craft",
    ["镶嵌片"] = "tessera",
    ["镶嵌画"] = "mosaic",
    ["镶嵌着"] = "inlaid with",
    ["镶嵌踝类初龙"] = "ankle-embedded archosaur",
    ["镶成"] = "inlaid",
    ["镶接"] = "inlay",
    ["镶有"] = "inlaid with",
    ["镶板"] = "paneling",
    ["镶满"] = "inlaid with",
    ["镶片"] = "inlay",
    ["镶牙"] = "dental crown",
    ["镶玉"] = "jade inlaid",
    ["镶玻璃"] = "glazing",
    ["镶着"] = "inlaid",
    ["镶碗"] = "inlaid bowl",
    ["镶竹荪"] = "stuffed bamboo fungus",
    ["镶花边"] = "lace",
    ["镶落叶夜蛾"] = "leaf-embedding moth",
    ["镶边"] = "edging",
    ["镶金"] = "gold-plated",
    ["镶金边"] = "gold-edged",
    ["镶钻"] = "diamond-set",
    ["镶钻石"] = "diamond-inlaid",
    ["镶银"] = "silver-inlaid",
    ["镶面"] = "veneer",
    ["镶黄"] = "inlaid yellow",
    ["镶黄旗"] = "xianghuang banner",
}

return M
