local M = {}

M.mapping = {
    ["遍于"] = "pervade",
    ["遍体"] = "all over the body",
    ["遍体鳞伤"] = "covered with wounds",
    ["遍历"] = "traverse",
    ["遍历二叉树"] = "traverse binary tree",
    ["遍历名山大川"] = "travel famous mountains",
    ["遍历数组"] = "traverse array",
    ["遍历文件"] = "traverse file",
    ["遍历文件夹"] = "traverse folder",
    ["遍历目录"] = "traverse directory",
    ["遍及"] = "pervade",
    ["遍及全国"] = "nationwide",
    ["遍及全球"] = "worldwide",
    ["遍在蛋白"] = "ubiquitin",
    ["遍地"] = "everywhere",
    ["遍地开花"] = "blossom everywhere",
    ["遍地英雄下夕烟"] = "heroes everywhere at sunset",
    ["遍地都是"] = "everywhere",
    ["遍天下"] = "all over the world",
    ["遍寻"] = "search everywhere",
    ["遍尝"] = "taste all",
    ["遍山"] = "all over the mountains",
    ["遍布"] = "widespread",
    ["遍布全国"] = "nationwide",
    ["遍布整个"] = "all over",
    ["遍布着"] = "covered with",
    ["遍插茱萸"] = "insert dogwood everywhere",
    ["遍插茱萸少一人"] = "one less dogwood",
    ["遍数"] = "frequency",
    ["遍海角天涯"] = "all over the world",
    ["遍绕篱边日渐斜"] = "around the fence as the sun sets",
    ["遍览"] = "browse",
    ["遍访"] = "visit everywhere",
    ["遍身"] = "all over the body",
    ["遍身罗绮者"] = "those clad in silk",
    ["遍野"] = "all over the fields",
}

return M
